'use strict';
const fs=require('fs'); const path=require('path');
const G1=require('./jeeves.speech-kernel.js');
const SR=24000,BASE_F0=118,BASE_AMP=.52;
const FORMANTS={AA:[730,1090,2440],AE:[660,1720,2410],AH:[640,1190,2390],AO:[570,840,2410],EH:[530,1840,2480],ER:[490,1350,1690],IH:[400,1990,2550],IY:[270,2290,3010],OW:[570,840,2410],UH:[440,1020,2240],UW:[300,870,2240],AY:[650,1500,2500],EY:[500,1900,2600]};
const VOWELS=new Set(Object.keys(FORMANTS)); const STOP=new Set(['P','B','T','D','K','G']); const FRIC=new Set(['F','V','S','Z','SH','ZH','TH','DH','H']);
const STRESS=new Set(['navigation','orientation','diamond','gate','bridge','define','questions','connections','stars','answers','reality','existence','therefore','never','lost','home','nothing','navigates','better','compass']);
function rand(i){const x=Math.sin((i+1)*12.9898)*43758.5453;return x-Math.floor(x);}
function stressWeight(tok,prevWord){if(tok.type!=='ph')return 0;const stressed=STRESS.has(tok.word);if(!stressed)return 0;if(prevWord===tok.word)return .72;return 1;}
function phraseProgress(tokens,index){let total=0,pos=0;for(let i=0;i<tokens.length;i++){if(tokens[i].type==='ph'){if(i<index)pos++;total++;}}return total?pos/Math.max(1,total-1):0;}
function f0For(tok,progress,weight){const phrase=121+(108-121)*progress;const stress=weight*(8+5*Math.sin(Math.PI*Math.min(1,progress+.1)));return Math.max(106,Math.min(136,phrase+stress));}
function ampFor(progress,weight){const final=progress>.82?.90:1;return Math.min(.62,BASE_AMP*(weight?1.10:.94)*final);}
function synthPh(p,dur,f0,amp){const n=Math.max(1,Math.floor(dur*SR)),out=new Float32Array(n);if(VOWELS.has(p)||['R','L','W','Y','M','N','NG'].includes(p)){const F=FORMANTS[p]||FORMANTS.AH;for(let i=0;i<n;i++){const t=i/SR;let s=0;for(let h=1;h<=24;h++){const f=h*f0;let gain=.03;for(const ff of F)gain+=1/(1+Math.pow((f-ff)/90,2));s+=Math.sin(2*Math.PI*f*t)*gain/h;}const env=Math.min(1,i/(.01*SR),(n-i)/(.02*SR));out[i]=s*amp*.22*env;}}else if(FRIC.has(p)||['CH','JH'].includes(p)){for(let i=0;i<n;i++){const env=Math.min(1,i/(.008*SR),(n-i)/(.012*SR));out[i]=((rand(i)-.5)*2)*.22*env*(p==='H'?.5:1)*(amp/BASE_AMP);}}else if(STOP.has(p)){const burst=Math.min(n,Math.floor(.025*SR));for(let i=0;i<burst;i++)out[i]=((rand(i*3)-.5)*2)*.28*(1-i/burst)*(amp/BASE_AMP);}return out;}
function silence(d){return new Float32Array(Math.max(1,Math.floor(d*SR)));}
function concat(a){const n=a.reduce((s,x)=>s+x.length,0),o=new Float32Array(n);let k=0;for(const x of a){o.set(x,k);k+=x.length;}return o;}
function render(text){const tokens=G1.phonemesFor(text),parts=[];let prevWord='';for(let i=0;i<tokens.length;i++){const tok=tokens[i],d=G1.g1Duration(tok);if(tok.type!=='ph'){parts.push(silence(d));continue;}const progress=phraseProgress(tokens,i),weight=stressWeight(tok,prevWord),f0=f0For(tok,progress,weight),amp=ampFor(progress,weight);parts.push(synthPh(tok.v,d,f0,amp));prevWord=tok.word;}return concat(parts);}
function wav(buf){const b=Buffer.alloc(44+buf.length*2);b.write('RIFF',0);b.writeUInt32LE(36+buf.length*2,4);b.write('WAVE',8);b.write('fmt ',12);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(SR,24);b.writeUInt32LE(SR*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(buf.length*2,40);for(let i=0;i<buf.length;i++){const x=Math.max(-1,Math.min(1,buf[i]));b.writeInt16LE(Math.round(x*32767),44+i*2);}return b;}
function renderSet(out){fs.mkdirSync(out,{recursive:true});const all=[],manifest={schema:'DIAMOND_GATE_SPEECH_KERNEL_G2_RENDER_v1',sampleRate:SR,baseF0Hz:BASE_F0,baseAmplitude:BASE_AMP,heldTimingGeneration:'G1',lines:[]};G1.LINES.forEach((text,i)=>{const audio=render(text),id=`C${String(i+1).padStart(2,'0')}`,file=`G2_${id}.wav`;fs.writeFileSync(path.join(out,file),wav(audio));all.push(audio,silence(.42));manifest.lines.push({generation:'G2',id,text,file,durationSeconds:audio.length/SR});});fs.writeFileSync(path.join(out,'G2_COMPASS_8_BEATS.wav'),wav(concat(all)));fs.writeFileSync(path.join(out,'G2_render-manifest.json'),JSON.stringify(manifest,null,2));}
if(require.main===module)renderSet(process.argv[2]||'.');
module.exports={render,renderSet,f0For,ampFor,stressWeight};
