#!/usr/bin/env node
import fs from'node:fs';import path from'node:path';import{spawnSync}from'node:child_process';
const LOCATOR='.github/operation-intake/locator.v1.json',REPOSITORY='smansfield635-create/smansfield635-create.github.io';
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v;
const write=(p,v)=>{fs.mkdirSync(path.dirname(path.resolve(p)),{recursive:true});fs.writeFileSync(path.resolve(p),JSON.stringify(stable(v),null,2)+'\n')};
const fail=(code,detail=null)=>{let e=Error(code);e.code=code;e.detail=detail;throw e};
function args(a){if(a.length===1&&a[0]==='--self-test')return{self:true};let o={};for(let i=0;i<a.length;i+=2){if(!['--selection','--output','--bridge-root'].includes(a[i])||a[i+1]===undefined)fail('CLI_ARGUMENTS_NOT_CLOSED');o[a[i].slice(2)]=a[i+1]}if(!o.selection||!o.output)fail('CLI_ARGUMENTS_INCOMPLETE');return o}
function locator(){let x=JSON.parse(fs.readFileSync(LOCATOR,'utf8'));if(x.schema!=='REPOSITORY_OPERATION_INTAKE_LOCATOR_v1'||x.status!=='ACTIVE_FAIL_CLOSED'||!x.entrypoint||!x.lockRef||!x.lockManager)fail('CANONICAL_LOCATOR_INVALID');return x}
function selection(p){let s=JSON.parse(fs.readFileSync(p,'utf8'));if(s.schema!=='FIXED_FIXTURE_INTAKE_SELECTION_RECEIPT_v1'||s.result!=='FIXTURE_SELECTED_FAIL_CLOSED'||s.action!=='ADMIT'||s.arbitraryPayloadAccepted!==false||s.authorityCreated!==false||s.repositoryMutationPerformed!==false)fail('SELECTION_INVALID');let b=s.bridgeRequest;if(!b||b.repository!==REPOSITORY||!b.operationRequest||!b.constructionProcedure)fail('REQUEST_ENVELOPE_INVALID');if(b.exactGoverningHead!==b.operationRequest.exactGoverningHead||b.exactGoverningHead!==b.constructionProcedure.exactGoverningHead)fail('FROZEN_HEAD_BINDING_MISMATCH');return{s,b}}
function self(){let L=locator(),checks=[L.entrypoint==='tools/operation-intake/repository-operation-intake-gate.v1.mjs',L.lockManager==='tools/operation-intake/repository-operation-lock-manager.v1.mjs',typeof L.lockRef==='string'&&L.lockRef.startsWith('refs/heads/operation-locks/'),fs.existsSync(L.entrypoint),fs.existsSync(L.lockManager)];return{schema:'FIXED_FIXTURE_DIFFERENTIAL_CANONICAL_INTAKE_SELF_TEST_v2',result:checks.every(Boolean)?'PASS_CLOSED':'FAIL_CLOSED',checkCount:checks.length,checks,canonicalLocator:LOCATOR,canonicalIdentitiesResolvedAtRuntime:true,admissionSemanticsDuplicated:false}}
let A=args(process.argv.slice(2));if(A.self){let r=self();process.stdout.write(JSON.stringify(r,null,2)+'\n');process.exit(r.result==='PASS_CLOSED'?0:1)}
try{let{ s,b}=selection(A.selection),L=locator();if(!process.env.GITHUB_TOKEN)fail('GITHUB_TOKEN_MISSING');let dir=path.dirname(path.resolve(A.output)),rp=dir+'/operation-request.json',pp=dir+'/construction-procedure.json',cp=dir+'/canonical-admission-receipt.json';write(rp,b.operationRequest);write(pp,b.constructionProcedure);let c=spawnSync(process.execPath,[L.entrypoint,'--request',rp,'--procedure',pp,'--repository',REPOSITORY,'--lock-ref',L.lockRef,'--output',cp],{encoding:'utf8',env:process.env,timeout:120000});if(!fs.existsSync(cp))fail('CANONICAL_RECEIPT_MISSING',{exitCode:c.status});let receipt=JSON.parse(fs.readFileSync(cp,'utf8'));let out={schema:'FIXED_FIXTURE_DIFFERENTIAL_CANONICAL_INTAKE_RECEIPT_v2',result:receipt.result==='ADMITTED_AND_LOCKED'?'CANONICAL_RECEIPT_PRESERVED':'FAIL_CLOSED',fixtureId:s.fixtureId,canonicalLocator:LOCATOR,canonicalGateExecuted:true,canonicalReceiptJson:receipt,canonicalChildExitCode:c.status,admissionResultRewritten:false,authorityCreated:false,repositoryMutationPerformed:false};write(A.output,out);process.exitCode=out.result==='CANONICAL_RECEIPT_PRESERVED'?0:1}catch(e){write(A.output,{schema:'FIXED_FIXTURE_DIFFERENTIAL_CANONICAL_INTAKE_RECEIPT_v2',result:'FAIL_CLOSED',errorCode:e.code||'UNEXPECTED_FAILURE',detail:e.detail||e.message,canonicalGateExecuted:false,admissionResultRewritten:false,authorityCreated:false,repositoryMutationPerformed:false});process.exitCode=1}
