/**
 * /showroom/globe/h-earth/functional-landscape/navigation.js
 * H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_PROPOSAL_RUN_6F_v1
 *
 * Terrain-supported successor: ordinary ground locomotion is projected onto
 * the exact presented terrain before camera clearance/stand-off is applied.
 * A stale camera Y is never carried horizontally through rising terrain.
 */
import { H_EARTH_3D_CAMERA_CAPACITY } from '../capacity.js';
import { sampleHEarthTerrainField } from '../../../../h-earth-3d/terrain/h-earth.terrain-field.js';
import { H_EARTH_FUNCTIONAL_LANDSCAPE_REALIZATION_PLAN } from '../../../../h-earth-3d/integration/h-earth.landscape-realization-planner.js';
import {
  H_EARTH_VISIBLE_TERRAIN_CLEARANCE_CONTRACT_ID,
  H_EARTH_VISIBLE_TERRAIN_CLEARANCE_PROTECTED_FLOOR,
  sampleHEarthVisibleTerrainClearanceSurface,
  sampleHEarthVisibleTerrainClearanceEnvelope
} from './visible-terrain-clearance.js';

const freeze=(v,s=new WeakSet())=>{if(v===null||typeof v!=='object'||Object.isFrozen(v)||s.has(v))return v;s.add(v);Object.values(v).forEach(x=>freeze(x,s));return Object.freeze(v)};
const finite=v=>typeof v==='number'&&Number.isFinite(v);
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const normalizeDegrees=value=>{let r=value%360;if(r>180)r-=360;if(r<-180)r+=360;return r};

export const H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_CONTRACT_ID='H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_PROPOSAL_RUN_6F_v1';
export const H_EARTH_TERRAIN_RELATIVE_CAMERA_CLEARANCE_SUCCESSOR_CONTRACT_ID='H_EARTH_TERRAIN_SUPPORTED_LOCOMOTION_GEN324_v1';
export const H_EARTH_TERRAIN_SUPPORTED_LOCOMOTION_CONTRACT_ID='H_EARTH_TERRAIN_SUPPORTED_LOCOMOTION_GEN324_v1';

export const H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_PROFILE=freeze({
  contractId:H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_CONTRACT_ID,
  cameraClearanceSuccessorContractId:H_EARTH_TERRAIN_RELATIVE_CAMERA_CLEARANCE_SUCCESSOR_CONTRACT_ID,
  terrainSupportedLocomotionContractId:H_EARTH_TERRAIN_SUPPORTED_LOCOMOTION_CONTRACT_ID,
  visibleTerrainClearanceContractId:H_EARTH_VISIBLE_TERRAIN_CLEARANCE_CONTRACT_ID,
  protectedGeographicFloor:H_EARTH_VISIBLE_TERRAIN_CLEARANCE_PROTECTED_FLOOR,
  eyeHeight:2.25,minimumTerrainClearance:1.6,clearanceDeadband:0.28,
  maximumUphillRisePerProposal:12,maximumDownhillSettlePerProposal:3.25,
  lookAheadClearanceDistance:6,clearanceFootprintRadius:1.25,
  movementStepWorldUnits:5,maximumMovementIntentWorldUnits:12,
  sweptTerrainSampleSpacing:0.35,hardTerrainSupportOffset:2.25,
  lookDistanceWorldUnits:18,turnStepDegrees:6,pitchStepDegrees:4,
  pitchMinimumDegrees:-42,pitchMaximumDegrees:32,
  verticalFovMinimumDegrees:H_EARTH_3D_CAMERA_CAPACITY.futureControllerCapacity.verticalFovDegrees.minimum,
  verticalFovMaximumDegrees:H_EARTH_3D_CAMERA_CAPACITY.futureControllerCapacity.verticalFovDegrees.maximum,
  nearPlane:H_EARTH_3D_CAMERA_CAPACITY.initialProjectionCandidate.nearPlane,
  farPlane:H_EARTH_3D_CAMERA_CAPACITY.initialProjectionCandidate.farPlane,
  selectionProjectionModel:'CHUNK_LOCAL_NEAREST_AVAILABLE_TERRAIN_MEMBER',
  authority:freeze({emitsCameraProposal:true,validatesTerrainClearance:true,retainsLastLawfulStateForRecovery:true,samplesPresentedTerrainRepresentation:true,terrainSupportedLocomotion:true,ownsCanonicalCameraState:false,ownsTerrainField:false,ownsVisibleRelief:false,ownsGeography:false,ownsTopology:false,ownsNavigationScale:false,ownsSemanticAddressIdentity:false,ownsCollisionOrPhysics:false,ownsRenderer:false})
});

export const H_EARTH_FUNCTIONAL_LANDSCAPE_WAYPOINTS=freeze({
  COAST:{waypointId:'COAST',label:'Coastal entry',position:{x:0,z:-96},yawDegrees:0,pitchDegrees:-8},
  BERM:{waypointId:'BERM',label:'Coastal berm',position:{x:0,z:-132},yawDegrees:0,pitchDegrees:-7},
  LOWLAND:{waypointId:'LOWLAND',label:'Lowland',position:{x:-42,z:-158},yawDegrees:-18,pitchDegrees:-6},
  HILL:{waypointId:'HILL',label:'Navigable hill',position:{x:72,z:-172},yawDegrees:18,pitchDegrees:-8},
  RIDGE:{waypointId:'RIDGE',label:'Ridge or bluff',position:{x:145,z:-225},yawDegrees:12,pitchDegrees:-10}
});
const terrainChunks=()=>H_EARTH_FUNCTIONAL_LANDSCAPE_REALIZATION_PLAN.chunks.filter(c=>c.terrainMemberAddressIds.length>0&&c.physicalRole.includes('TERRAIN'));
export function resolveHEarthNavigableTerrainChunk(worldX,worldZ){if(!finite(worldX)||!finite(worldZ))return null;const e=1e-8;return terrainChunks().filter(c=>worldX>=c.worldBounds.xMin-e&&worldX<=c.worldBounds.xMax+e&&worldZ>=c.worldBounds.zMin-e&&worldZ<=c.worldBounds.zMax+e).sort((a,b)=>a.chunkId.localeCompare(b.chunkId))[0]??null}
function parseAddress(address){const m=/:R(\d+):C(\d+)$/.exec(address);return m?{address,row:Number(m[1]),column:Number(m[2])}:null}
function resolveSemanticSelection(chunk,x,z){const candidates=chunk.terrainMemberAddressIds.map(parseAddress).filter(Boolean);if(!candidates.length)return freeze({selectedSemanticAddressId:null,selectionProjectionModel:H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_PROFILE.selectionProjectionModel});const xp=clamp((x-chunk.worldBounds.xMin)/Math.max(1e-8,chunk.worldBounds.xMax-chunk.worldBounds.xMin),0,.999999),zp=clamp((z-chunk.worldBounds.zMin)/Math.max(1e-8,chunk.worldBounds.zMax-chunk.worldBounds.zMin),0,.999999),tc=chunk.addressRange.columnMin+Math.floor(xp*4),tr=chunk.addressRange.rowMin+Math.floor(zp*4),selected=[...candidates].sort((a,b)=>(Math.abs(a.row-tr)+Math.abs(a.column-tc))-(Math.abs(b.row-tr)+Math.abs(b.column-tc))||a.address.localeCompare(b.address))[0];return freeze({selectedSemanticAddressId:selected.address,targetSemanticCoordinate:{row:tr,column:tc},selectionProjectionModel:H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_PROFILE.selectionProjectionModel})}

function resolveLawfulPosition({worldX,worldZ,yawDegrees=0}){
  const chunk=resolveHEarthNavigableTerrainChunk(worldX,worldZ);if(!chunk)return freeze({eligible:false,status:'POSITION_OUTSIDE_NAVIGABLE_TERRAIN',issues:['NO_NAVIGABLE_TERRAIN_CHUNK']});
  const canonicalTerrainSample=sampleHEarthTerrainField(worldX,worldZ),surface=sampleHEarthVisibleTerrainClearanceSurface(worldX,worldZ);if(canonicalTerrainSample?.valid!==true||surface?.valid!==true)return freeze({eligible:false,status:'TERRAIN_SAMPLE_INVALID',issues:['PRESENTED_TERRAIN_SAMPLE_INVALID']});
  const p=H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_PROFILE,visible=sampleHEarthVisibleTerrainClearanceEnvelope(worldX,worldZ,{yawDegrees,lookAheadDistance:p.lookAheadClearanceDistance,lateralRadius:p.clearanceFootprintRadius});if(visible?.valid!==true)return freeze({eligible:false,status:'VISIBLE_TERRAIN_CLEARANCE_SAMPLE_INVALID',issues:['VISIBLE_TERRAIN_CLEARANCE_SAMPLE_INVALID']});
  const supportY=surface.visibleElevation+p.hardTerrainSupportOffset,clearanceY=visible.visibleElevation+p.minimumTerrainClearance,targetY=visible.visibleElevation+p.eyeHeight,y=Math.max(supportY,clearanceY,targetY),selection=resolveSemanticSelection(chunk,worldX,worldZ);
  return freeze({eligible:true,status:'POSITION_TERRAIN_SUPPORTED_PASS',position:{x:worldX,y,z:worldZ},terrainElevation:surface.visibleElevation,visibleTerrainElevation:surface.visibleElevation,clearanceReferenceElevation:visible.visibleElevation,canonicalTerrainElevation:canonicalTerrainSample.elevation,minimumCameraY:Math.max(supportY,clearanceY),targetCameraY:y,clearance:y-surface.visibleElevation,recovered:false,verticalResponseMode:'HARD_TERRAIN_SUPPORT',verticalDelta:0,clearanceSurfaceContractId:H_EARTH_VISIBLE_TERRAIN_CLEARANCE_CONTRACT_ID,protectedGeographicFloor:H_EARTH_VISIBLE_TERRAIN_CLEARANCE_PROTECTED_FLOOR,chunkId:chunk.chunkId,physicalRole:chunk.physicalRole,formationIds:chunk.formationIds,selectedSemanticAddressId:selection.selectedSemanticAddressId,selectionProjectionModel:selection.selectionProjectionModel,terrainSample:canonicalTerrainSample,visibleTerrainSample:visible,surfaceSample:surface,terrainSupported:true,issues:[]})
}
function sweepSupportedPath(state,targetX,targetZ,yawDegrees){const p=H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_PROFILE,dx=targetX-state.position.x,dz=targetZ-state.position.z,d=Math.hypot(dx,dz),n=Math.max(1,Math.ceil(d/p.sweptTerrainSampleSpacing)),samples=[];let last=state;for(let i=1;i<=n;i++){const t=i/n,r=resolveLawfulPosition({worldX:state.position.x+dx*t,worldZ:state.position.z+dz*t,yawDegrees});if(!r.eligible)return freeze({eligible:false,status:'SWEPT_TERRAIN_SUPPORT_REJECTED',issues:r.issues,samples});samples.push(r);last=r}return freeze({eligible:true,status:'SWEPT_TERRAIN_SUPPORT_PASS',result:last,samples})}
function createState({positionResult,yawDegrees,pitchDegrees,verticalFovDegrees,sequence,action,accepted,rejectionReason=null,previousY=null,sweptSampleCount=0}){const p=H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_PROFILE,verticalDelta=finite(previousY)?positionResult.position.y-previousY:0;return freeze({contractId:H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_CONTRACT_ID,cameraClearanceSuccessorContractId:H_EARTH_TERRAIN_RELATIVE_CAMERA_CLEARANCE_SUCCESSOR_CONTRACT_ID,terrainSupportedLocomotionContractId:H_EARTH_TERRAIN_SUPPORTED_LOCOMOTION_CONTRACT_ID,stateId:`H_EARTH_NAVIGATION_STATE_${String(sequence).padStart(4,'0')}`,sequence,action,accepted,recovered:false,rejectionReason,position:positionResult.position,yawDegrees:normalizeDegrees(yawDegrees),pitchDegrees:clamp(pitchDegrees,p.pitchMinimumDegrees,p.pitchMaximumDegrees),verticalFovDegrees:clamp(verticalFovDegrees,p.verticalFovMinimumDegrees,p.verticalFovMaximumDegrees),terrainElevation:positionResult.terrainElevation,visibleTerrainElevation:positionResult.visibleTerrainElevation,clearanceReferenceElevation:positionResult.clearanceReferenceElevation,canonicalTerrainElevation:positionResult.canonicalTerrainElevation,minimumCameraY:positionResult.minimumCameraY,targetCameraY:positionResult.targetCameraY,clearance:positionResult.clearance,verticalResponseMode:positionResult.verticalResponseMode,verticalDelta,verticalAcceleration:0,clearanceSurfaceContractId:positionResult.clearanceSurfaceContractId,protectedGeographicFloor:positionResult.protectedGeographicFloor,chunkId:positionResult.chunkId,physicalRole:positionResult.physicalRole,formationIds:positionResult.formationIds,selectedSemanticAddressId:positionResult.selectedSemanticAddressId,selectionProjectionModel:positionResult.selectionProjectionModel,terrainClearanceReceiptId:`H_EARTH_VISIBLE_TERRAIN_CLEARANCE_RECEIPT_${String(sequence).padStart(4,'0')}`,terrainSupported:true,sweptTerrainSupportSampleCount:sweptSampleCount,canonicalCameraStateAuthority:false,collisionOrPhysicsClaim:false,geographyAuthorityCreated:false,topologyAuthorityCreated:false,navigationScaleAuthorityCreated:false})}
export function createHEarthFunctionalLandscapeNavigationState({waypointId='COAST'}={}){const w=H_EARTH_FUNCTIONAL_LANDSCAPE_WAYPOINTS[waypointId]??H_EARTH_FUNCTIONAL_LANDSCAPE_WAYPOINTS.COAST,r=resolveLawfulPosition({worldX:w.position.x,worldZ:w.position.z,yawDegrees:w.yawDegrees});if(!r.eligible)return freeze({ok:false,status:'INITIAL_NAVIGATION_STATE_REJECTED',issues:r.issues});return freeze({ok:true,status:'INITIAL_NAVIGATION_STATE_COMPLETE',state:createState({positionResult:r,yawDegrees:w.yawDegrees,pitchDegrees:w.pitchDegrees,verticalFovDegrees:56,sequence:1,action:`GOTO_WAYPOINT:${w.waypointId}`,accepted:true}),issues:[]})}
function translationForAction(state,action,magnitude){const y=state.yawDegrees*Math.PI/180,f={x:Math.sin(y),z:-Math.cos(y)},r={x:Math.cos(y),z:Math.sin(y)};switch(action){case'MOVE_FORWARD':return{x:f.x*magnitude,z:f.z*magnitude};case'MOVE_BACKWARD':return{x:-f.x*magnitude,z:-f.z*magnitude};case'STRAFE_LEFT':return{x:-r.x*magnitude,z:-r.z*magnitude};case'STRAFE_RIGHT':return{x:r.x*magnitude,z:r.z*magnitude};default:return{x:0,z:0}}}
export function proposeHEarthFunctionalLandscapeNavigation(currentState,intent={}){if(!currentState||currentState.contractId!==H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_CONTRACT_ID)return freeze({ok:false,status:'NAVIGATION_PROPOSAL_REJECTED',state:currentState??null,issues:['CURRENT_NAVIGATION_STATE_INVALID']});const action=typeof intent.action==='string'?intent.action:'NO_OP',sequence=currentState.sequence+1,p=H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_PROFILE;let x=currentState.position.x,z=currentState.position.z,yaw=currentState.yawDegrees,pitch=currentState.pitchDegrees,fov=currentState.verticalFovDegrees;if(action==='RESET')return createHEarthFunctionalLandscapeNavigationState();if(action==='GOTO_WAYPOINT'){const w=H_EARTH_FUNCTIONAL_LANDSCAPE_WAYPOINTS[intent.waypointId];if(!w)return freeze({ok:false,status:'NAVIGATION_WAYPOINT_REJECTED',state:currentState,issues:['UNKNOWN_WAYPOINT']});const r=resolveLawfulPosition({worldX:w.position.x,worldZ:w.position.z,yawDegrees:w.yawDegrees});return freeze({ok:true,status:'NAVIGATION_PROPOSAL_ACCEPTED',state:createState({positionResult:r,yawDegrees:w.yawDegrees,pitchDegrees:w.pitchDegrees,verticalFovDegrees:fov,sequence,action,accepted:true,previousY:currentState.position.y}),issues:[]})}if(['MOVE_FORWARD','MOVE_BACKWARD','STRAFE_LEFT','STRAFE_RIGHT'].includes(action)){const magnitude=clamp(finite(intent.magnitude)?Math.abs(intent.magnitude):p.movementStepWorldUnits,0,p.maximumMovementIntentWorldUnits),d=translationForAction(currentState,action,magnitude);x+=d.x;z+=d.z}else if(action==='TURN_LEFT')yaw-=clamp(finite(intent.degrees)?Math.abs(intent.degrees):p.turnStepDegrees,0,8);else if(action==='TURN_RIGHT')yaw+=clamp(finite(intent.degrees)?Math.abs(intent.degrees):p.turnStepDegrees,0,8);else if(action==='PITCH_UP')pitch+=clamp(finite(intent.degrees)?Math.abs(intent.degrees):p.pitchStepDegrees,0,8);else if(action==='PITCH_DOWN')pitch-=clamp(finite(intent.degrees)?Math.abs(intent.degrees):p.pitchStepDegrees,0,8);else if(action==='ZOOM_IN')fov-=clamp(finite(intent.degrees)?Math.abs(intent.degrees):3,0,6);else if(action==='ZOOM_OUT')fov+=clamp(finite(intent.degrees)?Math.abs(intent.degrees):3,0,6);else if(action==='SET_CAMERA_POSITION'){x=intent.position?.x;z=intent.position?.z}
  const translated=Math.hypot(x-currentState.position.x,z-currentState.position.z)>1e-9,sweep=translated?sweepSupportedPath(currentState,x,z,yaw):null,r=translated?(sweep.eligible?sweep.result:null):resolveLawfulPosition({worldX:x,worldZ:z,yawDegrees:yaw});if(!r?.eligible)return freeze({ok:false,status:'NAVIGATION_PROPOSAL_REJECTED_STATE_PRESERVED',state:currentState,issues:sweep?.issues??r?.issues??['TERRAIN_SUPPORT_REJECTED']});const state=createState({positionResult:r,yawDegrees:yaw,pitchDegrees:pitch,verticalFovDegrees:fov,sequence,action,accepted:true,previousY:currentState.position.y,swe