export const SCENE_SPEC = Object.freeze({
  sceneId: "DGB_LAWS_GEOMETRIC_GRAMMAR_SYNTHETIC_COMMONS_CROSSING_v1",
  pageFamily: "ORIENTATION_AND_METHOD_RESEARCH_PROTOTYPE",
  primaryQuestion: "Can a shared crossing reopen without sacrificing safety, trust, or traceability?",
  evidenceStatus: "SYNTHETIC_ILLUSTRATIVE_FIXTURE",
  assumptions: [
    "The scenario is fictional.",
    "The displayed relationship is definitional for prototype testing only.",
    "No object size, brightness, speed, or settlement state communicates evidence strength.",
    "The DOM owns content and actions; the renderer owns presentation only."
  ],
  variables: {
    capacity: { id: "C", label: "Current capacity", min: 0, max: 10, value: 7 },
    pressure: { id: "P", label: "Unresolved pressure", min: 0, max: 10, value: 4 },
    available: { id: "A", label: "Available choice space", expression: "max(0, C - P)" }
  },
  cameraContract: {
    mode: "STABLE_ORIENTATION_WITH_STAGE_FOCUS",
    automaticTravel: "OPTIONAL_BOUNDED_STAGE_SETTLEMENT",
    userInterrupt: true,
    returnToOrientation: true,
    evidenceSignalProhibited: true
  },
  interactionContract: {
    semanticAuthority: "DOM_CONTROLS",
    pointer: true,
    keyboard: true,
    touch: true,
    dragRequired: false,
    stateRestore: true
  },
  motion: {
    full: "BOUNDED_STAGE_SETTLEMENT_AND_RELATIONSHIP_DEFORMATION",
    reduced: "DIRECT_STATE_SUBSTITUTION_WITH_SHORT_CROSSFADE",
    static: "LABELED_SVG_RELATIONSHIP_MAP"
  },
  mobileDegradation: [
    "Preserve primary relationship",
    "Use one active stage at a time",
    "Limit camera freedom",
    "Preserve full DOM interpretation and audit text"
  ],
  longDescription: "The Commons Crossing scene centers a gold crystal that represents a stable promise: shared access must remain safe, trustworthy, and traceable. A bounded field represents unresolved pressure such as demand, delay, uncertainty, and competing needs. A path curves through two gates toward a wireframe volume that represents the choices still available under the declared assumptions. A lattice connects supporting records. A fracture marks an explicit contradiction rather than generic failure. An orbit represents recurring review and return. A layered ledger preserves each transition. The scene is synthetic and does not describe a real bridge, engineering determination, community decision, dataset, or validated law.",
  primitives: [
    {
      id: "field",
      index: 1,
      label: "Field",
      shortLabel: "Pressure",
      semanticMeaning: "FORCE_CONSTRAINT_INFLUENCE_ENVIRONMENTAL_CONDITION_PRESSURE",
      storyTitle: "Pressure enters the commons.",
      practical: "Demand, delay, uncertainty, and competing needs alter what choices remain available. The stable promise is not the same thing as the conditions acting upon it.",
      trajectory: "When unresolved pressure keeps increasing, the practical path bends, narrows, or closes even if the stated commitment remains unchanged.",
      engineeringTitle: "A bounded field acts on a path.",
      engineering: "The scene specification declares the field source, target, distribution, boundary, and status. The renderer consumes that record; it does not infer meaning from color, motion, or shape.",
      relation: "FIELD ACTS_ON PATH",
      motionPurpose: "DEFORMATION",
      staticEquivalent: "Bounded gradient with curved path",
      empirical: "The scenario is synthetic. The field is an illustrative condition, not a measured force or observed environmental variable.",
      color: "#68e4ff"
    },
    {
      id: "path",
      index: 2,
      label: "Path",
      shortLabel: "Path",
      semanticMeaning: "PROCESS_ORDERED_SEQUENCE_TRAJECTORY_INVESTIGATION_STATE_TRANSITION",
      storyTitle: "A declared promise becomes a traversable sequence.",
      practical: "A goal becomes actionable only when the route, order, branches, reversals, and stopping conditions are visible.",
      trajectory: "An undefined route creates motion without accountable progress. A declared route makes both advancement and interruption inspectable.",
      engineeringTitle: "An ordered curve exposes state progression.",
      engineering: "The path record declares direction, branch points, reversibility, and termination. Stage focus changes emphasis without changing the route definition.",
      relation: "PATH PASSES_THROUGH GATE",
      motionPurpose: "PATH_TRAVERSAL",
      staticEquivalent: "Numbered route with explicit branch and stop markers",
      empirical: "No real process duration, success rate, or causal sequence is represented.",
      color: "#f5d36b"
    },
    {
      id: "gate",
      index: 3,
      label: "Gate",
      shortLabel: "Gate",
      semanticMeaning: "ADMISSION_REJECTION_TRANSITION_THRESHOLD_TEST_CONDITION",
      storyTitle: "The route advances only through inspectable conditions.",
      practical: "A gate protects the promise from being replaced by urgency. Pass, fail, and unresolved are different outcomes and must remain different.",
      trajectory: "When failed or unresolved conditions are treated as permission, the route may continue while its foundation has already been lost.",
      engineeringTitle: "Every gate corresponds to an explicit predicate.",
      engineering: "The synthetic gate exposes input, condition, pass result, fail result, and unresolved result. No portal-like object is admitted without a predicate.",
      relation: "GATE ADMITS_OBJECT_INTO VOLUME",
      motionPurpose: "GATE_TRANSITION",
      staticEquivalent: "Predicate card with pass, fail, and unresolved branches",
      empirical: "The predicate is illustrative and is not a certification standard.",
      color: "#71e3ba"
    },
    {
      id: "lattice",
      index: 4,
      label: "Lattice",
      shortLabel: "Structure",
      semanticMeaning: "TYPED_RELATIONSHIPS_DEPENDENCY_VARIABLE_CORRESPONDENCE_LAW_TO_EVIDENCE_CONNECTION_MULTI_AUTHORITY_STRUCTURE",
      storyTitle: "Support is a structure, not a pile.",
      practical: "A decision becomes trustworthy when each dependency, contradiction, and source relationship can be named rather than merely accumulated.",
      trajectory: "More records do not necessarily create stronger support. Untyped connections can hide conflict and make weak foundations appear dense.",
      engineeringTitle: "Nodes and edges carry declared types.",
      engineering: "The lattice differentiates supports, constrains, contradicts, and derives-from relationships. A visual network without typed edges would fail the scene contract.",
      relation: "LATTICE CONNECTS CRYSTALS_AND_LEDGERS",
      motionPurpose: "CONVERGENCE_AND_DIVERGENCE",
      staticEquivalent: "Labeled dependency graph",
      empirical: "No real source network or evidence weight is represented.",
      color: "#9f82ff"
    },
    {
      id: "volume",
      index: 5,
      label: "Volume",
      shortLabel: "Available future",
      semanticMeaning: "BOUNDED_STATE_SPACE_CAPACITY_RECOVERABILITY_ADMISSIBILITY_FEASIBLE_REGION_UNCERTAINTY_ENVELOPE",
      storyTitle: "Choices occupy a bounded future.",
      practical: "Capacity and unresolved pressure do not merely change confidence; they change which actions remain available without abandoning the promise.",
      trajectory: "As available space contracts, later choices become more expensive, more fragile, or inaccessible. Relief can reopen paths without rewriting the original commitment.",
      engineeringTitle: "A wireframe volume maps the illustrative choice space.",
      engineering: "The volume scale is generated from the structured formula record A = max(0, C - P). Dimensional display is explanatory and does not imply three measured variables.",
      relation: "GATE ADMITS_OBJECT_INTO VOLUME",
      motionPurpose: "VOLUME_EXPANSION_OR_CONTRACTION",
      staticEquivalent: "Before-and-after bounded region",
      empirical: "The volume is not an observed feasible region and has no statistical interpretation.",
      color: "#68e4ff"
    },
    {
      id: "orbit",
      index: 6,
      label: "Orbit",
      shortLabel: "Return",
      semanticMeaning: "RECURRENCE_CYCLE_CORRESPONDENCE_CONTEXTUAL_RELATIONSHIP_RETURN",
      storyTitle: "Accountability requires return.",
      practical: "A one-time pass is not permanent permission. The crossing returns to review because conditions, use, and responsibility change over time.",
      trajectory: "Systems that cannot return to their evidence gradually substitute memory, status, or confidence for inspection.",
      engineeringTitle: "The orbit represents scheduled recurrence.",
      engineering: "The orbit is a declared return relationship, not perpetual decorative rotation. Full motion uses one bounded revolution during stage activation; reduced motion uses fixed review markers.",
      relation: "ORBIT RETURNS_OBJECT_TO CONTEXT",
      motionPurpose: "ORBITAL_CORRESPONDENCE",
      staticEquivalent: "Fixed review cycle with return arrows",
      empirical: "No real maintenance interval or recurrence period is asserted.",
      color: "#f5d36b"
    },
    {
      id: "fracture",
      index: 7,
      label: "Fracture",
      shortLabel: "Contradiction",
      semanticMeaning: "CONTRADICTION_DIVERGENCE_FAILED_CONTINUITY_LOST_SUPPORT_STRUCTURAL_INCOHERENCE",
      storyTitle: "Contradiction breaks a relationship, not the whole world.",
      practical: "A failed condition should expose the exact continuity that was lost. It should not turn every disagreement into spectacle or total collapse.",
      trajectory: "When contradictions are hidden, incompatible claims remain joined until later decisions inherit the conflict.",
      engineeringTitle: "A typed fracture severs one declared relation.",
      engineering: "The fracture appears only where two synthetic records cannot remain jointly coherent. It closes a path edge rather than triggering an explosion.",
      relation: "FRACTURE BREAKS_LATTICE_OR_PATH",
      motionPurpose: "SEPARATION",
      staticEquivalent: "Broken edge with contradiction label",
      empirical: "No real contradiction, fault, or failure event is represented.",
      color: "#ff778d"
    },
    {
      id: "crystal",
      index: 8,
      label: "Crystal",
      shortLabel: "Invariant",
      semanticMeaning: "STABLE_IDENTITY_INVARIANT_RESOLVED_AUTHORITY_PERSISTENT_STRUCTURE",
      storyTitle: "The promise remains identifiable under change.",
      practical: "The stable center is not a claim of perfection. It is the part of the commitment that must remain recognizable while applications, conditions, and decisions change.",
      trajectory: "Without a stable identity, adaptation can quietly become replacement. With one, change can be judged against what it was meant to preserve.",
      engineeringTitle: "Invariant geometry anchors the scene.",
      engineering: "The crystal keeps a stable mesh identity while orientation, illumination, surrounding field, and stage emphasis change.",
      relation: "FIELD ACTS_ON CRYSTAL_WITHOUT_REDEFINING IT",
      motionPurpose: "STATE_SETTLEMENT",
      staticEquivalent: "Stable central marker across all stage diagrams",
      empirical: "Crystal form does not indicate proof, certainty, validation, or material composition.",
      color: "#ffb44f"
    },
    {
      id: "ledger",
      index: 9,
      label: "Ledger",
      shortLabel: "Record",
      semanticMeaning: "CUSTODY_PROVENANCE_VERSION_RESULT_DEPENDENCY_HISTORY_AUDIT_RECORD",
      storyTitle: "What happened remains traceable after the scene settles.",
      practical: "A durable decision preserves the sequence of conditions, changes, outcomes, and unresolved questions so later reviewers can return without reconstructing history from memory.",
      trajectory: "When lineage disappears, each new decision starts by renegotiating what the previous decision meant.",
      engineeringTitle: "Layered records preserve exact transition lineage.",
      engineering: "The ledger stores stage IDs, parameter state, motion mode, visible objects, context status, and errors. Spatial layering reveals sequence but never replaces readable text.",
      relation: "LEDGER RECORDS_EACH_TRANSITION",
      motionPurpose: "ASSEMBLY",
      staticEquivalent: "Ordered version lineage with stable identifiers",
      empirical: "The ledger records prototype state only and is not a scientific receipt.",
      color: "#c7d4ff"
    }
  ],
  typedRelationships: [
    ["field", "ACTS_ON", "path"],
    ["field", "ACTS_ON", "crystal"],
    ["path", "PASSES_THROUGH", "gate"],
    ["gate", "ADMITS_INTO", "volume"],
    ["lattice", "CONNECTS", "crystal"],
    ["lattice", "CONNECTS", "ledger"],
    ["fracture", "BREAKS", "lattice"],
    ["orbit", "RETURNS_TO", "crystal"],
    ["ledger", "RECORDS", "path"]
  ]
});
