const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const source=fs.readFileSync(__dirname+'/atmosphere.js','utf8');
function harness({reduced=false}={}){
 let now=0,id=0,audioCount=0,playResolve;
 const timers=new Map(),rafs=new Map(),media=[];
 class Target{constructor(){this.events={};this.style={};this.dataset={};this.attrs={};this.children=[];this.isConnected=false}addEventListener(k,f){(this.events[k]??=[]).push(f)}dispatchEvent(e){for(const f of this.events[e.type]||[])f(e)}emit(k){this.dispatchEvent({type:k})}setAttribute(k,v){this.attrs[k]=v}append(c){this.children.push(c);c.isConnected=true}querySelector(){return null}insertAdjacentElement(_,c){this.append(c)}getContext(){return new Proxy({},{get:()=>()=>{}})}}
 const doc=new Target(),win=new Target(),mount=new Target(),finale=new Target(),pause=new Target(),sound=new Target(),pauseFooter=new Target(),soundFooter=new Target(),main=new Target();
 doc.hidden=false;doc.readyState='complete';doc.documentElement={clientWidth:390,clientHeight:844};doc.createElement=()=>new Target();doc.querySelector=s=>s==='[data-dgb-fibonacci-cosmos]'?mount:s==='[data-analytics-finale]'?finale:s==='[data-effects-pause]'?pause:s==='[data-fireworks-sound]'?sound:s==='main'?main:null;doc.querySelectorAll=s=>s==='[data-effects-pause]'?[pause,pauseFooter]:s==='[data-fireworks-sound]'?[sound,soundFooter]:[];
 const queries={};const matchMedia=q=>queries[q]??=(Object.assign(new Target(),{matches:q.includes('reduced')?reduced:true}));
 let observer;
 class IO{constructor(fn){observer=fn}observe(){}}
 class Audio extends Target{constructor(){super();audioCount++;media.push(this);this.paused=true}play(){this.paused=false;return new Promise(resolve=>{playResolve=resolve})}pause(){this.paused=true}}
 const context=vm.createContext({document:doc,window:{matchMedia},matchMedia,innerWidth:390,innerHeight:844,devicePixelRatio:3,navigator:{hardwareConcurrency:4},performance:{now:()=>now},console,Audio,IntersectionObserver:IO,Event:class{constructor(type){this.type=type}},addEventListener:win.addEventListener.bind(win),setTimeout:(fn,delay)=>{timers.set(++id,{fn,at:now+delay});return id},clearTimeout:i=>timers.delete(i),setInterval:(fn,delay)=>{timers.set(++id,{fn,at:now+delay,interval:delay});return id},clearInterval:i=>timers.delete(i),requestAnimationFrame:fn=>{rafs.set(++id,fn);return id},cancelAnimationFrame:i=>rafs.delete(i)});
 vm.runInContext(source,context);
 return{timers,rafs,mount,pause,sound,pauseFooter,soundFooter,main,context,media,get audioCount(){return audioCount},rerun:()=>vm.runInContext(source,context),resolveAudio:async()=>{playResolve?.();await Promise.resolve();await Promise.resolve()},hidden:v=>{doc.hidden=v;doc.emit('visibilitychange')},motion:v=>{queries['(prefers-reduced-motion: reduce)'].matches=v;queries['(prefers-reduced-motion: reduce)'].emit('change')},finale:()=>observer([{isIntersecting:true,intersectionRatio:1}]),page:k=>win.emit(k),tick:ms=>{const end=now+ms;let n=0;while(true){let next=[...timers.entries()].filter(([,t])=>t.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!next)break;assert.ok(n++<1000);const[i,t]=next;now=t.at;timers.delete(i);if(t.interval)timers.set(i,{...t,at:now+t.interval});t.fn()}now=end},frame:()=>{const frames=[...rafs.values()];rafs.clear();now+=16;frames.forEach(f=>f(now))}};
}
test('single init, lazy audio, and source mobile density caps',()=>{const h=harness();assert.equal(h.audioCount,0);assert.equal(h.mount.children.length,3);assert.equal(h.mount.children[0].width,390);h.rerun();assert.equal(h.mount.children.length,3);assert.equal(h.audioCount,0)});
test('reduced motion retains static stars without timers or fireworks',()=>{const h=harness({reduced:true});assert.equal(h.timers.size,0);assert.equal(h.rafs.size,0);assert.equal(h.mount.children.length,3);h.sound.emit('click');assert.equal(h.audioCount,0);h.motion(false);assert.ok(h.timers.size>0)});
for(const mode of ['hidden','motion','page','pause'])test(mode+' interrupts finale, clears work and resumes without replay',()=>{const h=harness();h.finale();assert.ok(h.timers.size>=23);if(mode==='page')h.page('pagehide');else if(mode==='pause')h.pause.emit('click');else h[mode](true);assert.equal(h.timers.size,0);assert.equal(h.rafs.size,0);if(mode==='page')h.page('pageshow');else if(mode==='pause')h.pause.emit('click');else h[mode](false);assert.ok(h.timers.size>0&&h.timers.size<5);h.finale();assert.ok(h.timers.size<5);h.tick(5500);assert.ok(h.rafs.size>0);h.frame()});
test('pending sound cannot enable after hiding and stays off on return',async()=>{const h=harness();h.sound.emit('click');assert.equal(h.audioCount,1);h.hidden(true);await h.resolveAudio();assert.equal(h.sound.attrs['aria-pressed'],'false');assert.equal(h.media[0].paused,true);h.hidden(false);assert.equal(h.sound.attrs['aria-pressed'],'false')});
test('rapid sound toggle cancels pending enable; media error resets UI',async()=>{const h=harness();h.sound.emit('click');h.sound.emit('click');await h.resolveAudio();assert.equal(h.sound.attrs['aria-pressed'],'false');assert.equal(h.media[0].paused,true);h.sound.emit('click');h.media[0].emit('error');await h.resolveAudio();assert.equal(h.sound.textContent,'Fireworks sound unavailable');assert.equal(h.sound.attrs['aria-pressed'],'false')});

test('fireworks layer is above panel surfaces and below foreground text',()=>{const h=harness();assert.equal(h.main.style.zIndex,'auto');assert.equal(h.mount.children[2].style.zIndex,'1');assert.equal(h.mount.children[2].style.pointerEvents,'none')});
test('top and footer controls stay synchronized',async()=>{const h=harness();h.pause.emit('click');assert.equal(h.pauseFooter.attrs['aria-pressed'],'true');assert.equal(h.soundFooter.disabled,true);h.pauseFooter.emit('click');assert.equal(h.pause.attrs['aria-pressed'],'false');h.soundFooter.emit('click');await h.resolveAudio();assert.equal(h.sound.attrs['aria-pressed'],'true');assert.equal(h.soundFooter.attrs['aria-pressed'],'true');h.sound.emit('click');assert.equal(h.soundFooter.attrs['aria-pressed'],'false')});
