import {buildFAP1SpatialWeatherObjects,evaluateFAP1SpatialLOD} from './fap1-spatial-lod.gb.mjs';
import {createW5LocalRayMarchSurface,verifyW5LocalRayMarchReceipt} from './fap1-w5-local-raymarch.gc-v6-macro-locked.mjs';

const freeze=v=>Object.freeze(v),clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
export const FAP1_W5_HANDOFF_SCHEMA='FAP1_W5_HANDOFF_v4_24049_MACRO_LOCKED_PROXIMITY_ONLY';
export const HANDOFF_MIN_RAW_LOCAL_WEIGHT=.55;
export const HANDOFF_LOCAL_DOMINANT_WEIGHT=.72;

function proximityWeight(entry){const raw=clamp(entry?.alpha?.l??0,0,1);return raw<HANDOFF_MIN_RAW_LOCAL_WEIGHT?0:clamp((raw-HANDOFF_MIN_RAW_LOCAL_WEIGHT)/(1-HANDOFF_MIN_RAW_LOCAL_WEIGHT),0,1);}
function contributionFor(entry){const local=proximityWeight(entry);return freeze({macro:1-local,local,rawLocal:clamp(entry?.alpha?.l??0,0,1),regime:local<=0?'MACRO_LOCKED':local>=HANDOFF_LOCAL_DOMINANT_WEIGHT?'LOCAL_DOMINANT':'MACRO_LOCAL_OVERLAP'});}
function carveoutFor(entry,weight){const v=entry.object.V_i;return freeze({weatherId:entry.object.ID_i,center:v.center,axisU:v.axisU,axisUp:v.axisUp,axisV:v.axisV,radii:v.radii,weight});}

export function createBoundedW5Handoff({worldCanvas,parentReceipt,gaAuthority,getSunDirection}={}){
  if(!(worldCanvas instanceof HTMLCanvasElement))throw new Error('FAP1_W5_HANDOFF_WORLD_CANVAS_REQUIRED');
  if(!parentReceipt||typeof parentReceipt.getCameraFrame!=='function')throw new Error('FAP1_W5_HANDOFF_PARENT_RECEIPT_REQUIRED');
  if(!gaAuthority||typeof gaAuthority.descriptorPacket!=='function'||typeof gaAuthority.renderNow!=='function')throw new Error('FAP1_W5_HANDOFF_GA_AUTHORITY_REQUIRED');
  if(typeof gaAuthority.setLocalCarveout!=='function'||typeof gaAuthority.clearLocalCarveout!=='function')throw new Error('FAP1_W5_SPATIAL_CARVEOUT_AUTHORITY_REQUIRED');
  const localSurface=createW5LocalRayMarchSurface({worldCanvas});let lastReceipt=null,quality='REST',lastCarveoutKey='NONE';
  function syncCarveout(active,weight){
    if(!active){if(lastCarveoutKey!=='NONE'){gaAuthority.clearLocalCarveout();gaAuthority.renderNow();lastCarveoutKey='NONE';}return;}
    const quant=Math.round(weight*20)/20,key=`${active.object.ID_i}:${quant.toFixed(2)}`;
    if(key!==lastCarveoutKey){gaAuthority.setLocalCarveout(carveoutFor(active,quant));gaAuthority.renderNow();lastCarveoutKey=key;}
  }
  function render(){
    const camera=parentReceipt.getCameraFrame(),packet=gaAuthority.descriptorPacket()??gaAuthority.renderNow(),objects=buildFAP1SpatialWeatherObjects({packet}),spatialState=evaluateFAP1SpatialLOD(objects,camera);
    const promoted=spatialState.objects.filter(e=>e.localPromoted===true&&e.Q_i===true&&proximityWeight(e)>0).sort((a,b)=>proximityWeight(b)-proximityWeight(a)||a.distanceToVolume-b.distanceToVolume||a.object.ID_i.localeCompare(b.object.ID_i));
    const active=promoted[0]??null,sunDirection=typeof getSunDirection==='function'?getSunDirection():[.42,.78,.46];
    if(!active){syncCarveout(null,0);const localReceipt=localSurface.render({camera,spatialState,sunDirection,quality});lastReceipt=freeze({schema:FAP1_W5_HANDOFF_SCHEMA,active:false,weatherId:null,regime:'MACRO_LOCKED',rawLocalWeight:0,localWeight:0,macroContribution:1,localContribution:0,contributionSum:1,persistentWeatherIdentity:true,macroWeatherFrozen:true,macroReference:'24049',macroMassPreservationLaw:'NO_W5_PARTICIPATION_BEFORE_TRUE_PROXIMITY',spatialCarveoutActive:false,macroOutsideLocalVolumePreserved:true,l5LightingActive:true,l5LightingModel:localReceipt.l5LightingModel,l5Quality:localReceipt.quality,l5LightSteps:localReceipt.lightSteps,performancePolicy:'CACHED_BRICK_PLUS_PROXIMITY_ONLY',handoffAuthority:'BOUNDED_GB_HANDOFF_ACTIVE'});return lastReceipt;}
    const contribution=contributionFor(active);syncCarveout(active,contribution.local);const localReceipt=localSurface.render({camera,spatialState,sunDirection,quality}),verification=verifyW5LocalRayMarchReceipt(localReceipt);if(!verification.pass)throw new Error(`FAP1_W5_HANDOFF_LOCAL_SURFACE_INVALID:${verification.failures.join(',')}`);
    lastReceipt=freeze({schema:FAP1_W5_HANDOFF_SCHEMA,active:true,weatherId:active.object.ID_i,regime:contribution.regime,rawLocalWeight:contribution.rawLocal,localWeight:contribution.local,macroContribution:contribution.macro,localContribution:contribution.local,contributionSum:1,persistentWeatherIdentity:localReceipt.weatherId===active.object.ID_i,localBrickAddress:localReceipt.brickAddress??null,macroWeatherFrozen:true,macroReference:'24049',macroMassPreservationLaw:'24049_MACRO_UNCHANGED_UNTIL_TRUE_PROXIMITY_THEN_LOCAL_SPATIAL_SPLIT',spatialCarveoutActive:true,spatialCarveoutWeatherId:active.object.ID_i,spatialCarveoutRadii:active.object.V_i.radii,macroOutsideLocalVolumePreserved:true,macroRendererWeatherAuthority:'FAP1_ONLY',localRendererWeatherAuthority:'FAP1_DESCRIPTOR_REFINEMENT_ONLY',canonicalDensityPreserved:true,macroCloudTuning:false,l5LightingActive:true,l5LightingModel:localReceipt.l5LightingModel,l5DensityAuthority:localReceipt.l5DensityAuthority??'W5_FAP1_REFINEMENT',l5Quality:localReceipt.quality,l5LightSteps:localReceipt.lightSteps,densityTextureFormat:localReceipt.densityTextureFormat??null,localSpatialHandoffMask:localReceipt.spatialHandoffMask===true,multipleScattering:false,groundContribution:false,performancePolicy:'CACHED_BRICK_PLUS_QUANTIZED_CARVEOUT',handoffAuthority:'BOUNDED_GB_HANDOFF_ACTIVE'});return lastReceipt;
  }
  return freeze({schema:FAP1_W5_HANDOFF_SCHEMA,render,setQuality(v){quality=v==='CAPTURE'?'CAPTURE':v==='INTERACTIVE'?'INTERACTIVE':'REST';localSurface.setQuality(quality);},getReceipt:()=>lastReceipt,beginInteraction(){quality='INTERACTIVE';localSurface.beginInteraction();},endInteraction(){quality='REST';localSurface.endInteraction();},destroy(){gaAuthority.clearLocalCarveout();gaAuthority.renderNow();localSurface.destroy();}});
}
export function verifyBoundedW5Handoff(r,epsilon=1e-6){const failures=[];if(r?.persistentWeatherIdentity!==true)failures.push('PERSISTENT_WEATHER_IDENTITY_FAILED');if(Math.abs((r?.contributionSum??NaN)-1)>epsilon)failures.push('CONTRIBUTION_SUM_NOT_ONE');if(r?.macroWeatherFrozen!==true||r?.macroReference!=='24049')failures.push('24049_MACRO_FREEZE_FAILED');if(r?.macroOutsideLocalVolumePreserved!==true)failures.push('MACRO_OUTSIDE_LOCAL_VOLUME_NOT_PRESERVED');if(r?.active&&r?.canonicalDensityPreserved!==true)failures.push('CANONICAL_DENSITY_NOT_PRESERVED');if(r?.macroCloudTuning===true)failures.push('MACRO_TUNING_FORBIDDEN');if(r?.l5LightingActive!==true||r?.l5LightingModel!=='DIRECT_SUN_TRANSMITTANCE_ONLY')failures.push('L5_SCOPE_INVALID');if(!Number.isInteger(r?.l5LightSteps)||![3,5,8].includes(r.l5LightSteps))failures.push('L5_LIGHT_STEP_SCHEDULE_INVALID');if(r?.active&&r?.densityTextureFormat!=='R8_UNORM_LINEAR')failures.push('W5_TEXTURE_INVALID');if(r?.multipleScattering===true||r?.groundContribution===true)failures.push('L5_SCOPE_EXPANSION_FORBIDDEN');if(r?.handoffAuthority!=='BOUNDED_GB_HANDOFF_ACTIVE')failures.push('HANDOFF_AUTHORITY_MISSING');return freeze({schema:'FAP1_W5_HANDOFF_INVARIANTS_v4',pass:failures.length===0,failures:freeze(failures),weatherId:r?.weatherId??null});}
