import {localCoordinates,weatherBrickAddress} from './fap1-spatial-lod.gb.mjs';

const freeze=value=>Object.freeze(value);
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const smooth=(a,b,v)=>{const t=clamp((v-a)/(b-a||1),0,1);return t*t*(3-2*t);};
const mix=(a,b,t)=>a+(b-a)*t;
const dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];

export const FAP1_W5_LOCAL_DENSITY_SCHEMA='FAP1_W5_LOCAL_DENSITY_REFINEMENT_v6_MESO_BODY_DIFFERENTIATION';
export const W5_GENERATION=6;
export const W5_BRICK_RESOLUTION=16;
export const W5_MAX_ACTIVE_OBJECTS=1;
export const W5_EMPTY_THRESHOLD=0.0025;

function hash32(value){let h=2166136261;for(const ch of String(value)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
function hashUnit(x,y,z,seed){let h=(hash32(seed)^Math.imul((x|0)+4099,374761393)^Math.imul((y|0)+8191,668265263)^Math.imul((z|0)+12289,2246822519))>>>0;h^=h>>>13;h=Math.imul(h,1274126177);h^=h>>>16;return(h>>>0)/4294967295;}
function valueNoise3(x,y,z,seed){const ix=Math.floor(x),iy=Math.floor(y),iz=Math.floor(z),fx=x-ix,fy=y-iy,fz=z-iz,sx=fx*fx*(3-2*fx),sy=fy*fy*(3-2*fy),sz=fz*fz*(3-2*fz),n=(dx,dy,dz)=>hashUnit(ix+dx,iy+dy,iz+dz,seed),x00=mix(n(0,0,0),n(1,0,0),sx),x10=mix(n(0,1,0),n(1,1,0),sx),x01=mix(n(0,0,1),n(1,0,1),sx),x11=mix(n(0,1,1),n(1,1,1),sx);return mix(mix(x00,x10,sy),mix(x01,x11,sy),sz);}
function fbm3(x,y,z,seed){let sum=0,amp=.58,norm=0,scale=1;for(let octave=0;octave<4;octave++){sum+=valueNoise3(x*scale,y*scale,z*scale,seed+octave*1013)*amp;norm+=amp;scale*=2.03;amp*=.48;}return sum/(norm||1);}
function hash31(x,y,z){let px=x*.1031-Math.floor(x*.1031),py=y*.1031-Math.floor(y*.1031),pz=z*.1031-Math.floor(z*.1031);const d=px*(py+33.33)+py*(pz+33.33)+pz*(px+33.33);px+=d;py+=d;pz+=d;const value=(px+py)*pz;return value-Math.floor(value);}
function macroNoise3(x,y,z){const ix=Math.floor(x),iy=Math.floor(y),iz=Math.floor(z),fx=x-ix,fy=y-iy,fz=z-iz,sx=fx*fx*(3-2*fx),sy=fy*fy*(3-2*fy),sz=fz*fz*(3-2*fz),n=(dx,dy,dz)=>hash31(ix+dx,iy+dy,iz+dz),a=mix(n(0,0,0),n(1,0,0),sx),b=mix(n(0,1,0),n(1,1,0),sx),c=mix(n(0,0,1),n(1,0,1),sx),d=mix(n(0,1,1),n(1,1,1),sx);return mix(mix(a,b,sy),mix(c,d,sy),sz);}
function macroFbm(x,y,z){return macroNoise3(x,y,z)*.62+macroNoise3(x*2.07+5.3,y*2.07+1.7,z*2.07+9.2)*(.62*.48);}
function verticalEnvelope(z){return smooth(0,.075,z)*(1-smooth(.86,1,z));}
function genusCode(genus){return({Ci:0,Cc:1,Cs:2,Ac:3,As:4,Ns:5,Sc:6,St:7,Cu:8,Cb:9})[genus]??8;}
function rand(seed,index){return hashUnit(index*7+3,index*11+5,index*13+9,seed);}

function macroCoordinates(worldPoint,object){const d=[worldPoint[0]-object.V_i.center[0],worldPoint[1]-object.V_i.center[1],worldPoint[2]-object.V_i.center[2]],r=object.F_i?.macroRadii;if(!Array.isArray(r)||r.length!==3)throw new Error('FAP1_W5_MACRO_RADII_REQUIRED');return[dot(d,object.V_i.axisU)/r[0],dot(d,object.V_i.axisUp)/r[1],dot(d,object.V_i.axisV)/r[2]];}
function macroAnchorShape(object,q){const x=q[0],vertical=q[1],y=q[2],z=clamp((vertical+1)*.5,0,1),r=Math.hypot(x,y),mr=object.F_i.macroRadii,fs=clamp(Math.sqrt(Math.max(mr[0]*mr[2],1))/260,1,9),qx=x*fs,qy=y*fs,seed=object.W_i.seed??0,n=macroFbm(qx*2.15+seed*19,qy*2.15,z*3.2),v=verticalEnvelope(z),g=genusCode(object.W_i.genus);let shape=0;if(g<2.5){const veil=.5+.5*Math.sin(qx*1.55+qy*.72+seed*7+n*2.2);shape=(1-smooth(.70,1.08,r))*v*smooth(.32,.63,n+.12*veil)*.44;}else if(g<4.5){const cells=.5+.5*Math.sin(qx*2.7+n*2.4)*Math.cos(qy*2.3);shape=(1-smooth(.70,1.08,r))*v*smooth(.39,.66,n+.18*cells)*.60;}else if(g<7.5){const sheet=.5+.5*Math.sin(qx*1.35+qy*.47+seed*5);shape=(1-smooth(.70,1.08,r))*v*smooth(.35,.62,n+.10*sheet)*.68;}else if(g<8.5){const taper=mix(1,.48,smooth(.08,.95,z)),cell=.5+.5*Math.sin(qx*2.6+seed*9)*Math.cos(qy*2.35);shape=(1-smooth(taper*.65,taper*1.08,r))*v*smooth(.44,.66,n+.22*cell)*.88;}else{const taper=mix(.90,.39,smooth(.05,.72,z)),cell=.5+.5*Math.sin(qx*2.2+seed*7)*Math.cos(qy*2),tower=(1-smooth(taper*.62,taper*1.10,r))*v*smooth(.39,.62,n+.20*cell),anvilBand=smooth(.62,.76,z)*(1-smooth(.95,1,z)),anvil=(1-smooth(.48,1.32,r))*anvilBand*smooth(.34,.59,n+.14*cell)*.76;shape=Math.max(tower,anvil);if(object.weatherClass==='CYCLONE'){const eye=1-smooth(.10,.19,r),wall=smooth(.12,.22,r)*(1-smooth(.31,.46,r));shape=Math.max(shape,wall*.64*v);shape*=1-eye*.985;}}return clamp(shape,0,1.8);}

function bodyCount(cls){return cls==='LOW_CUMULIFORM'?7:cls==='DEEP_CONVECTION'?6:cls==='CYCLONE'?7:cls==='MID_FRONTAL'?5:cls==='HIGH_ICE'?4:5;}
function buildMesoBodies(object){const cls=object.weatherClass,seed=hash32(`${object.ID_i}:MESO`),count=bodyCount(cls),out=[];for(let i=0;i<count;i++){const a=rand(seed,i*9),b=rand(seed,i*9+1),c=rand(seed,i*9+2),d=rand(seed,i*9+3),e=rand(seed,i*9+4),f=rand(seed,i*9+5);let center=[(a-.5)*1.1,(b-.5)*.5,(c-.5)*1.1],radii=[.30+.15*d,.25+.14*e,.30+.15*f],role='BODY';if(cls==='LOW_CUMULIFORM'){center=[(a-.5)*1.24,(b-.5)*.30-.04,(c-.5)*1.24];radii=[.20+.13*d,.15+.11*e,.20+.13*f];role=i<3?'PRIMARY_COMPLEX':i<5?'SECONDARY_COMPLEX':'PERIPHERAL_FRAGMENT';}else if(cls==='DEEP_CONVECTION'){center=[(a-.5)*1.02,(b-.5)*.42-.02,(c-.5)*1.02];radii=i===0?[.29,.68,.29]:[.18+.11*d,.30+.28*e,.18+.11*f];role=i===0?'PRIMARY_TOWER':i<4?'SUBSIDIARY_TOWER':'SHOULDER';}else if(cls==='CYCLONE'){const angle=i/count*Math.PI*2+(a-.5)*.34,ring=.42+.18*b;center=[Math.cos(angle)*ring,(c-.5)*.24,Math.sin(angle)*ring];radii=[.21+.10*d,.30+.24*e,.21+.10*f];role='CONVECTIVE_BAND_BODY';}else if(cls==='MID_FRONTAL'){center=[(i-(count-1)/2)*.27+(a-.5)*.16,(b-.5)*.26,(c-.5)*.70];radii=[.40+.18*d,.16+.12*e,.27+.15*f];role=i===2?'FRONTAL_CORE':'FRONTAL_SEGMENT';}else if(cls==='HIGH_ICE'){center=[(i-(count-1)/2)*.31+(a-.5)*.18,(b-.5)*.17+.15,(c-.5)*.68];radii=[.46+.18*d,.10+.08*e,.26+.16*f];role='ICE_VEIL_SEGMENT';}out.push(freeze({index:i,center:freeze(center),radii:freeze(radii),role,baseOffset:center[1]-radii[1],topOffset:center[1]+radii[1]}));}return freeze(out);}
function ellipsoidSupport(q,b){const x=(q[0]-b.center[0])/b.radii[0],y=(q[1]-b.center[1])/b.radii[1],z=(q[2]-b.center[2])/b.radii[2];return 1-smooth(.70,1.06,Math.hypot(x,y,z));}
function mesoBodyField(object,q,bodies){let primary=0,secondary=0;for(const b of bodies){const s=ellipsoidSupport(q,b);if(b.role==='PRIMARY_TOWER'||b.role==='PRIMARY_COMPLEX'||b.role==='FRONTAL_CORE')primary=Math.max(primary,s);else secondary=Math.max(secondary,s);}let field=Math.max(primary,secondary*.92);if(object.weatherClass==='DEEP_CONVECTION'){const anvil=smooth(.25,.52,q[1])*(1-smooth(.78,1,q[1]))*(1-smooth(.62,1.0,Math.hypot(q[0],q[2])));field=Math.max(field,anvil*.62);}else if(object.weatherClass==='MID_FRONTAL'){const connective=(1-smooth(.50,.92,Math.abs(q[2])))*(1-smooth(.34,.70,Math.abs(q[1])));field=Math.max(field,connective*.30);}else if(object.weatherClass==='HIGH_ICE'){const veil=(1-smooth(.40,.90,Math.abs(q[2])))*(1-smooth(.26,.68,Math.abs(q[1]-.12)));field=Math.max(field,veil*.24);}else if(object.weatherClass==='CYCLONE'){const rr=Math.hypot(q[0],q[2]),band=smooth(.20,.36,rr)*(1-smooth(.76,.96,rr));field=Math.max(field,band*.34);}return clamp(field,0,1.35);}
function coherentCavityMask(object,q){const seed=hash32(object.ID_i)+Math.floor((object.W_i.seed??0)*100000),u=n=>hashUnit(n,n*3+7,n*5+11,seed+n*101),primary=[(u(1)-.5)*.20,(u(2)-.5)*.28,(u(3)-.5)*.22],secondary=[(u(4)-.5)*.62,(u(5)-.5)*.42,(u(6)-.5)*.62],deep=object.weatherClass==='DEEP_CONVECTION'||object.weatherClass==='CYCLONE',pR=deep?[.34,.42,.36]:[.30,.34,.32],sR=deep?[.26,.32,.28]:[.22,.27,.24],voidAt=(c,r)=>{const x=(q[0]-c[0])/r[0],y=(q[1]-c[1])/r[1],z=(q[2]-c[2])/r[2];return 1-smooth(.62,1.05,Math.hypot(x,y,z));};return clamp(Math.max(voidAt(primary,pR),voidAt(secondary,sR)*.86),0,1);}
function localRefinementFactor(object,q,bodies){const seed=Math.floor((object.W_i.seed??0)*100000)+hash32(object.ID_i)%100000,fine=fbm3(q[0]*7.8+4.3,q[1]*8.6-2.1,q[2]*7.4+6.4,seed+401),lobe=fbm3(q[0]*3.3+1.7,q[1]*3.8-4.6,q[2]*3.1+2.9,seed+557),cavity=fbm3(q[0]*2.15-8.2,q[1]*2.4+5.7,q[2]*2.05-1.9,seed+733),meso=mesoBodyField(object,q,bodies),radius=Math.hypot(q[0],q[1],q[2]),boundaryLock=smooth(.76,.94,radius),threshold=(object.weatherClass==='MID_FRONTAL'||object.weatherClass==='HIGH_ICE')?.14:.22;let body=meso<threshold?0:clamp(.14+meso*1.46,0,1.58);if(object.weatherClass==='DEEP_CONVECTION'){const lowerErosion=1-smooth(-.72,-.18,q[1]);body*=1-lowerErosion*.34*(1-meso);}let detail=clamp(1+(lobe-.5)*.42+(fine-.5)*.28-smooth(.62,.77,cavity)*.82,0,1.55);detail*=1-coherentCavityMask(object,q)*.97;return mix(body*detail,1,boundaryLock);}

export function sampleW5LocalDensity(object,worldPoint){if(!object||object.authority!=='FAP1_DESCRIPTOR_ONLY')throw new Error('FAP1_W5_OBJECT_AUTHORITY_REQUIRED');const localQ=localCoordinates(worldPoint,object);if(localQ[0]*localQ[0]+localQ[1]*localQ[1]+localQ[2]*localQ[2]>=1)return 0;const macroShape=macroAnchorShape(object,macroCoordinates(worldPoint,object));if(macroShape<=0)return 0;const bodies=buildMesoBodies(object),refinement=localRefinementFactor(object,localQ,bodies),density=clamp((object.W_i.density??0)*(object.W_i.support??1)*macroShape*refinement,0,1.8);return density<W5_EMPTY_THRESHOLD?0:density;}
export function chooseW5ActiveObject(spatialState){const candidates=(spatialState?.objects??[]).filter(entry=>entry.localPromoted===true&&entry.Q_i===true).sort((a,b)=>a.distanceToVolume-b.distanceToVolume||a.object.ID_i.localeCompare(b.object.ID_i));return candidates.length?candidates[0]:null;}
export function buildW5DensityBrick(object,{bx=0,by=0,bz=0,generation=W5_GENERATION,resolution=W5_BRICK_RESOLUTION}={}){if(!Number.isInteger(resolution)||resolution<4||resolution>32)throw new Error('FAP1_W5_BRICK_RESOLUTION_INVALID');const address=weatherBrickAddress(object,bx,by,bz,generation),values=new Float32Array(resolution*resolution*resolution),span=2/resolution,bodies=buildMesoBodies(object);let occupied=0,maxDensity=0,sumDensity=0,index=0,insideVolumeSamples=0,insideOccupiedSamples=0,gapColumns=0;for(let z=0;z<resolution;z++)for(let y=0;y<resolution;y++)for(let x=0;x<resolution;x++){const qx=-1+(x+.5)*span,qy=-1+(y+.5)*span,qz=-1+(z+.5)*span,q2=qx*qx+qy*qy+qz*qz,r=object.V_i.radii,c=object.V_i.center,point=[c[0]+object.V_i.axisU[0]*qx*r[0]+object.V_i.axisUp[0]*qy*r[1]+object.V_i.axisV[0]*qz*r[2],c[1]+object.V_i.axisU[1]*qx*r[0]+object.V_i.axisUp[1]*qy*r[1]+object.V_i.axisV[1]*qz*r[2],c[2]+object.V_i.axisU[2]*qx*r[0]+object.V_i.axisUp[2]*qy*r[1]+object.V_i.axisV[2]*qz*r[2]],density=sampleW5LocalDensity(object,point);values[index++]=density;if(q2<1)insideVolumeSamples++;if(density>0){occupied++;sumDensity+=density;maxDensity=Math.max(maxDensity,density);if(q2<1)insideOccupiedSamples++;}}for(let z=0;z<resolution;z++)for(let x=0;x<resolution;x++){let any=false;for(let y=0;y<resolution;y++){if(values[x+y*resolution+z*resolution*resolution]>W5_EMPTY_THRESHOLD){any=true;break;}}if(!any)gapColumns++;}const insideEmpty=Math.max(0,insideVolumeSamples-insideOccupiedSamples);return freeze({schema:FAP1_W5_LOCAL_DENSITY_SCHEMA,address,weatherId:object.ID_i,generation,resolution,sampleCount:values.length,occupiedSampleCount:occupied,occupancyFraction:occupied/values.length,emptySampleFraction:1-occupied/values.length,insideVolumeSampleCount:insideVolumeSamples,insideOccupiedSampleCount:insideOccupiedSamples,insideEmptySampleCount:insideEmpty,interiorEmptySampleFraction:insideVolumeSamples?insideEmpty/insideVolumeSamples:0,meanOccupiedDensity:occupied?sumDensity/occupied:0,maxDensity,values,authority:'FAP1_DESCRIPTOR_REFINEMENT_ONLY',correspondenceBasis:'FAP1_PRESERVED_MACRO_COORDINATES_TIMES_MESO_BODY_FIELD_TIMES_LOCAL_REFINEMENT',refinementCanCreateEmptyPockets:true,coherentObjectSpaceCavities:true,mesoBodyField:true,mesoBodyCount:bodies.length,mesoBodies:bodies,bodyOwnershipWeatherId:object.ID_i,verticalIntervalsDifferentiated:new Set(bodies.map(b=>`${b.baseOffset.toFixed(3)}:${b.topOffset.toFixed(3)}`)).size>1,gapColumnFraction:gapColumns/(resolution*resolution),macroWeatherMutation:false,l5LightingMutation:false,boundaryLockRadius:.94,cameraCentered:false,persistentWeatherIdentity:true,lightingApplied:false,visibleRendererMutation:false});}
export function createW5RefinementState(spatialState){const active=chooseW5ActiveObject(spatialState);if(!active)return freeze({schema:FAP1_W5_LOCAL_DENSITY_SCHEMA,active:false,activeWeatherId:null,brick:null,maxActiveObjects:W5_MAX_ACTIVE_OBJECTS,visibleRendererMutation:false,l5LightingActive:false});const brick=buildW5DensityBrick(active.object);return freeze({schema:FAP1_W5_LOCAL_DENSITY_SCHEMA,active:true,activeWeatherId:active.object.ID_i,distanceToVolume:active.distanceToVolume,inside:active.inside,alpha:active.alpha,brick,maxActiveObjects:W5_MAX_ACTIVE_OBJECTS,visibleRendererMutation:false,l5LightingActive:false});}
export function verifyW5RefinementState(state){const failures=[];if(state?.active){if(!state.activeWeatherId)failures.push('ACTIVE_WEATHER_ID_MISSING');if(state.brick?.weatherId!==state.activeWeatherId)failures.push('BRICK_WEATHER_ID_MISMATCH');if(state.brick?.mesoBodyField!==true||!(state.brick?.mesoBodyCount>=4))failures.push('MESO_BODY_FIELD_MISSING');if(state.brick?.bodyOwnershipWeatherId!==state.activeWeatherId)failures.push('MESO_BODY_WEATHER_IDENTITY_MISMATCH');if(state.brick?.verticalIntervalsDifferentiated!==true)failures.push('MESO_VERTICAL_INTERVALS_NOT_DIFFERENTIATED');if(state.brick?.macroWeatherMutation!==false)failures.push('MACRO_WEATHER_MUTATION_FORBIDDEN');if(state.brick?.l5LightingMutation!==false)failures.push('L5_MUTATION_FORBIDDEN');if(state.brick?.cameraCentered!==false)failures.push('CAMERA_CENTERED_LOCAL_VOLUME_FORBIDDEN');if(state.brick?.persistentWeatherIdentity!==true)failures.push('PERSISTENT_WEATHER_IDENTITY_MISSING');if(!(state.brick?.interiorEmptySampleFraction>=0&&state.brick?.interiorEmptySampleFraction<=1))failures.push('INVALID_INTERIOR_EMPTY_FRACTION');}if(state?.visibleRendererMutation!==false)failures.push('VISIBLE_RENDERER_MUTATION_FORBIDDEN_AT_W5_BODY_STAGE');if(state?.l5LightingActive!==false)failures.push('L5_PREMATURE_ACTIVATION');return freeze({schema:'FAP1_W5_LOCAL_DENSITY_INVARIANTS_v6_MESO_BODY_DIFFERENTIATION',pass:failures.length===0,failures:freeze(failures),activeWeatherId:state?.activeWeatherId??null});}
