import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {SOURCE_MODES,OPERATION_ID,HARD_CONSTRAINTS,assert,sha256,syntheticConfigurationEvaluator,zeroPassInferenceGuard,writeCanonicalJson} from './causal-evidence-adapter.v1.mjs';
import {planMode,planExecution,validateExecutionPlan} from './deterministic-shard-wave-planner.v1.mjs';
import {SegmentedEvidenceWriter,verifySegmentedEvidence} from './streaming-evidence-writer.v1.mjs';
import {executeSyntheticShard} from './shard-worker.v1.mjs';
import {reduceExecution} from './deterministic-reducer.v1.mjs';
import {compareDeterministicRerun} from './deterministic-rerun-comparator.v1.mjs';

const here=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(here,'../../../..');
const manifestPath=path.join(here,'changed-path-manifest.v1.json');
const readJson=f=>JSON.parse(fs.readFileSync(f,'utf8'));
const expectFailure=async(code,fn)=>{let got=null;try{await fn()}catch(e){got=String(e.code??e.message).split(':')[0]}assert(got===code,'NEGATIVE_FIXTURE_DID_NOT_FAIL',`${code}:${got}`)};
function exactPathBoundary(){const m=readJson(manifestPath);assert(m.pathCount===25&&m.addedPaths.length===25,'PATH_COUNT_MISMATCH');assert(new Set(m.addedPaths).size===25,'DUPLICATE_PATH');for(const p of m.addedPaths)assert(fs.existsSync(path.join(root,p)),'MISSING_APPROVED_PATH',p);const operationDir=path.relative(root,here).replaceAll('\\','/'),actual=[];for(const p of ['.github/workflows/h-earth-inter-hill-estate-v2-causal-evidence-execution-001.yml','.github/workflows/h-earth-inter-hill-estate-v2-causal-evidence-wave-001.yml'])if(fs.existsSync(path.join(root,p)))actual.push(p);for(const f of fs.readdirSync(here))actual.push(`${operationDir}/${f}`);actual.push('h-earth-3d/validation/h-earth.inter-hill-estate-v2-causal-evidence-execution-001.mjs');const extras=actual.filter(p=>!m.addedPaths.includes(p));assert(extras.length===0,'UNAPPROVED_PATH_PRESENT',extras.join(','));return m}
function jsonAndSchemaValidation(){for(const file of fs.readdirSync(here).filter(x=>x.endsWith('.json'))){const value=readJson(path.join(here,file));assert(value&&typeof value==='object','JSON_OBJECT_REQUIRED',file)}const input=readJson(path.join(here,'input-schema.v1.json')),output=readJson(path.join(here,'output-schema.v1.json')),artifacts=readJson(path.join(here,'artifact-schemas.v1.json'));for(const s of [input,output,artifacts])assert(typeof s.$id==='string'&&s.$id.length>0,'SCHEMA_ID_MISSING');return true}
function identityAndLockVerification(){const s=readJson(path.join(here,'source-evidence-manifest.v1.json'));assert(s.sourceIdentities.currentMain.commit==='502f791f26f19b9802920a7d1d24671aeae822c2','MAIN_IDENTITY_MISMATCH');assert(s.sourceIdentities.generator.blob==='80ff6fa6f8b349babf668fa40f54456ed140452b','GENERATOR_IDENTITY_MISMATCH');assert(s.sourceIdentities.orchestrator.blob==='d443e7e900e260b4399dfd6014bce4e158ac32c9','ORCHESTRATOR_IDENTITY_MISMATCH');assert(s.lock322.generation===322&&s.lock322.released===false,'LOCK_322_CUSTODY_MISMATCH');assert(s.proposedPathIntersectionWithLock322.length===0,'LOCK_322_PATH_INTERSECTION');return true}
function workflowVerification(){const main=fs.readFileSync(path.join(root,'.github/workflows/h-earth-inter-hill-estate-v2-causal-evidence-execution-001.yml'),'utf8'),wave=fs.readFileSync(path.join(root,'.github/workflows/h-earth-inter-hill-estate-v2-causal-evidence-wave-001.yml'),'utf8');for(const token of ['epoch-a-wave-0','epoch-a-wave-5','epoch-b-wave-0','epoch-b-wave-5','reduce-and-compare'])assert(main.includes(token),'WORKFLOW_STAGE_MISSING',token);for(const token of ['max-parallel: 8','fail-fast: false','timeout-minutes: 45'])assert(wave.includes(token),'WAVE_CONTROL_MISSING',token);return true}
function plannerFixtures(){const cases=readJson(path.join(here,'fixtures.v1.json')).plannerCases;for(const c of cases){const m=planMode({sourceMode:SOURCE_MODES[0],eligibleSeedCount:c.eligibleSeedCount,configurationDenominator:c.eligibleSeedCount*36,eligibleSeedListDigest:'0'.repeat(64),terrainPartitionDigest:'1'.repeat(64)});assert(m.shardCount===c.expectedShards,'SHARD_ARITHMETIC_FAILURE');assert(m.waveCount===c.expectedWaves,'WAVE_ARITHMETIC_FAILURE')}return true}
async function negativePlanFixtures(){const manifest={sourceMode:SOURCE_MODES[0],eligibleSeedCount:130,configurationDenominator:4680,eligibleSeedListDigest:'0'.repeat(64),terrainPartitionDigest:'1'.repeat(64)},mode=planMode(manifest),base={schema:'X',operationId:OPERATION_ID,shardSize:64,maxShardsPerWave:128,maxParallelShards:8,sourceModeOrder:SOURCE_MODES,modes:[mode],waves:mode.waves,waveCount:mode.waveCount,totalEligibleSeedCount:130,totalConfigurationDenominator:4680};const gap=structuredClone(base);gap.modes[0].shards[1].seedIndexStart++;await expectFailure('SHARD_GAP_OR_OVERLAP',()=>validateExecutionPlan(gap));const overlap=structuredClone(base);overlap.modes[0].shards[1].seedIndexStart--;await expectFailure('SHARD_GAP_OR_OVERLAP',()=>validateExecutionPlan(overlap));const duplicate=structuredClone(base);duplicate.modes[0].shards[1].seedIndexStart=0;await expectFailure('SHARD_GAP_OR_OVERLAP',()=>validateExecutionPlan(duplicate));return true}
async function streamingFixture(){const d=fs.mkdtempSync(path.join(os.tmpdir(),'h-earth-stream-')),w=new SegmentedEvidenceWriter({outputDir:d,maxRecords:2,maxBytes:1024});for(let i=0;i<5;i++)w.append({i,value:`v${i}`});const index=w.close();assert(index.segmentCount===3,'SEGMENT_COUNT_FAILURE');verifySegmentedEvidence(d,index);fs.rmSync(d,{recursive:true,force:true});return true}
function syntheticManifest(sourceMode,count=3){const seeds=Array.from({length:count},(_,i)=>({canonicalSeedIndex:i,nodeId:100+i,row:0,column:i,worldX:i,worldZ:0,slopeDegrees:i,distanceFromCenter:i,waterMembership:false,traversabilityResult:true,distancePredicateResult:true}));return {schema:'H_EARTH_INTER_HILL_ESTATE_V2_ELIGIBLE_SEED_MANIFEST_v1',operationId:OPERATION_ID,candidateHead:'5'.repeat(40),sourceMode,terrainPartitionDigest:sha256({sourceMode,partition:true}),resolvedCenter:{nodeId:100,row:0,column:0,worldX:0,worldZ:0},eligibilityPredicateDigest:sha256('predicate'),orientationDictionaryDigest:sha256(Array.from({length:36},(_,i)=>i*5)),eligibleSeedCount:count,configurationDenominator:count*36,firstEligibleNodeId:seeds[0]?.nodeId??null,finalEligibleNodeId:seeds.at(-1)?.nodeId??null,eligibleSeeds:seeds,eligibleSeedListDigest:sha256({sourceMode,seeds})}}
async function reducerAndRerunFixtures(){const temp=fs.mkdtempSync(path.join(os.tmpdir(),'h-earth-reducer-')),manifests=SOURCE_MODES.map(m=>syntheticManifest(m,3)),plan=planExecution(manifests),receipts=[];for(const mode of plan.modes)for(const shard of mode.shards){const out=path.join(temp,mode.sourceMode,String(shard.shardIndex));receipts.push(await executeSyntheticShard({shard,eligibleManifest:manifests.find(x=>x.sourceMode===mode.sourceMode),outputRoot:out}))}const a=reduceExecution({plan,shardReceipts:receipts,epoch:'A'}),b=reduceExecution({plan,shardReceipts:structuredClone(receipts),epoch:'B'}),comparison=compareDeterministicRerun({left:a,right:b});assert(comparison.byteIdentical,'SYNTHETIC_RERUN_NOT_IDENTICAL');const missing=receipts.slice(1);await expectFailure('UNEVALUABLE_MISSING_SHARD',()=>reduceExecution({plan,shardReceipts:missing}));const duplicate=[...receipts,receipts[0]];await expectFailure('DUPLICATE_SHARD',()=>reduceExecution({plan,shardReceipts:duplicate}));const capacity=structuredClone(receipts);capacity[0].shardDisposition='UNEVALUABLE_SHARD_TIMEOUT';await expectFailure('CAPACITY_FAILURE_NOT_DOMAIN_RESULT',()=>reduceExecution({plan,shardReceipts:capacity}));const zero=zeroPassInferenceGuard({passingArrangementCount:0,domainExhaustion:true});assert(!zero.terrainInfeasibilityEstablished&&!zero.estateInfeasibilityEstablished&&!zero.zeroPassInferenceApplied,'ZERO_PASS_INFERENCE_VIOLATION');fs.rmSync(temp,{recursive:true,force:true});return {planDigest:plan.executionPlanDigest,canonicalDigest:a.canonicalScientificReceipt.canonicalDigest}}
export async function runLocalVerification({outputFile=null}={}){const checks=[];const run=async(name,fn)=>{await fn();checks.push({name,result:'PASS'})};await run('EXACT_PATH_BOUNDARY',exactPathBoundary);await run('JSON_AND_SCHEMA_VALIDATION',jsonAndSchemaValidation);await run('IDENTITY_AND_LOCK_PRESERVATION',identityAndLockVerification);await run('WORKFLOW_CONTROLS',workflowVerification);await run('SHARD_AND_WAVE_ARITHMETIC',plannerFixtures);await run('GAP_OVERLAP_DUPLICATE_FIXTURES',negativePlanFixtures);await run('STREAMING_SEGMENT_FIXTURE',streamingFixture);let synthetic;await run('REDUCER_CAPACITY_ZERO_PASS_AND_RERUN_FIXTURES',async()=>{synthetic=await reducerAndRerunFixtures()});const result={schema:'H_EARTH_INTER_HILL_ESTATE_V2_LOCAL_VERIFICATION_RETURN_v1',operationId:OPERATION_ID,result:'PASS',checkCount:checks.length,checks,synthetic};if(outputFile)writeCanonicalJson(outputFile,result);return result}
if(process.argv[1]===fileURLToPath(import.meta.url))runLocalVerification({outputFile:process.argv[2]??null}).then(x=>console.log(JSON.stringify(x))).catch(e=>{console.error(e.stack);process.exit(1)})
