/** Portable clearing qualification adapted from the independent West delta fixture. Invoke on a frozen clean checkout. */
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';import {pathToFileURL} from 'node:url';
const root=execFileSync('git',['rev-parse','--show-toplevel'],{encoding:'utf8'}).trim(),args=process.argv.slice(2),arg=k=>args.includes(k)?args[args.indexOf(k)+1]:undefined,baseline=arg('--baseline')||'c313922b22cb76c64d35297c6bc9dec1b6578188',expected=arg('--head')||execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),output=arg('--output')||path.join(os.tmpdir(),'woodland-clearing-verification.json'),baseRoot=fs.mkdtempSync(path.join(os.tmpdir(),'woodland-clearing-baseline-'));
const record=JSON.parse(fs.readFileSync(path.join(root,'showroom/globe/h-earth/validation/woodland-clearing-trial.record.json')));assert.equal(baseline,record.baseline,'FROZEN_BASELINE_IDENTITY');
const copied=new Set();function copyBaseline(rel){if(copied.has(rel))return;assert(!rel.startsWith('../'),'BASELINE_DEPENDENCY_ESCAPE');copied.add(rel);const data=execFileSync('git',['show',baseline+':'+rel],{cwd:root,maxBuffer:40*1024*1024}),dest=path.join(baseRoot,rel);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,data);if(/\.(m?js)$/.test(rel)){const text=data.toString('utf8');for(const m of text.matchAll(/(?:from\s*|import\s*\()(['"])(\.[^'"]+)\1/g)){const dep=path.posix.normalize(path.posix.join(path.posix.dirname(rel),m[2].split('?')[0]));copyBaseline(dep)}}}
for(const line of execFileSync('git',['ls-tree','-r',baseline,'--','showroom/globe/h-earth/render'],{cwd:root,encoding:'utf8'}).trim().split('\n'))copyBaseline(line.split('\t')[1]);
const changed=execFileSync('git',['diff','--name-only',baseline,'HEAD'],{cwd:root,encoding:'utf8'}).trim().split('\n').filter(Boolean);assert(changed.every(p=>record.allowedPaths.includes(p)),'EXACT_SCOPE_MISMATCH');
const git=(...a)=>execFileSync('git',a,{cwd:root,encoding:'utf8',maxBuffer:40*1024*1024}),hash=b=>createHash('sha256').update(b).digest('hex'),digest=o=>hash(JSON.stringify(o)),same=(a,b,label)=>assert.equal(digest(a),digest(b),label);assert.equal(git('rev-parse','HEAD').trim(),expected,'HEAD_CUSTODY');assert.equal(git('status','--porcelain').trim(),'','CLEAN_HEAD_REQUIRED');
const limits=record.frozenLimits;assert.equal(limits.baseline,baseline);assert.equal(limits.status,'FROZEN_BEFORE_CONSTRUCTION');const bounds={minX:-155.40267987050615,maxX:-123.40267987050615,minZ:-226.74616902099837,maxZ:-194.74616902099837},eligible=new Set(['P2_TREE_A_03','P2_TREE_A_06','P2_TREE_A_08','P2_TREE_A_11']);same([...eligible],limits.preservation.eligibleTrees,'FROZEN_ELIGIBLE_SET');
const sourcePaths=git('ls-files','showroom/globe/h-earth/render').trim().split('\n').filter(Boolean);const hashes=()=>Object.fromEntries(sourcePaths.map(p=>[p,hash(fs.readFileSync(path.join(root,p)))]));const sourceStart=hashes(),limitsSha=hash(JSON.stringify(limits));let baselineRenderFiles=0;for(const line of git('ls-tree','-r',baseline,'--','showroom/globe/h-earth/render').trim().split('\n')){const [meta,p]=line.split('\t'),blob=meta.split(' ')[2],bytes=fs.readFileSync(path.join(baseRoot,p));assert.equal(createHash('sha1').update(Buffer.concat([Buffer.from(`blob ${bytes.length}\0`),bytes])).digest('hex'),blob,`BASELINE_BLOB_CUSTODY:${p}`);baselineRenderFiles++;}
const importAt=performance.now();const oldPreview=await import(pathToFileURL(path.join(baseRoot,'showroom/globe/h-earth/render/landscape-preview.js')));const newPreview=await import(pathToFileURL(path.join(root,'showroom/globe/h-earth/render/landscape-preview.js')));const oldTerrain=oldPreview.previewHEarthFunctionalLandscape().componentResults.terrain.primitive,newTerrain=newPreview.previewHEarthFunctionalLandscape().componentResults.terrain.primitive;same(newTerrain,oldTerrain,'CANONICAL_TERRAIN_DRIFT');const terrainBefore=digest(newTerrain);
const oldBuilder=(await import(pathToFileURL(path.join(baseRoot,'showroom/globe/h-earth/render/geometry-landscape-sector.p2.js')))).buildHEarthLandscapeSector,newBuilder=(await import(pathToFileURL(path.join(root,'showroom/globe/h-earth/render/geometry-landscape-sector.p2.js')))).buildHEarthLandscapeSector;const oldSector=oldBuilder({terrainPrimitive:oldTerrain}),sector=newBuilder({terrainPrimitive:newTerrain});assert.equal(oldSector.eligible,true);assert.equal(sector.eligible,true,JSON.stringify(sector.issues));assert.equal(oldSector.diagnostics.triangleCount,limits.baselineGeometry.sectorTriangles,'BASELINE_GEOMETRY_COST');assert(sector.diagnostics.triangleCount<=limits.constructionLimits.sectorTriangles,'SECTOR_BUDGET');
const primitive=(s,kind)=>s.primitives.find(p=>p.primitiveId===`H_EARTH_LANDSCAPE_P2_${kind}`),part=(s,obj,kind)=>{const p=primitive(s,kind),prefix={BARK:'bark',CANOPY:'canopy',ROCK:'stone',GRASS:'grass'}[kind],start=obj[prefix+'VertexStart'],count=obj[prefix+'VertexCount'];assert(Number.isInteger(start)&&Number.isInteger(count),`OBJECT_SPAN_MISSING:${obj.id}:${kind}`);const indices=[];for(let i=0;i<p.geometry.indices.length;i+=3){const face=p.geometry.indices.slice(i,i+3);if(face.some(j=>j>=start&&j<start+count)){assert(face.every(j=>j>=start&&j<start+count),'CROSS_OBJECT_FACE');indices.push(...face.map(j=>j-start));}}return {vertices:p.geometry.vertices.slice(start,start+count),normals:p.geometry.normals.slice(start,start+count),indices,colors:p.renderMaterial.vertexRgba.slice(start,start+count)};};
const normalize=obj=>{const r=JSON.parse(JSON.stringify(obj));for(const k of Object.keys(r))if(/Vertex(Start|Count)$/.test(k))delete r[k];if(r.rootPoints)for(const p of r.rootPoints)if(Number.isInteger(p.vertexIndex))p.vertexIndex-=obj.grassVertexStart;if(r.supportRings)for(const p of r.supportRings)p.start-=obj.stoneVertexStart;return r;},withinCircle=(o)=>o.x-o.crownRadius>=bounds.minX&&o.x+o.crownRadius<=bounds.maxX&&o.z-o.crownRadius>=bounds.minZ&&o.z+o.crownRadius<=bounds.maxZ,insideVertex=v=>v.x>=bounds.minX&&v.x<=bounds.maxX&&v.z>=bounds.minZ&&v.z<=bounds.maxZ;
const oldObjects=new Map(oldSector.manifest.map(o=>[o.id,o])),objects=new Map(sector.manifest.map(o=>[o.id,o]));let preservedObjects=0,changedInsideObjects=0;const changedIds=[],removedInsideObjects=[];
for(const [id,old] of oldObjects){const now=objects.get(id);const kinds=old.kind==='TREE'?['BARK','CANOPY']:old.kind==='GRASS'?['GRASS']:['ROCK'];const allowed=old.kind==='TREE'?eligible.has(id):kinds.every(k=>part(oldSector,old,k).vertices.every(insideVertex))&&(!Number.isFinite(old.crownRadius)||withinCircle(old));if(!now){assert(old.kind!=='TREE'&&allowed,`OUTSIDE_OR_TREE_OBJECT_REMOVED:${id}`);removedInsideObjects.push({id,kind:old.kind});continue;}if(old.kind==='TREE'){same(normalize(now),normalize(old),`TREE_ECOLOGY_DRIFT:${id}`);assert.equal(eligible.has(id),withinCircle(old),`STRICT_TREE_FOOTPRINT_SET:${id}`);}
 if(!allowed){same(normalize(now),normalize(old),`OUTSIDE_MANIFEST_DRIFT:${id}`);for(const k of kinds)same(part(sector,now,k),part(oldSector,old,k),`OUTSIDE_GEOMETRY_MATERIAL_DRIFT:${id}:${k}`);preservedObjects++;}
 else {const changed=kinds.some(k=>digest(part(sector,now,k))!==digest(part(oldSector,old,k)));if(changed){changedInsideObjects++;changedIds.push(id);}for(const k of kinds)assert(part(sector,now,k).vertices.every(insideVertex),`CLEARING_REPLACEMENT_ESCAPES:${id}:${k}`);if(id==='P2_TREE_A_11'){const a=part(sector,now,'BARK'),b=part(oldSector,old,'BARK');for(const key of ['vertices','normals','indices'])same(a[key],b[key],`TARGET_WOOD_HIERARCHY_DRIFT:${key}`);}}
}
// Added objects are authorized inside the clearing. Validate their actual full
// geometry and ground support; population preservation applies only to trees.
const terrainGeometry=newTerrain.geometry,terrainBins=new Map();for(let i=0;i<terrainGeometry.indices.length;i+=3){const t=terrainGeometry.indices.slice(i,i+3).map(j=>{const v=terrainGeometry.vertices[j];return{x:Math.fround(v.x),y:Math.fround(v.y),z:Math.fround(v.z)};});const loX=Math.min(...t.map(v=>v.x)),hiX=Math.max(...t.map(v=>v.x)),loZ=Math.min(...t.map(v=>v.z)),hiZ=Math.max(...t.map(v=>v.z));if(hiX<bounds.minX||loX>bounds.maxX||hiZ<bounds.minZ||loZ>bounds.maxZ)continue;for(let x=Math.floor(loX/8);x<=Math.floor(hiX/8);x++)for(let z=Math.floor(loZ/8);z<=Math.floor(hiZ/8);z++){const key=`${x},${z}`;if(!terrainBins.has(key))terrainBins.set(key,[]);terrainBins.get(key).push(t);}}
const surfaceY=(x,z)=>{for(const [a,b,c] of terrainBins.get(`${Math.floor(x/8)},${Math.floor(z/8)}`)||[]){const d=(b.z-c.z)*(a.x-c.x)+(c.x-b.x)*(a.z-c.z);if(Math.abs(d)<1e-10)continue;const u=((b.z-c.z)*(x-c.x)+(c.x-b.x)*(z-c.z))/d,v=((c.z-a.z)*(x-c.x)+(a.x-c.x)*(z-c.z))/d,w=1-u-v;if(Math.min(u,v,w)>=-1e-7)return u*a.y+v*b.y+w*c.y;}return null;};
const addedObjectChecks=[];
for(const [id,obj] of objects)if(!oldObjects.has(id)){
 assert.notEqual(obj.kind,'TREE',`TREE_POPULATION_ADDED:${id}`);
 const kinds=['BARK','CANOPY','ROCK','GRASS'].filter(k=>Number.isInteger(obj[({BARK:'bark',CANOPY:'canopy',ROCK:'stone',GRASS:'grass'})[k]+'VertexStart']));
 assert(kinds.length>0,`ADDED_OBJECT_GEOMETRY_CUSTODY_UNRESOLVED:${id}`);
 const parts=kinds.map(k=>part(sector,obj,k)),vertices=parts.flatMap(p=>p.vertices);assert(vertices.length>0,`ADDED_OBJECT_EMPTY:${id}`);assert(vertices.every(insideVertex),`ADDED_OBJECT_GEOMETRY_OUTSIDE_CLEARING:${id}`);
 if(Number.isFinite(obj.crownRadius))assert(withinCircle(obj),`DECLARED_ADDED_FOOTPRINT_OUTSIDE_CLEARING:${id}`);
 let supports=0;
 if(obj.support?.witnesses?.length){for(const w of obj.support.witnesses){const actual=surfaceY(w.x,w.z);assert(actual!==null,`ADDED_SUPPORT_GROUND_MISSING:${id}`);assert(Math.abs(actual-w.surfaceY)<1e-5,`ADDED_SUPPORT_SURFACE_DRIFT:${id}`);assert(Number.isFinite(obj.support.minimumBurial)&&actual-w.meshY>=obj.support.minimumBurial-1e-5,`ADDED_DECLARED_SUPPORT_BURIAL:${id}`);supports++;}}
 else if(obj.rootPoints?.length){for(const r of obj.rootPoints){const actual=surfaceY(r.x,r.z),vertex=Number.isInteger(r.vertexIndex)?primitive(sector,'GRASS').geometry.vertices[r.vertexIndex]:r;assert(actual!==null,`ADDED_ROOT_GROUND_MISSING:${id}`);assert(vertex&&Number.isFinite(vertex.y)&&vertex.y<=actual+1e-5,`ADDED_ROOT_SUPPORT:${id}`);supports++;}}
 else {const actual=surfaceY(obj.x,obj.z);assert(actual!==null&&Number.isFinite(obj.y)&&Math.abs(actual-obj.y)<1e-5,`ADDED_ANCHOR_SUPPORT:${id}`);supports++;}
 addedObjectChecks.push({id,kind:obj.kind,vertexCount:vertices.length,supportChecks:supports,declaredRadius:Number.isFinite(obj.crownRadius)?obj.crownRadius:null});changedIds.push(id);
}
assert.equal(sector.diagnostics.treeCount,oldSector.diagnostics.treeCount,'TREE_POPULATION_DRIFT');same(sector.diagnostics.rejections,oldSector.diagnostics.rejections,'ECOLOGY_SELECTION_DRIFT');same(digest(newTerrain),terrainBefore,'TERRAIN_INPUT_MUTATED');
console.log('Independent outside-object, target hierarchy, terrain and scope checks pass.');const reverse=newBuilder({terrainPrimitive:newTerrain,reverseGenerationOrder:true,grassCellOrder:'CHUNKED'});same(reverse,sector,'REVERSE_CHUNKED_DETERMINISM');assert.equal(git('rev-parse','HEAD').trim(),expected,'END_HEAD_CUSTODY');assert.equal(git('status','--porcelain').trim(),'','END_CLEAN_CUSTODY');same(hashes(),sourceStart,'END_SOURCE_CUSTODY');assert.equal(hash(JSON.stringify(limits)),limitsSha,'FROZEN_LIMITS_CUSTODY');
const report={schema:'H_EARTH_CLEARING_INDEPENDENT_WEST_DELTA_v1',status:'PASS',baseline,candidate:expected,limitsSha256:limitsSha,sourceSha256:sourceStart,baselineRenderFiles,eligibleTrees:[...eligible],preservedObjects,changedInsideObjects,removedInsideObjects,changedIds,baselineTriangles:oldSector.diagnostics.triangleCount,candidateTriangles:sector.diagnostics.triangleCount,sectorCeiling:limits.constructionLimits.sectorTriangles,primitiveCount:sector.primitives.length,treeCount:sector.diagnostics.treeCount,grassTuftCount:sector.diagnostics.grassTuftCount,rockCount:sector.diagnostics.rockCount,addedObjectChecks,terrainSha256:terrainBefore,generationOrder:'FORWARD_EQUALS_REVERSE_CHUNKED',durationMs:performance.now()-importAt,remainingIndependentChecks:['shared-renderer unflagged defaults and spatial mask','projected material UV/alpha/texture GPU contracts','actual full-residency GPU allocations/drawcalls/static-shadow lifecycle','same-camera96redraw cost ratios','owner phone/tablet physical disposition'],physicalAcceptance:false};fs.writeFileSync(output,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,sourceSha256:'RECORDED_IN_REPORT'},null,2));

fs.rmSync(baseRoot,{recursive:true,force:true});
