#!/usr/bin/env node
import fs from "node:fs";import os from "node:os";import path from "node:path";import {fileURLToPath} from "node:url";
import {ACTIVE_LEDGER_HEAD,ASSIGNMENT_HOLDER,ASSIGNMENT_ID,AuditError,OPERATION_ID,ROLE_ID,assert,canonicalPayloadBytes,computeLedgerHead,loadRegistry,outputManifestSha256,packageEntries,packageFingerprint,parseArgs,readJson,safeTarget,validateActiveLedger,validatePackage,writeJson} from "./lib.v1.mjs";
const moduleDir=path.dirname(fileURLToPath(import.meta.url));const defaultRepoRoot=path.resolve(moduleDir,"../..");
export function materializePackage({pkg,repoRoot=defaultRepoRoot,outputRoot,receiptPath}){const registry=loadRegistry(repoRoot);validatePackage(pkg,registry);assert(outputRoot,"INPUT_SCHEMA_INVALID","output_root");const entries=packageEntries(pkg);for(const e of entries){const t=safeTarget(outputRoot,e.path);fs.mkdirSync(path.dirname(t),{recursive:true});fs.writeFileSync(t,canonicalPayloadBytes(e.payload),"utf8");}const receipt={schema:"METHODS_ROLE_6_AUDIT_MATERIALIZATION_RECEIPT_v1",operationId:pkg.operationId,assignmentHead:pkg.assignmentHead,assignmentId:pkg.assignmentId,executionHolder:pkg.executionHolder,substantiveOutputCount:27,returnPacketCount:1,materializedPathCount:28,materializedPaths:entries.map(e=>e.path),packageFingerprint:packageFingerprint(pkg,registry),commandEmittedReturnReceiptPending:true,unauthorizedPathWritten:false,productMutationPerformed:false,mergePerformed:false};if(receiptPath)writeJson(receiptPath,receipt);return receipt;}
export function returnRole6Assignment({pkg,repoRoot=defaultRepoRoot,ledgerPath,outputReceiptPath,successorLedgerPath}){const registry=loadRegistry(repoRoot);validatePackage(pkg,registry);assert(ledgerPath&&outputReceiptPath&&successorLedgerPath,"INPUT_SCHEMA_INVALID","return_arguments");assert(outputReceiptPath===safeTarget(repoRoot,registry.commandEmittedPaths[0]),"UNAUTHORIZED_PATH","return_receipt");const ledger=readJson(ledgerPath),assignment=validateActiveLedger(ledger),rp=pkg.returnPacket.payload;assignment.status="RETURNED";assignment.returnDisposition=rp.disposition;assignment.outputManifestSha256=rp.outputManifestSha256;ledger.revision=2;ledger.ledgerHead=computeLedgerHead(ledger);const receipt={schema:"METHODS_INFORMATION_BENCHMARK_ASSIGNMENT_RETURN_RECEIPT_v1",status:"PASS_OPERATION_ASSIGNMENT_RETURNED",assignmentId:ASSIGNMENT_ID,roleId:ROLE_ID,operationId:OPERATION_ID,holderExecutionId:ASSIGNMENT_HOLDER,disposition:rp.disposition,predecessorAssignmentHead:ACTIVE_LEDGER_HEAD,assignmentHead:ledger.ledgerHead,ledgerRevision:2,assignmentAuthorityActive:false,postTerminationRoleState:"INACTIVE",outputManifestSha256:rp.outputManifestSha256,outputAdopted:false,nextRoleAssignmentPerformed:false,mergePerformed:false};writeJson(successorLedgerPath,ledger);writeJson(outputReceiptPath,receipt);return receipt;}
export function makeSyntheticPackage(repoRoot=defaultRepoRoot){const r=loadRegistry(repoRoot);const outputs=r.substantiveOutputs.map(({id,path:entryPath,ordinal})=>({id,path:entryPath,payload:{schema:id,ordinal,status:"SYNTHETIC_TEST_ONLY"}}));const pkg={schema:"METHODS_ROLE_6_AUDIT_PACKAGE_v1",operationId:r.operationId,assignmentHead:r.assignmentHead,assignmentId:r.assignmentId,packetHead:"fa7e74403ff43e017bccef7462f4e001918cf0a3",packetCanonicalSha256:"5c93a8ebe638b9f06a4e14fc42f8ee202c8801e940527aa4fb987006a04e0cdc",executionHolder:ASSIGNMENT_HOLDER,substantiveOutputs:outputs,returnPacket:{id:r.returnArtifacts[0].id,path:r.returnArtifacts[0].path,payload:{schema:"METHODS_INFORMATION_BENCHMARK_ROLE_OPERATION_RETURN_v1",assignmentId:ASSIGNMENT_ID,roleId:ROLE_ID,operationId:OPERATION_ID,holderExecutionId:ASSIGNMENT_HOLDER,disposition:"PASS_RETURN",outputManifestSha256:"0".repeat(64),fixtureOnly:false}}};pkg.returnPacket.payload.outputManifestSha256=outputManifestSha256(pkg);return pkg;}
export function runSelfTest(repoRoot=defaultRepoRoot){const temp=fs.mkdtempSync(path.join(os.tmpdir(),"methods-role6-audit-"));try{const pkg=makeSyntheticPackage(repoRoot),receipt=materializePackage({pkg,repoRoot,outputRoot:temp});assert(receipt.materializedPathCount===28,"BYTE_VERIFICATION_FAILURE","count");for(const e of packageEntries(pkg))assert(fs.readFileSync(safeTarget(temp,e.path),"utf8")===canonicalPayloadBytes(e.payload),"BYTE_VERIFICATION_FAILURE",e.path);return{...receipt,selfTest:"PASS_CLOSED"};}finally{fs.rmSync(temp,{recursive:true,force:true});}}
async function main(){const args=parseArgs(process.argv.slice(2));if(args.selfTest){process.stdout.write(`${JSON.stringify(runSelfTest(),null,2)}\n`);return;}assert(args.input,"INPUT_SCHEMA_INVALID","input");const pkg=readJson(args.input);if(args.returnAssignment){assert(args.ledger&&args.outputReceipt&&args.successorLedger,"INPUT_SCHEMA_INVALID","return_args");const r=returnRole6Assignment({pkg,ledgerPath:args.ledger,outputReceiptPath:path.resolve(args.outputReceipt),successorLedgerPath:path.resolve(args.successorLedger)});process.stdout.write(`${JSON.stringify(r)}\n`);return;}assert(args.outputRoot&&args.receipt,"INPUT_SCHEMA_INVALID","materialize_args");const r=materializePackage({pkg,outputRoot:args.outputRoot,receiptPath:args.receipt});process.stdout.write(`${JSON.stringify(r)}\n`);}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))main().catch(e=>{const code=e instanceof AuditError?e.code:"MATERIALIZATION_WRITE_FAILURE";process.stderr.write(`${code}:${e.message}\n`);process.exitCode=1;});
