import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {sampleHEarthRun8CSuccessorSurfaceMaterial} from '../../../../h-earth-3d/environment/h-earth.successor-surface-material.run8c.js';
import {sampleHEarthGen311PlacementStructureDisposition} from '../../../../h-earth-3d/environment/h-earth.gen2514-qualified-placement-authority.js';
import {createHash} from 'node:crypto';
import {getHEarthRun8ER2ImmutableLiveRenderPackage,getHEarthRun8ER2VegetationWorldTruthPlan,createHEarthRun8ER2VegetationPresentationBatch} from './live-render-package.run8e-r2.js';
import {constructHEarthGen2515VegetationPresentationBatch} from './run8e-successor-environment.js';
const digest=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
const pkg=getHEarthRun8ER2ImmutableLiveRenderPackage();
assert.equal(pkg.eligible,true);
const packageBefore=digest(pkg), selectedAnchors=[];
const sourceHashes=Object.fromEntries(['grass-lowland-trial.js','live-render-package.run8e-r2.js','persistent-live-renderer.run8e-r3c.cp2-additive-bandlimited-relief-v2.js','grass-lowland-trial.verify.mjs'].map(path=>[path,createHash('sha256').update(readFileSync(new URL(path,import.meta.url))).digest('hex')]));
const helperSource=readFileSync(new URL('grass-lowland-trial.js',import.meta.url),'utf8'),acceptedStart=helperSource.indexOf('function replaceTuft('),acceptedFunctionSha256=createHash('sha256').update(helperSource.slice(acceptedStart,helperSource.indexOf('/**',acceptedStart))).digest('hex');
assert.equal(acceptedFunctionSha256,'7a908ba17b685bd6dcaf2c197e2bb9750b56f41d1ced1cbd727a30de7263ec5d','accepted blade builder changed');
const triangles=[],waterTriangles=[];
for(const span of pkg.primitiveSpans.filter(s=>s.role==='TERRAIN'||s.primitiveId.endsWith(':FAR_OCEAN_CONTINUATION')))for(let i=span.indexStart;i<span.indexStart+span.indexCount;i+=3){
 const v=pkg.buffers.indices.slice(i,i+3).map(n=>({x:Math.fround(pkg.buffers.positions[n*3]),y:Math.fround(pkg.buffers.positions[n*3+1]),z:Math.fround(pkg.buffers.positions[n*3+2])}));
 if(Math.max(...v.map(p=>p.x)) < -33 || Math.min(...v.map(p=>p.x)) > 35 || Math.max(...v.map(p=>p.z)) < -205 || Math.min(...v.map(p=>p.z)) > -130)continue;
 (span.role==='TERRAIN'?triangles:waterTriangles).push(v);
}
function terrainSample(p,source=triangles){for(const [a,b,c] of source){const d=(b.z-c.z)*(a.x-c.x)+(c.x-b.x)*(a.z-c.z);if(Math.abs(d)<1e-12)continue;const u=((b.z-c.z)*(p.x-c.x)+(c.x-b.x)*(p.z-c.z))/d,v=((c.z-a.z)*(p.x-c.x)+(a.x-c.x)*(p.z-c.z))/d,w=1-u-v;if(Math.min(u,v,w)>=-1e-7){const ab=[b.x-a.x,b.y-a.y,b.z-a.z],ac=[c.x-a.x,c.y-a.y,c.z-a.z],nx=ab[1]*ac[2]-ab[2]*ac[1],ny=ab[2]*ac[0]-ab[0]*ac[2],nz=ab[0]*ac[1]-ab[1]*ac[0];return {y:u*a.y+v*b.y+w*c.y,slope:Math.hypot(nx,nz)/Math.abs(ny)};}}throw Error('ROOT_OUTSIDE_TERRAIN');}
function terrainY(p,source=triangles){return terrainSample(p,source).y;}
const basinBounds={minX:-18,maxX:34,minZ:-204,maxZ:-131},gridKey=(x,z)=>`${x}:${z}`,wetGrid=new Set(),basinCells=new Set(),bankDistance=new Map();
for(let z=basinBounds.minZ;z<=basinBounds.maxZ;z++)for(let x=basinBounds.minX;x<=basinBounds.maxX;x++)if(terrainY({x,z},waterTriangles)>terrainY({x,z}))wetGrid.add(gridKey(x,z));
const queue=[[-6,-164]];assert(wetGrid.has(gridKey(...queue[0])));basinCells.add(gridKey(...queue[0]));for(let i=0;i<queue.length;i++){const [x,z]=queue[i];for(const [dx,dz] of [[-1,0],[1,0],[0,-1],[0,1]]){const nx=x+dx,nz=z+dz,k=gridKey(nx,nz);if(wetGrid.has(k)&&!basinCells.has(k)){basinCells.add(k);queue.push([nx,nz]);}}}
const bankQueue=queue.map(p=>[...p,0]);for(const [x,z] of queue)bankDistance.set(gridKey(x,z),0);for(let i=0;i<bankQueue.length;i++){const [x,z,d]=bankQueue[i];if(d===4)continue;for(const [dx,dz] of [[-1,0],[1,0],[0,-1],[0,1]]){const nx=x+dx,nz=z+dz,k=gridKey(nx,nz);if(!bankDistance.has(k)){bankDistance.set(k,d+1);bankQueue.push([nx,nz,d+1]);}}}
assert.equal(basinCells.size,1638,'surveyed basin topology changed');
const rendererSource=readFileSync(new URL('persistent-live-renderer.run8e-r3c.cp2-additive-bandlimited-relief-v2.js',import.meta.url),'utf8');
const guarded=`    // Explicit oasis colors already encode live, straw and dead foliage.
    if(vMaterialParameters.w<0.5){
      float vegetationVariation=noise2(vWorldPosition.xz*0.42+identitySignal*19.0);
      base=mix(base*vec3(0.56,0.83,0.58),base*vec3(0.92,1.28,0.82),vegetationVariation);
    }`;
const originalTint=`    float vegetationVariation=noise2(vWorldPosition.xz*0.42+identitySignal*19.0);
    base=mix(base*vec3(0.56,0.83,0.58),base*vec3(0.92,1.28,0.82),vegetationVariation);`;
assert(rendererSource.includes(guarded)&&rendererSource.includes('mats.push(0,0,0,vertexColors?1:0)'));
const reverseRenderer=rendererSource.replace(guarded,originalTint).replace('mats.push(0,0,0,vertexColors?1:0)','mats.push(0,0,0,0)');assert.equal(createHash('sha256').update(reverseRenderer).digest('hex'),'a5932b71cc3318f7d5475bde94481a40fae6676c34279d4ad6c2024c8641fad6','renderer delta expanded beyond oasis tint bypass');
const grassAnchorCells2m=new Set(),grassRootCells1m=new Set(),naturalColorSignatures=new Set();const wholeBladePaletteCounts={brown:0,yellowGreen:0,green:0,other:0};let coloredVertices=0,gradientGrassBlades=0,shortBlades=0,tallBlades=0;
const baselineCoverage={exactHead:'e07981a377e08b32bfc8ee13314ea3a1c3d197ee',grassTufts:96,anchorCells2m:16,rootCells1m:48};
let oasisPrimitives=0,oasisGrass=0,oasisCattails=0,oasisHeads=0,oasisTriangles=0,oasisRoots=0,wetMin=Infinity,wetMax=-Infinity,dryMin=Infinity,dryMax=-Infinity;
function verifyOasis(p){
 const g=p.geometry,m=p.metadata.oasisFoliage,head=m.kind==='ROUNDED_CATTAIL_SEEDHEAD',wet=m.kind==='CATTAIL_STEM_AND_LEAVES';assert(m);const colors=m.vertexColorsSrgb;assert(Array.isArray(colors)&&colors.length===g.vertices.length,'color vertex count');assert.equal(m.colorEncoding,'SRGB_NORMALIZED_RGB');const localColors=new Set();for(const c of colors){assert(Array.isArray(c)&&c.length===3&&c.every(v=>Number.isFinite(v)&&v>=0&&v<=1),'normalized color');localColors.add(c.map(v=>v.toFixed(5)).join(':'));coloredVertices++;}assert(localColors.size>=6,'natural color variation missing');naturalColorSignatures.add(colors[0].map(v=>v.toFixed(5)).join(':'));
 if(!head&&!wet){const a=p.metadata.worldAnchor;grassAnchorCells2m.add(`${Math.floor((a.x+14)/2)}:${Math.floor((a.z+174)/2)}`);for(let i=0;i<g.vertices.length;i+=16){const [red,green,blue]=colors[i];const category=red>green&&green>blue?'brown':red/green>=.85&&green>blue?'yellowGreen':green>red?'green':'other';wholeBladePaletteCounts[category]++;const bottom=colors[i].reduce((a,b)=>a+b,0),tip=colors[i+15].reduce((a,b)=>a+b,0);assert(tip>bottom,'grass root-tip gradient absent');gradientGrassBlades++;const height=g.vertices[i+15].y-g.vertices[i+1].y;if(height<.25)shortBlades++;else tallBlades++;}for(const r of m.rootPoints)grassRootCells1m.add(`${Math.floor(r.x+14)}:${Math.floor(r.z+174)}`);}
 if(head)for(const c of colors)assert(c[0]>c[1]&&c[1]>c[2],'seedhead brown palette');oasisPrimitives++;if(head)oasisHeads++;else if(wet)oasisCattails++;else oasisGrass++;
 for(const v of g.vertices){assert([v.x,v.y,v.z].every(Number.isFinite));assert(v.x>=-18&&v.x<=34&&v.z>=-204&&v.z<=-131,'oasis vertex outside');}
 const edges=new Map();let volume=0;
 for(let i=0;i<g.indices.length;i+=3){const ids=g.indices.slice(i,i+3),[a,b,c]=ids.map(n=>{assert(Number.isInteger(n)&&n>=0&&n<g.vertices.length);return g.vertices[n];});const u=[b.x-a.x,b.y-a.y,b.z-a.z],v=[c.x-a.x,c.y-a.y,c.z-a.z];assert(Math.hypot(u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0])>1e-10,'oasis degenerate');oasisTriangles++;volume+=a.x*(b.y*c.z-b.z*c.y)+a.y*(b.z*c.x-b.x*c.z)+a.z*(b.x*c.y-b.y*c.x);for(let e=0;e<3;e++){let a=ids[e],b=ids[(e+1)%3],key=[Math.min(a,b),Math.max(a,b)].join(':');let item=edges.get(key)??{count:0,orientation:0};item.count++;item.orientation+=a<b?1:-1;edges.set(key,item);}}
 if(head){assert(volume>0,'head outward volume');for(const e of edges.values()){assert.equal(e.count,2,'head not closed');assert.equal(e.orientation,0,'head winding');}assert.equal(m.rootPoints.length,0);return;}
 assert(m.rootPoints.length>0);
 for(const p of m.rootPoints){const v=g.vertices[p.vertexIndex];assert(v);const surface=terrainSample(v),y=surface.y,wy=terrainY(v,waterTriangles),clearance=y-wy;assert(surface.slope<=.450001,'actual triangle too steep');const gridDistance=bankDistance.get(gridKey(Math.round(v.x),Math.round(v.z)));assert(gridDistance!==undefined&&gridDistance<=4,'root outside selected basin bank');assert(Math.abs(v.y-y)<=.00002,'oasis root contact');const soil=sampleHEarthRun8CSuccessorSurfaceMaterial(v.x,v.z),estate=sampleHEarthGen311PlacementStructureDisposition(v.x,v.z);assert(soil.valid&&['LOWLAND_SOIL','COASTAL_SOIL'].includes(soil.surfaceClass)&&Number.isFinite(soil.slope)&&soil.slope<=.45&&Number.isFinite(soil.soilDepth)&&soil.soilDepth>=.2);assert.equal(estate.status,'NO_KNOWN_ESTATE_FOOTPRINT_OVERLAP');assert.equal(estate.hardExclusions.length,0);assert.equal(estate.planningHolds.length,0);if(wet){assert(basinCells.has(gridKey(Math.round(v.x),Math.round(v.z))),'wet root not in selected component');assert(clearance>=-.45002&&clearance<=.00002);wetMin=Math.min(wetMin,clearance);wetMax=Math.max(wetMax,clearance);}else{assert(clearance>=.03498&&clearance<=1.10002);dryMin=Math.min(dryMin,clearance);dryMax=Math.max(dryMax,clearance);}oasisRoots++;}
}
const truth=getHEarthRun8ER2VegetationWorldTruthPlan();assert.equal(truth.batches.length,108);
let count=0,unchanged=0,changed=0,roots=0,maxRootError=0,triangleCount=0,suppressed=0,rendered=0,emptyBatches=0;const suppressedByArchetype={},unchangedByArchetype={};const changedPlacements=new Set(),allIds=new Set();
for(const descriptor of truth.batches){
 const original=constructHEarthGen2515VegetationPresentationBatch(descriptor.batchId),candidate=createHEarthRun8ER2VegetationPresentationBatch(descriptor.batchId),repeat=createHEarthRun8ER2VegetationPresentationBatch(descriptor.batchId);
 assert.equal(candidate.eligible,true);assert.equal(candidate.instanceCount,original.instanceCount);assert.deepEqual(candidate.placementIds,original.placementIds);assert.equal(digest(candidate),digest(repeat),'repeat differs');count+=candidate.instanceCount;
 for(const id of candidate.placementIds){assert(!allIds.has(id));allIds.add(id);}
 const byId=new Map(candidate.primitives.map(p=>[p.primitiveId,p]));assert.equal(byId.size,candidate.primitives.length);rendered+=candidate.primitives.length;if(!candidate.primitives.length)emptyBatches++;let batchSuppressed=0;
 for(const p of candidate.primitives){if(p.metadata?.oasisFoliage){assert.equal(candidate.batchId,'GEN2514_BATCH:H_EARTH_GEN311_PLACEMENT:0001527b');verifyOasis(p);continue;}assert(original.primitives.some(before=>before.primitiveId===p.primitiveId),'new primitive identity');assert(p.materialHint.archetypeId!=='COASTAL_GRASS_TUFT'||p.metadata.lowlandGrassTrial,'legacy grass rendered');}
 for(let i=0;i<original.primitives.length;i++){
  const before=original.primitives[i],after=byId.get(before.primitiveId),archetype=before.materialHint.archetypeId;
  if(!after){assert.equal(archetype,'COASTAL_GRASS_TUFT','nongrass suppressed');const a=before.metadata.worldAnchor;assert(!(a.x>=-32&&a.x<=-16&&a.z>=-158&&a.z<=-142),'accepted patch suppressed');suppressed++;batchSuppressed++;suppressedByArchetype[archetype]=(suppressedByArchetype[archetype]??0)+1;continue;}
  assert.equal(before.primitiveId,after.primitiveId);
  if(archetype!=='COASTAL_GRASS_TUFT'){assert.equal(digest(before),digest(after),'nongrass changed');unchanged++;unchangedByArchetype[archetype]=(unchangedByArchetype[archetype]??0)+1;continue;}
  changed++;const anchor=before.metadata.worldAnchor;selectedAnchors.push({placementId:before.metadata.gen2514PlacementId,...anchor});assert(anchor.x>=-32&&anchor.x<=-16&&anchor.z>=-158&&anchor.z<=-142);assert.equal(before.materialHint.archetypeId,'COASTAL_GRASS_TUFT');changedPlacements.add(before.metadata.gen2514PlacementId);assert.deepEqual(after.materialHint,before.materialHint);
  for(const [key,value] of Object.entries(before.metadata))assert.deepEqual(after.metadata[key],value,`metadata changed: ${key}`);
  const g=after.geometry;assert(g.vertices.length>before.geometry.vertices.length);
  for(const v of g.vertices){assert([v.x,v.y,v.z].every(Number.isFinite));assert(v.x>=-32&&v.x<=-16&&v.z>=-158&&v.z<=-142);}
  for(const n of g.normals??[])assert([n.x,n.y,n.z].every(Number.isFinite));
  for(let j=0;j<g.indices.length;j+=3){const [a,b,c]=g.indices.slice(j,j+3).map(n=>{assert(Number.isInteger(n)&&n>=0&&n<g.vertices.length);return g.vertices[n];});const u=[b.x-a.x,b.y-a.y,b.z-a.z],v=[c.x-a.x,c.y-a.y,c.z-a.z];assert(Math.hypot(u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0])>1e-10,'degenerate triangle');triangleCount++;}
  const points=after.metadata.lowlandGrassTrial.rootPoints;assert(points.length>=96);
  for(const p of points){const vertex=g.vertices[p.vertexIndex];assert(vertex);const soil=sampleHEarthRun8CSuccessorSurfaceMaterial(vertex.x,vertex.z);assert.equal(soil.valid,true);assert(['LOWLAND_SOIL','COASTAL_SOIL'].includes(soil.surfaceClass));assert(Number.isFinite(soil.slope)&&soil.slope<=.45);const estate=sampleHEarthGen311PlacementStructureDisposition(vertex.x,vertex.z);assert.equal(estate.status,'NO_KNOWN_ESTATE_FOOTPRINT_OVERLAP');assert.equal(estate.hardExclusions.length,0);assert.equal(estate.planningHolds.length,0);const err=Math.abs(vertex.y-terrainY(vertex));assert(err<=0.00002,`root error ${err}`);maxRootError=Math.max(maxRootError,err);roots++;}
 }
 if(candidate.lowlandGrassTrial){assert.equal(candidate.lowlandGrassTrial.suppressedLegacyGrassCount,batchSuppressed);assert.equal(candidate.lowlandGrassTrial.renderedPrimitiveCount,candidate.primitives.length);assert.equal(candidate.lowlandGrassTrial.completeWorldPlacementPresentationClaimed,false);}
}
assert(suppressed>0);assert.equal(rendered,unchanged+changed+oasisPrimitives);assert(oasisGrass>96&&oasisGrass<=360);assert(grassAnchorCells2m.size>baselineCoverage.anchorCells2m);assert(grassRootCells1m.size>baselineCoverage.rootCells1m);assert(shortBlades>0&&tallBlades>0);assert(naturalColorSignatures.size>20);assert(oasisCattails>18&&oasisCattails<=72);assert.equal(oasisHeads,oasisCattails);assert(oasisTriangles<=350000);
assert.equal(count,27585);assert.equal(allIds.size,27585);assert.equal(changedPlacements.size,4);assert.equal(changed,4);
const packageAfter=digest(pkg);assert.equal(packageAfter,packageBefore);
console.log(JSON.stringify({status:'PASS',basinEvidence:{seed:{x:-6,z:-164},wetCells:basinCells.size,gridSpacingMeters:1,bankAssociation:'ROUNDED_GRID_CARDINAL_DISTANCE_AT_MOST_4',bounds:basinBounds},rendererEvidence:{oasisMarkerOnly:true,originalTintFallbackBytePreserved:true,allOtherRendererBytesPreserved:true},acceptedFunctionSha256,densityCoverage:{baseline:baselineCoverage,grassTufts:oasisGrass,anchorCells2m:grassAnchorCells2m.size,rootCells1m:grassRootCells1m.size,occupiedRootCells:[...grassRootCells1m].sort()},colorEvidence:{wholeBladePaletteCounts,paletteClassification:'Grass root RGB: brown R>G>B; otherwise yellow-green R/G>=0.85 and G>B; otherwise green G>R; remaining other',coloredVertices,distinctPrimitiveRootColors:naturalColorSignatures.size,gradientGrassBlades,shortBlades,tallBlades,normalizedSrgb:true},oasis:{primitiveCount:oasisPrimitives,grassTuftCount:oasisGrass,cattailCount:oasisCattails,closedSeedheadCount:oasisHeads,triangleCount:oasisTriangles,rootCount:oasisRoots,dryClearanceMeters:[dryMin,dryMax],wetClearanceMeters:[wetMin,wetMax],bounds:basinBounds},sourceHashes,packageBefore,packageAfter,selectedAnchors,instanceCount:count,batchCount:truth.batches.length,changedPrimitives:changed,changedPlacementIds:[...changedPlacements],unchangedNongrassPrimitives:unchanged,unchangedByArchetype,suppressedLegacyGrassPrimitives:suppressed,suppressedByArchetype,renderedPrimitiveCount:rendered,consumedPlacementCount:count,emptyPresentationBatches:emptyBatches,renderedLegacyGrassCount:0,rootCount:roots,maxRootErrorMeters:maxRootError,trialTriangleCount:triangleCount,deterministic:true,contactSurface:'BASE_PACKAGE_FLOAT32_TRIANGLES',refinementActivationVerified:false},null,2));
