#!/usr/bin/env node
import fs from 'node:fs';
import {spawnSync} from 'node:child_process';

const OP='COMPASS_COHERENCE_OBJECT_PORTAL_AND_IDENTITY_SIMPLIFICATION_20260818_001';
const LOCK=1536;
const BASE='f3622b8d394437dd1b1a23165fd13dc5d73cb875';
const OUT=process.env.COMPASS_VERIFICATION_OUTPUT||'/tmp/compass-coherence-display.json';
const allowed=new Set(['index.html','assets/compass/compass.capability-carousel.js','assets/compass/compass.capability-carousel.css','assets/compass/compass.identity-3d.js','assets/compass/compass.identity-3d.css','.github/ai-router/projects/compass/verify-display-continuity.v1.mjs','.github/ai-router/projects/compass/verify-performance-successor.mjs','.github/workflows/compass-carousel-successor-live-qualification.yml','.github/workflows/compass-display-continuity-validation.yml','.github/workflows/compass-performance-successor-validation.yml']);
const read=p=>fs.readFileSync(p,'utf8');
const git=args=>spawnSync('git',args,{encoding:'utf8'});
const checks=[];const check=(id,pass,detail)=>checks.push({id,pass:Boolean(pass),detail});
const html=read('index.html'),identity=read('assets/compass/compass.identity-3d.js'),brain=read('assets/compass/compass.brain-scene.js'),mirror=read('assets/compass/compass.mirrorland-window.js'),capJs=read('assets/compass/compass.capability-carousel.js'),capCss=read('assets/compass/compass.capability-carousel.css'),flagship=read('assets/compass/compass.identity-3d.css');
const diff=git(['diff','--name-only',BASE,'HEAD']);const changed=(diff.stdout||'').trim().split(/\r?\n/).filter(Boolean);
const roomIds=[...html.matchAll(/data-room-id="([^"]+)"/g)].map(m=>m[1]).filter(id=>/^(north|east|south|west)-\d+$/.test(id));
check('EXACT_ALLOWED_PATH_SCOPE',diff.status===0&&changed.every(p=>allowed.has(p)),changed.join(','));
check('GEN1536_ONE_AUTHORITATIVE_COMPASS',identity.includes("const GLOBAL='DGB_COMPASS_IDENTITY_3D_GEN1536'")&&identity.includes("identityContract='ONE_AUTHORITATIVE_COMPASS_GEN1536'")&&!identity.includes('mountSpatialCompass()'),'one authoritative Compass identity; secondary spatial Compass not mounted');
check('NO_ORNAMENTAL_TOP_ROTATION',!identity.includes('class="compass-identity-o-control"')&&!identity.includes('is-revolving')&&identity.includes("boundedRevolution:false"),'top ornamental Compass rotation removed');
check('NO_SECONDARY_SPATIAL_COMPASS',!identity.includes('TRUE_3D_FIXED_CENTER_VISUAL_SIBLING_GEN1534')&&identity.includes("secondarySpatialCompass:false"),'secondary Compass removed at source');
check('OBJECT_PORTAL_CONTRACT',capJs.includes("OBJECT_FIRST_STABLE_GEOMETRY_GEN1536")&&['compass-brain-portal','compass-trophy-portal','compass-house-portal'].every(x=>capJs.includes(x)),'Brain Trophy House remain object-first capability identities');
check('NO_PARENT_PRIMARY_CTA_CHROME',!capJs.includes('RUN THE DIAGNOSTIC')&&!capJs.includes('Explore the Awards Layer')&&!capJs.includes('OPEN HOUSE GUIDES'),'parent capability CTA buttons removed');
check('SHORT_SUBORDINATE_COPY',capJs.includes('Compare how you live and decide with what matters to you.')&&capJs.includes('One body of work. Five reasons to look closer.')&&capJs.includes('Choose Jeeves, Elara, or Auren.'),'short copy follows each object');
check('OBJECT_PORTAL_ACCESSIBILITY',capJs.includes('aria-label="Enter Coheriscope')&&capJs.includes('aria-label="Enter Awards and Recognition')&&capJs.includes('aria-label="Choose a House guide below"')&&capCss.includes('.compass-object-portal:focus-visible'),'object identities have semantic names and focus treatment');
check('STABLE_CAPABILITY_GEOMETRY',capCss.includes('height:clamp(390px,48vw,480px)')&&capCss.includes('contain:layout paint')&&!capCss.includes('backdrop-filter:blur(18px)'),'capability cards retain fixed bounded geometry without Coheriscope expansion');
check('HOUSE_GUIDES_BENEATH_OBJECT',capJs.includes('data-house-guide-selector')&&capJs.includes('data-house-function="jeeves"')&&capJs.includes('href="/showroom/globe/hearth/jeeves/"')&&capJs.includes('data-house-function="elara"')&&capJs.includes('href="/elara/"')&&capJs.includes('data-house-function="auren"')&&capJs.includes('href="/products/auren/"'),'Jeeves Elara and Auren are directly selectable beneath the House object');
check('NO_HOUSE_NESTED_STATE',!capJs.includes('data-house-orbit')&&!capJs.includes('data-return-house')&&!capJs.includes('RETURN TO ORBIT')&&!capJs.includes("mode='house'")&&!capJs.includes('house-members'),'obsolete House nested state and Return to Orbit contract removed');
check('CANONICAL_LAWS_SPACECRAFT',identity.includes("designId:'DGB_SCOUTCRAFT_01'")&&identity.includes("sourceModule:'/laws/index.spacecraft.geometry.js'")&&identity.includes("adoption:'DIRECT_CANONICAL_GEOMETRY_MODULE_CONSUMPTION'"),'canonical Laws spacecraft unchanged');
check('CORRECTED_BRAIN_ANATOMY',['midbrain','pons','medulla','cerebellum'].every(x=>brain.includes(x))&&!brain.includes('cerebellum-left')&&!brain.includes('cerebellum-right'),'corrected brain anatomy preserved');
check('FOUR_CARDINALS',['north','east','south','west'].every(x=>html.includes(`data-cardinal-id="${x}"`)),'four cardinal stars preserved');
check('NINETEEN_ROOMS',new Set(roomIds).size===19,`room declarations=${new Set(roomIds).size}`);
check('MIRRORLAND_STATE_MEANING',['MIRRORLAND_REVEALING','MIRRORLAND_FOCUSED','MIRRORLAND_WITHDRAWING'].every(x=>mirror.includes(x)),'Mirrorland semantics preserved');
check('PERFORMANCE_PRESENTATION_FLOOR',flagship.includes('filter:none!important')&&flagship.includes('contain:layout paint')&&capCss.includes('@media(prefers-reduced-motion:reduce)'),'Gen1534 compositor/reduced-motion floor retained');
const pass=checks.every(c=>c.pass);const receipt={schema:'COMPASS_COHERENCE_DISPLAY_VERIFICATION_RECEIPT_v1',operation:OP,lockGeneration:LOCK,base:BASE,candidate:process.env.COMPASS_CANDIDATE_HEAD||git(['rev-parse','HEAD']).stdout.trim(),result:pass?'PASS_CLOSED':'FAIL_CLOSED',changedPaths:changed,checks};fs.writeFileSync(OUT,JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt,null,2));process.exit(pass?0:1);
