#!/usr/bin/env node
import fs from 'node:fs';
import {spawnSync} from 'node:child_process';
const OP='COMPASS_GEN1538_REFERENCE_ARCHITECTURE_RECOVERY_AND_CAROUSEL_CONTINUITY_20260818_005';
const LOCK=1537;
const OUT=process.env.COMPASS_VERIFICATION_OUTPUT||'/tmp/compass-gen1538-display.json';
const head=spawnSync('git',['rev-parse','HEAD^{commit}'],{encoding:'utf8'}).stdout.trim();
const base=process.env.COMPASS_SCOPE_BASE_SHA||'21ee87e945a62492b8f9447a5049f4ae0ab1ceb9';
const changed=spawnSync('git',['diff','--name-only',`${base}...HEAD`],{encoding:'utf8'}).stdout.trim().split('\n').filter(Boolean);
const allowed=new Set(['index.html','assets/compass/compass.css','assets/compass/compass.capability-carousel.css','assets/compass/compass.capability-carousel.js','assets/compass/compass.brain-scene.js','assets/compass/compass.trophy-scene.js','assets/compass/compass.house-scene.js','.github/ai-router/projects/compass/verify-display-continuity.v1.mjs','.github/ai-router/projects/compass/verify-performance-successor.mjs','.github/workflows/compass-carousel-successor-live-qualification.yml','.github/workflows/compass-display-continuity-validation.yml','.github/workflows/compass-performance-successor-validation.yml']);
const read=p=>fs.readFileSync(p,'utf8');
const index=read('index.html'),cap=read('assets/compass/compass.capability-carousel.js'),house=read('assets/compass/compass.house-scene.js');
const checks=[];const check=(id,pass,evidence)=>checks.push({id,pass:Boolean(pass),evidence});
check('EXACT_SCOPE',changed.every(p=>allowed.has(p)),changed);
check('CONSTELLATION_IS_COMPASS',index.includes('data-compass-scene')&&index.includes('data-compass-cardinal')&&index.includes('Rotate the Compass'),true);
check('GEN1537_CENTER_COMPASS_ARCHIVED_AT_RUNTIME',cap.includes("archived-by-gen1538")&&cap.includes("gen1538CentralCompass='absent'"),true);
check('MIRRORLAND_DIRECT_HIT_PROTECTED',cap.includes("data-gen1538-hit-authority")||cap.includes("gen1538HitAuthority='protected-direct-controller-surface'"),true);
check('TRL7_REFERENCE_LOGIC_PRESERVED',cap.includes("rail('proof',['TRL 7','Bounded','Checked'])")&&cap.includes('setTimeout(settle,320)'),true);
check('CAPABILITY_TRL7_PARITY_BOUND',cap.includes("portalContract='TRL7_REFERENCE_PARITY_GEN1538'")&&cap.includes('setTimeout(()=>{busy=false;fn()},320)'),true);
check('DIRECT_HOUSE_GUIDES',cap.includes('data-house-function="jeeves"')&&cap.includes('data-house-function="elara"')&&cap.includes('data-house-function="auren"')&&!cap.includes('data-return-house'),true);
check('HOUSE_TRUE_3D_WEBGL',house.includes("houseRenderer:'procedural-webgl-v1'")&&house.includes('gl.drawElements')&&house.includes('pitched-roof')&&house.includes('recessed-door'),true);
check('NO_PROTECTED_RUNTIME_MUTATION',!changed.some(p=>['assets/compass/compass.statement-carousel.js','assets/compass/compass.statement-carousel.css','assets/compass/compass.orbit-input.js','assets/compass/compass.controller.js','assets/compass/compass.crystals.js','assets/compass/compass.cosmos.js','assets/compass/compass.mirrorland-window.js'].includes(p)),changed);
const failures=checks.filter(x=>!x.pass);const receipt={schema:'COMPASS_GEN1538_DISPLAY_VERIFICATION_RECEIPT_v1',operation:OP,lockGeneration:LOCK,candidate:head,base,changed,result:failures.length?'FAIL_CLOSED':'PASS_CLOSED',checks,failures:failures.map(x=>x.id)};fs.writeFileSync(OUT,JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt,null,2));if(failures.length)process.exit(1);
