'use strict';
const fs=require('fs'); const path=require('path');
const G1=require('./jeeves.speech-kernel.js');
const SR=24000,BASE_AMP=.52;
const FORMANTS={AA:[730,1090,2440],AE:[660,1720,2410],AH:[640,1190,2390],AO:[570,840,2410],EH:[530,1840,2480],ER:[490,1350,1690],IH:[400,1990,2550],IY:[270,2290,3010],OW:[570,840,2410],UH:[440,1020,2240],UW:[300,870,2240],AY:[650,1500,2500],EY:[500,1900,2600]};
const VOWELS=new Set(Object.keys(FORMANTS)); const STOP=new Set(['P','B','T','D','K','G']); const FRIC=new Set(['F','V','S','Z','SH','ZH','TH','DH','H']); const SON=new Set(['R','L','W','Y','M','N','NG']);
const STRESS=new Set(['navigation','orientation','diamond','gate','bridge','define','questions','connections','stars','answers','reality','existence','therefore','never','lost','home','nothing','navigates','better','compass']);
function hash01(a,b,c){const x=Math.sin((a+1)*12.9898+(b+1)*78.233+(c+1)*37.719)*43758.5453;return x-Math.floor(x);}
function stressWeight(tok,prevWord){if(tok.type!=='ph'||!STRESS.has(tok.word))return 0;return prevWord===tok.word?.72:1;}
function phraseProgress(tokens,index){let total=0,pos=0;for(let i=0;i<tokens.length;i++){if(tokens[i].type==='ph'){if(i<index)pos++;total++;}}return total?pos/Math.max(1,total-1):0;}
function macroF0(progress,weight){const phrase=121+(108-121)*progress;const stress=weight*(8+5*Math.sin(Math.PI*Math.min(1,progress+.1)));return Math.max(106,Math.min(136,phrase+stress));}
function macroAmp(progress,weight){const final=progress>.82?.90:1;return Math.min(.62,BASE_AMP*(weight?1.10:.94)*final);}
function microF0(baseF0,i,n,seed){const t=i/Math.max(1,n-1),j=(hash01(seed,i>>5,1)-.5)*.016,d=.9*Math.sin(2*Math.PI*(.65*t+hash01(seed,2,3)));return baseF0*(1+j)+d;}
function microAmp(baseAmp,i,n,seed){const t=i/Math.max(1,n-1),s=(hash01(seed,i>>6,4)-.5)*.03,d=.012*Math.sin(2*Math.PI*(.5*t+hash01(seed,5,6)));return baseAmp*(1+s+d);}
function formantsFor(p){return FORMANTS[p]||FORMANTS.AH;} function lerp(a,b,t){return a+(b-a)*t;} function smooth(t){return t*t*(3-2*t);}
function interpFormants(prev,p,next,t){const cur=formantsFor(p),P=VOWELS.has(prev)?formantsFor(prev):cur,N=VOWELS.has(next)?formantsFor(next):cur;const edge=.22;let out=cur.slice();if(t<edge){const u=smooth(t/edge);out=cur.map((x,k)=>lerp(P[k],x,u));}else if(t>1-edge){const u=smooth((t-(1-edge))/edge);out=cur.map((x,k)=>lerp(x,N[k],u));}return out;}
function spectralTilt(t,seed){return 0.92+0.10*Math.sin(Math.PI*t)+0.025*(hash01(seed,13,17)-.5);}
function synthPh(p,dur,baseF0,baseAmp,seed,prev,next){const n=Math.max(1,Math.floor(dur*SR)),out=new Float32Array(n);if(VOWELS.has(p)||SON.has(p)){for(let i=0;i<n;i++){const q=i/Math.max(1,n-1),f0=microF0(baseF0,i,n,seed),amp=microAmp(baseAmp,i,n,seed),F=interpFormants(prev,p,next,q),tilt=spectralTilt(q,seed);let s=0;for(let h=1;h<=24;h++){const f=h*f0;let gain=.025;for(const ff of F)gain+=1/(1+Math.pow((f-ff)/105,2));s+=Math.sin(2*Math.PI*f*(i/SR))*gain/(h*(1+.028*h/tilt));}const a=.008+.004*hash01(seed,7,8),r=.016+.008*hash01(seed,9,10),env=Math.min(1,i/(a*SR),(n-i)/(r*SR));out[i]=s*amp*.24*env;}}else if(FRIC.has(p)||['CH','JH'].includes(p)){for(let i=0;i<n;i++){const q=i/Math.max(1,n-1),amp=microAmp(baseAmp,i,n,seed),env=Math.min(1,i/(.006*SR),(n-i)/(.014*SR)),release=.72+.28*smooth(q);out[i]=((hash01(seed,i,11)-.5)*2)*.20*env*release*(p==='H'?.5:1)*(amp/BASE_AMP);}}else if(STOP.has(p)){const burst=Math.min(n,Math.floor(.022*SR));for(let i=0;i<burst;i++){const amp=microAmp(baseAmp,i,burst,seed),q=i/Math.max(1,burst-1);out[i]=((hash01(seed,i*3,12)-.5)*2)*.25*(1-q)*(amp/BASE_AMP);}}return out;}
function silence(d){return new Float32Array(Math.max(1,Math.floor(d*SR)));} function concat(a){const n=a.reduce((s,x)=>s+x.length,0),o=new Float32Array(n);let k=0;for(const x of a){o.set(x,k);k+=x.length;}return o;}
function render(text){const tokens=G1.phonemesFor(text),parts=[];let prevWord='',seed=0;const ph=tokens.map((t,i)=>t.type==='ph'?i:-1).filter(i=>i>=0);const neighbor=(i,dir)=>{let j=i+dir;while(j>=0&&j<tokens.length){if(tokens[j].type==='ph')return tokens[j].v;if(tokens[j].type==='punct')break;j+=dir;}return null;};for(let i=0;i<tokens.length;i++){const tok=tokens[i],d=G1.g1Duration(tok);if(tok.type!=='ph'){parts.push(silence(d));continue;}const progress=phraseProgress(tokens,i),weight=stressWeight(tok,prevWord),f0=macroF0(progress,weight),amp=macroAmp(progress,weight);parts.push(synthPh(tok.v,d,f0,amp,seed++,neighbor(i,-1),neighbor(i,1)));prevWord=tok.word;}return concat(parts);}
function wav(buf){const b=Buffer.alloc(44+buf.length*2);b.write('RIFF',0);b.writeUInt32LE(36+buf.length*2,4);b.write('WAVE',8);b.write('fmt ',12);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(SR,24);b.writeUInt32LE(SR*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(buf.length*2,40);for(let i=0;i<buf.length;i++){const x=Math.max(-1,Math.min(1,buf[i]));b.writeInt16LE(Math.round(x*32767),44+i*2);}return b;}
function renderSet(out){fs.mkdirSync(out,{recursive:true});const all=[],manifest={schema:'DIAMOND_GATE_SPEECH_KERNEL_G4_RENDER_v1',sampleRate:SR,heldTimingGeneration:'G1',heldMacroProsodyGeneration:'G2',heldMicroProsodyGeneration:'G3',lines:[]};G1.LINES.forEach((text,i)=>{const audio=render(text),id=`C${String(i+1).padStart(2,'0')}`,file=`G4_${id}.wav`;fs.writeFileSync(path.join(out,file),wav(audio));all.push(audio,silence(.42));manifest.lines.push({generation:'G4',id,text,file,durationSeconds:audio.length/SR});});fs.writeFileSync(path.join(out,'G4_COMPASS_8_BEATS.wav'),wav(concat(all)));fs.writeFileSync(path.join(out,'G4_render-manifest.json'),JSON.stringify(manifest,null,2));}
if(require.main===module)renderSet(process.argv[2]||'.');
module.exports={render,renderSet,interpFormants,spectralTilt};
