import { canonicalDigest, deepFreeze } from '../../tools/instrument-platform/platform-core.mjs';
import { IMI_EMPIRICAL_ENGINE_META, DEFAULT_IMI_ORDINAL_SCALE } from '../../tools/imi-empirical-platform/imi-core-and-empirical-portfolio-engine.v1.mjs';

const authorityBody = {
  schemaVersion: 'IMI_EMPIRICAL_PLATFORM_AUTHORITY_v1',
  operation: 'IMI_ACTIVE_TOOLBASE_EMPIRICAL_PLATFORM_INTEGRATION_AND_BRANCH_OPERATIONAL_INTAKE_v1',
  deliverable: 'IMI_CORE_AND_EMPIRICAL_PORTFOLIO_ENGINE_v1',
  class: 'REPOSITORY_INTEGRATED_EMPIRICAL_INTRINSIC_MANEUVERABILITY_INDEX_ROUTE_SCORING_PORTFOLIO_RECEIPT_CROSS_DOMAIN_SYNTHESIS_GENERALIZABILITY_PROTOCOL_AND_PARALLEL_EXTERNAL_TEST_TOOL',
  status: 'PREOFFICIAL_REPOSITORY_BRANCH_OPERATIONAL_EMPIRICAL_TOOL_WITH_PHASE_3_EXECUTED_AND_TWO_OPEN_HELD_TRACKS',
  sourceDisposition: 'SANDBOX_PROTOTYPE_PROMOTED_AS_NONCONTROLLING_SOURCE_MATERIAL',
  empiricalFunction: [
    'ROUTE_SPECIFIC_IMI_SCORING',
    'CS_WMI_ADDITIVE_AND_GEOMETRIC_COMPARATORS',
    'MISSINGNESS_AND_UNEVALUABLE_CLASSIFICATION',
    'HARD_COLLAPSE_DETECTION',
    'CASE_LEVEL_OUTPUT',
    'STUDY_RECEIPT_GENERATION',
    'PORTFOLIO_REGISTRY_APPEND_ENTRY_GENERATION',
    'GENERIC_EMPIRICAL_INTAKE_RUNNER',
    'REPOSITORY_BRANCH_OUTPUT_ARCHIVE_WRITER',
    'CURRENT_PUBLIC_SOURCE_RUNTIME_DOWNLOAD_AND_IDENTITY_BINDING',
    'EXISTING_FOUR_DOMAIN_EXECUTION_SURFACE_COMPLETION',
    'CROSS_DOMAIN_MEASUREMENT_BEHAVIOR_SYNTHESIS',
    'ENGINE_ROUTE_DOMAIN_DATASET_AND_UNRESOLVED_FINDING_CLASSIFICATION',
    'ROUTE_EVIDENCE_LEVEL_ASSIGNMENT',
    'GENERALIZABILITY_DOMAIN_ADMISSION_STANDARD',
    'PREREGISTERED_CROSS_DOMAIN_HYPOTHESES',
    'FOUR_TRACK_REPLICATION_GRID',
    'HELD_OUT_DATA_REQUIREMENTS',
    'INDEPENDENT_REPRODUCTION_STANDARD',
    'NEGATIVE_RESULT_AND_DISAGREEMENT_CUSTODY',
    'PHASE_3_PARALLEL_EXTERNAL_TEST_EXECUTION',
    'SOURCE_AVAILABILITY_HOLD_CLASSIFICATION',
    'HELD_OUT_TEMPORAL_BEE_REPLICATION',
    'DSSI_REMAINING_COUNTRY_CONTINUATION',
    'PHASE_3_COLLECTIVE_DISPOSITION_AND_PHASE_4_GATE'
  ],
  includedSchemas: [
    'IMI_ROUTE_SCHEMA_v1',
    'IMI_STUDY_RECEIPT_SCHEMA_v1',
    'IMI_EMPIRICAL_PORTFOLIO_REGISTRY_SCHEMA_v1',
    'IMI_SCOPE_GENERALIZABILITY_AND_PRACTICAL_VALUE_FIVE_PHASE_PLAN_v1',
    'IMI_MULTI_DOMAIN_EMPIRICAL_PORTFOLIO_SYNTHESIS_PROTOCOL_v1',
    'IMI_MULTI_DOMAIN_EMPIRICAL_PORTFOLIO_SYNTHESIS_v1',
    'IMI_MULTI_DOMAIN_EMPIRICAL_PORTFOLIO_SYNTHESIS_RECEIPT_v1',
    'IMI_GENERALIZABILITY_PROTOCOL_v1',
    'IMI_GENERALIZABILITY_PROTOCOL_RECEIPT_v1',
    'IMI_GENERALIZABILITY_PROTOCOL_VERIFICATION_RESULT_v1',
    'IMI_PHASE_3_PARALLEL_EXTERNAL_TESTS_MANIFEST_v1',
    'IMI_PHASE_3_HOSPITAL_EXTERNAL_REPLICATION_RECEIPT_v1',
    'IMI_PHASE_3_SPEECH_HELD_OUT_REPRODUCTION_RECEIPT_v1',
    'IMI_PHASE_3_BEE_LONGER_PANEL_RECEIPT_v1',
    'IMI_PHASE_3_DSSI_REMAINING_COUNTRY_RECEIPT_v1',
    'IMI_PHASE_3_PARALLEL_EXTERNAL_TESTS_SUMMARY_v1',
    'IMI_PHASE_3_PARALLEL_EXTERNAL_TESTS_RECEIPT_v1'
  ],
  engineMeta: IMI_EMPIRICAL_ENGINE_META,
  defaultOrdinalScale: DEFAULT_IMI_ORDINAL_SCALE.scaleId,
  exactPathScope: [
    '.github/workflows/h-earth-imi-empirical-platform.yml',
    'h-earth-3d/control-plane/imi-empirical-platform/IMI_EMPIRICAL_PLATFORM_AUTHORITY.v1.mjs',
    'h-earth-3d/control-plane/imi-empirical-platform/IMI_SCOPE_GENERALIZABILITY_AND_PRACTICAL_VALUE_FIVE_PHASE_PLAN_v1.json',
    'h-earth-3d/tools/imi-empirical-platform/README.md',
    'h-earth-3d/tools/imi-empirical-platform/index.html',
    'h-earth-3d/tools/imi-empirical-platform/imi-core-and-empirical-portfolio-engine.v1.mjs',
    'h-earth-3d/tools/imi-empirical-platform/schemas/route.schema.v1.json',
    'h-earth-3d/tools/imi-empirical-platform/schemas/study-receipt.schema.v1.json',
    'h-earth-3d/tools/imi-empirical-platform/schemas/portfolio-registry.schema.v1.json',
    'h-earth-3d/tools/imi-empirical-platform/synthesis/imi-multi-domain-empirical-portfolio-synthesis-protocol.v1.json',
    'h-earth-3d/tools/imi-empirical-platform/generalizability/imi-generalizability-protocol.v1.json',
    'h-earth-3d/tools/imi-empirical-platform/generalizability/imi-phase3-parallel-external-tests-manifest.v1.json',
    'h-earth-3d/tools/imi-empirical-platform/routes/example-hospital-route.v1.json',
    'h-earth-3d/tools/imi-empirical-platform/routes/cms-hospital-refresh-2026-route.v1.json',
    'h-earth-3d/tools/imi-empirical-platform/routes/usda-honey-bee-refresh-2026-route.v1.json',
    'h-earth-3d/tools/imi-empirical-platform/routes/dssi-sovereign-debt-service-expansion-2026-route.v1.json',
    'h-earth-3d/tools/imi-empirical-platform/routes/spontaneous-speech-current-repository-rerun-2026-route.v1.json',
    'h-earth-3d/tools/imi-empirical-platform/examples/example-hospital-rows.v1.json',
    'h-earth-3d/tools/imi-empirical-platform/studies/runs/IMI_SPONTANEOUS_SPEECH_REPOSITORY_RERUN_2026_v1/spontaneous-speech-rerun-summary.v1.json',
    'h-earth-3d/tools/imi-empirical-platform/studies/runs/IMI_USDA_HONEY_BEE_COLONY_RESILIENCE_REFRESH_2026_v1/usda-honey-bee-phase-consolidation-receipt.v1.json',
    'h-earth-3d/tools/imi-empirical-platform/studies/runs/IMI_EXISTING_FOUR_DOMAIN_EMPIRICAL_PORTFOLIO_COMPLETION_v1/imi-existing-four-domain-portfolio-completion-receipt.v1.json',
    'h-earth-3d/tools/imi-empirical-platform/studies/runs/IMI_MULTI_DOMAIN_EMPIRICAL_PORTFOLIO_SYNTHESIS_v1/imi-multi-domain-empirical-portfolio-synthesis.v1.json',
    'h-earth-3d/tools/imi-empirical-platform/studies/runs/IMI_MULTI_DOMAIN_EMPIRICAL_PORTFOLIO_SYNTHESIS_v1/imi-multi-domain-empirical-portfolio-synthesis-receipt.v1.json',
    'h-earth-3d/tools/imi-empirical-platform/studies/runs/IMI_GENERALIZABILITY_PROTOCOL_v1/imi-generalizability-protocol-receipt.v1.json',
    'h-earth-3d/tools/imi-empirical-platform/studies/runs/IMI_PARALLEL_EXTERNAL_TESTS_v1/hospital-phase3-durable-evidence-package.v1.json',
    'h-earth-3d/tools/imi-empirical-platform/studies/runs/IMI_PARALLEL_EXTERNAL_TESTS_v1/speech-phase3-durable-evidence-package.v1.json',
    'h-earth-3d/tools/imi-empirical-platform/studies/runs/IMI_PARALLEL_EXTERNAL_TESTS_v1/bee-phase3-durable-evidence-package.v1.json',
    'h-earth-3d/tools/imi-empirical-platform/studies/runs/IMI_PARALLEL_EXTERNAL_TESTS_v1/dssi-phase3-durable-evidence-package.v1.json',
    'h-earth-3d/tools/imi-empirical-platform/studies/runs/IMI_PARALLEL_EXTERNAL_TESTS_v1/imi-phase3-collective-durable-evidence-package.v1.json',
    'h-earth-3d/validation/imi-empirical-platform/imi.empirical-platform.runner.mjs',
    'h-earth-3d/validation/imi-empirical-platform/imi.empirical-intake.runner.mjs',
    'h-earth-3d/validation/imi-empirical-platform/imi.empirical-operational-suite.runner.mjs',
    'h-earth-3d/validation/imi-empirical-platform/imi.cms-hospital-refresh-2026.runner.mjs',
    'h-earth-3d/validation/imi-empirical-platform/imi.usda-honey-bee-refresh-2026.runner.mjs',
    'h-earth-3d/validation/imi-empirical-platform/imi.dssi-sovereign-debt-service-expansion-2026.runner.mjs',
    'h-earth-3d/validation/imi-empirical-platform/imi.spontaneous-speech-rerun-2026.runner.mjs',
    'h-earth-3d/validation/imi-empirical-platform/imi.existing-four-domain-portfolio-completion.runner.mjs',
    'h-earth-3d/validation/imi-empirical-platform/imi.multi-domain-portfolio-synthesis.runner.mjs',
    'h-earth-3d/validation/imi-empirical-platform/imi.multi-domain-portfolio-synthesis.runtime-boundary-adapter.mjs',
    'h-earth-3d/validation/imi-empirical-platform/imi.multi-domain-portfolio-synthesis.phase-progression-adapter.mjs',
    'h-earth-3d/validation/imi-empirical-platform/imi.generalizability-protocol.runner.mjs',
    'h-earth-3d/validation/imi-empirical-platform/imi.phase3.hospital-external-or-next-release.runner.mjs',
    'h-earth-3d/validation/imi-empirical-platform/imi.phase3.speech-heldout-dataset.runner.mjs',
    'h-earth-3d/validation/imi-empirical-platform/imi.phase3.bee-longer-panel.runner.mjs',
    'h-earth-3d/validation/imi-empirical-platform/imi.phase3.dssi-remaining-country-continuation.runner.mjs',
    'h-earth-3d/validation/imi-empirical-platform/imi.phase3.parallel-external-tests.collective.runner.mjs'
  ],
  operationalIntakeContract: {
    branchOperational: true,
    oneRepositoryBasedEngine: 'h-earth-3d/tools/imi-empirical-platform/imi-core-and-empirical-portfolio-engine.v1.mjs',
    genericRunner: 'h-earth-3d/validation/imi-empirical-platform/imi.empirical-intake.runner.mjs',
    suiteRunner: 'h-earth-3d/validation/imi-empirical-platform/imi.empirical-operational-suite.runner.mjs',
    outputFiles: [
      'imi-study-run-output.v1.json',
      'imi-study-receipt.v1.json',
      'imi-case-results.v1.json',
      'imi-portfolio-registry.v1.json',
      'imi-portfolio-summary.v1.json',
      'imi-empirical-intake-operational-receipt.v1.json'
    ],
    explicitDatasetAdmissionRequired: true,
    automaticPerceivedDataCapture: false
  },
  currentEmpiricalExecutionSurface: {
    hospitalCurrentRepositoryRun: 'PASS_CLOSED_CMS_HOSPITAL_REFRESH_2026_REPOSITORY_INTAKE_RUN',
    spontaneousSpeechCurrentRepositoryRun: 'PASS_CLOSED_SPONTANEOUS_SPEECH_CURRENT_REPOSITORY_RERUN_2026',
    honeyBeeCurrentRepositoryRun: 'PASS_CLOSED_USDA_HONEY_BEE_CURRENT_REFRESH_PHASE_CONSOLIDATED',
    dssiCurrentRepositoryRun: 'PASS_CLOSED_DSSI_PARTIAL_ALL_COUNTRY_EXPANSION_PHASE_CONSOLIDATED',
    collectiveResult: 'PASS_CLOSED_EXISTING_FOUR_DOMAIN_EMPIRICAL_EXECUTION_SURFACE_COMPLETE',
    collectiveReceipt: 'h-earth-3d/tools/imi-empirical-platform/studies/runs/IMI_EXISTING_FOUR_DOMAIN_EMPIRICAL_PORTFOLIO_COMPLETION_v1/imi-existing-four-domain-portfolio-completion-receipt.v1.json'
  },
  scopeGeneralizabilityProgram: {
    program: 'IMI_SCOPE_GENERALIZABILITY_AND_PRACTICAL_VALUE_PROGRAM_v1',
    phaseCount: 5,
    phase1Status: 'PASS_CLOSED',
    phase1Operation: 'IMI_MULTI_DOMAIN_EMPIRICAL_PORTFOLIO_SYNTHESIS_v1',
    phase1Result: 'PASS_CLOSED_PHASE_1_MULTI_DOMAIN_EMPIRICAL_PORTFOLIO_SYNTHESIS',
    phase1SynthesisPath: 'h-earth-3d/tools/imi-empirical-platform/studies/runs/IMI_MULTI_DOMAIN_EMPIRICAL_PORTFOLIO_SYNTHESIS_v1/imi-multi-domain-empirical-portfolio-synthesis.v1.json',
    phase1ReceiptPath: 'h-earth-3d/tools/imi-empirical-platform/studies/runs/IMI_MULTI_DOMAIN_EMPIRICAL_PORTFOLIO_SYNTHESIS_v1/imi-multi-domain-empirical-portfolio-synthesis-receipt.v1.json',
    phase2Status: 'PASS_CLOSED',
    phase2Operation: 'IMI_GENERALIZABILITY_PROTOCOL_v1',
    phase2Result: 'PASS_CLOSED_PHASE_2_GENERALIZABILITY_PROTOCOL',
    phase2ProtocolPath: 'h-earth-3d/tools/imi-empirical-platform/generalizability/imi-generalizability-protocol.v1.json',
    phase2ReceiptPath: 'h-earth-3d/tools/imi-empirical-platform/studies/runs/IMI_GENERALIZABILITY_PROTOCOL_v1/imi-generalizability-protocol-receipt.v1.json',
    phase3Status: 'EXECUTED_WITH_OPEN_HELD_TRACKS',
    phase3Operation: 'IMI_PARALLEL_EXTERNAL_TESTS_v1',
    phase3Result: 'PHASE_3_EXECUTED_PARTIAL_TRACKS_HELD_OPEN',
    phase3ManifestPath: 'h-earth-3d/tools/imi-empirical-platform/generalizability/imi-phase3-parallel-external-tests-manifest.v1.json',
    phase3CollectiveEvidencePath: 'h-earth-3d/tools/imi-empirical-platform/studies/runs/IMI_PARALLEL_EXTERNAL_TESTS_v1/imi-phase3-collective-durable-evidence-package.v1.json',
    openHeldTracks: [
      'HOSPITAL_EXTERNAL_OR_NEXT_RELEASE_REPLICATION',
      'SPEECH_HELD_OUT_DATASET_REPRODUCTION'
    ],
    phase4Status: 'NOT_AUTHORIZED_NO_ADMISSIBLE_CANDIDATE_TRACK',
    phase5Status: 'NOT_AUTHORIZED',
    nextOperation: 'RESOLVE_OPEN_PHASE_3_HOLDS_WITHOUT_ROUTE_RETUNING',
    phasesFourAndFiveExecuted: false,
    planPath: 'h-earth-3d/control-plane/imi-empirical-platform/IMI_SCOPE_GENERALIZABILITY_AND_PRACTICAL_VALUE_FIVE_PHASE_PLAN_v1.json'
  },
  phase1Determination: {
    evaluatedCases: 4598,
    validCases: 3570,
    unevaluableCases: 1028,
    hardCollapseCases: 3,
    routeFamilies: 4,
    computationalGeneralizability: 'SUPPORTED_ACROSS_FOUR_CURRENT_ROUTE_FAMILIES',
    structuralGeneralizability: 'PARTIALLY_SUPPORTED_FOR_COMMON_OUTPUT_CLASSES',
    distributionalGeneralizability: 'NOT_YET_ESTABLISHED_INSTRUMENT_WIDE',
    predictiveGeneralizability: 'ROUTE_SPECIFIC_AND_INCOMPLETE',
    operationalGeneralizability: 'SUPPORTED_AT_INTERNAL_REPOSITORY_REPRODUCTION_LEVEL',
    decisionGeneralizability: 'NOT_YET_TESTED',
    universalMultiplicativeSuperiorityEstablished: false
  },
  phase2Determination: {
    protocolDigest: 'fnv1a32:54474299',
    frozenPlanDigest: 'fnv1a32:ab7fcb4d',
    receiptDigest: 'fnv1a32:52fffa7f',
    protocolStatus: 'FROZEN',
    domainAdmissionCriterionCount: 10,
    preregisteredHypothesisCount: 6,
    replicationTrackCount: 4,
    heldOutMandatoryRuleCount: 10,
    independentReproductionOutputCount: 12,
    newDataInspected: false,
    newDataTestsExecuted: false,
    phase3Authorized: true
  },
  phase3Determination: {
    executedTracks: 4,
    passClosedTracks: 2,
    heldOpenTracks: 2,
    failedTracks: 0,
    phase4CandidateTracks: 0,
    phase3Closed: false,
    hospital: {
      result: 'HELD_NO_ELIGIBLE_NEXT_RELEASE_OR_NON_CMS_PACKAGE',
      reason: 'CMS_REQUIRED_DATASET_PAIR_NOT_NEWER_THAN_FROZEN_BASELINE_AND_NO_NON_CMS_PACKAGE_PROVIDED'
    },
    speech: {
      result: 'HELD_LAWFUL_HELD_OUT_SPEECH_PACKAGE_NOT_AVAILABLE_TO_EXECUTION',
      reason: 'CONTROLLED_ACCESS_OR_SUPPLIED_FIVE_FEATURE_PACKAGE_REQUIRED'
    },
    bees: {
      result: 'PASS_CLOSED_PHASE_3_BEE_LONGER_PANEL_EXECUTED_WITH_FINDINGS_RETAINED',
      heldOutCases: 80,
      validCases: 80,
      weakestFactorClasses: 3,
      meanAbsoluteImiAdditiveDifference: 0.2619061964764452,
      heldOutTemporalAssociationSupported: false,
      phase4Candidate: false
    },
    dssi: {
      result: 'PASS_CLOSED_PHASE_3_DSSI_REMAINING_COUNTRY_CONTINUATION_MINIMUM_MET',
      newCountryCases: 34,
      combinedCountryCount: 66,
      candidateCountryCount: 70,
      meanAbsoluteImiAdditiveDifference: 0.09633105268598466,
      outcomeTestExecuted: false,
      phase4Candidate: false
    },
    collectiveReceiptDigest: 'fnv1a32:b2e43be0',
    phase4Authorized: false
  },
  phase3WorkflowEvidence: {
    verifiedHeadSha: 'a8db6015e3f29c5818bc052433e5e4a4d4fbcf20',
    workflowName: 'H-Earth IMI Empirical Platform',
    workflowRunId: 31032196707,
    baseVerificationJobId: 92395391998,
    hospitalJobId: 92395538003,
    speechJobId: 92395537952,
    beeJobId: 92395538028,
    dssiJobId: 92395538020,
    collectiveJobId: 92396112934,
    workflowConclusion: 'success'
  },
  boundaries: {
    officialScaleClaimed: false,
    routeCertificationPerformed: false,
    realStudyDataLoaded: true,
    empiricalValidationClaimed: false,
    productionReleaseAuthorized: false,
    publicReleaseAuthorized: false,
    mainBranchMerged: false,
    liveWebsiteOperational: false,
    rawCrossRouteIMIMagnitudeComparisonAuthorized: false,
    universalMultiplicativeSuperiorityClaimed: false,
    universalPredictiveValidityClaimed: false,
    phase2GeneralizabilityProtocolExecuted: true,
    externalTestsExecuted: true,
    allPhase3TracksClosed: false,
    decisionUtilityPilotsExecuted: false,
    phase4Authorized: false,
    independentMultiDomainReproductionExecuted: false,
    phase5Authorized: false,
    fullCrossDomainResearchSynthesisPerformed: true,
    stop: 'STOP_WITH_PHASE_3_EXECUTED_TWO_TRACKS_PASS_CLOSED_TWO_TRACKS_HELD_OPEN_PHASE_4_NOT_AUTHORIZED'
  },
  result: 'IMI_EMPIRICAL_PLATFORM_PHASE_3_EXECUTED_PARTIAL_TRACKS_HELD_OPEN_PHASE_4_NOT_AUTHORIZED'
};

export const IMI_EMPIRICAL_PLATFORM_AUTHORITY_v1 = deepFreeze({
  ...authorityBody,
  authorityDigest: canonicalDigest(authorityBody)
});

export default IMI_EMPIRICAL_PLATFORM_AUTHORITY_v1;
