#!/usr/bin/env node
import fs from'node:fs';import path from'node:path';import crypto from'node:crypto';import{execFileSync}from'node:child_process';import{fileURLToPath,pathToFileURL}from'node:url';
const G='e876e6107d3e01a19e76c9fd487b6de0d511cb25',T='9c1fa274cdf53afcbb26a7c84a5dc55fc8f7ca51',L=387,S='7134a2ba0f38a426070bac6da4c63e369fc55654ddd7b4bd27a93f1cc6e9a87d',O='THREE_TIER_CODESPACE_EXECUTION_SUBSTRATE_INTEGRATION_v1',R='.github/ai-router/codespace-execution';
const A=["AGENTS.md","AI_ENTRYPOINT.json",".github/ai-router/router.v1.json",".github/ai-router/execution-backends.v1.json",".github/ai-router/shared-procedures.v1.json",".github/ai-router/codespace-execution/AGENTS.md",".github/ai-router/codespace-execution/README.md",".github/ai-router/codespace-execution/execution-environment-contract.v1.json",".github/ai-router/codespace-execution/builder-profile.v1.json",".github/ai-router/codespace-execution/fresh-verifier-profile.v1.json",".github/ai-router/codespace-execution/outage-continuity-policy.v1.json",".github/ai-router/codespace-execution/project-profiles/imi.v1.json",".github/ai-router/codespace-execution/project-profiles/methods-information-benchmark.v1.json",".github/ai-router/codespace-execution/project-profiles/h-earth-v2.v1.json",".github/ai-router/codespace-execution/schemas/environment-receipt.schema.v1.json",".github/ai-router/codespace-execution/schemas/command-execution-receipt.schema.v1.json",".github/ai-router/codespace-execution/schemas/equality-receipt.schema.v1.json",".github/ai-router/codespace-execution/schemas/destruction-receipt.schema.v1.json",".github/ai-router/codespace-execution/verify-substrate.v1.mjs",".github/ai-router/codespace-execution/templates/devcontainer.template.v1.json",".github/ai-router/codespace-execution/templates/actions-replay-workflow.template.v1.yml",".github/ai-router/codespace-execution/receipts/builder.receipt.v1.json",".github/ai-router/codespace-execution/receipts/fresh-verifier.receipt.v1.json",".github/ai-router/codespace-execution/receipts/independent-equality.receipt.v1.json",".github/ai-router/codespace-execution/receipts/operation-closure.receipt.v1.json"];
const Q=new Set([R+'/receipts/builder.receipt.v1.json',R+'/receipts/fresh-verifier.receipt.v1.json',R+'/receipts/independent-equality.receipt.v1.json',R+'/receipts/operation-closure.receipt.v1.json']);
const P=new Map([['AGENTS.md','d62c71d82c09bf9c2f8c0643ad6501f32f21d2d2'],['AI_ENTRYPOINT.json','177438dea822a8039d5476842b8b141bffcccced'],['.github/ai-router/router.v1.json','abfab1c5f33ca66b32b5b5a438a06016c04cab10']]);
const M=new Set(['.github/ai-router/execution-backends.v1.json','.github/ai-router/shared-procedures.v1.json']),X=A.filter(p=>!P.has(p));
const st=v=>Array.isArray(v)?v.map(st):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,st(v[k])])):v,txt=v=>JSON.stringify(st(v),null,2)+'\n';
const git=(r,...a)=>execFileSync('git',a,{cwd:r,encoding:'utf8'}).trim(),js=(r,p)=>JSON.parse(fs.readFileSync(path.join(r,p),'utf8')),same=(a,b)=>JSON.stringify([...new Set(a)].sort())===JSON.stringify([...new Set(b)].sort());
function args(v){let o={mode:'builder',output:null};for(let i=0;i<v.length;i++)if(v[i]==='--mode')o.mode=v[++i]??'';else if(v[i]==='--output')o.output=v[++i]??null;else throw Error('UNKNOWN_ARGUMENT:'+v[i]);if(!['builder','fresh-verifier'].includes(o.mode))throw Error('INVALID_MODE:'+o.mode);return o}
function fp(r){let h=crypto.createHash('sha256');h.update(`operation=${O}\ngoverning=${G}\nlock=${L}\nscope=${S}\n`);for(const p of A.filter(x=>!Q.has(x)).sort()){h.update(p);h.update('\0');h.update(fs.readFileSync(path.join(r,p)));h.update('\0')}return h.digest('hex')}
export function verifyThreeTierExecutionSubstrate({mode='builder',output=null}={}){const start=path.dirname(fileURLToPath(import.meta.url)),r=git(start,'rev-parse','--show-toplevel'),c={},ck=(i,p,d=null)=>c[i]={pass:!!p,detail:d},h=git(r,'rev-parse','HEAD^{commit}'),tr=git(r,'rev-parse','HEAD^{tree}'),mb=git(r,'merge-base',G,h),wt=git(r,'status','--porcelain=v1','--untracked-files=all'),ns=git(r,'diff','--name-status',G+'..'+h).split(/\r?\n/).filter(Boolean),chg=ns.map(x=>x.split('\t').at(-1)),sm=new Map(ns.map(x=>{let f=x.split('\t');return[f.at(-1),f[0]]}));
ck('GOVERNING_HEAD_PRESENT',git(r,'cat-file','-t',G)==='commit');ck('GOVERNING_TREE_EXACT',git(r,'rev-parse',G+'^{tree}')===T);ck('GOVERNING_ANCESTRY',mb===G,mb);ck('CANDIDATE_DISTINCT_FROM_GOVERNING',h!==G,h);ck('WORKTREE_CLEAN',wt==='',wt);ck('ALLOWED_SCOPE_COUNT_25',A.length===25,A.length);ck('EXPECTED_CHANGED_COUNT_22',X.length===22,X.length);ck('EXACT_CHANGED_SCOPE',same(chg,X)&&chg.length===X.length,chg);ck('NO_DELETIONS',ns.every(x=>!x.startsWith('D\t')));ck('TWO_INTEGRATION_FILES_MODIFIED',[...M].every(p=>sm.get(p)==='M'));ck('TWENTY_NEW_FILES_ADDED',X.filter(p=>!M.has(p)).every(p=>sm.get(p)==='A'));ck('ALL_25_BOUND_PATHS_MATERIALIZED',A.every(p=>fs.existsSync(path.join(r,p))));
for(const[p,b]of P){let a=git(r,'hash-object',p);ck('PRESERVED_'+p.replace(/[^A-Za-z0-9]+/g,'_').toUpperCase(),a===b,{expected:b,actual:a})}
const e=js(r,'AI_ENTRYPOINT.json'),ro=js(r,'.github/ai-router/router.v1.json'),be=js(r,'.github/ai-router/execution-backends.v1.json'),sp=js(r,'.github/ai-router/shared-procedures.v1.json'),co=js(r,R+'/execution-environment-contract.v1.json'),bu=js(r,R+'/builder-profile.v1.json'),fr=js(r,R+'/fresh-verifier-profile.v1.json'),ou=js(r,R+'/outage-continuity-policy.v1.json'),pp=['imi.v1.json','methods-information-benchmark.v1.json','h-earth-v2.v1.json'].map(x=>js(r,R+'/project-profiles/'+x)),rs=['environment-receipt.schema.v1.json','command-execution-receipt.schema.v1.json','equality-receipt.schema.v1.json','destruction-receipt.schema.v1.json'].map(x=>js(r,R+'/schemas/'+x));
ck('ENTRYPOINT_BINDINGS_EXIST',e.executionBackendRegistry==='.github/ai-router/execution-backends.v1.json'&&e.sharedProcedureRegistry==='.github/ai-router/shared-procedures.v1.json');ck('ROUTER_ALREADY_OWNS_SUBSTRATE_PREFIX',ro.routerInfrastructure?.ownedPathPrefixes?.includes('.github/ai-router/'));ck('CODESPACE_BACKEND_REGISTERED',be.backends?.some(b=>b.backendId==='CODESPACE_DISPOSABLE_EXECUTION'&&b.nativeChatGPTTerminalTransportRequired===false&&b.nativeChatGPTTerminalTransportCreated===false&&b.persistentCodespaceAuthorityAllowed===false));
let need=new Set(['DISPOSABLE_EXECUTION_REQUEST','FRESH_VERIFIER_REEXECUTION','INDEPENDENT_EXECUTION_EQUALITY','EXECUTION_ENVIRONMENT_DESTRUCTION']),have=new Set((sp.procedures??[]).map(x=>x.procedureId));ck('FOUR_EXECUTION_PROCEDURES_REGISTERED',[...need].every(x=>have.has(x)));ck('ENVIRONMENT_CONTRACT_BOUND',co.schema==='THREE_TIER_CODESPACE_EXECUTION_ENVIRONMENT_CONTRACT_v1'&&co.governingHead===G&&co.constructionLock?.generation===L&&co.constructionLock?.scopeHash===S&&co.nativeChatGPTTerminalTransportCreated===false);ck('BUILDER_PROFILE_BOUND',bu.roleId==='THREE_TIER_CODESPACE_EXECUTION_SUBSTRATE_BUILDER'&&bu.mayRepairCandidate===false&&bu.mayMutateTarget===false);ck('FRESH_VERIFIER_DISTINCT',fr.roleId==='FRESH_THREE_TIER_CODESPACE_EXECUTION_SUBSTRATE_VERIFIER'&&fr.distinctFromBuilder===true&&fr.freshCleanEnvironmentRequired===true&&fr.builderMutableStateReuseProhibited===true);ck('OUTAGE_CONTINUITY_FAILS_CLOSED',ou.manualMetadataReconstructionAsExecutionProof===false&&ou.noActiveFallbackDisposition==='BLOCKED_NONTERMINAL_EXECUTION_SURFACE_UNAVAILABLE');ck('THREE_PROJECT_PROFILES',same(pp.map(x=>x.projectId),['IMI','METHODS_INFORMATION_BENCHMARK','H_EARTH'])&&pp.every(x=>x.productMutationAuthorityCreated===false&&x.mergeAuthorityCreated===false));ck('FOUR_RECEIPT_SCHEMAS',rs.length===4&&rs.every(x=>x.$schema==='https://json-schema.org/draft/2020-12/schema'&&x.type==='object'));
let ag=fs.readFileSync(path.join(r,R+'/AGENTS.md'),'utf8'),rd=fs.readFileSync(path.join(r,R+'/README.md'),'utf8'),at=fs.readFileSync(path.join(r,R+'/templates/actions-replay-workflow.template.v1.yml'),'utf8');ck('NO_NATIVE_TERMINAL_CAPABILITY_CLAIM',/does not create a ChatGPT terminal API/i.test(ag)&&/cannot manufacture a native ChatGPT Codespaces terminal connector/i.test(rd));ck('ACTIONS_TEMPLATE_NONACTIVE',at.includes('NONACTIVE TEMPLATE')&&!((R+'/templates/actions-replay-workflow.template.v1.yml').startsWith('.github/workflows/')));ck('NO_PRODUCT_PATH_IN_BOUNDARY',!A.some(p=>p.startsWith('h-earth-3d/')||p.startsWith('showroom/')||p.startsWith('control-plane/methods-information-benchmark/')));
for(const p of Q){let z=js(r,p);ck('RECEIPT_'+path.basename(p).replace(/[^A-Za-z0-9]+/g,'_').toUpperCase(),z.operationId===O&&z.governingHead===G&&z.lockGeneration===L&&z.scopeHash===S&&z.evidenceInvented===false)}
const f=fp(r),bad=Object.entries(c).filter(([,v])=>v.pass!==true).map(([k])=>k),rec=st({schema:'THREE_TIER_CODESPACE_EXECUTION_SUBSTRATE_VERIFICATION_RECEIPT_v1',result:bad.length?'FAIL_CLOSED':'PASS',mode,operationId:O,governingHead:G,governingTree:T,lockGeneration:L,scopeHash:S,candidateHead:h,candidateTree:tr,allowedPathCount:A.length,changedPathCount:chg.length,preservedBindingPathCount:P.size,substrateFingerprint:f,fingerprintPathCount:A.length-Q.size,receiptFilesExcludedFromFingerprint:[...Q].sort(),checks:c,issues:bad});if(output){let a=path.resolve(output);fs.mkdirSync(path.dirname(a),{recursive:true});fs.writeFileSync(a,txt(rec))}return rec}
async function main(){let a=args(process.argv.slice(2)),r=verifyThreeTierExecutionSubstrate(a);process.stdout.write(txt(r));if(r.result!=='PASS')process.exitCode=1}const invoked=process.argv[1]&&pathToFileURL(path.resolve(process.argv[1])).href===import.meta.url;if(invoked)main().catch(e=>{process.stderr.write(txt({schema:'THREE_TIER_CODESPACE_EXECUTION_SUBSTRATE_VERIFIER_FAILURE_v1',result:'FAIL_CLOSED',error:e instanceof Error?e.message:String(e)}));process.exitCode=1});
