const CONTRACT=Object.freeze({
 id:'AWARDS_COHERENCE_LIVING_OBJECT_CYCLE_C_V2_RECOGNIZABLE_BRAIN',cycle:'C_COHERENCE',claim:'Coherence can be inspected without pretending uncertainty is certainty.',recognizableObject:'BRAIN',signatureEvent:'NEURAL_SYNCHRONIZATION',eventCount:1,
 sourceBinding:Object.freeze({governingHead:'56c1630070b869f5e3a2d91e53a0812fd885a046',brainFreeze:Object.freeze({path:'/inspection/compass/brain-gen1-hra/geometry.freeze.v1.json',blob:'48048557e21435310dc8c255c3e880df3deb208c',authority:'NIH Human Reference Atlas',asset:'Allen_M_Brain.glb',meshes:283,triangles:656268}),brainInspector:Object.freeze({path:'/inspection/compass/brain-gen1-hra/inspector.js',blob:'1af870372007f93d72f7864a5f698432f0cfab21'})}),
 semanticBinding:Object.freeze({posture:'CALIBRATE_SELF_ALIGN_TEAMS_STABILIZE_SCALE',rule:'NO_RECEIPTS_NO_UPGRADE',observerInvariant:'SAME_RECEIPTS_SAME_RESULT',actionClasses:Object.freeze(['PROCEED','HOLD','CONTAIN']),dimensions:Object.freeze(['SCOPE','RECEIPTS','RULES','SCALE']),numericScoreAuthorized:false,coherenceIndexMeaning:'QUALITATIVE_SOURCE_BOUND_ALIGNMENT_INDEX',scoreMeaning:'BOUNDED_ACTION_CLASSIFICATION_NOT_A_NUMERIC_EFFICACY_SCORE'}),
 geometryLaw:Object.freeze({vertexMutation:'FORBIDDEN',topologyMutation:'FORBIDDEN',componentRemodeling:'FORBIDDEN',awardsPresentation:'LIGHTWEIGHT_SOURCE_BOUND_SILHOUETTE'}),lifecycle:Object.freeze(['REAR_INERT','APPROACHING','FOREGROUND_REST','SIGNATURE_PLAY','FOREGROUND_IDLE','SELECT_RESPONSE','READER_OPEN','RETURN_RESTORING'])
});
const STYLE_ID='awards-coherence-brain-v2-style';
const STYLE=`
.awards-brain-object{position:relative;width:100%;height:100%;min-height:220px;overflow:hidden;isolation:isolate;pointer-events:none;display:grid;place-items:center;background:radial-gradient(circle at 50% 49%,rgba(197,128,143,.10),transparent 48%)}
.awards-brain-object .brain{position:relative;width:82%;height:72%;max-width:184px;max-height:158px;filter:drop-shadow(0 12px 18px rgba(0,0,0,.35));transition:transform .75s cubic-bezier(.2,.8,.2,1),filter .75s ease}
.awards-brain-object .hemisphere{position:absolute;top:8%;bottom:16%;width:51%;background:linear-gradient(145deg,#b76f7f,#7e4354 72%,#512b39);border:1px solid rgba(244,190,198,.28);box-shadow:inset 0 0 22px rgba(255,222,225,.08);overflow:hidden}
.awards-brain-object .left{left:2%;border-radius:62% 40% 42% 58%/48% 58% 45% 52%;transform:rotate(-3deg)}.awards-brain-object .right{right:2%;border-radius:40% 62% 58% 42%/58% 48% 52% 45%;transform:rotate(3deg)}
.awards-brain-object .hemisphere:before,.awards-brain-object .hemisphere:after{content:'';position:absolute;inset:10% 8%;border-radius:50%;background:repeating-radial-gradient(ellipse at 35% 40%,transparent 0 8px,rgba(54,22,35,.34) 9px 11px,transparent 12px 18px);opacity:.82;transition:filter .7s ease,opacity .7s ease}
.awards-brain-object .hemisphere:after{inset:18% 14%;background:repeating-radial-gradient(ellipse at 66% 56%,transparent 0 6px,rgba(255,199,207,.16) 7px 8px,transparent 9px 15px)}
.awards-brain-object .seam{position:absolute;left:50%;top:15%;bottom:22%;width:2px;transform:translateX(-50%);background:linear-gradient(transparent,rgba(246,203,209,.30),rgba(246,203,209,.42),transparent);box-shadow:0 0 5px rgba(246,203,209,.16);transition:box-shadow .7s ease,background .7s ease}
.awards-brain-object .stem{position:absolute;left:50%;bottom:2%;width:20%;height:28%;transform:translateX(-50%);border-radius:40% 40% 58% 58%;background:linear-gradient(180deg,#83495a,#4b2a36);border:1px solid rgba(236,178,190,.2);z-index:-1}
.awards-brain-object .signal{position:absolute;width:7px;height:7px;border-radius:50%;background:#d68da0;box-shadow:0 0 8px rgba(214,141,160,.28);opacity:.28;transition:opacity .55s ease,box-shadow .55s ease,transform .55s ease}
.awards-brain-object .s1{left:22%;top:31%}.awards-brain-object .s2{left:36%;top:55%}.awards-brain-object .s3{right:22%;top:35%}.awards-brain-object .s4{right:34%;top:59%}.awards-brain-object .s5{left:48%;top:41%}
.awards-brain-object[data-coh-phase='sync'] .brain{transform:scale(1.035);filter:drop-shadow(0 12px 18px rgba(0,0,0,.32)) drop-shadow(0 0 14px rgba(222,151,169,.18))}
.awards-brain-object[data-coh-phase='sync'] .hemisphere:before{filter:brightness(1.22);opacity:1}.awards-brain-object[data-coh-phase='sync'] .seam{background:linear-gradient(transparent,#f2c1cb,#fff0e8,#f2c1cb,transparent);box-shadow:0 0 13px rgba(244,188,201,.65)}
.awards-brain-object[data-coh-phase='sync'] .signal{opacity:1;background:#fff0da;box-shadow:0 0 7px #fff0da,0 0 18px rgba(147,197,253,.72);transform:scale(1.25)}
.awards-brain-object[data-coh-phase='equivalent'] .signal{opacity:.92;box-shadow:0 0 7px #fff0da,0 0 13px rgba(147,197,253,.55)}.awards-brain-object[data-coh-phase='equivalent'] .seam{box-shadow:0 0 10px rgba(244,188,201,.5)}
.awards-brain-object[data-coh-phase='selected'] .brain{transform:scale(.97)}.awards-brain-object[data-coh-phase='rear']{opacity:.3;filter:saturate(.62) blur(1px)}
@media(max-width:760px){.awards-brain-object .brain{width:86%;height:70%;max-width:170px}}
@media(prefers-reduced-motion:reduce){.awards-brain-object *{transition:none!important}}
`;
function ensureStyle(doc){let s=doc.getElementById(STYLE_ID);if(s)return;s=doc.createElement('style');s.id=STYLE_ID;s.textContent=STYLE;doc.head.append(s)}
function markup(){return `<div class="awards-brain-object" data-awards-lo="coherence" data-awards-lo-state="FOREGROUND_REST" data-coh-phase="rest" data-recognizable-object="BRAIN" aria-hidden="true"><div class="brain"><i class="hemisphere left"></i><i class="hemisphere right"></i><i class="stem"></i><i class="seam"></i><i class="signal s1"></i><i class="signal s2"></i><i class="signal s3"></i><i class="signal s4"></i><i class="signal s5"></i></div></div>`}
export function mountCoherenceLivingObject(root,options={}){
 if(!root||typeof root.replaceChildren!=='function')throw new TypeError('COHERENCE_ROOT_REQUIRED');ensureStyle(root.ownerDocument||document);const reduced=options.reducedMotion??globalThis.matchMedia?.('(prefers-reduced-motion: reduce)')?.matches??false;const wrap=(root.ownerDocument||document).createElement('div');wrap.innerHTML=markup();const node=wrap.firstElementChild;root.replaceChildren(node);let state='FOREGROUND_REST',classification='HOLD',token=0,timers=[];const clear=()=>{timers.forEach(clearTimeout);timers=[]};const phase=v=>node.dataset.cohPhase=v;const schedule=(fn,ms,t)=>timers.push(setTimeout(()=>{if(t===token)fn()},ms));
 function setClassification(next){if(!CONTRACT.semanticBinding.actionClasses.includes(next))throw new Error(`COHERENCE_INVALID_CLASSIFICATION:${next}`);classification=next;return classification}
 function setState(next){if(!CONTRACT.lifecycle.includes(next))throw new Error(`COHERENCE_INVALID_STATE:${next}`);state=next;node.dataset.awardsLoState=next;return state}
 function stable(){setState('FOREGROUND_IDLE');if(!reduced)phase('rest')}
 function playSignature(){token++;clear();const t=token;setState('SIGNATURE_PLAY');setClassification('HOLD');if(reduced){phase('equivalent');return stable()}phase('rest');schedule(()=>{phase('sync');setClassification('PROCEED')},420,t);schedule(()=>{phase('rest');setClassification('HOLD')},2700,t);schedule(()=>stable(),3350,t);return t}
 function selectResponse(){token++;clear();setState('SELECT_RESPONSE');setClassification('HOLD');phase(reduced?'equivalent':'selected')}
 function readerOpen(){setState('READER_OPEN')}
 function restore(){token++;clear();setClassification('HOLD');setState('RETURN_RESTORING');phase(reduced?'equivalent':'rest');const t=token;schedule(()=>setState('FOREGROUND_REST'),reduced?0:380,t)}
 function setLifecycle(next){token++;clear();setState(next);phase(next==='REAR_INERT'?'rear':reduced?'equivalent':'rest')}
 function inspect(){return Object.freeze({contract:CONTRACT.id,cycle:CONTRACT.cycle,state,phase:node.dataset.cohPhase,reducedMotion:!!reduced,webglContexts:0,recognizableObject:CONTRACT.recognizableObject,signatureEvent:CONTRACT.signatureEvent,eventCount:1,classification,numericScore:false,sourceBinding:CONTRACT.sourceBinding,semanticBinding:CONTRACT.semanticBinding,geometryLaw:CONTRACT.geometryLaw})}
 function destroy(){token++;clear();root.replaceChildren()}if(reduced)phase('equivalent');return Object.freeze({contract:CONTRACT,setState:setLifecycle,playSignature,selectResponse,readerOpen,restore,setClassification,inspect,destroy,element:node})
}
export {CONTRACT as AWARDS_COHERENCE_CYCLE_C_CONTRACT};
