const CONTRACT=Object.freeze({
 id:'AWARDS_TRUST_LIVING_OBJECT_CYCLE_D_V2_NINE_SUMMITS',cycle:'D_TRUST',claim:'Software should have to earn the right to say it worked.',recognizableObject:'NINE_SUMMITS',signatureEvent:'EARNED_ASCENT_REVEAL',eventCount:1,
 sourceBinding:Object.freeze({governingHead:'56c1630070b869f5e3a2d91e53a0812fd885a046',nineSummits:Object.freeze({path:'/nine-summits/index.html',blob:'99ae0cdafe5ad649d04d381ccbb2aa565aff86cd',coreMessage:'the-climb-becomes-a-world'}),literalMountainDonorGeometryPresent:false,boundedConstructionException:'ONE_LIGHTWEIGHT_NINE_SUMMIT_MASSIF_IN_AWARDS_MODULE_ONLY'}),
 semanticBinding:Object.freeze({authorityProgression:Object.freeze(['INTENT','EXECUTION','VERIFICATION','EVIDENCE','AUTHORIZED_CLAIM']),boundedDispositions:Object.freeze(['HOLD','DENY','FAIL_CLOSED','AUTHORIZED']),executionImpliesSuccess:false,executionImpliesClaimAuthority:false,authorizedClaimRequires:Object.freeze(['VERIFICATION','EVIDENCE']),rule:'NO_AUTHORIZED_CLAIM_WITHOUT_VERIFICATION_AND_EVIDENCE'}),
 lifecycle:Object.freeze(['REAR_INERT','APPROACHING','FOREGROUND_REST','SIGNATURE_PLAY','FOREGROUND_IDLE','SELECT_RESPONSE','READER_OPEN','RETURN_RESTORING'])
});
const STYLE_ID='awards-trust-nine-summits-v2-style';
const STYLE=`
.awards-summits-object{position:relative;width:100%;height:100%;min-height:220px;overflow:hidden;isolation:isolate;pointer-events:none;background:radial-gradient(circle at 52% 76%,rgba(212,175,55,.10),transparent 48%)}
.awards-summits-object .summit-sky{position:absolute;inset:8% 2% 10%;border-radius:46% 46% 15px 15px/18% 18% 15px 15px;background:linear-gradient(180deg,#102b40 0%,#35596a 50%,#b3a47f 100%);overflow:hidden;border:1px solid rgba(215,198,150,.14)}
.awards-summits-object .summit{position:absolute;bottom:8%;left:var(--x);width:var(--w);height:var(--h);transform:translateX(-50%) translateY(8%) scaleY(.92);transform-origin:50% 100%;clip-path:polygon(50% 0,100% 100%,0 100%);background:linear-gradient(145deg,#697164 0 34%,#34463e 35% 72%,#1b2d2a 73%);filter:brightness(var(--b));transition:transform .85s cubic-bezier(.2,.8,.2,1),filter .75s ease,opacity .75s ease;opacity:.86}
.awards-summits-object .summit:after{content:'';position:absolute;left:24%;right:30%;top:8%;height:18%;background:rgba(231,226,202,.75);clip-path:polygon(50% 0,100% 100%,58% 76%,32% 100%,0 82%);opacity:.42;transition:opacity .7s ease}
.awards-summits-object .summit:nth-child(2n):after{left:34%;right:20%}.awards-summits-object .ridge-base{position:absolute;left:-5%;right:-5%;bottom:-2%;height:29%;background:linear-gradient(180deg,#2c4037,#152723);clip-path:polygon(0 48%,11% 32%,21% 44%,33% 25%,47% 43%,59% 21%,73% 38%,85% 25%,100% 42%,100% 100%,0 100%)}
.awards-summits-object .ascent{position:absolute;left:12%;bottom:14%;width:8px;height:8px;border-radius:50%;background:#f5dc91;box-shadow:0 0 7px #f5dc91,0 0 16px rgba(245,220,145,.62);opacity:.2;transform:translate(0,0);transition:transform 1.8s cubic-bezier(.25,.75,.2,1),opacity .35s ease,box-shadow .5s ease}
.awards-summits-object[data-trust-phase='ascent'] .summit{transform:translateX(-50%) translateY(0) scaleY(1);filter:brightness(calc(var(--b) + .15));opacity:1}.awards-summits-object[data-trust-phase='ascent'] .summit:after{opacity:.82}
.awards-summits-object[data-trust-phase='ascent'] .ascent{opacity:1;transform:translate(94px,-92px);box-shadow:0 0 8px #fff1b8,0 0 22px rgba(245,220,145,.85)}
.awards-summits-object[data-trust-phase='equivalent'] .summit{transform:translateX(-50%) translateY(0) scaleY(1);opacity:1}.awards-summits-object[data-trust-phase='equivalent'] .summit:after{opacity:.7}.awards-summits-object[data-trust-phase='equivalent'] .ascent{opacity:.9;transform:translate(94px,-92px)}
.awards-summits-object[data-trust-phase='selected'] .summit-sky{box-shadow:inset 0 0 28px rgba(0,0,0,.2),0 0 20px rgba(234,211,154,.16)}.awards-summits-object[data-trust-phase='rear']{opacity:.3;filter:saturate(.62) blur(1px)}
@media(max-width:760px){.awards-summits-object .ascent{width:7px;height:7px}.awards-summits-object[data-trust-phase='ascent'] .ascent,.awards-summits-object[data-trust-phase='equivalent'] .ascent{transform:translate(82px,-84px)}}
@media(prefers-reduced-motion:reduce){.awards-summits-object *{transition:none!important}}
`;
const PEAKS=[{x:5,w:28,h:43,b:.72},{x:16,w:34,h:56,b:.78},{x:28,w:31,h:48,b:.74},{x:39,w:39,h:70,b:.86},{x:51,w:43,h:82,b:.94},{x:63,w:35,h:62,b:.82},{x:73,w:38,h:72,b:.88},{x:84,w:31,h:52,b:.76},{x:95,w:29,h:46,b:.7}];
function ensureStyle(doc){let s=doc.getElementById(STYLE_ID);if(s)return;s=doc.createElement('style');s.id=STYLE_ID;s.textContent=STYLE;doc.head.append(s)}
function markup(){const peaks=PEAKS.map((p,i)=>`<i class="summit" data-summit="${i+1}" style="--x:${p.x}%;--w:${p.w}%;--h:${p.h}%;--b:${p.b}"></i>`).join('');return `<div class="awards-summits-object" data-awards-lo="trust" data-awards-lo-state="FOREGROUND_REST" data-trust-phase="rest" data-trust-step="INTENT" data-trust-disposition="HOLD" data-recognizable-object="NINE_SUMMITS" aria-hidden="true"><div class="summit-sky">${peaks}<i class="ridge-base"></i><i class="ascent"></i></div></div>`}
export function mountTrustLivingObject(root,options={}){
 if(!root||typeof root.replaceChildren!=='function')throw new TypeError('TRUST_ROOT_REQUIRED');ensureStyle(root.ownerDocument||document);const reduced=options.reducedMotion??globalThis.matchMedia?.('(prefers-reduced-motion: reduce)')?.matches??false;const wrap=(root.ownerDocument||document).createElement('div');wrap.innerHTML=markup();const node=wrap.firstElementChild;root.replaceChildren(node);let state='FOREGROUND_REST',step='INTENT',disposition='HOLD',token=0,timers=[];const clear=()=>{timers.forEach(clearTimeout);timers=[]};const phase=v=>node.dataset.trustPhase=v;const schedule=(fn,ms,t)=>timers.push(setTimeout(()=>{if(t===token)fn()},ms));const paint=()=>{node.dataset.trustStep=step;node.dataset.trustDisposition=disposition};
 function setState(next){if(!CONTRACT.lifecycle.includes(next))throw new Error(`TRUST_INVALID_STATE:${next}`);state=next;node.dataset.awardsLoState=next;return state}
 function setStep(next){if(!CONTRACT.semanticBinding.authorityProgression.includes(next))throw new Error(`TRUST_INVALID_STEP:${next}`);step=next;paint();return step}
 function setDisposition(next){if(!CONTRACT.semanticBinding.boundedDispositions.includes(next))throw new Error(`TRUST_INVALID_DISPOSITION:${next}`);if(next==='AUTHORIZED'&&step!=='AUTHORIZED_CLAIM')throw new Error('TRUST_AUTHORITY_WITHOUT_EVIDENCE');disposition=next;paint();return disposition}
 function stable(){setState('FOREGROUND_IDLE');if(!reduced)phase('rest')}
 function playSignature(){token++;clear();const t=token;setState('SIGNATURE_PLAY');step='INTENT';disposition='HOLD';paint();if(reduced){step='AUTHORIZED_CLAIM';disposition='AUTHORIZED';paint();phase('equivalent');return stable()}phase('rest');schedule(()=>phase('ascent'),360,t);schedule(()=>{step='AUTHORIZED_CLAIM';disposition='AUTHORIZED';paint()},1600,t);schedule(()=>phase('rest'),2700,t);schedule(()=>stable(),3350,t);return t}
 function hold(){token++;clear();step='VERIFICATION';disposition='HOLD';paint();setState('SELECT_RESPONSE');phase(reduced?'equivalent':'selected')}
 function deny(){token++;clear();disposition='DENY';paint();setState('SELECT_RESPONSE');phase('selected')}
 function failClosed(){token++;clear();disposition='FAIL_CLOSED';paint();setState('SELECT_RESPONSE');phase('selected')}
 function selectResponse(){hold()}
 function readerOpen(){setState('READER_OPEN')}
 function restore(){token++;clear();step='INTENT';disposition='HOLD';paint();setState('RETURN_RESTORING');phase(reduced?'equivalent':'rest');const t=token;schedule(()=>setState('FOREGROUND_REST'),reduced?0:380,t)}
 function setLifecycle(next){token++;clear();setState(next);phase(next==='REAR_INERT'?'rear':reduced?'equivalent':'rest')}
 function inspect(){return Object.freeze({contract:CONTRACT.id,cycle:CONTRACT.cycle,state,step,disposition,reducedMotion:!!reduced,webglContexts:0,recognizableObject:CONTRACT.recognizableObject,summitCount:9,signatureEvent:CONTRACT.signatureEvent,eventCount:1,executionImpliesSuccess:false,executionImpliesClaimAuthority:false,sourceBinding:CONTRACT.sourceBinding,semanticBinding:CONTRACT.semanticBinding})}
 function destroy(){token++;clear();root.replaceChildren()}if(reduced)phase('equivalent');paint();return Object.freeze({contract:CONTRACT,setState:setLifecycle,playSignature,selectResponse,readerOpen,restore,hold,deny,failClosed,setDisposition,inspect,destroy,element:node})
}
export {CONTRACT as AWARDS_TRUST_CYCLE_D_CONTRACT};
