(()=>{
'use strict';
const SOURCE='https://ccf-ontology.hubmapconsortium.org/objects/v1.2/Allen_M_Brain.glb';
const EXPECTED={meshes:283,triangles:656268};
const canvas=document.getElementById('brain');
const status=document.getElementById('status');
const gl=canvas.getContext('webgl2',{alpha:false,antialias:false,powerPreference:'high-performance',preserveDrawingBuffer:true});
if(!gl){status.textContent='RENDER FAILED · WebGL2 unavailable';return}
let lost=false;
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();lost=true;status.textContent='RENDER FAILED · WebGL context lost'});
const I=()=>new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);
function mul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o}
function trs(n){if(n.matrix)return new Float32Array(n.matrix);const t=n.translation||[0,0,0],s=n.scale||[1,1,1],q=n.rotation||[0,0,0,1],x=q[0],y=q[1],z=q[2],w=q[3],x2=x+x,y2=y+y,z2=z+z,xx=x*x2,xy=x*y2,xz=x*z2,yy=y*y2,yz=y*z2,zz=z*z2,wx=w*x2,wy=w*y2,wz=w*z2;return new Float32Array([(1-(yy+zz))*s[0],(xy+wz)*s[0],(xz-wy)*s[0],0,(xy-wz)*s[1],(1-(xx+zz))*s[1],(yz+wx)*s[1],0,(xz+wy)*s[2],(yz-wx)*s[2],(1-(xx+yy))*s[2],0,t[0],t[1],t[2],1])}
function transformPoint(m,x,y,z){return[m[0]*x+m[4]*y+m[8]*z+m[12],m[1]*x+m[5]*y+m[9]*z+m[13],m[2]*x+m[6]*y+m[10]*z+m[14]]}
function transformNormal(m,x,y,z){let nx=m[0]*x+m[4]*y+m[8]*z,ny=m[1]*x+m[5]*y+m[9]*z,nz=m[2]*x+m[6]*y+m[10]*z;const q=Math.hypot(nx,ny,nz)||1;return[nx/q,ny/q,nz/q]}
function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s)||'shader compile failed');return s}
const vs=`#version 300 es\nin vec3 aP;in vec3 aN;uniform mat4 uR;uniform float uAspect;uniform float uZoom;out vec3 vN;out vec3 vP;void main(){vec4 p=uR*vec4(aP*uZoom,1.);vP=p.xyz;vN=normalize(mat3(uR)*aN);gl_Position=vec4(p.x/max(uAspect,1.),p.y,p.z*.48,1.);}`;
const fs=`#version 300 es\nprecision highp float;in vec3 vN;in vec3 vP;out vec4 outColor;void main(){vec3 n=normalize(vN);vec3 key=normalize(vec3(-.62,.72,.52));vec3 fill=normalize(vec3(.65,.10,.55));vec3 view=normalize(vec3(0.,.03,2.4)-vP);float kd=max(dot(n,key),0.);float fd=max(dot(n,fill),0.);float rim=pow(1.-max(dot(n,view),0.),2.0);float front=.78+.22*clamp(vP.z+.7,0.,1.4);vec3 base=vec3(.72,.70,.66)*(.25+.70*kd+.12*fd)*front;vec3 edge=vec3(.95,.96,.93)*rim*.20;outColor=vec4(base+edge,1.);}`;
const prog=gl.createProgram();gl.attachShader(prog,shader(gl.VERTEX_SHADER,vs));gl.attachShader(prog,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(prog);if(!gl.getProgramParameter(prog,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(prog)||'program link failed');
const loc={p:gl.getAttribLocation(prog,'aP'),n:gl.getAttribLocation(prog,'aN'),r:gl.getUniformLocation(prog,'uR'),aspect:gl.getUniformLocation(prog,'uAspect'),zoom:gl.getUniformLocation(prog,'uZoom')};
let vertexBuffer=null,vertexCount=0,yaw=.34,pitch=-.08,zoom=1,drag=false,lx=0,ly=0,lastDistance=0,raf=0,ready=false;
function parseGLB(buf){const dv=new DataView(buf);if(dv.getUint32(0,true)!==0x46546c67||dv.getUint32(4,true)!==2)throw Error('Invalid GLB');let off=12,json=null,bin=null;while(off<buf.byteLength){const n=dv.getUint32(off,true),t=dv.getUint32(off+4,true);off+=8;const chunk=buf.slice(off,off+n);off+=n;if(t===0x4e4f534a)json=JSON.parse(new TextDecoder().decode(chunk).replace(/\u0000+$/,''));else if(t===0x004e4942)bin=chunk}if(!json||!bin)throw Error('GLB JSON/BIN chunks missing');return{json,bin}}
const bytes={5120:1,5121:1,5122:2,5123:2,5125:4,5126:4};const comps={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT2:4,MAT3:9,MAT4:16};
function makeReader(model,bin){const dv=new DataView(bin);function readScalar(off,type){switch(type){case 5120:return dv.getInt8(off);case 5121:return dv.getUint8(off);case 5122:return dv.getInt16(off,true);case 5123:return dv.getUint16(off,true);case 5125:return dv.getUint32(off,true);case 5126:return dv.getFloat32(off,true);default:throw Error(`Unsupported componentType ${type}`)}}function value(accessorIndex,item,component=0){const a=model.accessors[accessorIndex],bv=model.bufferViews[a.bufferView],size=bytes[a.componentType],stride=bv.byteStride||size*comps[a.type],off=(bv.byteOffset||0)+(a.byteOffset||0)+item*stride+component*size;let v=readScalar(off,a.componentType);if(a.normalized&&a.componentType!==5126){if(a.componentType===5120)v=Math.max(v/127,-1);else if(a.componentType===5121)v/=255;else if(a.componentType===5122)v=Math.max(v/32767,-1);else if(a.componentType===5123)v/=65535;else if(a.componentType===5125)v/=4294967295}return v}return{value}}
function flatten(model,bin){const R=makeReader(model,bin),parts=[],lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];const roots=(model.scenes?.[model.scene||0]?.nodes)||model.nodes.map((_,i)=>i);let triangles=0;function visit(index,parent){const node=model.nodes[index],world=mul(parent,trs(node));if(node.mesh!==undefined){const mesh=model.meshes[node.mesh];for(const pr of mesh.primitives||[]){if(pr.mode!==undefined&&pr.mode!==4)continue;if(pr.attributes?.POSITION===undefined||pr.attributes?.NORMAL===undefined||pr.indices===undefined)continue;const pa=model.accessors[pr.attributes.POSITION];if(pa.min&&pa.max){for(const x of [pa.min[0],pa.max[0]])for(const y of [pa.min[1],pa.max[1]])for(const z of [pa.min[2],pa.max[2]]){const p=transformPoint(world,x,y,z);for(let d=0;d<3;d++){lo[d]=Math.min(lo[d],p[d]);hi[d]=Math.max(hi[d],p[d])}}}const ia=model.accessors[pr.indices];const tri=Math.floor(ia.count/3);triangles+=tri;parts.push({world,pos:pr.attributes.POSITION,norm:pr.attributes.NORMAL,idx:pr.indices,count:tri*3})}}for(const child of node.children||[])visit(child,world)}for(const r of roots)visit(r,I());if(!parts.length)throw Error('No renderable triangle primitives');const center=lo.map((v,i)=>(v+hi[i])/2),extent=Math.max(...hi.map((v,i)=>v-lo[i]));if(!Number.isFinite(extent)||extent<=0)throw Error('Invalid atlas bounds');const scale=1.58/extent,total=parts.reduce((n,p)=>n+p.count,0),data=new Float32Array(total*6);let w=0;for(const part of parts){for(let i=0;i<part.count;i++){const vi=R.value(part.idx,i,0);const px=R.value(part.pos,vi,0),py=R.value(part.pos,vi,1),pz=R.value(part.pos,vi,2);const nx=R.value(part.norm,vi,0),ny=R.value(part.norm,vi,1),nz=R.value(part.norm,vi,2);const p=transformPoint(part.world,px,py,pz),n=transformNormal(part.world,nx,ny,nz);data[w++]=(p[0]-center[0])*scale;data[w++]=(p[1]-center[1])*scale;data[w++]=(p[2]-center[2])*scale;data[w++]=n[0];data[w++]=n[1];data[w++]=n[2]}}return{data,triangles,parts:parts.length}}
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,innerWidth<700?1.15:1.45),w=Math.max(2,Math.round(r.width*d)),h=Math.max(2,Math.round(r.height*d));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h)}}
function rotation(y,p){const cy=Math.cos(y),sy=Math.sin(y),cx=Math.cos(p),sx=Math.sin(p);return new Float32Array([cy,sy*sx,sy*cx,0,0,cx,-sx,0,-sy,cy*sx,cy*cx,0,0,0,0,1])}
function draw(){if(!vertexBuffer||lost)return;resize();gl.clearColor(.018,.028,.038,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.useProgram(prog);gl.bindBuffer(gl.ARRAY_BUFFER,vertexBuffer);gl.enableVertexAttribArray(loc.p);gl.vertexAttribPointer(loc.p,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(loc.n);gl.vertexAttribPointer(loc.n,3,gl.FLOAT,false,24,12);gl.uniformMatrix4fv(loc.r,false,rotation(yaw,pitch));gl.uniform1f(loc.aspect,canvas.width/Math.max(1,canvas.height));gl.uniform1f(loc.zoom,zoom);gl.drawArrays(gl.TRIANGLES,0,vertexCount)}
function verifyPixels(){if(lost)return false;draw();gl.finish();const w=Math.min(96,canvas.width),h=Math.min(96,canvas.height),x=Math.max(0,Math.floor((canvas.width-w)/2)),y=Math.max(0,Math.floor((canvas.height-h)/2)),pix=new Uint8Array(w*h*4);gl.readPixels(x,y,w,h,gl.RGBA,gl.UNSIGNED_BYTE,pix);let changed=0;for(let i=0;i<pix.length;i+=4){if(pix[i]>10||pix[i+1]>12||pix[i+2]>14){changed++;if(changed>20)return true}}return false}
function schedule(){if(!raf)raf=requestAnimationFrame(()=>{raf=0;draw()})}
canvas.addEventListener('pointerdown',e=>{drag=true;lx=e.clientX;ly=e.clientY;canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;yaw+=(e.clientX-lx)*.008;pitch=Math.max(-1.32,Math.min(1.18,pitch+(e.clientY-ly)*.006));lx=e.clientX;ly=e.clientY;schedule()});for(const ev of ['pointerup','pointercancel'])canvas.addEventListener(ev,e=>{drag=false;canvas.releasePointerCapture?.(e.pointerId);schedule()});canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.58,Math.min(2.1,zoom*Math.exp(-e.deltaY*.001)));schedule()},{passive:false});canvas.addEventListener('touchstart',e=>{if(e.touches.length===2)lastDistance=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY)},{passive:true});canvas.addEventListener('touchmove',e=>{if(e.touches.length!==2||!lastDistance)return;const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);zoom=Math.max(.58,Math.min(2.1,zoom*d/lastDistance));lastDistance=d;schedule()},{passive:true});canvas.addEventListener('touchend',()=>{lastDistance=0},{passive:true});new ResizeObserver(schedule).observe(canvas);
(async()=>{try{status.textContent='FETCHING QUALIFIED NIH/HRA BRAIN…';const r=await fetch(SOURCE,{mode:'cors',cache:'force-cache'});if(!r.ok)throw Error(`HTTP ${r.status}`);const buf=await r.arrayBuffer();status.textContent=`BUILDING SINGLE OBJECT · ${(buf.byteLength/1048576).toFixed(1)} MB SOURCE…`;const p=parseGLB(buf),flat=flatten(p.json,p.bin);vertexBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,vertexBuffer);gl.bufferData(gl.ARRAY_BUFFER,flat.data,gl.STATIC_DRAW);vertexCount=flat.data.length/6;canvas.dataset.meshes=String(p.json.meshes?.length||0);canvas.dataset.triangles=String(flat.triangles);canvas.dataset.singleObject='true';canvas.dataset.drawCalls='1';draw();await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));ready=verifyPixels();if(!ready)throw Error('single-object draw produced no visible center pixels');status.textContent=`VISIBLE · single brain object · ${flat.triangles.toLocaleString()} triangles · 1 draw call`;canvas.dataset.ready='true';if((p.json.meshes?.length||0)!==EXPECTED.meshes||flat.triangles!==EXPECTED.triangles)status.textContent+=' · source identity changed'}catch(e){console.error(e);status.textContent=`RENDER FAILED · ${e.message}`;canvas.dataset.ready='false';canvas.dataset.failure=e.message}})();
})();
