(()=>{
'use strict';
const SOURCE='https://ccf-ontology.hubmapconsortium.org/objects/v1.2/Allen_M_Brain.glb';
const EXPECTED={meshes:283,triangles:656268};
const rules={
 brainstem:/pons|pontine|varolii|medulla|oblongata|myelencephalon|pyramid|midbrain|mesencephalon|tectum|tegmentum|cerebral[ _-]*pedunc|superior[ _-]*collic|inferior[ _-]*collic|spinal[ _-]*cord|cervical[ _-]*cord/i,
 cerebellum:/cerebell|folia/i,
 cerebrum:/cerebr|cortex|cortical|frontal|parietal|occipital|temporal|hemisphere|gyrus|sulcus/i
};
const canvas=document.getElementById('brain'),status=document.getElementById('status');
const visible={cerebrum:true,cerebellum:true,brainstem:true,other:true};
for(const k of Object.keys(visible))document.getElementById(k).addEventListener('change',e=>{visible[k]=e.target.checked;draw();});
const gl=canvas.getContext('webgl2',{alpha:true,antialias:true,powerPreference:'high-performance',preserveDrawingBuffer:true});
if(!gl){status.textContent='WebGL2 is required for this high-resolution source.';return}
const I=()=>new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);
function mul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o}
function trs(n){if(n.matrix)return new Float32Array(n.matrix);const t=n.translation||[0,0,0],s=n.scale||[1,1,1],q=n.rotation||[0,0,0,1],x=q[0],y=q[1],z=q[2],w=q[3],x2=x+x,y2=y+y,z2=z+z,xx=x*x2,xy=x*y2,xz=x*z2,yy=y*y2,yz=y*z2,zz=z*z2,wx=w*x2,wy=w*y2,wz=w*z2;return new Float32Array([(1-(yy+zz))*s[0],(xy+wz)*s[0],(xz-wy)*s[0],0,(xy-wz)*s[1],(1-(xx+zz))*s[1],(yz+wx)*s[1],0,(xz+wy)*s[2],(yz-wx)*s[2],(1-(xx+yy))*s[2],0,t[0],t[1],t[2],1])}
function transform(m,p){return[m[0]*p[0]+m[4]*p[1]+m[8]*p[2]+m[12],m[1]*p[0]+m[5]*p[1]+m[9]*p[2]+m[13],m[2]*p[0]+m[6]*p[1]+m[10]*p[2]+m[14]]}
function scaleMat(s){const m=I();m[0]=m[5]=m[10]=s;return m}function translate(x,y,z){const m=I();m[12]=x;m[13]=y;m[14]=z;return m}
function rotate(yaw,pitch){const cy=Math.cos(yaw),sy=Math.sin(yaw),cx=Math.cos(pitch),sx=Math.sin(pitch);return new Float32Array([cy,sy*sx,sy*cx,0,0,cx,-sx,0,-sy,cy*sx,cy*cx,0,0,0,0,1])}
function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
const vs=`#version 300 es\nin vec3 aP;in vec3 aN;uniform mat4 uM;uniform float uAspect;out vec3 vN;out vec3 vP;void main(){vec4 p=uM*vec4(aP,1.);vP=p.xyz;vN=normalize(mat3(uM)*aN);gl_Position=vec4(p.x/max(uAspect,1.),p.y,p.z*.24,1.);}`;
const fs=`#version 300 es\nprecision highp float;in vec3 vN;in vec3 vP;out vec4 outColor;void main(){vec3 n=normalize(vN);vec3 view=normalize(vec3(0.,.04,2.4)-vP);vec3 key=normalize(vec3(-.62,.72,.44));vec3 fill=normalize(vec3(.58,.10,.68));vec3 low=normalize(vec3(-.15,-.65,.36));float kd=max(dot(n,key),0.);float fd=max(dot(n,fill),0.);float ld=max(dot(n,low),0.);float rim=pow(1.-max(dot(n,view),0.),2.1);float depth=.54+.20*clamp(vP.z+.8,0.,1.5);vec3 neutral=vec3(.68,.67,.64)*(.28+.65*kd+.10*fd+.05*ld)*depth;vec3 edge=vec3(.94,.95,.93)*rim*.16;outColor=vec4(neutral+edge,1.);}`;
const prog=gl.createProgram();gl.attachShader(prog,shader(gl.VERTEX_SHADER,vs));gl.attachShader(prog,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(prog);if(!gl.getProgramParameter(prog,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(prog));
const loc={p:gl.getAttribLocation(prog,'aP'),n:gl.getAttribLocation(prog,'aN'),m:gl.getUniformLocation(prog,'uM'),aspect:gl.getUniformLocation(prog,'uAspect')};
let model=null,binBuffer=null,draws=[],fit=I(),yaw=.34,pitch=-.08,zoom=1,drag=false,lx=0,ly=0,raf=0;
const componentBytes={5120:1,5121:1,5122:2,5123:2,5125:4,5126:4};const components={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT2:4,MAT3:9,MAT4:16};
function accessorInfo(i){const a=model.accessors[i],bv=model.bufferViews[a.bufferView],offset=(bv.byteOffset||0)+(a.byteOffset||0),stride=bv.byteStride||componentBytes[a.componentType]*components[a.type];return{a,bv,offset,stride}}
function bindAccessor(i,attribute){const q=accessorInfo(i);gl.bindBuffer(gl.ARRAY_BUFFER,binBuffer);gl.enableVertexAttribArray(attribute);gl.vertexAttribPointer(attribute,components[q.a.type],q.a.componentType,!!q.a.normalized,q.stride,q.offset)}
function classify(name){if(rules.brainstem.test(name))return'brainstem';if(rules.cerebellum.test(name))return'cerebellum';if(rules.cerebrum.test(name))return'cerebrum';return'other'}
function parseGLB(buf){const dv=new DataView(buf);if(dv.getUint32(0,true)!==0x46546c67||dv.getUint32(4,true)!==2)throw Error('Invalid GLB');let off=12,json=null,bin=null;while(off<buf.byteLength){const n=dv.getUint32(off,true),t=dv.getUint32(off+4,true);off+=8;const chunk=buf.slice(off,off+n);off+=n;if(t===0x4e4f534a)json=JSON.parse(new TextDecoder().decode(chunk).replace(/\u0000+$/,''));else if(t===0x004e4942)bin=chunk}if(!json||!bin)throw Error('GLB JSON/BIN chunks missing');return{json,bin}}
function buildScene(bin){binBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,binBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Uint8Array(bin),gl.STATIC_DRAW);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,binBuffer);const roots=(model.scenes?.[model.scene||0]?.nodes)||model.nodes.map((_,i)=>i);const lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];let triangles=0;function visit(index,parent){const node=model.nodes[index],world=mul(parent,trs(node));if(node.mesh!==undefined){const mesh=model.meshes[node.mesh],name=`${node.name||''} ${mesh.name||''}`.trim();for(const pr of mesh.primitives||[]){if(pr.mode!==undefined&&pr.mode!==4)continue;if(pr.attributes?.POSITION===undefined||pr.attributes?.NORMAL===undefined||pr.indices===undefined)continue;const pos=model.accessors[pr.attributes.POSITION];if(pos.min&&pos.max){for(const x of [pos.min[0],pos.max[0]])for(const y of [pos.min[1],pos.max[1]])for(const z of [pos.min[2],pos.max[2]]){const p=transform(world,[x,y,z]);for(let d=0;d<3;d++){lo[d]=Math.min(lo[d],p[d]);hi[d]=Math.max(hi[d],p[d])}}}const ia=model.accessors[pr.indices];triangles+=Math.floor(ia.count/3);draws.push({world,group:classify(name),name,pos:pr.attributes.POSITION,norm:pr.attributes.NORMAL,idx:pr.indices,count:ia.count,type:ia.componentType})}}for(const child of node.children||[])visit(child,world)}for(const r of roots)visit(r,I());const center=lo.map((v,i)=>(v+hi[i])/2),extent=Math.max(...hi.map((v,i)=>v-lo[i]));fit=mul(scaleMat(1.72/Math.max(extent,1e-9)),translate(-center[0],-center[1],-center[2]));const counts=draws.reduce((a,d)=>(a[d.group]++,a),{cerebrum:0,cerebellum:0,brainstem:0,other:0});canvas.dataset.meshes=String(model.meshes.length);canvas.dataset.triangles=String(triangles);canvas.dataset.brainstem=String(counts.brainstem);status.textContent=`READY · ${model.meshes.length} meshes · ${triangles.toLocaleString()} triangles · brainstem ${counts.brainstem} draws`;if(model.meshes.length!==EXPECTED.meshes)status.textContent+=` · source mesh count changed from ${EXPECTED.meshes}`;draw()}
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,innerWidth<640?1.25:1.7),w=Math.max(2,Math.round(r.width*d)),h=Math.max(2,Math.round(r.height*d));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h)}}
function draw(){if(!model)return;resize();gl.clearColor(.018,.028,.038,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.useProgram(prog);gl.uniform1f(loc.aspect,canvas.width/Math.max(1,canvas.height));const R=rotate(yaw,pitch),F=mul(scaleMat(zoom),fit);for(const d of draws){if(!visible[d.group])continue;gl.uniformMatrix4fv(loc.m,false,mul(R,mul(F,d.world)));bindAccessor(d.pos,loc.p);bindAccessor(d.norm,loc.n);const q=accessorInfo(d.idx);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,binBuffer);gl.drawElements(gl.TRIANGLES,d.count,d.type,q.offset)}}
function schedule(){if(!raf)raf=requestAnimationFrame(()=>{raf=0;draw()})}canvas.addEventListener('pointerdown',e=>{drag=true;lx=e.clientX;ly=e.clientY;canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;yaw+=(e.clientX-lx)*.008;pitch=Math.max(-1.35,Math.min(1.2,pitch+(e.clientY-ly)*.006));lx=e.clientX;ly=e.clientY;schedule()});for(const ev of ['pointerup','pointercancel'])canvas.addEventListener(ev,e=>{drag=false;canvas.releasePointerCapture?.(e.pointerId);schedule()});canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.58,Math.min(2.2,zoom*Math.exp(-e.deltaY*.001)));schedule()},{passive:false});new ResizeObserver(schedule).observe(canvas);
(async()=>{try{status.textContent='FETCHING QUALIFIED NIH/HRA GLB…';const r=await fetch(SOURCE,{mode:'cors'});if(!r.ok)throw Error(`HTTP ${r.status}`);const buf=await r.arrayBuffer();status.textContent=`PARSING ${(buf.byteLength/1048576).toFixed(1)} MB GLB…`;const p=parseGLB(buf);model=p.json;buildScene(p.bin)}catch(e){console.error(e);status.textContent=`LOAD FAILED · ${e.message}`;canvas.dataset.failure=e.message}})();
})();
