#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');const REPO="smansfield635-create/smansfield635-create.github.io",LOCK_REF="refs/heads/operation-locks/repository-operation-intake-v1";
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v;const clone=v=>JSON.parse(JSON.stringify(v));const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));const write=(p,v)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(stable(v),null,2)+'\n')};const sha=v=>crypto.createHash('sha256').update(v).digest('hex');
const args=Object.fromEntries(process.argv.slice(2).reduce((a,v,i,x)=>i%2===0?[...a,[v.slice(2),x[i+1]]]:a,[]));const token=process.env.GITHUB_TOKEN;if(!token)throw Error('GITHUB_TOKEN_MISSING');const tmp=process.env.RUNNER_TEMP||'/tmp';
async function api(url,t=token){let r=await fetch(url,{headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${t}`,'X-GitHub-Api-Version':'2022-11-28'}});let s=await r.text(),b;try{b=s?JSON.parse(s):null}catch{b={raw:s}}if(!r.ok)throw Object.assign(Error('API_'+r.status),{body:b});return b}async function mainHead(){return(await api(`https://api.github.com/repos/${REPO}/branches/main`)).commit.sha}async function lockHead(){return(await api(`https://api.github.com/repos/${REPO}/git/ref/heads/operation-locks/repository-operation-intake-v1`)).object.sha}
function materialize(template,head,id,scope){let v=clone(template);v.requestId=id;v.executionHolder=id;v.requestNonce=sha(id+scope+head);v.exactGoverningHead=head;v.operationRequest.operationId=id;v.operationRequest.lockScope=scope;v.operationRequest.exactGoverningHead=head;v.constructionProcedure.procedureId=id+'_PROCEDURE';v.constructionProcedure.exactGoverningHead=head;return v}
function runBridge(input,label,env={}){let i=path.join(tmp,label+'.input.json'),o=path.join(tmp,label+'.output.json');write(i,input);let p=spawnSync(process.execPath,[path.join(root,'tools/pre-registration-intake-bridge/canonical-intake-execution-bridge.v1.mjs'),'--input',i,'--output',o],{cwd:root,env:{...process.env,...env,RUNNER_TEMP:tmp},shell:false,encoding:'utf8',timeout:180000});let r=fs.existsSync(o)?JSON.parse(fs.readFileSync(o,'utf8')):null;return{process:p,receipt:r,inputPath:i,outputPath:o}}
function closeLock(receipt,disposition='PASS_CLOSED'){let c=receipt.canonicalReceiptJson.lock,o=path.join(tmp,'close-'+c.lockGeneration+'.json');let p=spawnSync(process.execPath,[path.join(root,'tools/operation-intake/repository-operation-lock-manager.v1.mjs'),'--action','close','--repository',REPO,'--lock-ref',LOCK_REF,'--operation-id',c.operationId,'--lock-scope',c.lockScope,'--lock-generation',String(c.lockGeneration),'--terminal-disposition',disposition,'--output',o],{cwd:root,env:process.env,shell:false,encoding:'utf8',timeout:180000});let r=JSON.parse(fs.readFileSync(o,'utf8'));if(p.status!==0||r.result!=='TERMINAL_CLOSURE_COMMITTED')throw Error('LOCK_CLOSE_FAILED:'+JSON.stringify(r));return r}
async function run(){let head=await mainHead(),pre=await lockHead(),f=read('.github/pre-registration-intake-bridge/fixtures.v1.json'),run=process.env.GITHUB_RUN_ID||Date.now().toString(),attempt=process.env.GITHUB_RUN_ATTEMPT||'1',base='PRE_REGISTRATION_BRIDGE_REMOTE_'+run+'_'+attempt,scope=base+'_SCOPE';let tests={};
 let valid=runBridge(materialize(f.bridgeInputTemplate,head,base+'_VALID',scope),'bridge-valid');tests.VALID_REQUEST=valid.receipt?.canonicalReceiptJson?.result==='ADMITTED_AND_LOCKED';if(!tests.VALID_REQUEST)throw Error('VALID_NOT_ADMITTED:'+JSON.stringify(valid.receipt));
 let replayActive=runBridge(materialize(f.bridgeInputTemplate,head,base+'_VALID',scope),'bridge-replay-active');tests.REPLAY_ACTIVE=replayActive.receipt?.errorCode==='REPLAY_DETECTED_NO_EXECUTION';
 let conflict=runBridge(materialize(f.bridgeInputTemplate,head,base+'_CONFLICT',scope),'bridge-conflict');tests.LOCK_CONFLICT=conflict.receipt?.canonicalReceiptJson?.result==='ACTIVE_SCOPE_ALREADY_LOCKED';
 let beforeInvalid=await lockHead(),invalidInput=materialize(f.bridgeInputTemplate,head,base+'_INVALID',base+'_INVALID_SCOPE');delete invalidInput.operationRequest.requiredOutputs;let invalid=runBridge(invalidInput,'bridge-invalid'),afterInvalid=await lockHead();tests.INVALID_REQUEST=invalid.receipt?.canonicalReceiptJson?.result==='INPUT_INCOMPLETE_NOT_STARTED'&&beforeInvalid===afterInvalid;
 let stale=materialize(f.bridgeInputTemplate,'0'.repeat(40),base+'_STALE',base+'_STALE_SCOPE'),staleRun=runBridge(stale,'bridge-stale');tests.STALE_HEAD_REQUEST=staleRun.receipt?.errorCode==='GOVERNING_HEAD_MISMATCH';
 let tokenInput=materialize(f.bridgeInputTemplate,head,base+'_TOKEN',base+'_TOKEN_SCOPE'),tokenRun=runBridge(tokenInput,'bridge-token',{GITHUB_TOKEN:'insufficient'});tests.TOKEN_WITH_INSUFFICIENT_SCOPE=tokenRun.receipt?.result==='FAIL_CLOSED_NON_ADMISSION'&&tokenRun.receipt?.canonicalGateExecuted===false;
 let closure=closeLock(valid.receipt);let replayTerminal=runBridge(materialize(f.bridgeInputTemplate,head,base+'_VALID',scope),'bridge-replay-terminal');tests.REPLAY_TERMINAL=replayTerminal.receipt?.errorCode==='REPLAY_DETECTED_NO_EXECUTION';
 let post=await lockHead();let all=Object.values(tests).every(Boolean);let receipt={schema:'PRE_REGISTRATION_INTAKE_BRIDGE_REMOTE_PROOF_RECEIPT_v1',checkpointId:'CP6_REMOTE_END_TO_END_PROOF',result:all?'REMOTE_BEHAVIOR_MATCHES_FROZEN_CONTRACT':'REMOTE_PROOF_FAILED',authenticatedExecutionIdentity:{workflowRun:run,workflowAttempt:attempt,actor:process.env.GITHUB_ACTOR||null},canonicalGate:{path:"tools/operation-intake/repository-operation-intake-gate.v1.mjs",blob:"f0b22e6b9574507632f1ad07647710971a4d63de"},exactRequestDigest:valid.receipt.requestDigest,exactProcedureDigest:valid.receipt.procedureDigest,preExecutionLockHead:pre,postExecutionLockHead:post,validLockIdentity:valid.receipt.lockIdentity,closure,tests,proofOfNoUnrelatedRepositoryMutation:{mainHeadUnchanged:(await mainHead())===head,bridgeOrdinaryPathMutation:false,lockBranchOnlyCanonicalManager:true},auditTrail:valid.receipt.auditEvents};write(args.output,receipt);if(!all)process.exitCode=1;}
run().catch(e=>{write(args.output,{schema:'PRE_REGISTRATION_INTAKE_BRIDGE_REMOTE_PROOF_RECEIPT_v1',checkpointId:'CP6_REMOTE_END_TO_END_PROOF',result:'REMOTE_PROOF_FAILED',error:e.message});process.exitCode=1});
