/* TARGET FILE: /products/auren/auren.chamber.js
   AUREN_C2_TIMED_CONVERSATION_RUNTIME_V1 */
(()=>{"use strict";
const CONTRACT="AUREN_C2_TIMED_CONVERSATION_RUNTIME_V1";
const q=(s,r=document)=>r.querySelector(s),empty=n=>{while(n&&n.firstChild)n.removeChild(n.firstChild);};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const reduced=()=>typeof matchMedia==="function"&&matchMedia("(prefers-reduced-motion: reduce)").matches;
function bubble(text,kind="auren"){const n=document.createElement("div");n.className="auren-bubble auren-bubble-"+kind;const b=document.createElement("div");b.className="auren-bubble-body";b.textContent=text;n.appendChild(b);return n;}
function typing(){const n=document.createElement("div");n.className="auren-bubble auren-bubble-auren auren-typing";n.setAttribute("aria-label","Auren is typing");const b=document.createElement("div");b.className="auren-typing-dots";b.innerHTML="<i></i><i></i><i></i>";n.appendChild(b);return n;}
async function boot(){
 const root=q("[data-auren-chamber]"),thread=q("[data-auren-thread]"),options=q("[data-auren-options]");const sessionContext=globalThis.AUREN_SESSION_CONTEXT,voice=globalThis.AUREN_CHAMBER_VOICE,relationship=globalThis.AUREN_RELATIONSHIP,archetype=globalThis.AUREN_ARCHETYPE_EVIDENCE,stateDependent=globalThis.AUREN_STATE_DEPENDENT,sceneOffer=globalThis.AUREN_SCENE_OFFER,returnContext=globalThis.AUREN_RETURN_CONTEXT,custody=globalThis.AUREN_MANOR_CUSTODY,privacy=globalThis.AUREN_MANOR_PRIVACY,privacyRelationship=globalThis.AUREN_PRIVACY_RELATIONSHIP_MAPPING,env=globalThis.AUREN_ROOM_ENVIRONMENT,pres=globalThis.AUREN_ROOM_PRESENTATION;if(!root||!thread||!options||!sessionContext||!voice||!relationship||!archetype||!stateDependent||!sceneOffer||!returnContext||!custody||!privacy||!privacyRelationship||!env||!pres)return;
 env.mount(root);pres.mount(q("[data-auren-room]"));const relationshipView=q("[data-auren-relationship]");const relationshipLabel=q("[data-auren-relationship-label]");function syncRelationship(){const phase=relationship.getState().phase;root.setAttribute("data-auren-relationship-phase",phase);if(relationshipView){relationshipView.setAttribute("data-phase",phase);relationshipView.setAttribute("aria-label","Relationship with Auren: "+phase.toLowerCase());}if(relationshipLabel)relationshipLabel.textContent=phase.charAt(0)+phase.slice(1).toLowerCase();return phase;}syncRelationship();empty(thread);empty(options);let busy=true,sequence=0,current="root";const history=[];
 const wait=ms=>sleep(reduced()?Math.min(120,ms):ms);
 const reading=text=>Math.min(1200,650+Math.max(0,String(text).length-45)*5);
 function stage(visitor){empty(thread);if(visitor)thread.appendChild(bubble(visitor,"visitor"));root.setAttribute("data-auren-active-turn",String(history.length));}
 async function perform(visitor,messages,token){
  stage(visitor);root.setAttribute("data-auren-performance","LISTENING");await wait(450);if(token!==sequence)return false;
  for(let i=0;i<messages.length;i++){
   root.setAttribute("data-auren-performance","TYPING");const t=typing();thread.appendChild(t);await wait(i?600:760);if(token!==sequence)return false;t.remove();
   root.setAttribute("data-auren-performance","SPEAKING");thread.appendChild(bubble(messages[i]));if(i<messages.length-1){await wait(reading(messages[i]));if(token!==sequence)return false;}
  }
  root.setAttribute("data-auren-performance","READING_PAUSE");await wait(480);return token===sequence;
 }
 function renderOptions(nodeId){current=nodeId;empty(options);let list=voice.getOptions(nodeId);const offer=sceneOffer.evaluate({sourceNode:nodeId,relationship:relationship.getState(),destinationId:"manor",inLearnPath:["about","who","work","mirrorland","people","room"].includes(nodeId)});globalThis.AUREN_SCENE_OFFER_LAST_RECEIPT=offer;if(offer.offered&&list.length<3&&!list.some(x=>x.id==="manorOffer"))list=[...list,Object.freeze({id:"manorOffer",label:"Show me the Manor",relationshipAction:null,archetypeEvidence:null})];for(const p of list.slice(0,3)){const b=document.createElement("button");b.type="button";b.className="auren-option";b.textContent=p.label;b.addEventListener("click",()=>choose(p.id,p.relationshipAction,p.archetypeEvidence));options.appendChild(b);}root.setAttribute("data-auren-node",nodeId);root.setAttribute("data-auren-options-ready",options.childElementCount?"true":"false");root.setAttribute("data-auren-performance","CHOICES");busy=false;}
 function semanticSubject(id){if(["about","who","work"].includes(id))return"auren:self";if(["mirrorland","room"].includes(id))return"mirrorland:auren-domain";if(["people","privacyBoundary","privacyRespect","privacyLimited","privacyPress"].includes(id))return"manor:people";if(["products","archcoin","archcoinWhat","archcoinLive","archcoinFour","archcoinCapabilities","archcoinGo","fiveFlags","fiveFlagsHow","fiveFlagsWhy","fiveFlagsGo","moreProducts","education","educationHow","educationLimits","educationGo","nutrition","nutritionPrototype","nutritionOpen","nutritionGo","book","bookWhy","bookElara"].includes(id))return"auren:products";if(["manorOffer","manorReturnAck","admissionPressure","admissionAdmit","admissionDelay","admissionRefuse"].includes(id))return"manor:handoff";return null;}
 function recordSemanticChoice(from,id,node){const subjectId=semanticSubject(id),prior=semanticSubject(from);if(subjectId){const seen=sessionContext.getState().topics.some(x=>x.subjectId===subjectId);sessionContext.apply({eventType:seen?"TOPIC_REVISITED":"TOPIC_OPENED",subjectId,sourceBeat:id});sessionContext.apply({eventType:"TOPIC_MEANINGFULLY_PURSUED",subjectId,sourceBeat:id});if(prior&&prior!==subjectId)sessionContext.apply({eventType:"TOPIC_REDIRECTED",subjectId,sourceBeat:id});}
  if(id==="privacyBoundary"){const b=sessionContext.getBoundary("manor:people","protected-resident-identities");if(!b.known)sessionContext.apply({eventType:"BOUNDARY_ESTABLISHED",subjectId:"manor:people",boundaryId:"protected-resident-identities",sourceBeat:id,metadata:{authoritySensitive:true}});}
  if(id==="privacyRespect")sessionContext.apply({eventType:"BOUNDARY_ACKNOWLEDGED",subjectId:"manor:people",boundaryId:"protected-resident-identities",sourceBeat:id});
  if(id==="privacyLimited")sessionContext.apply({eventType:"BOUNDED_CONTEXT_REQUESTED",subjectId:"manor:people",boundaryId:"protected-resident-identities",sourceBeat:id});
  if(id==="privacyPress"){const b=sessionContext.getBoundary("manor:people","protected-resident-identities");if(!b.known)sessionContext.apply({eventType:"BOUNDARY_ESTABLISHED",subjectId:"manor:people",boundaryId:"protected-resident-identities",sourceBeat:id,metadata:{authoritySensitive:true}});sessionContext.apply({eventType:"BOUNDARY_PRESSURED",subjectId:"manor:people",boundaryId:"protected-resident-identities",sourceBeat:id});sessionContext.apply({eventType:"BOUNDARY_REASSERTED",subjectId:"manor:people",boundaryId:"protected-resident-identities",sourceBeat:id});}
  if(node?.route){sessionContext.apply({eventType:"HANDOFF_OFFERED",subjectId:subjectId||prior,threadId:null,destinationId:id==="bookElara"?"elara":id==="manorOffer"?"manor":"product",sourceBeat:id});}
 }
 async function choose(id,relationshipAction=null,archetypeEvidence=null){if(busy)return;const node=voice.getNode(id);if(!node)return;recordSemanticChoice(current,id,node);if(node.custodyChoiceId){globalThis.AUREN_CUSTODY_LAST_RECEIPT=custody.apply({type:"CHOOSE_ADMISSION_RESPONSE",scenarioId:custody.scenarioId,choiceId:node.custodyChoiceId});}if(node.privacyChoiceId){globalThis.AUREN_PRIVACY_LAST_RECEIPT=privacy.apply({type:"CHOOSE_PRIVACY_RESPONSE",scenarioId:privacy.scenarioId,choiceId:node.privacyChoiceId});globalThis.AUREN_PRIVACY_RELATIONSHIP_LAST_RECEIPT=privacyRelationship.map(globalThis.AUREN_PRIVACY_LAST_RECEIPT,relationship);}busy=true;sequence++;const token=sequence;empty(options);root.setAttribute("data-auren-options-ready","false");if(relationshipAction){relationship.transition({action:relationshipAction,sourceNode:current,choiceId:id});syncRelationship();}if(archetypeEvidence)archetype.observe({sourceNode:current,choiceId:id,evidence:archetypeEvidence});history.push(Object.freeze({from:current,to:id,prompt:node.prompt||id}));sessionContext.recordDelivered({beatId:"node:"+id+":"+history.length,subjectId:semanticSubject(id),threadId:sessionContext.getState().activeThread});const selected=stateDependent.select(node,sessionContext,archetype.getState());globalThis.AUREN_STATE_DEPENDENT_LAST_RECEIPT=selected.receipt;const ok=await perform(node.prompt||id,selected.responses,token);if(!ok)return;
  if(node.route){const a=document.createElement("a");a.className="auren-option";a.href=node.route;a.textContent=node.routeLabel||"Open destination";options.appendChild(a);const back=document.createElement("button");back.type="button";back.className="auren-option";back.textContent="Back to Products";back.addEventListener("click",()=>choose("products"));options.appendChild(back);root.setAttribute("data-auren-options-ready","true");root.setAttribute("data-auren-performance","CHOICES");busy=false;return;}renderOptions(id);}
 sequence++;const token=sequence;const supplied=globalThis.AUREN_C4_1_RETURN_RECEIPT||null;const beforeR=relationship.getState(),beforeA=archetype.getState();const ack=returnContext.consume(supplied,{relationshipRevision:beforeR.revision,archetypeRevision:beforeA.revision});globalThis.AUREN_RETURN_ACK_RECEIPT=ack;if(ack.acknowledged){const node=voice.getNode(ack.acknowledgmentNode);const selected=stateDependent.select(node,sessionContext,beforeA);globalThis.AUREN_STATE_DEPENDENT_LAST_RECEIPT=selected.receipt;const ok=await perform(null,selected.responses,token);if(ok){let list=voice.getOptions(ack.acknowledgmentNode);if(list.length<3)list=[...list,Object.freeze({id:"admissionPressure",label:"Give me a Manor decision",relationshipAction:null,archetypeEvidence:null})];empty(options);for(const p of list.slice(0,3)){const b=document.createElement("button");b.type="button";b.className="auren-option";b.textContent=p.label;b.addEventListener("click",()=>choose(p.id,p.relationshipAction,p.archetypeEvidence));options.appendChild(b);}current=ack.acknowledgmentNode;root.setAttribute("data-auren-node",ack.acknowledgmentNode);root.setAttribute("data-auren-options-ready","true");root.setAttribute("data-auren-performance","CHOICES");busy=false;}}else{const ok=await perform(null,voice.opening,token);if(ok)renderOptions("root");}root.setAttribute("data-auren-ready","true");
 globalThis.AUREN_ARCHETYPE_STATE=()=>archetype.getState();globalThis.AUREN_ARCHETYPE_APPLY=input=>archetype.apply(input);globalThis.AUREN_ARCHETYPE_RESET=()=>archetype.reset();
 globalThis.AUREN_RELATIONSHIP_STATE=()=>relationship.getState();globalThis.AUREN_RELATIONSHIP_TRANSITION=input=>relationship.transition(input);globalThis.AUREN_RELATIONSHIP_RESET=()=>{const receipt=relationship.reset();syncRelationship();return receipt;};
 globalThis.AUREN_SESSION_CONTEXT_STATE=()=>sessionContext.getState();globalThis.AUREN_CHAMBER_RECEIPT=Object.freeze({contract:CONTRACT,ready:true,sessionContextContract:sessionContext.contract,sessionContextBound:true,sessionContextBehaviorMode:"SEMANTIC_EVENTS_ACTIVE_SELECTION_PHASE_INERT",voice:voice.contract,geometry:globalThis.AUREN_ROOM_GEOMETRY.contract,presentation:pres.getReceipt(),environment:env.getReceipt(),conversationPrimary:true,progressiveRuntime:true,boundedActiveStage:true,timedPerformance:true,typingIndicator:true,choicesDelayedUntilTurnComplete:true,maxContextualChoices:3,historyMode:"MEMORY_NOT_ACTIVE_TRANSCRIPT",relationshipContract:relationship.contract,relationshipSessionOnly:true,archetypeContract:archetype.contract,archetypeSessionOnly:true,stateDependentContract:stateDependent.contract,sceneOfferContract:sceneOffer.contract,returnContextContract:returnContext.contract,custodyContract:custody.version,privacyContract:privacy.version,privacyRelationshipContract:privacyRelationship.contract});
}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})();
