/* AUREN_EARLY_ENCOUNTER_VOICE_V1 */
(()=>{"use strict";const C="AUREN_EARLY_ENCOUNTER_VOICE_V1";
const x=(id,prompt,responses,choices=[],extra={})=>Object.freeze({id,prompt,responses:Object.freeze(responses),choices:Object.freeze(choices.map(v=>Object.freeze(v))),...extra});
const N=Object.freeze({
meet:x("meet","Meet Auren",["I'm Auren. I'm thirteen, the Manor is mine, and people usually get stuck on one of those two things.","You can be surprised. Just don't confuse surprised with incapable."],[["age","Thirteen and running this place?","age"],["responsibility","So what are you actually responsible for?","responsibility"],["ownership","The Manor is yours?","ownership"]]),
age:x("age","Thirteen and running this place?",["Yep. Thirteen.","That's the part people stare at. The useful question is what I actually have to decide here."],[["responsibility","All right. What do you have to decide?","responsibility"],["manor","Show me what you mean.","manor"]]),
reaction:x("reaction","People give you a hard time about it?",["Sometimes. Mostly they decide what I can handle before I say anything.","I care more about whether I make the right call for this place than whether somebody thinks thirteen sounds impressive."],[["responsibility","What kind of calls are yours to make?","responsibility"],["manor","Show me what that looks like here.","manor"]]),
ownership:x("ownership","The Manor is yours?",["Yes. I inherited it while my parents are gone.","They disappeared while they were traveling. I don't know exactly what happened.","What I do know is what their absence left in my hands: this place and the people depending on it."],[["inheritance","So that's when the Manor became your responsibility?","inheritance"],["responsibility","What did you have to take on?","responsibility"],["manor","Show me what that means here.","manor"]]),
whoThey:x("whoThey","Who are “they”?",["My parents. They disappeared while they were traveling, and I don't know exactly what happened.","That's as far as that story goes today. The part that belongs here is what happened afterward: the Manor became mine to answer for."],[["responsibility","What did that make you responsible for?","responsibility"],["manor","Show me what changed.","manor"]]),
gone:x("gone","What do you mean, gone?",["They disappeared while they were traveling. I don't know exactly what happened.","I can give you theories someday. Not now. What matters here is what happened next: I had to become responsible for the Manor."],[["responsibility","What did that actually put on you?","responsibility"],["manor","Show me what that means.","manor"]]),
parents:x("parents","What happened to them?",["They disappeared while they were traveling. I don't know exactly what happened.","That's not a mystery I'm solving with somebody the first time we meet. What I can show you is what their absence changed here."],[["responsibility","What changed for you?","responsibility"],["manor","Show me what changed here.","manor"]]),
unknown:x("unknown","You really don't know?",["No. If I knew, I'd tell you I knew.","But uncertainty doesn't make the responsibility disappear. The Manor still needed somebody making decisions."],[["responsibility","So what decisions became yours?","responsibility"],["manor","Show me what you had to take over.","manor"]]),
dontPush:x("dontPush","Okay. I won't push.",["Good.","Then I'll give you the part that matters here: what I had to do after they were gone."],[["responsibility","What did you have to do?","responsibility"],["manor","Show me.","manor"]]),
inheritance:x("inheritance","So that's when the Manor became your responsibility?",["Yes. Owning it is the easy sentence.","The actual job is deciding what this place is for, what it has to protect, and what I refuse to turn it into."],[["responsibility","So what is the Manor for?","responsibility"],["manor","Show me what you mean.","manor"]]),
responsibility:x("responsibility","What do you actually do here?",["I decide what the Manor is for.","It has to be somewhere people can be safe without the place owning their lives for them. That means the hard part isn't the building. It's deciding what protection should actually look like."],[["protected","Who is the Manor meant to protect?","protected-people"],["manor","Show me how the place does that.","manor"]]),
control:x("control","How can protecting someone get in their way?",["You can make somebody so safe they stop getting to choose anything.","That's the line I watch. If the Manor keeps danger out by taking somebody's life over for them, then I did the wrong job.","Protection should give people room to stand on their own, not make them belong to the person protecting them."],[["manor","Show me how you built that into the Manor.","manor"],["responsibility","So that's the standard you use here?","responsibility"]]),
protected:x("protected","Who is the Manor meant to protect?",["People who need somewhere safe without becoming everybody else's story.","Their names are theirs. What I can tell you is what the Manor owes them."],[["protectedHow","What does the Manor owe them?","protection"],["protectedPress","You won't tell me who they are?","identities"],["manor","Show me how the place protects them.","manor"]],{boundaryId:"protected-resident-identities"}),
protectedHow:x("protectedHow","What does the Manor owe them?",["A safe room. Privacy. A way to move through the place without being put on display.","If I'm protecting somebody, they should still get to decide which parts of themselves belong to other people."],[["manor","Show me how the Manor makes room for that.","manor"],["responsibility","And you're the one who has to hold that line?","responsibility"]]),
protectedPress:x("protectedPress","You won't tell me who they are?",["No. If I give you their names because you're curious, then the privacy I just told you matters doesn't mean much.","I can show you what I built around that promise. I can tell you what I have to get right. Their stories stay theirs."],[["protectedHow","Then tell me what the Manor owes them.","protection"],["responsibility","What do you have to get right?","responsibility"],["manor","Show me how you protect that privacy.","manor"]],{boundaryId:"protected-resident-identities"}),
products:x("products","Products",["These aren't here because I need five things to sell you.","They're five different attempts to make something useful without pretending the hard parts don't exist. That's the part I pay attention to.","Pick one and I'll tell you what I notice first."],[["archcoin","ARCHCOIN","archcoin"],["education","Education","education"],["fiveFlags","Five Flags","five-flags"],["nutrition","Nutrition","nutrition"],["book","Book / Nine Summits","book"]]),
archcoin:x("archcoin","ARCHCOIN",["ARCHCOIN is four connected pieces around an agreement and the money moving through it.","What gets my attention is that the status isn't blurred together: Contract and Receivable are live; Payable and Allocation aren't yet.","I trust that more than somebody calling the whole thing finished because two pieces work."],[["archcoinWhy","Why does that matter to you?","auren-opinion"],["archcoinLive","What exactly is live?","status"],["archcoinGo","Show me the system itself.","depth"]]),
archcoinWhy:x("archcoinWhy","Why does that matter to you?",["Because every part having a job means you can tell what actually works and what still needs work.","I have enough responsibility already. I don't need a system lying to me about whether one of its pieces is ready."],[["archcoinLive","Then what can I actually verify right now?","status"],["archcoinGo","Show me ARCHCOIN.","depth"]]),
archcoinLive:x("archcoinLive","What exactly is live?",["ARCC for Contract and ARCR for Receivable are live on Ethereum mainnet. Payable and Allocation aren't.","That's a status fact. It doesn't magically prove price, buyers, or anything else outside what those live pieces actually show."],[["archcoinGo","Show me what those pieces actually do.","depth"],["products","That's enough. Show me the other products.","products"]]),
archcoinGo:x("archcoinGo","Show me ARCHCOIN.",["That's where I'd stop talking and let the system show you what is actually there."],[],{route:"/products/archcoin/",routeLabel:"Open ARCHCOIN"}),
education:x("education","Education",["The English Fluency Accelerator starts with 1,001 useful words and ideas, then pays attention to what you can actually do with them.","I like that better than somebody picking a level and hoping it's right."],[["educationHow","How does it figure out what I can do?","placement"],["educationWhy","Why do you like that better?","auren-opinion"],["educationGo","Show me Education.","depth"]]),
educationHow:x("educationHow","How does it figure out what I can do?",["By looking at what you actually show it, not just what level you say you are.","The public work doesn't prove every learning outcome yet. I'm not going to pretend it does."],[["educationWhy","Is that why you like it?","auren-opinion"],["educationGo","Show me what's available.","depth"]]),
educationWhy:x("educationWhy","Why do you like that better?",["Because people are wrong about themselves all the time. Too confident, not confident enough—both happen.","I'd rather start with what somebody can actually show me."],[["educationGo","Show me Education.","depth"],["products","Show me the other products.","products"]]),
educationGo:x("educationGo","Show me Education.",["Go look at the program itself. That's where the details belong."],[],{route:"/products/education/",routeLabel:"Open Education"}),
fiveFlags:x("fiveFlags","Five Flags",["Five Flags is harder than it looks. One person helps everybody else, but they only get five signals.","So they can point you in the right direction. They can't just give you the answer."],[["fiveWhy","Why only five?","five-signals"],["fiveHelp","So they can help, but they can't tell you?","limited-help"],["fiveTry","Can I try it?","try"]]),
fiveWhy:x("fiveWhy","Why only five?",["Because if the helper can say anything, they can basically solve it for you.","Five signals make them choose what's actually useful."],[["fiveHelp","So they can help, but not solve it?","limited-help"],["fiveTry","Can I try it?","try"]]),
fiveHelp:x("fiveHelp","So they can help, but they can't tell you?",["Exactly.","You still have to figure it out. That's the part I like."],[["fiveExcited","Why do you like that part?","auren-opinion"],["fiveTry","Can I try it?","try"]]),
fiveTry:x("fiveTry","Can I try it?",["Not yet. There'll be a demo soon. It's still being worked on.","I'm actually excited about that one."],[["fiveExcited","Why that one?","auren-excitement"],["fiveGo","Show me more about Five Flags.","depth"]]),
fiveExcited:x("fiveExcited","Why that one?",["Because you can't win by having one person do all the thinking.","Everybody still has to figure something out."],[["fiveGo","Show me more about Five Flags.","depth"],["products","Show me the other products.","products"]]),
fiveGo:x("fiveGo","Show me more about Five Flags.",["The product page can take it from here."],[],{route:"/products/five-flags/",routeLabel:"Open Five Flags"}),
nutrition:x("nutrition","Nutrition",["This one's still being worked on. The idea is a small drink you mix before a meal instead of turning eating into a whole project.","I like the fact that it's supposed to stay simple."],[["nutritionUse","What would I actually do with it?","use"],["nutritionOpen","What's still being worked out?","status"],["nutritionWhy","Why does simple matter to you?","auren-opinion"],["nutritionGo","Show me Nutrition.","depth"]]),
nutritionUse:x("nutritionUse","What would I actually do with it?",["The current idea is one serving mixed into about 350 milliliters of water shortly before a meal.","It's a prototype, not a finished health claim."],[["nutritionOpen","So what's not finished yet?","status"],["nutritionGo","Show me the current version.","depth"]]),
nutritionOpen:x("nutritionOpen","What's still being worked out?",["Things like how it mixes, how stable it is, testing, packaging, and the rest of the work that decides whether an idea is actually ready.","So no, I'm not calling it finished."],[["nutritionWhy","Is that why you like keeping it simple?","auren-opinion"],["nutritionGo","Show me Nutrition.","depth"]]),
nutritionWhy:x("nutritionWhy","Why does simple matter to you?",["Because if something meant to help with a meal becomes more annoying than the meal, that's ridiculous.","Simple is harder to mess up."],[["nutritionGo","Show me Nutrition.","depth"],["products","Show me the other products.","products"]]),
nutritionGo:x("nutritionGo","Show me Nutrition.",["The Nutrition page has the current work. That's the honest place to go next."],[],{route:"/products/nutrition/",routeLabel:"Open Nutrition"}),
book:x("book","Book / Nine Summits",["The Nine Summits of Love is the Book.","I have opinions about it. Elara is still the person I'd send you to if you want to go deep."],[["bookAuren","What makes the Book different to you?","auren-perspective"],["bookElaraWhy","Why Elara?","elara"],["bookElara","Take me to Elara.","depth"]]),
bookAuren:x("bookAuren","What makes the Book different to you?",["It asks bigger questions than most of the things on this list.","I like things that make people do some of the work themselves. You can probably see the pattern."],[["bookElaraWhy","And Elara sees it differently?","elara"],["bookElara","Take me to Elara.","depth"],["products","Show me the other products.","products"]]),
bookElaraWhy:x("bookElaraWhy","Why Elara?",["Because she can take you farther into it without me pretending her part is mine.","I can tell you what I think. She owns the deeper conversation."],[["bookElara","Take me to Elara.","depth"],["bookAuren","I want your side first.","auren-perspective"]]),
bookElara:x("bookElara","Take me to Elara.",["Good. Ask her yourself."],[],{route:"/elara/",routeLabel:"Talk to Elara"}),
manor:x("manor","Show me the Manor.",["All right. If I'm going to tell you what I'm responsible for, you should see the place those decisions are about."],[],{route:"/characters/?scene=manor&entry=fade",routeLabel:"Enter Mirror Manor"})
});
const opening=Object.freeze(["I'm Auren. I'm thirteen, the Manor is mine, and apparently those three facts are very difficult for people to hear in the same sentence."]);
const api=Object.freeze({contract:C,identity:"AUREN_VALE_SANCTUARY_BUILDER_V1",opening,getNode:id=>N[id]||null,getChoices:id=>(N[id]?.choices||[]).map(([id,label,anchor])=>Object.freeze({id,label,anchor})),getResponses:(id,ctx={})=>{const v=N[id];if(!v)return Object.freeze([]);if(v.boundaryId&&ctx.getBoundary?.("manor:people",v.boundaryId)?.interactionCaution&&v.pressureResponses)return Object.freeze([...v.pressureResponses]);return Object.freeze([...v.responses]);}});
Object.defineProperty(globalThis,"AUREN_CHAMBER_VOICE",{value:api,writable:false,configurable:false});globalThis.dispatchEvent(new CustomEvent("auren:voice-ready",{detail:{contract:C}}));})();