/* TARGET FILE: /products/auren/auren.chamber.js
   AUREN_C2_TIMED_CONVERSATION_RUNTIME_V1 */
(()=>{"use strict";
const CONTRACT="AUREN_C2_TIMED_CONVERSATION_RUNTIME_V1";
const q=(s,r=document)=>r.querySelector(s),empty=n=>{while(n&&n.firstChild)n.removeChild(n.firstChild);};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const reduced=()=>typeof matchMedia==="function"&&matchMedia("(prefers-reduced-motion: reduce)").matches;
function bubble(text,kind="auren"){const n=document.createElement("div");n.className="auren-bubble auren-bubble-"+kind;const b=document.createElement("div");b.className="auren-bubble-body";b.textContent=text;n.appendChild(b);return n;}
function typing(){const n=document.createElement("div");n.className="auren-bubble auren-bubble-auren auren-typing";n.setAttribute("aria-label","Auren is typing");const b=document.createElement("div");b.className="auren-typing-dots";b.innerHTML="<i></i><i></i><i></i>";n.appendChild(b);return n;}
async function boot(){
 const root=q("[data-auren-chamber]"),thread=q("[data-auren-thread]"),options=q("[data-auren-options]");const sessionContext=globalThis.AUREN_SESSION_CONTEXT,voice=globalThis.AUREN_CHAMBER_VOICE,archetype=globalThis.AUREN_ARCHETYPE_EVIDENCE,stateDependent=globalThis.AUREN_STATE_DEPENDENT,sceneOffer=globalThis.AUREN_SCENE_OFFER,returnContext=globalThis.AUREN_RETURN_CONTEXT,custody=globalThis.AUREN_MANOR_CUSTODY,privacy=globalThis.AUREN_MANOR_PRIVACY,env=globalThis.AUREN_ROOM_ENVIRONMENT,pres=globalThis.AUREN_ROOM_PRESENTATION;if(!root||!thread||!options||!sessionContext||!voice||!archetype||!stateDependent||!sceneOffer||!returnContext||!custody||!privacy||!env||!pres)return;
 env.mount(root);pres.mount(q("[data-auren-room]"));const conversationStatus=q("[data-auren-conversation-status]");const setConversationStatus=text=>{if(conversationStatus)conversationStatus.textContent=text;};root.removeAttribute("data-auren-relationship-phase");empty(thread);empty(options);let busy=true,sequence=0,current="root";const history=[];
 const wait=ms=>sleep(reduced()?Math.min(120,ms):ms);
 const reading=text=>Math.min(1200,650+Math.max(0,String(text).length-45)*5);
 function stage(visitor){empty(thread);if(visitor)thread.appendChild(bubble(visitor,"visitor"));root.setAttribute("data-auren-active-turn",String(history.length));}
 async function perform(visitor,messages,token){
  stage(visitor);root.setAttribute("data-auren-performance","LISTENING");await wait(450);if(token!==sequence)return false;
  for(let i=0;i<messages.length;i++){
   root.setAttribute("data-auren-performance","TYPING");const t=typing();thread.appendChild(t);await wait(i?600:760);if(token!==sequence)return false;t.remove();
   root.setAttribute("data-auren-performance","SPEAKING");thread.appendChild(bubble(messages[i]));if(i<messages.length-1){await wait(reading(messages[i]));if(token!==sequence)return false;}
  }
  root.setAttribute("data-auren-performance","READING_PAUSE");await wait(480);return token===sequence;
 }
 function renderOptions(nodeId){current=nodeId;empty(options);let list=voice.getOptions(nodeId);const offer=sceneOffer.evaluate({sourceNode:nodeId,sessionContext,destinationId:"manor",inLearnPath:["about","who","work","mirrorland","people","room","helpRoom","helpRoomDone","elara","jeeves","protectedPeople","privacyBoundary","privacyLimited","privacyPress","privacyRespect"].includes(nodeId)});globalThis.AUREN_SCENE_OFFER_LAST_RECEIPT=offer;if(offer.offered&&list.length<3&&!list.some(x=>x.id==="manorOffer"))list=[...list,Object.freeze({id:"manorOffer",label:"Show me the Manor",relationshipAction:null,archetypeEvidence:null})];for(const p of list.slice(0,3)){const b=document.createElement("button");b.type="button";b.className="auren-option";b.textContent=p.label;b.addEventListener("click",()=>choose(p.id));options.appendChild(b);}root.setAttribute("data-auren-node",nodeId);root.setAttribute("data-auren-options-ready",options.childElementCount?"true":"false");root.setAttribute("data-auren-performance","CHOICES");busy=false;}
 function semanticSubject(id){if(["about","who","work","helpRoom","helpRoomDone"].includes(id))return"auren:self";if(["mirrorland","room"].includes(id))return"mirrorland:auren-domain";if(["people"].includes(id))return"mirrorland:principal-characters";if(["elara"].includes(id))return"character:elara";if(["jeeves"].includes(id))return"character:jeeves";if(["protectedPeople","privacyBoundary","privacyRespect","privacyLimited","privacyPress"].includes(id))return"manor:people";if(["products","archcoin","archcoinWhat","archcoinLive","archcoinFour","archcoinCapabilities","archcoinGo","fiveFlags","fiveFlagsHow","fiveFlagsWhy","fiveFlagsGo","moreProducts","education","educationHow","educationLimits","educationGo","nutrition","nutritionPrototype","nutritionOpen","nutritionGo","book","bookWhy","bookElara"].includes(id))return"auren:products";if(["manorOffer","manorReturnAck","admissionPressure","admissionAdmit","admissionDelay","admissionRefuse"].includes(id))return"manor:handoff";return null;}
 function recordSemanticChoice(from,id,node){const subjectId=semanticSubject(id),prior=semanticSubject(from);if(subjectId){const seen=sessionContext.getState().topics.some(x=>x.subjectId===subjectId);sessionContext.apply({eventType:seen?"TOPIC_REVISITED":"TOPIC_OPENED",subjectId,sourceBeat:id});sessionContext.apply({eventType:"TOPIC_MEANINGFULLY_PURSUED",subjectId,sourceBeat:id});if(prior&&prior!==subjectId){sessionContext.apply({eventType:"TOPIC_REDIRECTED",subjectId,sourceBeat:id});const pressured=sessionContext.getState().boundaries.filter(x=>x.interactionCaution&&x.recovery!=="ESTABLISHED"&&x.subjectId!==subjectId);for(const b of pressured)sessionContext.apply({eventType:"BOUNDARY_THREAD_RELEASED",subjectId:b.subjectId,boundaryId:b.boundaryId,sourceBeat:id});}}
  if(id==="privacyBoundary"||id==="protectedPeople"){const b=sessionContext.getBoundary("manor:people","protected-resident-identities");if(!b.known)sessionContext.apply({eventType:"BOUNDARY_ESTABLISHED",subjectId:"manor:people",boundaryId:"protected-resident-identities",sourceBeat:id,metadata:{authoritySensitive:true}});}
  if(id==="privacyRespect")sessionContext.apply({eventType:"BOUNDARY_ACKNOWLEDGED",subjectId:"manor:people",boundaryId:"protected-resident-identities",sourceBeat:id});
  if(id==="privacyLimited")sessionContext.apply({eventType:"BOUNDED_CONTEXT_REQUESTED",subjectId:"manor:people",boundaryId:"protected-resident-identities",sourceBeat:id});
  if(id==="privacyPress"){const b=sessionContext.getBoundary("manor:people","protected-resident-identities");if(!b.known){sessionContext.apply({eventType:"BOUNDARY_ESTABLISHED",subjectId:"manor:people",boundaryId:"protected-resident-identities",sourceBeat:id,metadata:{authoritySensitive:true}});}else{sessionContext.apply({eventType:"BOUNDARY_PRESSURED",subjectId:"manor:people",boundaryId:"protected-resident-identities",sourceBeat:id});sessionContext.apply({eventType:"BOUNDARY_REASSERTED",subjectId:"manor:people",boundaryId:"protected-resident-identities",sourceBeat:id});}}
  if(node?.route){const destinationId=id==="bookElara"?"elara":id==="manorOffer"?"manor":id==="jeeves"?"jeeves":"product";const threadId=destinationId==="manor"?"handoff:manor:"+(prior||subjectId||"general"):destinationId==="elara"?"handoff:elara:"+(prior||subjectId||"general"):destinationId==="jeeves"?"handoff:jeeves:"+(prior||subjectId||"general"):null;if(threadId){sessionContext.apply({eventType:"UNRESOLVED_THREAD_OPENED",subjectId:prior||subjectId,threadId,sourceBeat:id});}sessionContext.apply({eventType:"HANDOFF_OFFERED",subjectId:prior||subjectId,threadId,destinationId,sourceBeat:id});}
 }
 async function choose(id){if(busy)return;const node=voice.getNode(id);if(!node)return;recordSemanticChoice(current,id,node);if(node.custodyChoiceId){globalThis.AUREN_CUSTODY_LAST_RECEIPT=custody.apply({type:"CHOOSE_ADMISSION_RESPONSE",scenarioId:custody.scenarioId,choiceId:node.custodyChoiceId});}if(node.privacyChoiceId){globalThis.AUREN_PRIVACY_LAST_RECEIPT=privacy.apply({type:"CHOOSE_PRIVACY_RESPONSE",scenarioId:privacy.scenarioId,choiceId:node.privacyChoiceId});}busy=true;sequence++;const token=sequence;empty(options);root.setAttribute("data-auren-options-ready","false");archetype.observeAction({sourceNode:current,choiceId:id});history.push(Object.freeze({from:current,to:id,prompt:node.prompt||id}));const selectedResponses=typeof voice.getResponses==="function"?voice.getResponses(id,{hasDelivered:beat=>sessionContext.hasDelivered(beat),getBoundary:(subject,boundary)=>sessionContext.getBoundary(subject,boundary)}):null;const selected=selectedResponses&&selectedResponses.length?Object.freeze({responses:selectedResponses,receipt:Object.freeze({contract:"AUREN_SUCCESSOR_VOICE_CONTEXT_SELECTION_V1",sourceNode:id,reason:"VOICE_CONTEXT_SELECTED"})}):stateDependent.select(node,sessionContext,archetype.getState());sessionContext.recordDelivered({beatId:"node:"+id,subjectId:semanticSubject(id),threadId:sessionContext.getState().activeThread});globalThis.AUREN_STATE_DEPENDENT_LAST_RECEIPT=selected.receipt;const ok=await perform(node.prompt||id,selected.responses,token);if(!ok)return;
  if(node.route){const destinationId=id==="bookElara"?"elara":id==="manorOffer"?"manor":id==="jeeves"?"jeeves":"product";const a=document.createElement("a");a.className="auren-option";a.href=node.route;a.textContent=node.routeLabel||"Open destination";a.addEventListener("click",()=>sessionContext.apply({eventType:"HANDOFF_ACCEPTED",subjectId:semanticSubject(id),threadId:sessionContext.getState().handoffContext?.originatingThreadId||null,destinationId,sourceBeat:id}));options.appendChild(a);const back=document.createElement("button");back.type="button";back.className="auren-option";back.textContent="Back to Products";back.addEventListener("click",()=>choose("products"));options.appendChild(back);root.setAttribute("data-auren-options-ready","true");root.setAttribute("data-auren-performance","CHOICES");busy=false;return;}renderOptions(id);}
 sequence++;const token=sequence;const supplied=globalThis.AUREN_C4_1_RETURN_RECEIPT||null;const beforeA=archetype.getState();const ack=returnContext.consume(supplied,{relationshipRevision:null,archetypeRevision:beforeA.revision});globalThis.AUREN_RETURN_ACK_RECEIPT=ack;if(ack.acknowledged){const hc=sessionContext.getState().handoffContext;if(hc?.destinationId==="manor"){sessionContext.apply({eventType:"HANDOFF_RETURNED",subjectId:hc.originatingSubjectId,threadId:hc.originatingThreadId,destinationId:"manor",sourceBeat:"manorReturnAck"});if(hc.originatingThreadId)sessionContext.apply({eventType:"HANDOFF_THREAD_RESUMED",subjectId:hc.originatingSubjectId,threadId:hc.originatingThreadId,destinationId:"manor",sourceBeat:"manorReturnAck"});}const node=voice.getNode(ack.acknowledgmentNode);const returnThread=sessionContext.getState().handoffContext?.originatingThreadId||null;const returnResponses=typeof voice.getReturnResponses==="function"?voice.getReturnResponses(returnThread):null;const selected=returnResponses&&returnResponses.length?Object.freeze({responses:returnResponses,receipt:Object.freeze({contract:"AUREN_SUCCESSOR_RETURN_THREAD_SELECTION_V1",sourceNode:ack.acknowledgmentNode,originatingThreadId:returnThread})}):stateDependent.select(node,sessionContext,beforeA);globalThis.AUREN_STATE_DEPENDENT_LAST_RECEIPT=selected.receipt;const ok=await perform(null,selected.responses,token);if(ok){let list=voice.getOptions(ack.acknowledgmentNode);empty(options);for(const p of list.slice(0,3)){const b=document.createElement("button");b.type="button";b.className="auren-option";b.textContent=p.label;b.addEventListener("click",()=>choose(p.id));options.appendChild(b);}current=ack.acknowledgmentNode;root.setAttribute("data-auren-node",ack.acknowledgmentNode);root.setAttribute("data-auren-options-ready","true");root.setAttribute("data-auren-performance","CHOICES");busy=false;}}else{const ok=await perform(null,voice.opening,token);if(ok)renderOptions("root");}root.setAttribute("data-auren-ready","true");
 globalThis.AUREN_ARCHETYPE_STATE=()=>archetype.getState();globalThis.AUREN_ARCHETYPE_APPLY=input=>archetype.observeAction(input);globalThis.AUREN_ARCHETYPE_RESET=()=>archetype.reset();
 globalThis.AUREN_SESSION_CONTEXT_STATE=()=>sessionContext.getState();globalThis.AUREN_CHAMBER_RECEIPT=Object.freeze({contract:CONTRACT,ready:true,sessionContextContract:sessionContext.contract,sessionContextBound:true,sessionContextBehaviorMode:"SEMANTIC_EVENTS_ACTIVE_PHASE_PRESENTATION_AND_MANOR_GATE_REMOVED",voice:voice.contract,geometry:globalThis.AUREN_ROOM_GEOMETRY.contract,presentation:pres.getReceipt(),environment:env.getReceipt(),conversationPrimary:true,progressiveRuntime:true,boundedActiveStage:true,timedPerformance:true,typingIndicator:true,choicesDelayedUntilTurnComplete:true,maxContextualChoices:3,historyMode:"MEMORY_NOT_ACTIVE_TRANSCRIPT",archetypeContract:archetype.contract,archetypeSessionOnly:true,stateDependentContract:stateDependent.contract,sceneOfferContract:sceneOffer.contract,returnContextContract:returnContext.contract,custodyContract:custody.version,privacyContract:privacy.version});
}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})();
