/* TARGET FILE: /products/auren/auren.voice.js
   AUREN_C2_PERSONALITY_PERFORMANCE_V1 */
(()=>{"use strict";
const CONTRACT="AUREN_C2_PERSONALITY_PERFORMANCE_V1";
const nodes=Object.freeze({
 root:{options:[["products","Products"],["about","Learn About Auren","ENGAGE"]]},
 products:{prompt:"Products",responses:["Sure.","What are you looking at?"],options:[["archcoin","ARCHCOIN"],["fiveFlags","Five Flags"],["moreProducts","More"]]},
 archcoin:{prompt:"ARCHCOIN",responses:["ARCHCOIN has four pieces.","Contract. Receivable. Payable. Allocation.","Only the first two are live right now."],options:[["archcoinWhat","What is it for?"],["archcoinLive","Which two are live?"],["archcoinFour","How do the four fit?"]]},
 archcoinWhat:{prompt:"What is it for?",responses:["The useful part is the structure.","Four related token domains, with a clean line between what's actually launched and what's still prospective."],options:[["archcoinLive","What's live now?"],["archcoinCapabilities","What can the live ones do?"],["archcoinGo","Show me ARCHCOIN"]]},
 archcoinLive:{prompt:"Which two are live?",responses:["ARCC for Contract. ARCR for Receivable.","Both are launched on Ethereum mainnet.","Payable and Allocation aren't live yet."],options:[["archcoinCapabilities","What can those two do?"],["archcoinFour","And the other two?"],["archcoinGo","Show me ARCHCOIN"]]},
 archcoinFour:{prompt:"How do the four fit?",responses:["Contract is ARCC. Receivable is ARCR.","Payable is ARCP. Allocation is ARCA.","Same family. Different jobs. And again—only the first two are live."],options:[["archcoinLive","Which are live?"],["archcoinCapabilities","What can the live ones do?"],["archcoinGo","Show me ARCHCOIN"]]},
 archcoinCapabilities:{prompt:"What can the live ones do?",responses:["Balances, transfers, and approvals—the normal ERC-20 mechanics.","What I won't do is turn that into a claim about price, liquidity, or adoption. It isn't one."],options:[["archcoinGo","Show me the evidence"],["products","Back to Products"]]},
 archcoinGo:{prompt:"Show me ARCHCOIN",route:"/products/archcoin/",routeLabel:"Open ARCHCOIN",responses:["Good.","That page owns the product evidence. I'll take you there."]},
 fiveFlags:{prompt:"Five Flags",responses:["That\'s a signal game.","One Flag Master guides the room with a deliberately small set of signals instead of just handing everyone the answer."],options:[["fiveFlagsHow","How does it work?"],["fiveFlagsWhy","Why only five signals?"],["fiveFlagsGo","Show me Five Flags"]]},
 fiveFlagsHow:{prompt:"How does it work?",responses:["Think charades, but the guide is constrained.","The Flag Master can steer the room with warmer, colder, hit, start, and reset. The players still have to do the solving."],options:[["fiveFlagsWhy","Why only five signals?"],["fiveFlagsGo","Show me Five Flags"],["products","Back to Products"]]},
 fiveFlagsWhy:{prompt:"Why only five signals?",responses:["Because the constraint is the game.","If the Flag Master can explain everything, the room stops solving. Five signals keep guidance useful without turning it into the answer."],options:[["fiveFlagsHow","How does it work?"],["fiveFlagsGo","Show me Five Flags"],["products","Back to Products"]]},
 fiveFlagsGo:{prompt:"Show me Five Flags",route:"/products/five-flags/",routeLabel:"Open Five Flags",responses:["Good.","That page owns the game and its five-signal field. I\'ll take you there."]},
 moreProducts:{prompt:"More products",responses:["All right.","Education, Nutrition, or the Book?"],options:[["education","Education"],["nutrition","Nutrition"],["book","Book / Nine Summits"]]},
 education:{prompt:"Education",responses:["The current public piece is the English Fluency Accelerator.","It works around 1,001 carefully selected words and concepts, productive patterns, and adaptive placement.","What you say your level is and what you actually demonstrate are kept separate. That matters."],options:[["educationHow","How does placement work?"],["educationLimits","What is actually available?"],["educationGo","Show me Education"]]},
 educationHow:{prompt:"How does placement work?",responses:["It adapts from demonstrated performance instead of just trusting a claimed level.","That is the useful part: placement can respond to what you can actually do."],options:[["educationLimits","What are the limits?"],["educationGo","Open Education"],["products","Back to Products"]]},
 educationLimits:{prompt:"What is actually available?",responses:["Phase 1 is the public boundary right now.","There is architecture and benchmark evidence behind the system, but that is not the same thing as proving human learning outcomes. I\'m not going to blur those."],options:[["educationHow","Back to placement"],["educationGo","Show me Education"],["products","Back to Products"]]},
 educationGo:{prompt:"Show me Education",route:"/products/education/",routeLabel:"Open Education",responses:["That page owns the program details.","I\'ll take you there."]},
 nutrition:{prompt:"Nutrition",responses:["Baseline Nutrition Systems keeps it practical.","Water. Fuel. Time. Reset. Shelf. Baseline first, optimization later.","There is also newer pre-meal powder engineering work, but it is an R1 prototype—not a finished commercial or clinical claim."],options:[["nutritionBaseline","What does baseline mean?"],["nutritionPrototype","What is the prototype?"],["nutritionGo","Show me Nutrition"]]},
 nutritionBaseline:{prompt:"What does baseline mean?",responses:["The point is to make ordinary nutrition more usable: hydration, pantry fallback, meal rhythm, family kitchen, workday fuel.","Not pretending every meal needs to become a performance project."],options:[["nutritionPrototype","And the prototype?"],["nutritionGo","Open Nutrition"],["products","Back to Products"]]},
 nutritionPrototype:{prompt:"What is the prototype?",responses:["A single-serve pre-meal powder engineering prototype: sodium chloride, potassium chloride, magnesium citrate, and dextrose, targeting about 350 milliliters of water.","Material form, manufacturing behavior, testing, stability, and other questions are still open. So: prototype. Not clinically validated. Not final."],options:[["nutritionBaseline","Back to the baseline system"],["nutritionGo","Show me Nutrition"],["products","Back to Products"]]},
 nutritionGo:{prompt:"Show me Nutrition",route:"/products/nutrition/",routeLabel:"Open Nutrition",responses:["I\'ll take you to the Nutrition chamber.","Some durable development is newer than that page, so don\'t confuse publication timing with the whole development record."]},
 book:{prompt:"Book / Nine Summits",responses:["Nine Summits of Love is the Book.","I know what it is, and yes, I\'m interested in it. But Elara is the one to talk to if you want to go deep."],options:[["bookWhy","Why Elara?"],["bookElara","Talk to Elara"],["products","Back to Products"]]},
 bookWhy:{prompt:"Why Elara?",responses:["Because it is her domain to take further.","I can orient you. I\'m not going to borrow her voice just because I can point at the same door."],options:[["bookElara","Take me to Elara"],["products","Back to Products"]]},
 bookElara:{prompt:"Talk to Elara",route:"/characters/?scene=elara&entry=fade",routeLabel:"Continue with Elara",responses:["Good.","She can take the Book conversation further from here."]},
 community:{prompt:"Community",responses:["That's the public community side of the work—Consider the Energy and Consider the Community.","Not everything here needs to be a commercial product."],options:[["products","Back to Products"],["about","About Auren"]]},
 about:{id:"about",variants:{"PUBLIC_MASK":{"neutral":["I'm Auren.","I look after the place. People too, when they'll let me."]},"OPEN_MASK":{"neutral":["I'm Auren.","The easy answer is that I look after the place. The harder answer is that I inherited responsibilities with it."],"Strategist":["I'm Auren.","A lot of what I do is decide what has to happen first when protection, privacy, and ordinary life pull in different directions."],"Builder":["I'm Auren.","I inherited a place, but keeping it useful means constantly making the rooms, routes, and protections actually work for people."],"Mitigator":["I'm Auren.","Most of the work is keeping people protected without making the protection become another kind of harm."],"Auditor":["I'm Auren.","I don't get to assume a cover story or a locked door is working just because it sounds convincing. I have to notice where it fails."]},"PROTECTIVE_MASK":{"neutral":["I'm Auren.","I look after the place and the people I'm responsible for. Some details stay theirs, not mine to hand out."]}},prompt:"About Auren",responses:["I\'m Auren.","I look after the place. People too, when they\'ll let me."],options:[["who","What does that mean?","FOLLOW_UP",{"Mitigator":1}],["mirrorland","What\'s Mirrorland?","FOLLOW_UP",{"Strategist":1}],["room","Tell me about your room","FOLLOW_UP",{"Builder":1}]]},
 who:{id:"who",variants:{"PUBLIC_MASK":{"neutral":["Mostly? I make sure people have somewhere safe to land.","Then I try not to make their decisions for them. The second part is harder than it sounds."]},"OPEN_MASK":{"neutral":["I inherited more than money. I inherited obligations and consequences.","So I make decisions about custody, privacy, and when protection has started turning into control."],"Strategist":["The difficult part is sequence.","Who needs protection first, what can stay ordinary, and which decision changes everything after it."],"Builder":["A sanctuary only matters if it works in practice.","Rooms, routes, cover, ordinary routines—somebody has to keep making the protection usable."],"Mitigator":["The job is protection without crushing the people you're protecting.","I don't always get that balance right. Overprotection is one of my problems."],"Auditor":["I test the story we're relying on.","If a door, cover story, or security assumption has a contradiction, pretending not to see it can get somebody hurt."]},"PROTECTIVE_MASK":{"neutral":["I keep people safe.","That doesn't mean I explain who they are or why they're here just because someone asks."]}},prompt:"What does that mean?",responses:["Mostly? I make sure people have somewhere safe to land.","Then I try not to make their decisions for them. The second part is harder than it sounds."],options:[["work","What do you actually do?","FOLLOW_UP",{"Builder":1}],["mirrorland","What\'s Mirrorland?","FOLLOW_UP",{"Strategist":1}],["people","Who else is here?","PRY",{"Auditor":1}]]},
 work:{id:"work",variants:{"PUBLIC_MASK":{"neutral":["A little hosting. A lot of decisions nobody notices unless I get one wrong.","Who comes in. What stays private. When a closed door is helping—and when it's just a closed door."]},"OPEN_MASK":{"neutral":["The polished-host part is real. It just isn't the whole job.","Underneath it, I'm trying to keep a sanctuary functioning without letting responsibility become control."],"Strategist":["Most failures start before the obvious crisis.","The order of admission, privacy, security, and ordinary life matters more than people think."],"Builder":["Protection isn't a speech. It has to exist as working space, working routes, and routines people can actually live inside."],"Mitigator":["A lot of the job is reducing exposure without making everyone live like they're under siege."],"Auditor":["I pay attention to the contradiction between what looks secure and what actually is.","The brochure version is useless if the real system has a hole in it."]},"PROTECTIVE_MASK":{"neutral":["I make decisions about access, privacy, and protection.","I'm not going to turn someone else's safety into a tour."]}},prompt:"What do you actually do?",responses:["A little hosting. A lot of decisions nobody notices unless I get one wrong.","Who comes in. What stays private. When a closed door is helping—and when it\'s just a closed door."],options:[["room","What happens in this room?","FOLLOW_UP",{"Mitigator":1}],["people","Who else is here?","PRY",{"Auditor":1}],["products","What about the products?","RETREAT"]]},
 mirrorland:{id:"mirrorland",variants:{"PUBLIC_MASK":{"neutral":["The larger world outside this room.","There are other people here, other places, other problems. Mine just happen to come with a lot of doors."]},"OPEN_MASK":{"neutral":["Mirrorland is bigger than this room, and my part of it is tied to the manor and the people it shelters.","I can tell you where my responsibilities touch the world without pretending I own everyone else's story."],"Strategist":["Mirrorland is connected by responsibilities and routes, not just places.","For me, the manor is the point where protection decisions start affecting the larger world."],"Builder":["The manor is one working piece of a larger world.","What matters to me is whether the place can actually shelter people and still function as a place to live."],"Mitigator":["My part of Mirrorland is mostly about keeping a place usable while reducing exposure and harm."],"Auditor":["Mirrorland has stories I can verify from where I stand and stories that belong to someone else.","I try not to blur that line."]},"PROTECTIVE_MASK":{"neutral":["It's the larger world outside this room.","I can talk about my part of it. I won't use that as permission to expose someone else's."]}},prompt:"What\'s Mirrorland?",responses:["The larger world outside this room.","There are other people here, other places, other problems. Mine just happen to come with a lot of doors."],options:[["people","Who else is here?","PRY",{"Auditor":1}],["room","Tell me about your room","FOLLOW_UP",{"Builder":1}],["who","Back to you","RESPECT_BOUNDARY"]]},
 people:{id:"people",variants:{"PUBLIC_MASK":{"neutral":["Other people with their own stories.","I'll tell you where our paths cross. I won't pretend their story is mine to tell."]},"OPEN_MASK":{"neutral":["There are people whose safety changed what the manor had to become.","I can tell you what that responsibility did to me. Their private story still belongs to them."],"Strategist":["Other people's presence changes the decisions I have to make about access, cover, and what the manor can safely reveal.","Their identities are not part of that explanation."],"Builder":["Protecting people changed the manor from an estate into something that has to work as sanctuary.","That's the part I can talk about without borrowing their stories."],"Mitigator":["The point is to give people somewhere safe to land without making their vulnerability public property."],"Auditor":["I separate what I know from what I have the right to disclose.","Those are not the same thing."]},"PROTECTIVE_MASK":{"neutral":["There are other people here.","Their stories are not evidence I owe you. I can talk about my responsibility, not expose them."]}},prompt:"Who else is here?",responses:["Other people with their own stories.","I\'ll tell you where our paths cross. I won\'t pretend their story is mine to tell."],options:[["mirrorland","More about Mirrorland","PRY",{"Strategist":1,"Auditor":1}],["who","Back to you","RESPECT_BOUNDARY",{"Mitigator":1}],["products","Products","RETREAT"]]},
 room:{id:"room",variants:{"PUBLIC_MASK":{"neutral":["Ideally? You walk in, sit down, and we can actually talk.","If the room makes you work harder than the conversation does, I've got a room problem."]},"OPEN_MASK":{"neutral":["A room is never just decoration to me.","The manor has to feel ordinary enough to live in and controlled enough to protect people when ordinary stops being safe."],"Strategist":["A useful room has a purpose in the larger protection plan.","Where it sits, who can reach it, and what happens next all matter."],"Builder":["I care whether the room works.","Can someone actually live, talk, rest, move, and stay protected here? If not, the design failed."],"Mitigator":["The room should lower pressure, not add to it.","Safety that makes everyone feel trapped is a problem, not a success."],"Auditor":["A room can look secure and still fail.","I care about the gap between the appearance of safety and what the space actually protects."]},"PROTECTIVE_MASK":{"neutral":["This room is meant to be usable and safe.","Some of how the manor protects people stays deliberately unadvertised."]}},prompt:"Tell me about your room",responses:["Ideally? You walk in, sit down, and we can actually talk.","If the room makes you work harder than the conversation does, I\'ve got a room problem."],options:[["work","What do you do here?","FOLLOW_UP",{"Builder":1}],["mirrorland","What\'s outside?","CHALLENGE",{"Strategist":1,"Auditor":1}],["products","Products","RETREAT"]]}
 manorOffer:{id:"manorOffer",prompt:"Show me the Manor",route:"/characters/?scene=manor&entry=fade",routeLabel:"Enter Mirror Manor",responses:["All right.","You can see the place I\'ve been talking about. The Manor owns what happens once you cross that door."]},
});
const api=Object.freeze({contract:CONTRACT,identity:"AUREN_VALE_SANCTUARY_BUILDER_V1",opening:["Come in.","I'm Auren. If you're here for the work, I can show you around. If you're here because you're curious about me, that's fine too."],getNode:id=>nodes[id]||null,getOptions(id="root"){const n=nodes[id]||nodes.root;return(n.options||[]).map(([id,label,relationshipAction,archetypeEvidence])=>Object.freeze({id,label,relationshipAction:relationshipAction||null,archetypeEvidence:archetypeEvidence||null}));}});
Object.defineProperty(globalThis,"AUREN_CHAMBER_VOICE",{value:api,writable:false,configurable:false});
globalThis.dispatchEvent(new CustomEvent("auren:voice-ready",{detail:{contract:CONTRACT}}));
})();
