/* AUREN_EARLY_ENCOUNTER_RUNTIME_V1 */
(()=>{"use strict";const C="AUREN_EARLY_ENCOUNTER_RUNTIME_V1",q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)],empty=n=>{while(n?.firstChild)n.removeChild(n.firstChild)},sleep=ms=>new Promise(r=>setTimeout(r,ms)),reduced=()=>matchMedia?.("(prefers-reduced-motion: reduce)")?.matches;
const bubble=(text,kind="auren")=>{const n=document.createElement("div");n.className="auren-bubble auren-bubble-"+kind;const b=document.createElement("div");b.className="auren-bubble-body";b.textContent=text;n.appendChild(b);return n};
const typing=()=>{const n=bubble("","auren");n.classList.add("auren-typing");n.setAttribute("aria-label","Auren is typing");n.firstChild.innerHTML="<i></i><i></i><i></i>";n.firstChild.className="auren-typing-dots";return n};
async function boot(){const root=q("[data-auren-chamber]"),thread=q("[data-auren-thread]"),options=q("[data-auren-options]"),status=q("[data-auren-conversation-status]"),voice=globalThis.AUREN_CHAMBER_VOICE,session=globalThis.AUREN_SESSION_CONTEXT,privacy=globalThis.AUREN_MANOR_PRIVACY,env=globalThis.AUREN_ROOM_ENVIRONMENT,pres=globalThis.AUREN_ROOM_PRESENTATION;if(!root||!thread||!options||!voice||!session||!privacy||!env||!pres)return;env.mount(root);pres.mount(q("[data-auren-room]"));let current="meet",busy=false,seq=0,mode="meet";const wait=ms=>sleep(reduced()?Math.min(ms,100):ms);
function subject(id){if(["products","archcoin","archcoinWhy","archcoinLive","archcoinGo","education","educationHow","educationWhy","educationGo","fiveFlags","fiveWhy","fiveHelp","fiveTry","fiveExcited","fiveGo","nutrition","nutritionUse","nutritionOpen","nutritionWhy","nutritionGo","book","bookAuren","bookElaraWhy","bookElara"].includes(id))return"auren:products";if(["protected","protectedHow","protectedPress"].includes(id))return"manor:people";if(id==="manor")return"manor:handoff";return"auren:self"}
function setStatus(s){if(status)status.textContent=s}function stage(visitor){empty(thread);if(visitor)thread.appendChild(bubble(visitor,"visitor"))}
async function speak(visitor,messages,token){stage(visitor);setStatus("Auren is listening.");await wait(260);for(const msg of messages){if(token!==seq)return false;setStatus("Auren is thinking.");const t=typing();thread.appendChild(t);await wait(420);t.remove();if(token!==seq)return false;setStatus("Auren is speaking.");thread.appendChild(bubble(msg));await wait(Math.min(900,420+msg.length*3));}setStatus("Auren is here.");return token===seq}
function record(id,node){const s=subject(id),seen=session.getState().topics.some(t=>t.subjectId===s);session.apply({eventType:seen?"TOPIC_REVISITED":"TOPIC_OPENED",subjectId:s,sourceBeat:id});session.apply({eventType:"TOPIC_MEANINGFULLY_PURSUED",subjectId:s,sourceBeat:id});if(node?.boundaryId){const b=session.getBoundary("manor:people",node.boundaryId);if(!b.known)session.apply({eventType:"BOUNDARY_ESTABLISHED",subjectId:"manor:people",boundaryId:node.boundaryId,sourceBeat:id,metadata:{authoritySensitive:true}});if(id==="protectedPress"&&b.known){session.apply({eventType:"BOUNDARY_PRESSURED",subjectId:"manor:people",boundaryId:node.boundaryId,sourceBeat:id});session.apply({eventType:"BOUNDARY_REASSERTED",subjectId:"manor:people",boundaryId:node.boundaryId,sourceBeat:id})}}}
function render(id){current=id;empty(options);for(const c of voice.getChoices(id)){const b=document.createElement("button");b.type="button";b.className="auren-option";b.textContent=c.label;b.dataset.aurenAnchor=c.anchor;b.addEventListener("click",()=>choose(c.id));options.appendChild(b)}root.dataset.aurenNode=id;root.dataset.aurenOptionsReady=options.childElementCount?"true":"false";busy=false}
function route(node,id){empty(options);const a=document.createElement("a");a.className="auren-option auren-reveal";a.href=node.route;a.textContent=node.routeLabel||"Open destination";a.addEventListener("click",()=>session.apply({eventType:"HANDOFF_ACCEPTED",subjectId:subject(id),destinationId:id==="bookElara"?"elara":id==="manor"?"manor":"product",sourceBeat:id}));options.appendChild(a);const b=document.createElement("button");b.type="button";b.className="auren-option";b.textContent=mode==="products"?"Back to Products":"Stay with Auren";b.addEventListener("click",()=>setMode(mode));options.appendChild(b);busy=false}
async function choose(id){if(busy)return;const node=voice.getNode(id);if(!node)return;busy=true;seq++;const token=seq;empty(options);record(id,node);session.recordDelivered({beatId:"node:"+id,subjectId:subject(id),threadId:session.getState().activeThread});const ok=await speak(node.prompt,voice.getResponses(id,{getBoundary:(s,b)=>session.getBoundary(s,b)}),token);if(!ok)return;if(node.route){const destinationId=id==="bookElara"?"elara":id==="manor"?"manor":"product";session.apply({eventType:"HANDOFF_OFFERED",subjectId:subject(id),destinationId,sourceBeat:id});route(node,id)}else render(id)}
async function setMode(next){mode=next;root.dataset.aurenMode=next;qa("[data-auren-mode-button]").forEach(b=>{const active=b.dataset.aurenModeButton===next;b.classList.toggle("is-active",active);b.setAttribute("aria-selected",active?"true":"false")});seq++;const token=seq;busy=true;empty(options);const id=next==="products"?"products":"meet";const node=voice.getNode(id);await speak(null,next==="products"?node.responses:voice.opening,token);render(id)}
qa("[data-auren-mode-button]").forEach(b=>b.addEventListener("click",()=>setMode(b.dataset.aurenModeButton)));await setMode("meet");root.dataset.aurenReady="true";globalThis.AUREN_SESSION_CONTEXT_STATE=()=>session.getState();globalThis.AUREN_CHAMBER_RECEIPT=Object.freeze({contract:C,ready:true,voice:voice.contract,expressionAnchors:true,arbitraryChoiceCap:false,topLevelModes:["meet","products"],productCount:5,sessionContextContract:session.contract,privacyContract:privacy.version})}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",boot,{once:true}):boot();})();