import fs from 'node:fs';import puppeteer from 'puppeteer-core';
const base=(process.env.PUBLIC_BASE_URL||'http://127.0.0.1:18790').replace(/\/$/,'');const out=process.env.RUNTIME_RESULT_PATH||'/tmp/auren-c1-result.json';const chrome=process.env.CHROME_PATH;if(!chrome)throw new Error('CHROME_PATH_REQUIRED');
const browser=await puppeteer.launch({executablePath:chrome,headless:'new',args:['--no-sandbox','--disable-dev-shm-usage']});const checks=[],failures=[];const add=(id,pass,evidence={})=>{checks.push({id,status:pass?'PASS':'FAIL',evidence});if(!pass)failures.push(id)};
const labels=p=>p.evaluate(()=>[...document.querySelectorAll('[data-auren-options] .auren-option')].map(x=>x.textContent.trim()));
const stage=p=>p.evaluate(()=>({text:document.querySelector('[data-auren-thread]')?.textContent||'',children:document.querySelector('[data-auren-thread]')?.children.length||0,height:Math.round(document.querySelector('.auren-thread-screen')?.getBoundingClientRect().height||0),pageHeight:document.documentElement.scrollHeight,node:document.querySelector('[data-auren-chamber]')?.getAttribute('data-auren-node')}));
async function click(p,label){await p.waitForFunction(x=>[...document.querySelectorAll('[data-auren-options] .auren-option')].some(b=>b.textContent.trim()===x),{timeout:10000},label);await p.evaluate(x=>[...document.querySelectorAll('[data-auren-options] .auren-option')].find(b=>b.textContent.trim()===x)?.click(),label);await p.waitForFunction(()=>document.querySelector('[data-auren-chamber]')?.getAttribute('data-auren-options-ready')==='true',{timeout:10000});}
try{const p=await browser.newPage();await p.setViewport({width:390,height:844,deviceScaleFactor:1,isMobile:true,hasTouch:true});const errors=[];p.on('pageerror',e=>errors.push(String(e)));const res=await p.goto(base+'/products/auren/',{waitUntil:'networkidle0',timeout:30000});await p.waitForFunction(()=>document.querySelector('[data-auren-chamber]')?.getAttribute('data-auren-ready')==='true',{timeout:10000});
let o=await labels(p);add('C1_ROUTE_READY',res?.status()===200,{status:res?.status()});add('C1_OPENING_EXACT_TWO',JSON.stringify(o)===JSON.stringify(['Products','About Auren']),{options:o});
const prohibited=['What makes a sanctuary?','What does custody mean to you?','What does custody mean here?','Protection or control?','Why “Sanctuary Builder”?','Custody · protection versus control','governing tension','central question'];const openingText=await p.evaluate(()=>document.body.innerText);add('C1_PROHIBITED_DEFAULT_LANGUAGE_ABSENT',prohibited.every(x=>!openingText.includes(x)),{found:prohibited.filter(x=>openingText.includes(x))});
const start=await stage(p);await click(p,'Products');o=await labels(p);add('C1_ROOT_REPLACED_PRODUCTS',!o.includes('About Auren')&&JSON.stringify(o)===JSON.stringify(['ARCHCOIN','Five Flags','More']),{options:o});await click(p,'ARCHCOIN');await click(p,"What's live now?");const prod=await stage(p);o=await labels(p);add('C1_PRODUCT_DEEP_PROGRESS',prod.text.includes('ARCC')&&prod.text.includes('ARCR')&&o.includes('Show me ARCHCOIN'),{options:o,text:prod.text});add('C1_ACTIVE_STAGE_BOUNDED_PRODUCTS',prod.children<=2&&prod.height<260,{children:prod.children,height:prod.height});
await p.reload({waitUntil:'networkidle0'});await p.waitForFunction(()=>document.querySelector('[data-auren-chamber]')?.getAttribute('data-auren-options-ready')==='true',{timeout:10000});await click(p,'About Auren');o=await labels(p);add('C1_ROOT_REPLACED_ABOUT',!o.includes('Products')&&o.includes('Who are you?')&&o.includes("What's Mirrorland?"),{options:o});await click(p,'Who are you?');await click(p,'What do you actually do?');const chr=await stage(p);o=await labels(p);add('C1_CHARACTER_DEEP_PROGRESS',chr.text.includes('make places safer')&&o.includes('How does this room fit?'),{options:o,text:chr.text});add('C1_ACTIVE_STAGE_BOUNDED_CHARACTER',chr.children<=2&&chr.height<260,{children:chr.children,height:chr.height});
const max=await p.evaluate(()=>document.querySelectorAll('[data-auren-options] .auren-option').length);add('C1_MAX_THREE_CHOICES',max<=3,{count:max});add('C1_NO_PAGE_ERRORS',errors.length===0,{errors});const end=await stage(p);add('C1_PAGE_HEIGHT_NOT_TURN_PROPORTIONAL',end.pageHeight<=start.pageHeight+220,{start:start.pageHeight,end:end.pageHeight});
}finally{await browser.close()}const result={schema:'AUREN_C1_BEHAVIORAL_QUALIFICATION_RECEIPT_v1',status:failures.length?'FAIL':'PASS',checks,failures};fs.writeFileSync(out,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));if(failures.length)process.exitCode=1;
