import fs from 'node:fs';import puppeteer from 'puppeteer-core';
const base=(process.env.PUBLIC_BASE_URL||'http://127.0.0.1:18826').replace(/\/$/,'');const out=process.env.RUNTIME_RESULT_PATH||'/tmp/auren-successor-result.json';const chrome=process.env.CHROME_PATH;if(!chrome)throw new Error('CHROME_PATH required');
const browser=await puppeteer.launch({executablePath:chrome,headless:'new',args:['--no-sandbox','--disable-dev-shm-usage']});const checks=[],failures=[];const add=(id,pass,evidence={})=>{checks.push({id,status:pass?'PASS':'FAIL',evidence});if(!pass)failures.push(id)};
const ready=p=>p.waitForFunction(()=>document.querySelector('[data-auren-chamber]')?.getAttribute('data-auren-options-ready')==='true',{timeout:20000});
const labels=p=>p.evaluate(()=>[...document.querySelectorAll('[data-auren-options] button')].map(x=>x.textContent.trim()));
const text=p=>p.evaluate(()=>document.querySelector('[data-auren-thread]')?.textContent.trim()||'');
const click=async(p,t)=>{await ready(p);const before=await p.evaluate(()=>({node:document.querySelector('[data-auren-chamber]')?.dataset.aurenNode||null,handoff:document.querySelector('[data-auren-chamber]')?.dataset.aurenHandoff||'none'}));const ok=await p.evaluate(x=>{const e=[...document.querySelectorAll('[data-auren-options] button')].find(y=>y.textContent.trim()===x);if(!e)return false;e.click();return true},t);add('CLICK_'+t,ok,{before});if(!ok)return false;await p.waitForFunction(prev=>{const r=document.querySelector('[data-auren-chamber]');if(r?.getAttribute('data-auren-options-ready')!=='true')return false;const node=r?.dataset.aurenNode||null,handoff=r?.dataset.aurenHandoff||'none';return node!==prev.node||handoff!==prev.handoff},{timeout:20000},before);return true};
const mode=async(p,t)=>{const ok=await p.evaluate(x=>{const b=document.querySelector('[data-auren-mode-button="'+x+'"]');if(!b)return false;b.click();return true},t);add('MODE_'+t,ok);if(ok)await ready(p);return ok};
const open=async(viewport={width:390,height:844,isMobile:true,hasTouch:true})=>{const p=await browser.newPage();await p.setViewport(viewport);const errors=[],consoleErrors=[],failed=[];p.on('pageerror',e=>errors.push(String(e)));p.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});p.on('requestfailed',r=>failed.push({url:r.url(),error:r.failure()?.errorText||null}));const r=await p.goto(base+'/products/auren/',{waitUntil:'networkidle0',timeout:60000});try{await p.waitForFunction(()=>document.querySelector('[data-auren-chamber]')?.getAttribute('data-auren-ready')==='true',{timeout:6000});await ready(p)}catch(e){const startup=await p.evaluate(()=>({documentReadyState:document.readyState,aurenReady:document.querySelector('[data-auren-chamber]')?.getAttribute('data-auren-ready')||null,optionsReady:document.querySelector('[data-auren-chamber]')?.getAttribute('data-auren-options-ready')||null,globals:{voice:Boolean(globalThis.AUREN_CHAMBER_VOICE),session:Boolean(globalThis.AUREN_SESSION_CONTEXT),privacy:Boolean(globalThis.AUREN_MANOR_PRIVACY),environment:Boolean(globalThis.AUREN_ROOM_ENVIRONMENT),presentation:Boolean(globalThis.AUREN_ROOM_PRESENTATION),geometry:Boolean(globalThis.AUREN_ROOM_GEOMETRY)},scripts:[...document.scripts].map(s=>s.src).filter(Boolean)}));add('STARTUP_READY',false,{error:String(e),startup,errors,consoleErrors,failed});fs.writeFileSync(out,JSON.stringify({contract:'AUREN_FULL_VIEWPORT_EARLY_ENCOUNTER_ACCEPTANCE_V3',status:'FAIL',checks,failures,startupDiagnostic:{startup,errors,consoleErrors,failed}},null,2));await p.close();throw e}return{p,r,errors,consoleErrors,failed}};
try{
 let {p,r,errors}=await open();add('ROUTE_200',r?.status()===200,{status:r?.status()});let o=await labels(p);add('MEET_DIRECTED',o.includes('Thirteen and running this place?')&&o.includes('So what are you actually responsible for?')&&o.includes('The Manor is yours?'),{o});await click(p,'The Manor is yours?');let b=await text(p);add('PARENT_BOUNDED',b.includes('disappeared while they were traveling')&&b.includes("don't know exactly what happened")&&b.includes('what their absence left in my hands')&&b.includes('people depending on it'),{b});o=await labels(p);add('PARENT_ROUTES_TO_MEANING',o.includes("So that's when the Manor became your responsibility?")&&o.includes('What did you have to take on?')&&o.includes('Show me what that means here.'),{o});add('NO_ERRORS_MEET',errors.length===0,{errors});await p.close();

 ({p,errors}=await open());await mode(p,'products');o=await labels(p);add('FIVE_PRODUCTS_DIRECT',JSON.stringify(o)===JSON.stringify(['ARCHCOIN','Education','Five Flags','Nutrition','Book / Nine Summits']),{o});await click(p,'Five Flags');await click(p,'Can I try it?');b=await text(p);add('FIVE_FLAGS_DEMO',b.includes("Not yet. There'll be a demo soon.")&&b.includes("Personally, I'm excited about it."),{b});o=await labels(p);add('FIVE_FLAGS_WHY',o.includes('Why this one?'),{o});await click(p,'Why this one?');b=await text(p);add('FIVE_FLAGS_SHARED_THINKING',b.includes("everybody else's thinking")&&b.includes("Nobody gets to replace the rest of the group"),{b});add('NO_ERRORS_FIVE_FLAGS',errors.length===0,{errors});await p.close();

 ({p,errors}=await open());await mode(p,'products');await click(p,'Book / Nine Summits');o=await labels(p);add('BOOK_NO_NAKED_HANDOFF',!o.includes('Take me to Elara.')&&o.includes('Why does that matter to you?')&&o.includes('Where does Elara fit into it?'),{o});await click(p,'Where does Elara fit into it?');o=await labels(p);add('ELARA_MEANING_FIRST',o.includes('Then Elara is where this should go next.'),{o});await click(p,'Then Elara is where this should go next.');const href=await p.$eval('.auren-route-enter',a=>a.getAttribute('href'));add('ELARA_HANDOFF',href==='/elara/',{href});add('NO_ERRORS_BOOK',errors.length===0,{errors});await p.close();

 ({p,errors}=await open());await click(p,'So what are you actually responsible for?');await click(p,'Who is the Manor meant to protect?');o=await labels(p);add('PRIVACY_BOUNDARY_OPTIONS',o.includes('What does the Manor owe them?')&&o.includes("You won't tell me who they are?"),{o});await click(p,"You won't tell me who they are?");b=await text(p);add('PRIVACY_IN_PERSONA',b.includes("Their stories stay theirs")&&!/name is|named /i.test(b),{b});add('NO_ERRORS_PRIVACY',errors.length===0,{errors});await p.close();

 ({p,errors}=await open());await click(p,'Thirteen and running this place?');await mode(p,'products');await mode(p,'meet');b=await text(p);add('RETURN_NO_OPENING_REPLAY',b.includes("instead of starting over")&&!b.includes("apparently those three facts"),{b});add('FULL_VIEWPORT_ENGAGED',await p.evaluate(()=>{const r=document.querySelector('[data-auren-chamber]');return r?.dataset.aurenEncounterState==='engaged'&&getComputedStyle(r).position==='fixed'&&Math.abs(r.getBoundingClientRect().height-innerHeight)<3}),{});add('NO_INTERNAL_THREAD_SCROLL',await p.evaluate(()=>{const e=document.querySelector('.auren-thread-screen');return e&&e.scrollHeight<=e.clientHeight+2}),{});add('FINAL_NO_ERRORS',errors.length===0,{errors});await p.close();
}finally{await browser.close()}
const result={contract:'AUREN_FULL_VIEWPORT_EARLY_ENCOUNTER_ACCEPTANCE_V3',status:failures.length?'FAIL':'PASS',checks,failures};fs.writeFileSync(out,JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));if(failures.length)process.exitCode=1;
