import fs from 'node:fs';import puppeteer from 'puppeteer-core';
const base=(process.env.PUBLIC_BASE_URL||'http://127.0.0.1:18826').replace(/\/$/,'');const out=process.env.RUNTIME_RESULT_PATH||'/tmp/auren-successor-result.json';const chrome=process.env.CHROME_PATH;if(!chrome)throw new Error('CHROME_PATH required');
const browser=await puppeteer.launch({executablePath:chrome,headless:'new',args:['--no-sandbox','--disable-dev-shm-usage']});const checks=[],failures=[];const add=(id,pass,evidence={})=>{checks.push({id,status:pass?'PASS':'FAIL',evidence});if(!pass)failures.push(id)};
const ready=p=>p.waitForFunction(()=>document.querySelector('[data-auren-chamber]')?.getAttribute('data-auren-options-ready')==='true',{timeout:20000});const labels=p=>p.evaluate(()=>[...document.querySelectorAll('[data-auren-options] .auren-option')].map(x=>x.textContent.trim()));const bubbles=p=>p.evaluate(()=>[...document.querySelectorAll('[data-auren-thread] .auren-bubble-body')].map(x=>x.textContent.trim()));
const click=async(p,t)=>{await ready(p);const before=await labels(p);const ok=await p.evaluate(x=>{const e=[...document.querySelectorAll('[data-auren-options] .auren-option')].find(y=>y.textContent.trim()===x);if(!e)return false;e.click();return true},t);add('CLICK_'+t,ok,{before});if(!ok)return false;await ready(p);return true};
const mode=async(p,t)=>{const ok=await p.evaluate(x=>{const b=document.querySelector('[data-auren-mode-button="'+x+'"]');if(!b)return false;b.click();return true},t);add('MODE_'+t,ok,{});if(ok)await ready(p);return ok};
const open=async()=>{const p=await browser.newPage();await p.setViewport({width:390,height:844,isMobile:true,hasTouch:true});const errors=[];p.on('pageerror',e=>errors.push(String(e)));const r=await p.goto(base+'/products/auren/',{waitUntil:'networkidle0',timeout:60000});await p.waitForFunction(()=>document.querySelector('[data-auren-chamber]')?.getAttribute('data-auren-ready')==='true',{timeout:20000});await ready(p);return{p,r,errors}};
try{
 let {p,r,errors}=await open();add('ROUTE_200',r?.status()===200,{status:r?.status()});add('TOP_LEVEL_MODES',await p.evaluate(()=>[...document.querySelectorAll('[data-auren-mode-button]')].map(x=>x.textContent.trim()).join('|')==='Meet Auren|Products'),{});let o=await labels(p);add('MEET_ANCHORS',o.includes("You're thirteen?")&&o.includes('The Manor is yours?')&&o.includes('People give you a hard time about it?'),{options:o});add('ANCHOR_METADATA',await p.evaluate(()=>[...document.querySelectorAll('[data-auren-options] .auren-option')].every(x=>Boolean(x.dataset.aurenAnchor))),{});const receipt=await p.evaluate(()=>globalThis.AUREN_CHAMBER_RECEIPT);add('NO_ARBITRARY_CHOICE_CAP',receipt?.arbitraryChoiceCap===false,{receipt});add('FIVE_PRODUCT_RECEIPT',receipt?.productCount===5,{receipt});await click(p,'The Manor is yours?');let b=await bubbles(p);add('PARENT_HOOK',b.some(x=>x.includes("while they're gone")),{bubbles:b});await click(p,'Who are “they”?');b=await bubbles(p);add('PARENTS_BOUNDED',b.some(x=>x==='My parents.'),{bubbles:b});await click(p,'What happened to them?');b=await bubbles(p);add('PARENT_CEILING',b.some(x=>x.includes('disappeared while they were traveling'))&&b.some(x=>x.includes("don't know exactly what happened"))&&!b.some(x=>/international incident|public account|evidence|theor/i.test(x)),{bubbles:b});add('NO_ERRORS_MEET',errors.length===0,{errors});await p.close();
 ({p,errors}=await open());await mode(p,'products');o=await labels(p);add('FIVE_PRODUCTS_DIRECT',JSON.stringify(o)===JSON.stringify(['ARCHCOIN','Education','Five Flags','Nutrition','Book / Nine Summits']),{options:o});add('NO_MORE_PRODUCTS',!o.some(x=>/more products|education · nutrition/i.test(x)),{options:o});await click(p,'Five Flags');o=await labels(p);add('FIVE_FLAGS_ANCHORS',o.includes('Why only five?')&&o.includes("So they can help, but they can't tell you?")&&o.includes('Can I try it?'),{options:o});await click(p,'Can I try it?');b=await bubbles(p);add('FIVE_FLAGS_DEMO_TRUTH',b.some(x=>x.includes("Not yet. There'll be a demo soon."))&&b.some(x=>x.includes("I'm actually excited about that one.")),{bubbles:b});o=await labels(p);add('FIVE_FLAGS_PERSONAL_ANCHOR',o.includes('Why that one?'),{options:o});await click(p,'Why that one?');b=await bubbles(p);add('FIVE_FLAGS_AUREN_REVEAL',b.some(x=>x.includes("one person do all the thinking")),{bubbles:b});add('NO_ERRORS_FIVE_FLAGS',errors.length===0,{errors});await p.close();
 ({p,errors}=await open());await mode(p,'products');await click(p,'Book / Nine Summits');o=await labels(p);add('BOOK_AUREN_ANCHOR',o.includes('What makes the Book different to you?')&&o.includes('Why Elara?')&&o.includes('Take me to Elara.'),{options:o});await click(p,'Take me to Elara.');const href=await p.$eval('a.auren-option',a=>a.getAttribute('href'));add('BOOK_ELARA_BOUNDARY',href==='/elara/',{href});add('NO_ERRORS_BOOK',errors.length===0,{errors});await p.close();
 ({p,errors}=await open());await click(p,'The Manor is yours?');await click(p,'So you inherited all of this?');await click(p,'What responsibility?');await click(p,'Who does it need to protect?');let st=await p.evaluate(()=>globalThis.AUREN_SESSION_CONTEXT_STATE());let bd=st.boundaries.find(x=>x.boundaryId==='protected-resident-identities');add('PRIVACY_BOUNDARY_ESTABLISHED',bd?.known===true,{boundary:bd});await click(p,'Who are they?');st=await p.evaluate(()=>globalThis.AUREN_SESSION_CONTEXT_STATE());bd=st.boundaries.find(x=>x.boundaryId==='protected-resident-identities');add('PRIVACY_PRESSURE_LOCAL',bd?.pressureCount>=1&&bd?.interactionCaution===true,{boundary:bd});b=await bubbles(p);add('PROTECTED_IDENTITIES_NOT_DISCLOSED',!b.some(x=>/name is|named |their names are/i.test(x))&&b.some(x=>x.includes('names and private stories are theirs')),{bubbles:b});add('NO_ERRORS_PRIVACY',errors.length===0,{errors});await p.close();
 ({p,errors}=await open());await mode(p,'products');await click(p,'Education');b=await bubbles(p);add('EDUCATION_PLAIN_LANGUAGE',b.some(x=>x.includes('what you can actually do'))&&!b.some(x=>/demonstrated performance|architecture|benchmark evidence/i.test(x)),{bubbles:b});await mode(p,'products');await click(p,'Nutrition');b=await bubbles(p);add('NUTRITION_PROTOTYPE_TRUTH',b.some(x=>x.includes("still being worked on")),{bubbles:b});add('NO_ERRORS_PRODUCTS',errors.length===0,{errors});await p.close();
 ({p,errors}=await open());add('ARCHETYPE_DIAGNOSTICS_INVISIBLE',await p.evaluate(()=>!/Strategist|Builder|Mitigator|Auditor|archetype|diagnostic/i.test((document.querySelector('[data-auren-thread]')?.textContent||'')+' '+(document.querySelector('[data-auren-options]')?.textContent||''))),{});await p.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}]);add('REDUCED_MOTION_MEDIA',await p.evaluate(()=>matchMedia('(prefers-reduced-motion: reduce)').matches),{});add('FINAL_NO_ERRORS',errors.length===0,{errors});await p.close();
}finally{await browser.close()}
const result={contract:'AUREN_EARLY_ENCOUNTER_EXACT_HEAD_QUALIFICATION_V2',status:failures.length?'FAIL':'PASS',checks,failures};fs.writeFileSync(out,JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));if(failures.length)process.exitCode=1;