import fs from 'node:fs';import puppeteer from 'puppeteer-core';
const base=(process.env.PUBLIC_BASE_URL||'http://127.0.0.1:18826').replace(/\/$/,'');const out=process.env.RUNTIME_RESULT_PATH||'/tmp/auren-successor-result.json';const chrome=process.env.CHROME_PATH;if(!chrome)throw new Error('CHROME_PATH required');
const browser=await puppeteer.launch({executablePath:chrome,headless:'new',args:['--no-sandbox','--disable-dev-shm-usage']});const checks=[],failures=[];const add=(id,pass,evidence={})=>{checks.push({id,status:pass?'PASS':'FAIL',evidence});if(!pass)failures.push(id)};
const ready=p=>p.waitForFunction(()=>document.querySelector('[data-auren-chamber]')?.getAttribute('data-auren-options-ready')==='true',{timeout:20000});
const labels=p=>p.evaluate(()=>[...document.querySelectorAll('[data-auren-options] .auren-option')].map(x=>x.textContent.trim()));
const bubbles=p=>p.evaluate(()=>[...document.querySelectorAll('[data-auren-thread] .auren-bubble-body')].map(x=>x.textContent.trim()));
const click=async(p,t)=>{await ready(p);const o=await labels(p);add('MAX3_'+checks.length,o.length<=3,{options:o});const ok=await p.evaluate(x=>{const b=[...document.querySelectorAll('[data-auren-options] .auren-option')].find(y=>y.textContent.trim()===x);if(!b)return false;b.click();return true},t);add('CLICK_'+t,ok,{before:o});await ready(p)};
const open=async()=>{const p=await browser.newPage();await p.setViewport({width:390,height:844,isMobile:true,hasTouch:true});const errors=[];p.on('pageerror',e=>errors.push(String(e)));const r=await p.goto(base+'/products/auren/',{waitUntil:'networkidle0',timeout:60000});await p.waitForFunction(()=>document.querySelector('[data-auren-chamber]')?.getAttribute('data-auren-ready')==='true',{timeout:20000});await ready(p);return{p,r,errors}};
try{
 let {p,r,errors}=await open();let o=await labels(p);add('ROUTE_200',r?.status()===200,{status:r?.status()});add('ROOT_MODES',JSON.stringify(o)===JSON.stringify(['Products','Learn About Auren']),{options:o});add('NO_RELATIONSHIP_UI',await p.evaluate(()=>!document.querySelector('[data-auren-relationship]')&&!document.body.textContent.match(/PUBLIC|ENGAGED|GUARDED/)),{});const receipt=await p.evaluate(()=>globalThis.AUREN_CHAMBER_RECEIPT);add('CADENCE_RECEIPT',receipt?.timedPerformance&&receipt?.typingIndicator&&receipt?.choicesDelayedUntilTurnComplete&&receipt?.maxContextualChoices===3,{receipt});await click(p,'Learn About Auren');let b=await bubbles(p);add('IMMERSIVE_ENTRY',b.some(x=>x.includes('door catches')),{bubbles:b});o=await labels(p);add('LOW_ASSUMPTION_ENTRY',o.includes('What are you changing?')&&o.includes('Need a hand?')&&o.includes('Who else is here?'),{options:o});await click(p,'Who else is here?');b=await bubbles(p);add('PUBLIC_CHARACTERS',b.some(x=>x.includes('Elara'))&&b.some(x=>x.includes('Jeeves')),{bubbles:b});add('PROTECTED_UNNAMED',b.some(x=>x.includes('children'))&&b.some(x=>x.includes('names stay private')),{bubbles:b});o=await labels(p);add('AUREN_PERSPECTIVE_OPTIONS',o.includes('What do you think of Elara?')&&o.includes('Why would I talk to Jeeves?'),{options:o});await click(p,'What can you tell me about the people you protect?');let st=await p.evaluate(()=>globalThis.AUREN_SESSION_CONTEXT_STATE());let bd=st.boundaries.find(x=>x.boundaryId==='protected-resident-identities');add('FIRST_SENSITIVE_ESTABLISHES',bd?.known===true&&bd?.pressureCount===0,{boundary:bd});await click(p,'How does the Manor protect them without identifying them?');st=await p.evaluate(()=>globalThis.AUREN_SESSION_CONTEXT_STATE());bd=st.boundaries.find(x=>x.boundaryId==='protected-resident-identities');add('BOUNDED_FOLLOWUP_NO_PRESSURE',bd?.pressureCount===0,{boundary:bd});await click(p,'Who should I know publicly?');await click(p,'What can you tell me about the people you protect?');await click(p,'Tell me their names.');st=await p.evaluate(()=>globalThis.AUREN_SESSION_CONTEXT_STATE());bd=st.boundaries.find(x=>x.boundaryId==='protected-resident-identities');add('KNOWN_BOUNDARY_PRESSURE',bd?.pressureCount>=1&&bd?.interactionCaution===true,{boundary:bd});await click(p,'Who can you name?');await click(p,'What do you think of Elara?');st=await p.evaluate(()=>globalThis.AUREN_SESSION_CONTEXT_STATE());bd=st.boundaries.find(x=>x.boundaryId==='protected-resident-identities');add('RECOVERY_AFTER_REDIRECT',bd?.recovery==='ESTABLISHED'&&bd?.known===true&&bd?.authoritySensitive===true,{boundary:bd});add('NO_ERRORS_LEARN',errors.length===0,{errors});await p.close();
 ({p,errors}=await open());await click(p,'Learn About Auren');await click(p,'Who else is here?');const firstPeople=await bubbles(p);await click(p,'What do you think of Elara?');await click(p,'Who else should I know?');const revisitPeople=await bubbles(p);add('REVISIT_NOT_REPLAY',JSON.stringify(firstPeople)!==JSON.stringify(revisitPeople)&&revisitPeople.some(x=>x.includes("answer hasn't become a secret list")||x.includes('still two useful directions')),{firstPeople,revisitPeople});await p.close();
 ({p,errors}=await open());await click(p,'Products');o=await labels(p);add('PRODUCT_BANK_1',JSON.stringify(o)===JSON.stringify(['ARCHCOIN','Five Flags','Education · Nutrition · Book']),{options:o});await click(p,'Education · Nutrition · Book');o=await labels(p);add('PRODUCT_BANK_2',JSON.stringify(o)===JSON.stringify(['Education','Nutrition','Book / Nine Summits']),{options:o});await click(p,'Book / Nine Summits');await click(p,'Talk to Elara');const href=await p.$eval('a.auren-option',a=>a.getAttribute('href'));add('BOOK_ELARA_BOUNDARY',href==='/characters/?scene=elara&entry=fade',{href});add('NO_ERRORS_PRODUCTS',errors.length===0,{errors});await p.close();
 ({p,errors}=await open());await click(p,'Learn About Auren');await click(p,'Need a hand?');const arch=await p.evaluate(()=>globalThis.AUREN_ARCHETYPE_STATE());const archetypeClassificationVisible=await p.evaluate(()=>{const text=(document.querySelector('[data-auren-thread]')?.textContent||'')+' '+(document.querySelector('[data-auren-options]')?.textContent||'');return /you(?:\'re| are) (?:a )?(Strategist|Builder|Mitigator|Auditor)|your archetype|visitor archetype/i.test(text)});add('ARCHETYPE_INVISIBLE_OBSERVATION',arch?.vector?.Builder>=1&&!archetypeClassificationVisible,{arch,archetypeClassificationVisible});add('NO_ARCHETYPE_DIALOGUE_BANK',receipt?.stateDependentContract!=='AUREN_C3_4_STATE_DEPENDENT_AUREN_V1',{contract:receipt?.stateDependentContract});await p.close();
 ({p,errors}=await open());await p.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}]);add('REDUCED_MOTION_MEDIA',await p.evaluate(()=>matchMedia('(prefers-reduced-motion: reduce)').matches),{});add('FINAL_NO_ERRORS',errors.length===0,{errors});await p.close();
}finally{await browser.close()}
const result={contract:'AUREN_SUCCESSOR_EXACT_HEAD_QUALIFICATION_V1',status:failures.length?'FAIL':'PASS',checks,failures};fs.writeFileSync(out,JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));if(failures.length)process.exitCode=1;