import fs from 'node:fs';import puppeteer from 'puppeteer-core';
const base=(process.env.PUBLIC_BASE_URL||'http://127.0.0.1:18791').replace(/\/$/,'');const out=process.env.RUNTIME_RESULT_PATH||'/tmp/auren-c2-result.json';const chrome=process.env.CHROME_PATH;if(!chrome)throw new Error('CHROME_PATH_REQUIRED');
const browser=await puppeteer.launch({executablePath:chrome,headless:'new',args:['--no-sandbox','--disable-dev-shm-usage']});const checks=[],failures=[];const add=(id,pass,evidence={})=>{checks.push({id,status:pass?'PASS':'FAIL',evidence});if(!pass)failures.push(id)};
const labels=p=>p.evaluate(()=>[...document.querySelectorAll('[data-auren-options] .auren-option')].map(x=>x.textContent.trim()));
async function clickAndObserve(p,label){await p.waitForFunction(x=>[...document.querySelectorAll('.auren-option')].some(b=>b.textContent.trim()===x),{},label);const before=Date.now();await p.evaluate(x=>[...document.querySelectorAll('.auren-option')].find(b=>b.textContent.trim()===x)?.click(),label);await p.waitForFunction(()=>document.querySelector('[data-auren-chamber]')?.getAttribute('data-auren-performance')==='TYPING');const typingAt=Date.now();const choicesDuring=await labels(p);await p.waitForFunction(()=>document.querySelector('[data-auren-chamber]')?.getAttribute('data-auren-performance')==='CHOICES',{timeout:15000});return{before,typingAt,doneAt:Date.now(),choicesDuring,final:await labels(p),text:await p.evaluate(()=>document.querySelector('[data-auren-thread]')?.innerText||''),bubbles:await p.evaluate(()=>document.querySelectorAll('[data-auren-thread] .auren-bubble-auren:not(.auren-typing)').length)}}
try{const p=await browser.newPage();await p.setViewport({width:390,height:844,isMobile:true,hasTouch:true});const errors=[];p.on('pageerror',e=>errors.push(String(e)));const res=await p.goto(base+'/products/auren/',{waitUntil:'networkidle0',timeout:30000});await p.waitForFunction(()=>document.querySelector('[data-auren-chamber]')?.getAttribute('data-auren-options-ready')==='true',{timeout:15000});let o=await labels(p);add('C2_ROUTE_READY',res?.status()===200,{status:res?.status()});add('C2_C1_ROOT_PRESERVED',JSON.stringify(o)===JSON.stringify(['Products','About Auren']),{options:o});const body=await p.evaluate(()=>document.body.innerText);const leaked=['I\'m the Sanctuary Builder','Custody · protection versus control','governing tension','central question','Core Class:','Primary Trait:'];add('C2_METADATA_FIREWALL',leaked.every(x=>!body.includes(x)),{found:leaked.filter(x=>body.includes(x))});
let obs=await clickAndObserve(p,'Products');add('C2_TYPING_NONZERO_PRODUCTS',obs.typingAt>obs.before,{delayMs:obs.typingAt-obs.before});add('C2_CHOICES_HIDDEN_DURING_TURN',obs.choicesDuring.length===0,{choicesDuring:obs.choicesDuring});await clickAndObserve(p,'ARCHCOIN');obs=await clickAndObserve(p,'How do the four fit?');add('C2_PRODUCT_MULTI_BEAT',obs.bubbles>=3&&obs.text.includes('Same family. Different jobs.'),{bubbles:obs.bubbles,text:obs.text});add('C2_PRODUCT_CHOICES_AFTER_TURN',obs.final.length>0,{options:obs.final,durationMs:obs.doneAt-obs.before});
await p.reload({waitUntil:'networkidle0'});await p.waitForFunction(()=>document.querySelector('[data-auren-chamber]')?.getAttribute('data-auren-options-ready')==='true',{timeout:15000});await clickAndObserve(p,'About Auren');obs=await clickAndObserve(p,'What does that mean?');add('C2_PERSONALITY_CHARACTER_BEAT',obs.text.includes('Mostly?')&&obs.text.includes('harder than it sounds')&&!obs.text.includes('Sanctuary Builder'),{text:obs.text,bubbles:obs.bubbles});add('C2_CHARACTER_MULTI_BEAT',obs.bubbles>=2,{bubbles:obs.bubbles});const receipt=await p.evaluate(()=>globalThis.AUREN_CHAMBER_RECEIPT);add('C2_RUNTIME_RECEIPT',receipt?.timedPerformance===true&&receipt?.typingIndicator===true&&receipt?.choicesDelayedUntilTurnComplete===true,{receipt});add('C2_NO_PAGE_ERRORS',errors.length===0,{errors});
}finally{await browser.close()}const result={schema:'AUREN_C2_PERSONALITY_PERFORMANCE_QUALIFICATION_RECEIPT_v1',status:failures.length?'FAIL':'PASS',checks,failures};fs.writeFileSync(out,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));if(failures.length)process.exitCode=1;
