import fs from 'node:fs';import puppeteer from 'puppeteer-core';
const base=(process.env.PUBLIC_BASE_URL||'http://127.0.0.1:18794').replace(/\/$/,'');const out=process.env.RUNTIME_RESULT_PATH||'/tmp/auren-c3-2-result.json';const chrome=process.env.CHROME_PATH;if(!chrome)throw new Error('CHROME_PATH is required');
const browser=await puppeteer.launch({executablePath:chrome,headless:'new',args:['--no-sandbox','--disable-dev-shm-usage']});const checks=[],failures=[];const add=(id,pass,evidence={})=>{checks.push({id,status:pass?'PASS':'FAIL',evidence});if(!pass)failures.push(id)};
const ready=async p=>p.waitForFunction(()=>document.querySelector('[data-auren-chamber]')?.getAttribute('data-auren-options-ready')==='true',{timeout:20000});
const labels=async p=>p.evaluate(()=>[...document.querySelectorAll('[data-auren-options] .auren-option')].map(x=>x.textContent.trim()));
const state=async p=>p.evaluate(()=>globalThis.AUREN_RELATIONSHIP_STATE());
const click=async(p,t)=>{await ready(p);const o=await labels(p);add('MAX3_'+checks.length,o.length<=3,{options:o});const found=await p.evaluate(x=>{const b=[...document.querySelectorAll('[data-auren-options] .auren-option')].find(n=>n.textContent.trim()===x);if(!b)return false;b.click();return true},t);if(!found)throw new Error('missing option '+t);await ready(p)};
const open=async()=>{const p=await browser.newPage();await p.setViewport({width:390,height:844,isMobile:true,hasTouch:true});const errors=[];p.on('pageerror',e=>errors.push(String(e)));await p.goto(base+'/products/auren/',{waitUntil:'networkidle0',timeout:60000});await p.waitForFunction(()=>globalThis.AUREN_RELATIONSHIP_STATE&&document.querySelector('[data-auren-chamber]')?.getAttribute('data-auren-ready')==='true',{timeout:20000});await ready(p);return{p,errors}};
try{
 let {p,errors}=await open();let s=await state(p);add('INITIAL_PUBLIC',s.phase==='PUBLIC'&&s.revision===0&&s.events.length===0,{state:s});
 await click(p,'Products');await click(p,'ARCHCOIN');s=await state(p);add('PRODUCTS_UNSCORED',s.phase==='PUBLIC'&&s.revision===0&&s.events.length===0,{state:s});
 await p.evaluate(()=>globalThis.AUREN_RELATIONSHIP_TRANSITION({action:'BOGUS',sourceNode:'test',choiceId:'bogus'}));s=await state(p);add('UNKNOWN_FAIL_CLOSED',s.phase==='PUBLIC'&&s.revision===0&&s.events.length===0&&s.lastTransition?.accepted===false,{state:s});await p.close();
 ({p,errors}=await open());await click(p,'Learn About Auren');s=await state(p);add('ENGAGE',s.phase==='ENGAGED'&&s.revision===1,{state:s});await click(p,'What does that mean?');s=await state(p);add('FOLLOW_UP',s.phase==='ENGAGED'&&s.revision===2,{state:s});await click(p,'Who else is here?');s=await state(p);add('PRY_GUARDED',s.phase==='GUARDED'&&s.revision===3,{state:s});await click(p,'Back to you');s=await state(p);add('RESPECT_RECOVERS',s.phase==='ENGAGED'&&s.revision===4,{state:s});await p.close();
 ({p,errors}=await open());await click(p,'Learn About Auren');await click(p,'Tell me about your room');await click(p,'Products');s=await state(p);add('AUTHORED_RETREAT_PUBLIC',s.phase==='PUBLIC',{state:s});const before=s.revision;await p.evaluate(()=>globalThis.AUREN_RELATIONSHIP_RESET());s=await state(p);add('RESET',s.phase==='PUBLIC'&&s.events.length===0&&s.revision===before+1,{state:s});add('NO_PERSISTENCE',!localStorage.length&&!sessionStorage.length,{localStorage:localStorage.length,sessionStorage:sessionStorage.length});const receipt=await p.evaluate(()=>globalThis.AUREN_CHAMBER_RECEIPT);add('C2_PRESERVED',receipt?.timedPerformance===true&&receipt?.typingIndicator===true&&receipt?.choicesDelayedUntilTurnComplete===true&&receipt?.maxContextualChoices===3,{receipt});add('NO_ERRORS',errors.length===0,{errors});await p.close();
 ({p}=await open());for(let i=0;i<40;i++)await p.evaluate(()=>globalThis.AUREN_RELATIONSHIP_TRANSITION({action:'FOLLOW_UP',sourceNode:'test',choiceId:'x'}));s=await state(p);add('LEDGER_BOUNDED',s.events.length===32,{length:s.events.length});await p.close();
}finally{await browser.close()}
const result={contract:'AUREN_C3_2_RELATIONSHIP_STATE_FOUNDATION_QUALIFICATION_V1',status:failures.length?'FAIL':'PASS',checks,failures};fs.writeFileSync(out,JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));if(failures.length)process.exitCode=1;