/** H_EARTH_SUCCESSOR_SURFACE_MATERIAL_PROJECTION_RUN_8C_v4_GRATITUDE_RECIPROCAL_SUBTROPICAL */
import { H_EARTH_SURFACE_STATE_FIELD_CONTRACT_ID,H_EARTH_SURFACE_CLASSES,sampleHEarthSurfaceState,evaluateHEarthSurfaceStateSample } from './h-earth.surface-state-field.js';
import { getHEarthCanonicalShorelineZ } from '../terrain/h-earth.terrain-field.js';
import { H_EARTH_RUN_8B_SUCCESSOR_TERRAIN_FIELD_CONTRACT_ID,sampleHEarthRun8BSuccessorTerrainField } from '../terrain/h-earth.successor-terrain-field.run8b.js';
import { H_EARTH_RUN_8A_NORMAL_LIGHT_AND_MATERIAL_INTERFACE_CONTRACT } from '../control-plane/run-8/h-earth.run8a.dimensional-reconciliation.js';
const freeze=(v,s=new WeakSet())=>{if(v===null||typeof v!=='object'||Object.isFrozen(v)||s.has(v))return v;s.add(v);Object.values(v).forEach(x=>freeze(x,s));return Object.freeze(v)};const finite=v=>typeof v==='number'&&Number.isFinite(v);const clamp=(v,a,b)=>Math.min(b,Math.max(a,v)),clamp01=v=>clamp(v,0,1),mix=(a,b,t)=>a+(b-a)*clamp01(t);
export const H_EARTH_RUN_8C_SUCCESSOR_SURFACE_MATERIAL_CONTRACT_ID='H_EARTH_SUCCESSOR_SURFACE_MATERIAL_PROJECTION_RUN_8C_v4_GRATITUDE_RECIPROCAL_SUBTROPICAL';
export const H_EARTH_RUN_8C_SUCCESSOR_SURFACE_MATERIAL_SOURCE_FILE='/h-earth-3d/environment/h-earth.successor-surface-material.run8c.js';
export const H_EARTH_RUN_8C_SUCCESSOR_SURFACE_MATERIAL_PROFILE=freeze({contractId:H_EARTH_RUN_8C_SUCCESSOR_SURFACE_MATERIAL_CONTRACT_ID,sourceSurfaceStateContractId:H_EARTH_SURFACE_STATE_FIELD_CONTRACT_ID,successorTerrainFieldContractId:H_EARTH_RUN_8B_SUCCESSOR_TERRAIN_FIELD_CONTRACT_ID,normalLightMaterialInterfaceContractId:H_EARTH_RUN_8A_NORMAL_LIGHT_AND_MATERIAL_INTERFACE_CONTRACT.contractId,projectionClass:'GRATITUDE_WARM_SUBTROPICAL_COASTAL_CAUSAL_MATERIAL_PROJECTION_RECIPROCAL',geographicIdentity:'GRATITUDE',continentalContext:'AUDRALIA',climateIdentity:'WARM_SUBTROPICAL_COASTAL',sourceClasses:H_EARTH_SURFACE_CLASSES,owns:{successorMaterialProjection:true,intrinsicRun7BSurfaceTruth:false,successorTerrainTruth:false,geometry:false,admission:false,renderer:false,camera:false,route:false,deployment:false}});
let prototypeMapCache=null;function copyPrototype(s){return freeze({sourceSurfaceClass:s.surfaceClass,baseColorProfile:{...s.baseColorProfile},roughness:s.roughness,reflectance:s.reflectance,wetness:s.wetness,waterSaturation:s.waterSaturation,rockExposure:s.rockExposure,soilDepth:s.soilDepth,sedimentClass:s.sedimentClass});}
export function getHEarthRun8CMaterialPrototypeMap(){if(prototypeMapCache)return prototypeMapCache;const p={};for(let z=64;z>=-256&&Object.keys(p).length<H_EARTH_SURFACE_CLASSES.length;z-=4)for(let x=-256;x<=256&&Object.keys(p).length<H_EARTH_SURFACE_CLASSES.length;x+=4){const s=sampleHEarthSurfaceState(x,z);if(s?.valid===true&&evaluateHEarthSurfaceStateSample(s).eligible===true&&H_EARTH_SURFACE_CLASSES.includes(s.surfaceClass)&&!p[s.surfaceClass])p[s.surfaceClass]=copyPrototype(s);}prototypeMapCache=freeze(p);return prototypeMapCache;}
function classify(t,d){if(d<-18)return'OPEN_WATER';if(d<0)return'NEARSHORE_WATER';if(d<12)return'WET_SAND';if(d<42)return'DRY_SAND';if(t.elevation>24||t.slope>0.35)return'STONE_AND_SPARSE_SOIL';if(t.elevation>8)return'COASTAL_SOIL';return'LOWLAND_SOIL';}
function causalSignals(t,d){const slopeExposure=clamp01(t.slope/.65),curvatureMagnitude=clamp01(Math.abs(t.curvature)/.2),shorelineMoisture=clamp01(1-Math.max(0,d)/180),elevationDrying=clamp01(Math.max(0,t.elevation)/82),lowlandRetention=clamp01((1-elevationDrying)*.58+(1-slopeExposure)*.42),shelterMoisture=clamp01(shorelineMoisture*.48+lowlandRetention*.38+(1-curvatureMagnitude)*.14),exposureDrying=clamp01(slopeExposure*.58+elevationDrying*.42);return freeze({slopeExposure,curvatureMagnitude,shorelineMoisture,elevationDrying,lowlandRetention,shelterMoisture,exposureDrying});}
function color(profile,c,s){const source={...profile};if(c.includes('WATER')||c==='WET_SAND'||c==='DRY_SAND')return freeze(source);const target=c==='LOWLAND_SOIL'?{linearR:.055,linearG:.255,linearB:.075}:c==='COASTAL_SOIL'?{linearR:.075,linearG:.225,linearB:.075}:{linearR:.115,linearG:.155,linearB:.09};const humidity=clamp01(.18+s.shelterMoisture*.72-s.exposureDrying*.24),strength=c==='STONE_AND_SPARSE_SOIL'?humidity*.2:humidity*.82;return freeze({...source,linearR:clamp01(mix(source.linearR,target.linearR,strength)),linearG:clamp01(mix(source.linearG,target.linearG,strength)),linearB:clamp01(mix(source.linearB,target.linearB,strength)),alpha:source.alpha});}
function project(p,c,t,d){const water=c.includes('WATER'),s=causalSignals(t,d),rockExposure=water?p.rockExposure:clamp01(p.rockExposure+s.slopeExposure*.31+s.curvatureMagnitude*.08),wetness=water?1:clamp01(p.wetness+s.shelterMoisture*.28-s.exposureDrying*.08),waterSaturation=water?1:clamp01(p.waterSaturation+s.shelterMoisture*.32-s.exposureDrying*.1);return freeze({baseColorProfile:color(p.baseColorProfile,c,s),roughness:clamp01(p.roughness+rockExposure*.07-wetness*.07),reflectance:clamp01(p.reflectance+wetness*.1-rockExposure*.03),wetness,waterSaturation,rockExposure,soilDepth:water?0:Math.max(0,p.soilDepth*(1-rockExposure*.58)*(0.82+s.lowlandRetention*.18)),sedimentClass:p.sedimentClass,slopePressure:s.slopeExposure,curvaturePressure:s.curvatureMagnitude,shorelineMoisture:s.shorelineMoisture,elevationDrying:s.elevationDrying,lowlandMoistureRetention:s.lowlandRetention,shelterMoisture:s.shelterMoisture,exposureDrying:s.exposureDrying,geographicIdentity:'GRATITUDE',continentalContext:'AUDRALIA',climateIdentity:'WARM_SUBTROPICAL_COASTAL',environmentalCausality:'SHORELINE_MOISTURE_ELEVATION_SLOPE_CURVATURE_SHELTER_EXPOSURE_ROCK'});}
export function sampleHEarthRun8CSuccessorSurfaceMaterial(worldX,worldZ){if(!finite(worldX)||!finite(worldZ))return freeze({valid:false,status:'RUN_8C_SUCCESSOR_SURFACE_MATERIAL_REJECTED_NONFINITE',worldX,worldZ,issues:['WORLD_COORDINATE_NONFINITE']});const t=sampleHEarthRun8BSuccessorTerrainField(worldX,worldZ);if(t?.valid!==true)return freeze({valid:false,status:'RUN_8C_SUCCESSOR_SURFACE_MATERIAL_REJECTED_TERRAIN',worldX,worldZ,issues:['RUN_8B_SUCCESSOR_TERRAIN_SAMPLE_INVALID']});const shorelineZ=getHEarthCanonicalShorelineZ(worldX),shorelineDistance=shorelineZ-worldZ,surfaceClass=classify(t,shorelineDistance),prototype=getHEarthRun8CMaterialPrototypeMap()[surfaceClass];if(!prototype)return freeze({valid:false,status:'RUN_8C_SUCCESSOR_SURFACE_MATERIAL_REJECTED_PROFILE',world:t.world,surfaceClass,issues:[`RUN_7B_MATERIAL_PROTOTYPE_UNAVAILABLE:${surfaceClass}`]});return freeze({valid:true,status:'RUN_8C_SUCCESSOR_SURFACE_MATERIAL_COMPLETE',contractId:H_EARTH_RUN_8C_SUCCESSOR_SURFACE_MATERIAL_CONTRACT_ID,world:t.world,normal:t.normal,slope:t.slope,curvature:t.curvature,mountainContribution:t.mountainContribution,domainRegion:t.domainRegion,shorelineZ,shorelineDistance,surfaceClass,materialProfileId:`H_EARTH_RUN_8C_${surfaceClass}_GRATITUDE_RECIPROCAL_SUBTROPICAL_v4`,...project(prototype,surfaceClass,t,shorelineDistance),sourceIdentities:{run7BSurfaceStateContractId:H_EARTH_SURFACE_STATE_FIELD_CONTRACT_ID,run8BSuccessorTerrainFieldContractId:H_EARTH_RUN_8B_SUCCESSOR_TERRAIN_FIELD_CONTRACT_ID,run8ANormalLightMaterialInterfaceContractId:H_EARTH_RUN_8A_NORMAL_LIGHT_AND_MATERIAL_INTERFACE_CONTRACT.contractId},authority:'SUCCESSOR_MATERIAL_PROJECTION_ONLY',issues:[]});}
export function evaluateHEarthRun8CSuccessorSurfaceMaterial(sample){const issues=[];if(sample?.valid!==true){issues.push('SUCCESSOR_SURFACE_MATERIAL_NOT_VALID');return freeze({eligible:false,status:'RUN_8C_SUCCESSOR_SURFACE_MATERIAL_FAIL',issues});}if(sample.contractId!==H_EARTH_RUN_8C_SUCCESSOR_SURFACE_MATERIAL_CONTRACT_ID)issues.push('SUCCESSOR_SURFACE_MATERIAL_CONTRACT_ID_MISMATCH');if(!H_EARTH_SURFACE_CLASSES.includes(sample.surfaceClass))issues.push('SUCCESSOR_SURFACE_CLASS_INVALID');for(const c of['roughness','reflectance','wetness','waterSaturation','rockExposure','slopePressure','curvaturePressure','shorelineMoisture','elevationDrying','lowlandMoistureRetention','shelterMoisture','exposureDrying'])if(!finite(sample[c])||sample[c]<0||sample[c]>1)issues.push(`SUCCESSOR_MATERIAL_CHANNEL_INVALID:${c}`);const col=sample.baseColorProfile;if(!col||['linearR','linearG','linearB','alpha'].some(k=>!finite(col[k])||col[k]<0||col[k]>1))issues.push('SUCCESSOR_MATERIAL_BASE_COLOR_INVALID');if(sample.sourceIdentities?.run7BSurfaceStateContractId!==H_EARTH_SURFACE_STATE_FIELD_CONTRACT_ID)issues.push('RUN_7B_SURFACE_SOURCE_IDENTITY_MISSING');if(sample.sourceIdentities?.run8BSuccessorTerrainFieldContractId!==H_EARTH_RUN_8B_SUCCESSOR_TERRAIN_FIELD_CONTRACT_ID)issues.push('RUN_8B_TERRAIN_SOURCE_IDENTITY_MISSING');if(sample.geographicIdentity!=='GRATITUDE'||sample.continentalContext!=='AUDRALIA'||sample.climateIdentity!=='WARM_SUBTROPICAL_COASTAL')issues.push('GRATITUDE_AUDRALIA_CLIMATE_IDENTITY_MISSING');return freeze({eligible:issues.length===0,status:issues.length?'RUN_8C_SUCCESSOR_SURFACE_MATERIAL_FAIL':'RUN_8C_SUCCESSOR_SURFACE_MATERIAL_PASS',issues});}
export default H_EARTH_RUN_8C_SUCCESSOR_SURFACE_MATERIAL_PROFILE;
