(()=>{'use strict';
const root=document.querySelector('[data-root]');
const ORDER=['north','east','south','west'];
const DATA={
 north:{label:'North',kicker:'NORTH · ORIENTATION',title:'Understand the estate.',body:'Products, purpose, context, and the routes that help you understand how the estate fits together.',impact:'Use North when you need context before choosing a more specialized room.',route:'/',routeLabel:'Go to Orientation',rooms:[['Products','See the estate’s dedicated products.','/products/'],['Guide Desk','See a broad map of the estate and how its rooms relate.','/site-guide/'],['Front Door','Enter through the estate’s formal introduction.','/door/'],['Meet Sean','Meet the person behind the estate.','/meet-sean-mansfield/'],['Philosophy Library','Explore the values and questions behind the estate.','/nine-summits-of-love/']]},
 east:{label:'East',kicker:'EAST · WORLDS',title:'Enter constructed worlds.',body:'Maps, planetary environments, civilizations, and alternate worlds where place itself becomes part of the explanation.',impact:'Use East when comparison, place, or a constructed world can answer the question.',route:'/showroom/globe/',routeLabel:'Go to Worlds',rooms:[['Atlas Study','Compare the estate’s major worlds from one atlas.','/showroom/globe/'],['ZIONTS','Explore a world shaped by familiar system choices and consequences.','/showroom/globe/earth/'],['Audralia Conservatory','Explore a civilization built around diagnosis and institutional integrity.','/showroom/globe/audralia/'],['Hearth','Explore habitation, memory, survival, and environmental history through place.','/showroom/globe/hearth/'],['H-Earth','Compare an alternate Earth expression with familiar reality.','/showroom/globe/h-earth/']]},
 south:{label:'South',kicker:'SOUTH · INSTRUMENTS',title:'Measure, verify, and govern.',body:'Measurement, standards, governance, diagnostics, and operational control when a question needs a bounded answer.',impact:'Use South when you need to measure, verify, govern, or decide what may happen next.',route:'/gauges/',routeLabel:'Go to Instruments',rooms:[['The Lab','Open gauges, diagnostic tools, and measurement surfaces.','/gauges/'],['Law Library','Read the laws and standards that govern estate systems.','/laws/'],['Council Room','See who may decide, verify, coordinate, or act.','/governance/'],['Control Cockpit','Turn findings into a bounded next action.','/showroom/globe/audralia/disposition/']]},
 west:{label:'West',kicker:'WEST · FRONTIER',title:'Build and test the frontier.',body:'Prototypes, energy, water, infrastructure, and long-range construction when the next useful step is to make something.',impact:'Use West when the next useful step is to inspect or build something practical.',route:'/explore/frontier/',routeLabel:'Go to Frontier',rooms:[['Frontier Workshop Yard','Open the estate’s practical construction area.','/explore/frontier/'],['Energy Bench','Explore generation, transfer, storage, efficiency, and loss.','/explore/frontier/energy/'],['Water Bench','Explore movement, storage, treatment, access, and distribution.','/explore/frontier/water/'],['Infrastructure Bay','Explore the foundations that keep systems working.','/explore/frontier/infrastructure/'],['Vision Window','Look at long-range direction and downstream consequences.','/explore/frontier/vision/']]}
};
const stars=[...document.querySelectorAll('.star[data-cardinal]')],scene=document.querySelector('[data-scene]'),rooms=document.querySelector('[data-rooms]'),grid=document.querySelector('[data-room-grid]');let active=0;
function renderCardinal(focus=false){const id=ORDER[active],d=DATA[id];root.dataset.cardinal=id;stars.forEach((s,i)=>{const on=i===active;s.classList.toggle('is-active',on);s.setAttribute('aria-pressed',String(on));s.tabIndex=on?0:-1});document.querySelector('[data-context-kicker]').textContent=d.kicker;document.querySelector('[data-context-title]').textContent=d.title;document.querySelector('[data-context-body]').textContent=d.body;document.querySelector('[data-context-impact]').textContent=d.impact;const link=document.querySelector('[data-context-route]');link.href=d.route;link.textContent=d.routeLabel;document.querySelector('[data-open-rooms]').textContent=`Open ${d.label}`;if(focus)stars[active].focus({preventScroll:true})}
function setActive(i,focus=false){active=(i+ORDER.length)%ORDER.length;rooms.hidden=true;renderCardinal(focus)}
stars.forEach((s,i)=>s.addEventListener('click',()=>i===active?openRooms():setActive(i,true)));scene.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();setActive(active+1,true)}if(e.key==='ArrowLeft'){e.preventDefault();setActive(active-1,true)}if((e.key==='Enter'||e.key===' ')&&e.target===stars[active]){e.preventDefault();openRooms()}});
let sx=null,sy=null;scene.addEventListener('pointerdown',e=>{if(e.target.closest('a'))return;sx=e.clientX;sy=e.clientY});scene.addEventListener('pointerup',e=>{if(sx==null)return;const dx=e.clientX-sx,dy=e.clientY-sy;sx=sy=null;if(Math.abs(dx)>42&&Math.abs(dx)>Math.abs(dy))setActive(active+(dx<0?1:-1))});
function openRooms(){const id=ORDER[active],d=DATA[id];document.querySelector('[data-room-kicker]').textContent=`${d.label.toUpperCase()} · ROOMS`;document.querySelector('[data-room-heading]').textContent=`${d.label} rooms`;grid.innerHTML='';d.rooms.forEach((r,i)=>{const a=document.createElement('a');a.className='room';a.href=r[2];a.innerHTML=`<span>${String(i+1).padStart(2,'0')}</span><strong>${r[0]}</strong><small>${r[1]}</small>`;grid.appendChild(a)});rooms.hidden=false;rooms.scrollIntoView({block:'nearest',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'})}
document.querySelector('[data-open-rooms]').addEventListener('click',openRooms);document.querySelector('[data-close-rooms]').addEventListener('click',()=>{rooms.hidden=true;stars[active].focus({preventScroll:true})});
const statements=[...document.querySelectorAll('.statement')];let si=0;function rs(){statements.forEach((s,i)=>s.classList.toggle('is-active',i===si));document.querySelector('[data-statement-count]').textContent=`${String(si+1).padStart(2,'0')} / ${String(statements.length).padStart(2,'0')}`};document.querySelector('[data-statement-prev]').addEventListener('click',()=>{si=(si-1+statements.length)%statements.length;rs()});document.querySelector('[data-statement-next]').addEventListener('click',()=>{si=(si+1)%statements.length;rs()});
const modal=document.querySelector('[data-modal]'),mirrorland=document.querySelector('[data-mirrorland]');function openModal(){modal.hidden=false;document.body.style.overflow='hidden';modal.querySelector('.threshold a')?.focus()}function closeModal(){modal.hidden=true;document.body.style.overflow='';mirrorland.focus({preventScroll:true})}mirrorland.addEventListener('click',openModal);document.querySelectorAll('[data-modal-close]').forEach(x=>x.addEventListener('click',closeModal));addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden){e.preventDefault();closeModal()}});
const CAP={understand:{kicker:'Assessment',title:'Coherence Diagnostic',body:'Compare what matters to you with how you are actually living and deciding. See areas of alignment, tension, and repeated mismatch.',href:'/coherence-diagnostic/',action:'Run the diagnostic',mark:'◎'},explore:{kicker:'Awards & Recognition',title:'One body of work. Several reasons to look closer.',body:'Explore the estate’s interactive worlds, browser-native systems, governed construction work, and current awards layer without collapsing those claims into the Compass itself.',href:'/showroom/globe/h-earth/awards/',action:'Explore the awards layer',mark:'◇'},ask:{kicker:'Ask for directions',title:'Talk to the House',body:'Tell the House what you are trying to understand or do. It points toward the room, tool, or experience most likely to help.',href:'/showroom/globe/hearth/jeeves/',action:'Ask the House',mark:'⌂'}};const tabs=[...document.querySelectorAll('[data-cap]')];tabs.forEach(t=>t.addEventListener('click',()=>{tabs.forEach(x=>{const on=x===t;x.classList.toggle('is-active',on);x.setAttribute('aria-selected',String(on))});const c=CAP[t.dataset.cap];document.querySelector('[data-cap-kicker]').textContent=c.kicker;document.querySelector('[data-cap-title]').textContent=c.title;document.querySelector('[data-cap-body]').textContent=c.body;const a=document.querySelector('[data-cap-link]');a.href=c.href;a.textContent=c.action;document.querySelector('.cap-mark').textContent=c.mark}));renderCardinal();rs();globalThis.DGB_COMPASS_PRESENTABLE_V2=Object.freeze({version:'2.0.1',cardinalOwner:'single',allFourStarsPresent:true,oneReadableCardinalLabel:true,roomsLayout:'non-overlapping-grid',capabilityLayout:'single-active-detail',mirrorland:'top-level-modal',productionRootMutation:false});})();
