(()=>{'use strict';
const mod=(n,m)=>((n%m)+m)%m;
const root=document.querySelector('[data-root]');
const statements=[...document.querySelectorAll('.statement')];let s=0;
function showStatement(i){s=mod(i,statements.length);statements.forEach((el,n)=>el.classList.toggle('active',n===s));document.querySelector('[data-statement-count]').textContent=`${String(s+1).padStart(2,'0')} / ${String(statements.length).padStart(2,'0')}`}
document.querySelector('[data-statement-prev]').onclick=()=>showStatement(s-1);document.querySelector('[data-statement-next]').onclick=()=>showStatement(s+1);
const statementHost=document.querySelector('.statements');let sx=null;statementHost.addEventListener('pointerdown',e=>sx=e.clientX,{passive:true});statementHost.addEventListener('pointerup',e=>{if(sx===null)return;const dx=e.clientX-sx;sx=null;if(Math.abs(dx)>40)showStatement(s+(dx<0?1:-1))},{passive:true});statementHost.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();showStatement(s+1)}if(e.key==='ArrowLeft'){e.preventDefault();showStatement(s-1)}});
const DATA={
north:{label:'North',kicker:'NORTH · ORIENTATION',title:'Understand the estate.',body:'Products, purpose, context, and the routes that help you understand how the estate fits together.',route:'/',rooms:[['Products','See the estate’s dedicated products.','/products/'],['Guide Desk','See the broad map of the estate.','/site-guide/'],['Front Door','Enter through the formal introduction.','/door/'],['Meet Sean','Meet the person behind the estate.','/meet-sean-mansfield/'],['Philosophy Library','Explore the values behind the estate.','/nine-summits-of-love/']]},
east:{label:'East',kicker:'EAST · WORLDS',title:'Enter constructed worlds.',body:'Maps, planetary environments, civilizations, and comparative worlds where place becomes part of the explanation.',route:'/showroom/globe/',rooms:[['Atlas Study','Compare the estate’s major worlds.','/showroom/globe/'],['ZIONTS','Study risk and recognizable consequences.','/showroom/globe/earth/'],['Audralia Conservatory','Explore a diagnostic civilization.','/showroom/globe/audralia/'],['Hearth','Explore habitation, memory, and survival.','/showroom/globe/hearth/'],['H-Earth','Compare an alternate Earth expression.','/showroom/globe/h-earth/']]},
south:{label:'South',kicker:'SOUTH · INSTRUMENTS',title:'Measure, verify, and govern.',body:'Measurement, standards, governance, diagnostics, and operational control when a question needs a bounded answer.',route:'/gauges/',rooms:[['The Lab','Open gauges and diagnostic tools.','/gauges/'],['Law Library','Read the laws and standards.','/laws/'],['Council Room','See governance and authority.','/governance/'],['Control Cockpit','Turn findings into bounded action.','/showroom/globe/audralia/disposition/']]},
west:{label:'West',kicker:'WEST · FRONTIER',title:'Build and test the frontier.',body:'Prototypes, energy, water, infrastructure, and long-range construction when the next useful step is to make something.',route:'/explore/frontier/',rooms:[['Frontier Workshop Yard','Open the practical construction area.','/explore/frontier/'],['Energy Bench','Explore generation and efficiency.','/explore/frontier/energy/'],['Water Bench','Explore movement, treatment, and access.','/explore/frontier/water/'],['Infrastructure Bay','Explore foundations that keep systems working.','/explore/frontier/infrastructure/'],['Vision Window','Inspect long-range direction and consequences.','/explore/frontier/vision/']]}}
const order=['north','east','south','west'];let d=0;
const panelK=document.querySelector('[data-panel-kicker]'),panelT=document.querySelector('[data-panel-title]'),panelB=document.querySelector('[data-panel-body]'),panelL=document.querySelector('[data-panel-link]'),openRooms=document.querySelector('[data-open-rooms]'),roomBox=document.querySelector('[data-rooms]'),roomGrid=document.querySelector('[data-room-grid]'),roomK=document.querySelector('[data-rooms-kicker]'),roomT=document.querySelector('[data-rooms-title]');
function renderDirection(){const id=order[d],x=DATA[id];root.dataset.direction=id;document.querySelectorAll('[data-dir]').forEach(btn=>btn.classList.toggle('active',btn.dataset.dir===id));panelK.textContent=x.kicker;panelT.textContent=x.title;panelB.textContent=x.body;panelL.href=x.route;panelL.textContent=`Go to ${x.label} →`;openRooms.textContent=`Open ${x.label}`;roomK.textContent=`${x.label.toUpperCase()} · ROOMS`;roomT.textContent=`${x.label} rooms`;roomGrid.innerHTML=x.rooms.map(r=>`<article class="room-card"><p class="kicker">${x.label.toUpperCase()}</p><h4>${r[0]}</h4><p>${r[1]}</p><a href="${r[2]}">Enter ${r[0]} →</a></article>`).join('')}
function setDir(i){d=mod(i,4);renderDirection()}
document.querySelectorAll('[data-dir]').forEach((btn,i)=>btn.addEventListener('click',()=>{if(i===d){roomBox.hidden=false;roomBox.scrollIntoView({block:'nearest',behavior:'smooth'})}else setDir(i)}));
const stage=document.querySelector('[data-stage]');let dx=null;stage.addEventListener('pointerdown',e=>dx=e.clientX,{passive:true});stage.addEventListener('pointerup',e=>{if(dx===null)return;const delta=e.clientX-dx;dx=null;if(Math.abs(delta)>45)setDir(d+(delta<0?1:-1))},{passive:true});stage.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();setDir(d+1)}if(e.key==='ArrowLeft'){e.preventDefault();setDir(d-1)}});
openRooms.onclick=()=>{roomBox.hidden=false;renderDirection();roomBox.scrollIntoView({block:'nearest',behavior:'smooth'})};document.querySelector('[data-close-rooms]').onclick=()=>{roomBox.hidden=true;stage.focus({preventScroll:true})};
const CAPS={understand:['ASSESSMENT','Coherence Diagnostic','Compare what matters to you with how you are actually living and deciding. See areas of alignment, tension, and repeated mismatch.','/coherence-diagnostic/','Run the diagnostic →'],explore:['AWARDS & RECOGNITION','One body of work. Five reasons to look closer.','Interactive worlds, original characters, browser-native 3D, a growing software platform, governed construction, continuity, and recovery.','/showroom/globe/h-earth/awards/','Explore the Awards Layer →'],ask:['ASK FOR DIRECTIONS','Talk to the House','Tell the House what you are trying to understand or do. It points toward the room, tool, or experience most likely to help.','/showroom/globe/hearth/jeeves/','Ask the House →']};
const capK=document.querySelector('[data-cap-kicker]'),capT=document.querySelector('[data-cap-title]'),capB=document.querySelector('[data-cap-body]'),capL=document.querySelector('[data-cap-link]');document.querySelectorAll('[data-cap]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-cap]').forEach(b=>{const on=b===btn;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on))});const x=CAPS[btn.dataset.cap];capK.textContent=x[0];capT.textContent=x[1];capB.textContent=x[2];capL.href=x[3];capL.textContent=x[4]}));
const modal=document.querySelector('[data-modal]');document.querySelector('[data-mirrorland]').onclick=()=>{modal.hidden=false;document.body.style.overflow='hidden';modal.querySelector('a').focus()};document.querySelectorAll('[data-modal-close]').forEach(el=>el.addEventListener('click',()=>{modal.hidden=true;document.body.style.overflow='';document.querySelector('[data-mirrorland]').focus({preventScroll:true})}));addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden){modal.hidden=true;document.body.style.overflow='';document.querySelector('[data-mirrorland]').focus({preventScroll:true})}});
showStatement(0);renderDirection();globalThis.DGB_COMPASS_PRESENTABLE_RECEIPT=Object.freeze({build:'presentable-001',allFourStarsPresent:true,oneReadableCardinalLabel:true,nonOverlappingCapabilities:true,mirrorlandTopLevelModal:true,productionCompassMutation:false});})();