#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import cp from 'node:child_process';import http from 'node:http';
const argv=process.argv.slice(2);const a={};for(let i=0;i<argv.length;i++)if(argv[i].startsWith('--'))a[argv[i].slice(2)]=argv[++i];const need=k=>{if(!a[k])throw new Error(`MISSING_${k.toUpperCase().replaceAll('-','_')}`);return a[k]};const hash=b=>crypto.createHash('sha256').update(b).digest('hex');const root=path.resolve(a.root||'.'),fixture=path.resolve(need('fixture')),out=path.resolve(need('output')),dest=need('destination');if(!dest.startsWith('proof-media/awards-compass-v2/')||!dest.endsWith('.mp4'))throw new Error('DESTINATION_NOT_AUTHORIZED');
const data=fs.readFileSync(fixture),sha=hash(data),stage=path.join(root,'.media-staging/awards-compass-v2');fs.rmSync(stage,{recursive:true,force:true});fs.mkdirSync(stage,{recursive:true});const b64=data.toString('base64'),parts=[],chunk=750000;for(let off=0,n=1;off<b64.length;off+=chunk,n++){const body=b64.slice(off,off+chunk),name=`part-${String(n).padStart(4,'0')}.b64`;fs.writeFileSync(path.join(stage,name),body+'\n');parts.push({name,chars:body.length,sha256:hash(Buffer.from(body))});}const manifest={schema:'AI_MEDIA_TRANSPORT_MANIFEST_v1',sourceBytes:data.length,sourceSha256:sha,base64Chars:b64.length,chunkChars:chunk,partCount:parts.length,parts};fs.writeFileSync(path.join(stage,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');const manifestSha=hash(fs.readFileSync(path.join(stage,'manifest.json')));
fs.mkdirSync(path.dirname(out),{recursive:true});const admissionPath=path.join(path.dirname(out),'admission-receipt.json');cp.execFileSync('node',['tools/ai-room-transport/ai-media-admission.v1.mjs','--source-sha256',sha,'--source-bytes',String(data.length),'--part-count',String(parts.length),'--manifest-sha256',manifestSha,'--execution-holder','AI_MEDIA_E2E_QUALIFIER','--output',admissionPath],{cwd:root});const admission=JSON.parse(fs.readFileSync(admissionPath));if(admission.result!=='PASS')throw new Error('P1_ADMISSION_FAIL');
const destReceipt=path.join(path.dirname(out),'destination-receipt.json');cp.execFileSync('node',['tools/ai-room-transport/ai-media-destination-job.v1.mjs','--root',root,'--admission-receipt',admissionPath,'--staging-dir','.media-staging/awards-compass-v2','--destination',dest,'--expected-sha256',sha,'--output',destReceipt],{cwd:root});const r=JSON.parse(fs.readFileSync(destReceipt));if(r.result!=='PASS')throw new Error('P2_DESTINATION_FAIL');
const writtenPath=path.join(root,dest),written=fs.readFileSync(writtenPath);if(hash(written)!==sha||!written.equals(data))throw new Error('P3_BYTE_SHA_FAIL');
cp.execFileSync('ffprobe',['-v','error','-show_entries','format=format_name,duration,size','-of','json',writtenPath],{stdio:['ignore','pipe','pipe']});
const server=http.createServer((req,res)=>{if(req.url!=='/candidate.mp4'){res.statusCode=404;return res.end();}const b=fs.readFileSync(writtenPath);res.writeHead(200,{'Content-Type':'video/mp4','Content-Length':b.length});res.end(b);});await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});const port=server.address().port;const fetched=await new Promise((resolve,reject)=>{http.get(`http://127.0.0.1:${port}/candidate.mp4`,res=>{const chunks=[];if(res.statusCode!==200)return reject(new Error('P5_HTTP_STATUS_FAIL'));if(res.headers['content-type']!=='video/mp4')return reject(new Error('P5_HTTP_TYPE_FAIL'));res.on('data',c=>chunks.push(c));res.on('end',()=>resolve(Buffer.concat(chunks)));}).on('error',reject);});server.close();if(hash(fetched)!==sha||!fetched.equals(data))throw new Error('P5_HTTP_SHA_FAIL');
const receipt={schema:'AI_MEDIA_END_TO_END_QUALIFICATION_RECEIPT_v2',result:'PASS_CLOSED',predicates:{P1_admission:true,P2_destination:true,P3_source_equals_reconstructed:true,P4_ffprobe_accepts:true,P5_http_fetch_equals_source:true},sourceSha256:sha,destinationSha256:hash(written),httpFetchedSha256:hash(fetched),sourceBytes:data.length,destinationBytes:written.length,partCount:parts.length,destination:dest,githubActionsDependency:false};fs.writeFileSync(out,JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt));
