const results=[];const report=(...v)=>results.push(v);
import {previewHEarthFunctionalLandscape} from '../../render/landscape-preview.js';
import {constructHEarthDistantContextGeometry} from '../../render/geometry-distant-context.js';
import {createHash} from 'node:crypto';
const p=previewHEarthFunctionalLandscape(),near=p.componentResults.terrain.primitive.geometry,far=p.componentResults.distantContext.meshDiagnostics.land,old=constructHEarthDistantContextGeometry(),hash=v=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
report('oceanEqual',hash(old.meshDiagnostics.ocean)===hash(p.componentResults.distantContext.meshDiagnostics.ocean));
const cross=(a,b,c)=>(b.x-a.x)*(c.z-a.z)-(b.z-a.z)*(c.x-a.x),area=poly=>Math.abs(poly.reduce((s,a,i)=>{const b=poly[(i+1)%poly.length];return s+a.x*b.z-b.x*a.z},0))/2;
function overlap(subject,tri){let out=subject,sign=Math.sign(cross(...tri));for(let i=0;i<3;i++){const a=tri[i],b=tri[(i+1)%3],src=out;out=[];for(let j=0;j<src.length;j++){const u=src[j],v=src[(j+1)%src.length],du=sign*cross(a,b,u),dv=sign*cross(a,b,v),inside=du>=0,next=dv>=0;if(inside)out.push(u);if(inside!==next){const t=du/(du-dv);out.push({x:u.x+(v.x-u.x)*t,z:u.z+(v.z-u.z)*t});}}if(out.length<3)return 0;}return area(out);}
function triangles(mesh){const out=[];for(let i=0;i<mesh.indices.length;i+=3){const points=mesh.indices.slice(i,i+3).map(j=>mesh.vertices[j]);out.push({points,b:[Math.min(...points.map(p=>p.x)),Math.min(...points.map(p=>p.z)),Math.max(...points.map(p=>p.x)),Math.max(...points.map(p=>p.z))]});}return out;}
const nt=triangles(near),ft=triangles(far);let count=0,total=0,max=0,neg=0;
for(const f of ft){if(cross(...f.points)<0)neg++;for(const n of nt){if(f.b[0]>=n.b[2]||f.b[2]<=n.b[0]||f.b[1]>=n.b[3]||f.b[3]<=n.b[1])continue;const a=overlap(f.points,n.points);if(a>1e-7){count++;total+=a;max=Math.max(max,a);}}}
report({nearTriangles:nt.length,farTriangles:ft.length,overlapPairCount:count,totalOverlapArea:total,maxOverlapArea:max,reversedTriangleCount:neg});
const axes=near.attributes,nx=axes.xValues.length,nz=axes.zValues.length;const edges=[];for(let j=0;j<nx-1;j++){edges.push([near.vertices[j],near.vertices[j+1]]);const o=(nz-1)*nx;edges.push([near.vertices[o+j],near.vertices[o+j+1]]);}for(let j=0;j<nz-1;j++){edges.push([near.vertices[j*nx],near.vertices[(j+1)*nx]],[near.vertices[j*nx+nx-1],near.vertices[(j+1)*nx+nx-1]]);}
let welded=0,maxResidual=0;for(const v of far.vertices){let best=Infinity;for(const [a,b] of edges){const dx=b.x-a.x,dz=b.z-a.z,t=((v.x-a.x)*dx+(v.z-a.z)*dz)/(dx*dx+dz*dz);if(t< -1e-8||t>1+1e-8)continue;const d=Math.hypot(v.x-a.x-t*dx,v.z-a.z-t*dz);if(d<1e-7){best=Math.min(best,Math.abs(v.y-a.y-t*(b.y-a.y)));}}if(best<1e-5){welded++;maxResidual=Math.max(maxResidual,best);}}
report({weldedVertices:welded,maximumSeamHeightResidual:maxResidual});
const ot=triangles(old.meshDiagnostics.land),contains=(point,list)=>list.some(t=>{if(point.x<t.b[0]||point.x>t.b[2]||point.z<t.b[1]||point.z>t.b[3])return false;const signs=t.points.map((a,i)=>cross(a,t.points[(i+1)%3],point));return signs.every(v=>v>=-1e-8)||signs.every(v=>v<=1e-8);});
let checkedSeamSegments=0,uncoveredSeamSegments=0;
for(const [a,b] of edges){const center={x:(a.x+b.x)/2,z:(a.z+b.z)/2},dx=b.x-a.x,dz=b.z-a.z,L=Math.hypot(dx,dz);const p1={x:center.x-dz/L*.001,z:center.z+dx/L*.001},p2={x:center.x+dz/L*.001,z:center.z-dx/L*.001};for(const point of [p1,p2])if(!contains(point,nt)&&contains(point,ot)){checkedSeamSegments++;if(!contains(point,ft))uncoveredSeamSegments++;}}
report({checkedSeamSegments,uncoveredSeamSegments,originalFarWindingPositive:ot.every(t=>cross(...t.points)>0)});
const triangleKey=t=>t.points.map(v=>[v.x,v.y,v.z].join(',')).sort().join('|'),newSet=new Set(ft.map(triangleKey));let outer=0,missingOuter=0;
for(const t of ot)if(t.points.every(v=>Math.hypot(v.x,v.z)>1150)){outer++;if(!newSet.has(triangleKey(t)))missingOuter++;}
report({unchangedOuterTriangles:outer,missingOuterTriangles:missingOuter});
if(count||neg||welded<100||uncoveredSeamSegments||missingOuter)process.exitCode=1;

import {createHEarthRun8ER2DCanonicalGPUUploadViews} from '../../render/gpu-upload-views.run8e-r2d.js';
import {buildHEarthLandscapeSector} from '../../render/geometry-landscape-sector.p2.js';
import {buildHEarthRun8ER2ImmutableLiveRenderPackage,evaluateHEarthRun8ER2ImmutableLiveRenderPackage} from '../../render/live-render-package.run8e-r2.js';
import {H_EARTH_GEN311_ESTATE_PLACEMENT_POLICY as policy} from '../../../../../h-earth-3d/environment/h-earth.gen2514-qualified-placement-authority.js';
const failures=[];const check=(ok,label)=>{if(!ok)failures.push(label);};
check(hash(old.meshDiagnostics.ocean)===hash(p.componentResults.distantContext.meshDiagnostics.ocean),'ocean geometry unchanged');
let seamVertexTotal=0,badSeamVertices=0,maxFloat32SeamResidual=0;
for(const v of far.vertices){let onEdge=false,best=Infinity,floatBest=Infinity;for(const [a,b] of edges){const dx=b.x-a.x,dz=b.z-a.z,t=((v.x-a.x)*dx+(v.z-a.z)*dz)/(dx*dx+dz*dz);if(t< -1e-8||t>1+1e-8||Math.hypot(v.x-a.x-t*dx,v.z-a.z-t*dz)>1e-7)continue;onEdge=true;best=Math.min(best,Math.abs(v.y-a.y-t*(b.y-a.y)));const A={x:Math.fround(a.x),y:Math.fround(a.y),z:Math.fround(a.z)},B={x:Math.fround(b.x),y:Math.fround(b.y),z:Math.fround(b.z)},V={x:Math.fround(v.x),y:Math.fround(v.y),z:Math.fround(v.z)},DX=B.x-A.x,DZ=B.z-A.z,T=((V.x-A.x)*DX+(V.z-A.z)*DZ)/(DX*DX+DZ*DZ);floatBest=Math.min(floatBest,Math.hypot(V.x-A.x-T*DX,V.y-A.y-T*(B.y-A.y),V.z-A.z-T*DZ));}if(onEdge){seamVertexTotal++;if(best>1e-7)badSeamVertices++;maxFloat32SeamResidual=Math.max(maxFloat32SeamResidual,floatBest);}}
check(seamVertexTotal>=349&&badSeamVertices===0,'all located seam vertices welded');check(maxFloat32SeamResidual<0.0002,'Float32 seam residual below 0.2mm');report({seamVertexTotal,badSeamVertices,maxFloat32SeamResidual});
const sector=buildHEarthLandscapeSector({terrainPrimitive:p.componentResults.terrain.primitive}),reverse=buildHEarthLandscapeSector({terrainPrimitive:p.componentResults.terrain.primitive,reverseGenerationOrder:true});
check(sector.eligible,'sector eligible');check(hash(sector)===hash(reverse),'order-independent complete sector');
// Independently intersect actual Float32 triangles; no use of builder ground sampler.
const fnt=nt.map(({points})=>points.map(v=>({x:Math.fround(v.x),y:Math.fround(v.y),z:Math.fround(v.z)})));
function height(x,z){for(const [a,b,c] of fnt){const D=cross(a,b,c),u=cross({x,z},b,c)/D,v=cross(a,{x,z},c)/D,w=1-u-v;if(Math.min(u,v,w)>=-1e-8)return u*a.y+v*b.y+w*c.y;}return NaN;}
const trees=sector.manifest.filter(x=>x.kind==='TREE'),rocks=sector.manifest.filter(x=>x.kind==='ROCK'),bark=sector.primitives.find(p=>p.primitiveId.endsWith('BARK')).geometry,stone=sector.primitives.find(p=>p.primitiveId.endsWith('ROCK')).geometry;
let maxAnchorResidual=0,maxRootAbove=-Infinity,minRootAbove=Infinity,rockUnsupported=0;
for(const [i,t] of trees.entries()){maxAnchorResidual=Math.max(maxAnchorResidual,Math.abs(t.y-height(t.x,t.z)));for(const v of bark.vertices.slice(t.barkVertexStart,t.barkVertexStart+6)){const h=Math.fround(v.y)-height(Math.fround(v.x),Math.fround(v.z));maxRootAbove=Math.max(maxRootAbove,h);minRootAbove=Math.min(minRootAbove,h);}}
for(const [i,r] of rocks.entries()){const vs=stone.vertices.slice(r.stoneVertexStart,r.stoneVertexStart+26);const lower=vs.filter(v=>v.y<r.y);if(!lower.length||lower.every(v=>Math.fround(v.y)>height(Math.fround(v.x),Math.fround(v.z))))rockUnsupported++;}
let minimumSupportBurial=Infinity,supportSamples=0;
for(const t of sector.manifest){const g=t.kind==='TREE'?bark:stone,start=t.kind==='TREE'?t.barkVertexStart:t.stoneVertexStart+1,n=t.kind==='TREE'?6:8;for(let i=0;i<n;i++){const a=g.vertices[start+i],b=g.vertices[start+(i+1)%n];for(let j=0;j<=16;j++){const f=j/16,x=Math.fround(a.x)+(Math.fround(b.x)-Math.fround(a.x))*f,z=Math.fround(a.z)+(Math.fround(b.z)-Math.fround(a.z))*f,y=Math.fround(a.y)+(Math.fround(b.y)-Math.fround(a.y))*f;const burial=height(x,z)-y;check(Number.isFinite(burial),'support sample finite');minimumSupportBurial=Math.min(minimumSupportBurial,burial);supportSamples++;}}}
check(minimumSupportBurial>=0.11999,'actual Float32 support ring has minimum 0.12m burial');report({minimumSupportBurial,supportSamples,supportMethod:'independent Float32 terrain intersection at 17 points per basal edge'});
check(maxAnchorResidual<1e-5,'manifest grounded to Float32 triangles');check(maxRootAbove<=0.001,'all trunk base perimeter vertices buried');check(rockUnsupported===0,'rocks intersect ground');
function segmentDist(x,z,a,b){let dx=b.x-a.x,dz=b.z-a.z,t=Math.max(0,Math.min(1,((x-a.x)*dx+(z-a.z)*dz)/(dx*dx+dz*dz)));return Math.hypot(x-a.x-t*dx,z-a.z-t*dz);}
let footprintViolations=0;for(const t of sector.manifest){const {x,z,crownRadius:r}=t,b=sector.diagnostics.bounds;if(x-r<b.minX||x+r>b.maxX||z-r<b.minZ||z+r>b.maxZ)footprintViolations++;for(const b of [policy.manorCore,policy.gardens,policy.outbuildingProposal,policy.acceptedEnvelope,policy.viewProposal])if(Math.hypot(x-Math.max(b.minX,Math.min(b.maxX,x)),z-Math.max(b.minZ,Math.min(b.maxZ,z)))<=r)footprintViolations++;for(let i=1;i<policy.footRoute.length;i++)if(segmentDist(x,z,policy.footRoute[i-1],policy.footRoute[i])<=r+policy.footRouteRadius)footprintViolations++;}
check(footprintViolations===0,'reservation footprints');
const pkg=buildHEarthRun8ER2ImmutableLiveRenderPackage({deferVegetation:true}),evaluation=evaluateHEarthRun8ER2ImmutableLiveRenderPackage(pkg);check(pkg.eligible,'live package eligibility');for(const span of pkg.primitiveSpans??[]){if(span.primitiveId.includes('LANDSCAPE_P2')||span.primitiveId.includes('FAR_LAND'))check(span.role!=='SHORELINE','dry geometry excludes water role:'+span.primitiveId);}check(evaluation.eligible,'live package evaluation');
const gpu=createHEarthRun8ER2DCanonicalGPUUploadViews(pkg);const sectorMaterialChecks=[];
for(const [suffix,expectedRole] of [['BARK',5],['CANOPY',3],['ROCK',5]]){const span=pkg.primitiveSpans.find(s=>s.primitiveId===`H_EARTH_LANDSCAPE_P2_${suffix}`);check(!!span,`sector span exists:${suffix}`);if(!span)continue;let mismatches=0;for(let i=span.vertexStart;i<span.vertexStart+span.vertexCount;i++)if(pkg.buffers.materialParameters[i*4+3]!==2||pkg.buffers.roleCodes[i]!==expectedRole||gpu.materialParameters[i*4+3]!==2||gpu.roleCodes[i]!==expectedRole)mismatches++;check(mismatches===0,`sector explicit material survives GPU transport:${suffix}`);sectorMaterialChecks.push({suffix,expectedRole,vertexCount:span.vertexCount,mismatches,expectedMaterialW:2});}report({sectorMaterialChecks});
const sectorColorChecks=[];const linearFromByte=v=>{const u=v/255;return u<=0.04045?u/12.92:((u+0.055)/1.055)**2.4;};
for(const source of sector.primitives){const span=pkg.primitiveSpans.find(s=>s.primitiveId===source.primitiveId);if(!span)continue;let immutableColorMismatches=0,gpuColorMismatches=0,vertexOrderMismatches=0,maxImmutableResidual=0,maxGPUResidual=0;for(let local=0;local<span.vertexCount;local++){const vertex=span.vertexStart+local,rgba=source.renderMaterial.vertexRgba[local],v=source.geometry.vertices[local];for(let c=0;c<4;c++){const expected=c===3?rgba[c]/255:linearFromByte(rgba[c]),actual=pkg.buffers.baseColorsLinear[vertex*4+c],actualGPU=gpu.baseColorsLinear[vertex*4+c],e=Math.abs(actual-expected),eg=Math.abs(actualGPU-Math.fround(expected));maxImmutableResidual=Math.max(maxImmutableResidual,e);maxGPUResidual=Math.max(maxGPUResidual,eg);if(e>1e-12)immutableColorMismatches++;if(eg>1e-9)gpuColorMismatches++;}for(const [c,k] of ['x','y','z'].entries())if(gpu.positions[vertex*3+c]!==Math.fround(v[k]))vertexOrderMismatches++;}check(immutableColorMismatches===0&&gpuColorMismatches===0&&vertexOrderMismatches===0,`sector source colors and vertex order survive admission/GPU:${source.primitiveId}`);sectorColorChecks.push({primitiveId:source.primitiveId,vertexCount:span.vertexCount,immutableColorMismatches,gpuColorMismatches,vertexOrderMismatches,maxImmutableResidual,maxGPUResidual});}report({sectorColorChecks});
report({sector:sector.diagnostics,maxAnchorResidual,maxRootAbove,minRootAbove,rockUnsupported,footprintViolations,package:{eligible:pkg.eligible,issues:pkg.issues,evaluation,primitiveCount:pkg.primitiveCount,triangleCount:pkg.triangleCount,vertexCount:pkg.vertexCount,roles:pkg.roleCounts,spans:pkg.primitiveSpans}});
console.log(JSON.stringify({schema:'H_EARTH_LANDSCAPE_P2_INDEPENDENT_QUALIFICATION_v1',results,failures,physicalDeviceAcceptance:'PENDING',passed:!process.exitCode&&failures.length===0},null,2));if(failures.length)process.exitCode=1;
