#!/usr/bin/env node
import fs from'node:fs';import path from'node:path';import cp from'node:child_process';import{fileURLToPath}from'node:url';import{assess,stable}from'./progressive-system-continuity-gate.v1.mjs';
const PROTOCOL='.github/ai-router/system-continuity/progressive-system-continuity-protocol.v1.json',REGISTRY='.github/ai-router/system-continuity/gap-registry.v1.json',WORKFLOW='.github/workflows/progressive-system-continuity-v1.yml';
const proof=(status='PASS',tag='p')=>({status,refs:status==='PASS'?[`SELF_TEST:${tag}`]:[]});
function root(){let c=path.dirname(fileURLToPath(import.meta.url));for(;;){if(fs.existsSync(path.join(c,'AI_ENTRYPOINT.json')))return c;let p=path.dirname(c);if(p===c)throw Error('ROOT_NOT_FOUND');c=p}}
const read=(r,p)=>JSON.parse(fs.readFileSync(path.join(r,p),'utf8'));
function request(head){return{schema:'PROGRESSIVE_SYSTEM_CONTINUITY_ASSESSMENT_REQUEST_v1',assessmentId:'BASE',subjectHead:head,systemId:'SYNTHETIC_SYSTEM',changedPaths:['.github/ai-router/system-continuity/synthetic.v1.json'],interfaceKeys:['SYNTHETIC_INTERFACE'],relatedGapIds:[],producerContracts:[{contractId:'P',operationIdPolicy:'STABLE_OPERATION_ID',outputReceiptSchemas:['SYNTHETIC_RECEIPT_v1'],interfaceKeys:['SYNTHETIC_INTERFACE']}],consumerContracts:[{contractId:'C',operationIdPolicy:'EXACT_REGISTERED_OPERATION_ID',acceptedReceiptSchemas:['SYNTHETIC_RECEIPT_v1'],interfaceKeys:['SYNTHETIC_INTERFACE']}],edges:[{edgeId:'P_C',producerContractId:'P',consumerContractId:'C',producerReceiptSchema:'SYNTHETIC_RECEIPT_v1'}],adapters:[],proofs:{localCorrectness:proof('PASS','local'),interfaceCompatibility:proof('PASS','interface'),transitionSimulation:proof('PASS','transition'),remoteInvocation:proof('PASS','remote'),postMergeContinuity:proof('PASS','postmerge')},requestedClosure:'SYSTEM_GAP_CLOSED'}}
function test(id,fn){try{let d=fn();return{id,pass:d?.pass===true,detail:d}}catch(e){return{id,pass:false,detail:{error:e.message}}}}
function main(){let a=process.argv.slice(2);if(a.length!==2||a[0]!=='--output')throw Error('USAGE');let out=a[1],r=root(),protocol=read(r,PROTOCOL),registry=read(r,REGISTRY),entry=read(r,'AI_ENTRYPOINT.json'),head=cp.spawnSync('git',['rev-parse','HEAD^{commit}'],{cwd:r,encoding:'utf8'}).stdout.trim(),tests=[];
 tests.push(test('ROOT_INTEGRATION',()=>({pass:protocol.protocolId==='REPOSITORY_PROGRESSIVE_SYSTEM_CONTINUITY_TRACK_v1'&&entry.systemContinuityTrack?.protocol===PROTOCOL&&entry.systemContinuityTrack?.status==='ACTIVE_FAIL_CLOSED'&&entry.systemContinuityTrack?.mandatoryFor?.includes('SYSTEM_GAP_CLOSED_CLAIM')&&fs.existsSync(path.join(r,WORKFLOW))})));
 tests.push(test('ROUTER_INFRASTRUCTURE_ROUTE',()=>{let p=path.join(process.env.RUNNER_TEMP||'/tmp','psc-router.json'),x=cp.spawnSync(process.execPath,['tools/repository-ai-entry-router.mjs','--path',WORKFLOW,'--output',p],{cwd:r,encoding:'utf8'}),q=fs.existsSync(p)?JSON.parse(fs.readFileSync(p)):null;return{pass:x.status===0&&q?.routes?.[0]?.projectId==='REPOSITORY_AI_ROUTER_INFRASTRUCTURE'&&q?.routes?.[0]?.disposition==='PASS'}}));
 tests.push(test('LOCAL_NOT_SYSTEM_CLOSURE',()=>{let q=request(head);q.requestedClosure='LOCAL_CAPABILITY_CLOSED';q.proofs.remoteInvocation=proof('NOT_PROVEN');q.proofs.postMergeContinuity=proof('NOT_PROVEN');let x=assess(q,registry);return{pass:x.result==='PASS'&&x.systemClosureGranted===false}}));
 tests.push(test('FULL_SYSTEM_CLOSURE',()=>{let x=assess(request(head),registry);return{pass:x.result==='PASS'&&x.classification==='SYSTEM_GAP_CLOSED'&&x.systemClosureGranted===true}}));
 tests.push(test('REMOTE_PROOF_REQUIRED',()=>{let q=request(head);q.proofs.remoteInvocation=proof('NOT_PROVEN');let x=assess(q,registry);return{pass:x.result==='BLOCK'&&x.errorCode==='REMOTE_INVOCATION_PROOF_MISSING'}}));
 tests.push(test('SCHEMA_MISMATCH_BLOCKS',()=>{let q=request(head);q.consumerContracts[0].acceptedReceiptSchemas=['OTHER_v1'];let x=assess(q,registry);return{pass:x.result==='BLOCK'&&x.errorCode==='PRODUCER_CONSUMER_INTERFACE_MISMATCH'}}));
 tests.push(test('OPERATION_ID_MISMATCH_BLOCKS',()=>{let q=request(head);q.producerContracts[0].operationIdPolicy='FRESH_SUCCESSOR_OPERATION_ID_REQUIRED';let x=assess(q,registry);return{pass:x.result==='BLOCK'&&x.errorCode==='PRODUCER_CONSUMER_INTERFACE_MISMATCH'}}));
 tests.push(test('PROVEN_ADAPTER_BRIDGES',()=>{let q=request(head);q.requestedClosure='INTERFACE_CONTINUITY_CLOSED';q.producerContracts[0].operationIdPolicy='FRESH_SUCCESSOR_OPERATION_ID_REQUIRED';q.consumerContracts[0].acceptedReceiptSchemas=['ADAPTED_v1'];q.edges[0].adapterId='A';q.adapters=[{adapterId:'A',status:'PROVEN',fromOperationIdPolicy:'FRESH_SUCCESSOR_OPERATION_ID_REQUIRED',toOperationIdPolicy:'EXACT_REGISTERED_OPERATION_ID',fromReceiptSchema:'SYNTHETIC_RECEIPT_v1',toReceiptSchema:'ADAPTED_v1',evidenceRefs:['SELF_TEST:adapter']}];let x=assess(q,registry);return{pass:x.result==='PASS'&&x.classification==='INTERFACE_CONTINUITY_CLOSED'}}));
 tests.push(test('OPEN_GAP_REQUIRES_RECONCILIATION',()=>{let g=structuredClone(registry);g.records.push({gapId:'SELF_TEST_OPEN_GAP',status:'OPEN',discoveredAtHead:'0'.repeat(40),summary:'self test',interfaceKeys:['SYNTHETIC_INTERFACE'],pathScopes:['self-test/'],evidenceRefs:['SELF_TEST'],closureRequirements:['RECONCILE'],authorityCreated:false});let x=assess(request(head),g);return{pass:x.result==='BLOCK'&&['ACTIVE_GAP_RECONCILIATION_REQUIRED','RELATED_OPEN_GAP_PREVENTS_SYSTEM_CLOSURE'].includes(x.errorCode)}}));
 tests.push(test('NO_AUTHORITY_CREATED',()=>{let x=assess(request(head),registry),keys=['repositoryWritesAuthorized','lifecycleAuthorityGranted','terminalClosureAuthorityGranted','successorAuthorityGranted','mergeAuthorityGranted','deploymentAuthorityGranted','productMutationAuthorityGranted','semanticAuthorityGranted','scientificClaimAuthorityGranted','genericCommandAuthority'];return{pass:keys.every(k=>x[k]===false)}}));
 let bad=tests.filter(x=>!x.pass),receipt=stable({schema:'PROGRESSIVE_SYSTEM_CONTINUITY_SELF_TEST_RECEIPT_v2',result:bad.length?'FAIL':'PASS',head,scenarioCount:tests.length,passedCount:tests.length-bad.length,failedCount:bad.length,scenarios:tests,duplicateRootTopologyRequired:false,productMutationPerformed:false,repositoryMutationPerformedBySelfTest:false,lifecycleMutationPerformed:false,genericCommandAuthority:false});fs.mkdirSync(path.dirname(path.resolve(out)),{recursive:true});fs.writeFileSync(out,JSON.stringify(receipt,null,2)+'\n');process.stdout.write(JSON.stringify(receipt,null,2)+'\n');if(bad.length)process.exitCode=1}
try{main()}catch(e){process.stderr.write(JSON.stringify({schema:'PROGRESSIVE_SYSTEM_CONTINUITY_SELF_TEST_RECEIPT_v2',result:'FAIL',error:e.message},null,2)+'\n');process.exitCode=1}
