import {fileURLToPath} from 'node:url';
import {OPERATION_ID,SOURCE_MODES,sha256,stable,assert,writeCanonicalJson} from './causal-evidence-adapter.v1.mjs';
export const MAXIMUM_SEEDS_PER_SHARD=64;
export const MAXIMUM_SHARDS_PER_WAVE=128;
export const MAXIMUM_PARALLEL_SHARDS=8;
export function planMode(manifest,{shardSize=MAXIMUM_SEEDS_PER_SHARD,maxShardsPerWave=MAXIMUM_SHARDS_PER_WAVE}={}){assert(SOURCE_MODES.includes(manifest.sourceMode),'SOURCE_MODE_INVALID');assert(Number.isInteger(manifest.eligibleSeedCount)&&manifest.eligibleSeedCount>=0,'ELIGIBLE_COUNT_INVALID');assert(shardSize===64,'SHARD_SIZE_NOT_FROZEN');assert(maxShardsPerWave===128,'WAVE_SIZE_NOT_FROZEN');const shards=[];for(let start=0,index=0;start<manifest.eligibleSeedCount;start+=shardSize,index++){const end=Math.min(manifest.eligibleSeedCount-1,start+shardSize-1),expectedSeedCount=end-start+1;shards.push(stable({sourceMode:manifest.sourceMode,eligibleSeedListDigest:manifest.eligibleSeedListDigest,terrainPartitionDigest:manifest.terrainPartitionDigest,shardIndex:index,seedIndexStart:start,seedIndexEnd:end,expectedSeedCount,expectedConfigurationCount:expectedSeedCount*36,waveIndex:Math.floor(index/maxShardsPerWave)}))}const waves=[];for(let first=0,waveIndex=0;first<shards.length;first+=maxShardsPerWave,waveIndex++){const members=shards.slice(first,first+maxShardsPerWave),expectedConfigurationCount=members.reduce((s,x)=>s+x.expectedConfigurationCount,0);waves.push(stable({schema:'H_EARTH_INTER_HILL_ESTATE_V2_DETERMINISTIC_WAVE_MANIFEST_v1',operationId:OPERATION_ID,sourceMode:manifest.sourceMode,eligibleSeedListDigest:manifest.eligibleSeedListDigest,totalEligibleSeedCount:manifest.eligibleSeedCount,configurationDenominator:manifest.configurationDenominator,shardSizeRule:'FIXED_MAXIMUM_64_ONLY_FINAL_SHARD_MAY_BE_SMALLER',firstShardIndex:members[0]?.shardIndex??null,finalShardIndex:members.at(-1)?.shardIndex??null,shardCount:members.length,waveIndex,expectedConfigurationCount,predecessorWaveIndex:waveIndex===0?null:waveIndex-1,artifactNamingConvention:'h-earth-v2-causal-001-<epoch>-<source-mode>-wave-<wave>-shard-<shard>-<digest>',shards:members}))}return {sourceMode:manifest.sourceMode,eligibleSeedCount:manifest.eligibleSeedCount,configurationDenominator:manifest.configurationDenominator,shardCount:shards.length,waveCount:waves.length,shards,waves}}
export function validateExecutionPlan(plan){const seen=new Set;for(const mode of plan.modes){let next=0;for(const shard of mode.shards){assert(shard.seedIndexStart===next,'SHARD_GAP_OR_OVERLAP',`${mode.sourceMode}:${shard.shardIndex}`);assert(shard.seedIndexEnd>=shard.seedIndexStart,'SHARD_RANGE_INVALID');for(let i=shard.seedIndexStart;i<=shard.seedIndexEnd;i++){assert(!seen.has(`${mode.sourceMode}:${i}`),'DUPLICATE_SEED_INDEX');seen.add(`${mode.sourceMode}:${i}`)}next=shard.seedIndexEnd+1}assert(next===mode.eligibleSeedCount,'SHARD_DOMAIN_INCOMPLETE');assert(mode.shards.reduce((s,x)=>s+x.expectedConfigurationCount,0)===mode.configurationDenominator,'CONFIGURATION_DENOMINATOR_MISMATCH');for(const wave of mode.waves)assert(wave.shardCount<=128,'MATRIX_JOB_LIMIT_EXCEEDED')}return true}
export function planExecution(manifests,{outputFile=null}={}){assert(Array.isArray(manifests)&&manifests.length===2,'TWO_SOURCE_MODES_REQUIRED');const byMode=new Map(manifests.map(m=>[m.sourceMode,m]));const modes=SOURCE_MODES.map(mode=>planMode(byMode.get(mode))),waves=[];let globalWaveIndex=0,predecessor=null;for(const mode of modes)for(const wave of mode.waves){const w=stable({...wave,globalWaveIndex,workflowRunSequenceIdentity:`${mode.sourceMode}:WAVE:${wave.waveIndex}`,predecessorGlobalWaveIndex:predecessor});w.waveManifestDigest=sha256(w);waves.push(w);predecessor=globalWaveIndex;globalWaveIndex++}const plan=stable({schema:'H_EARTH_INTER_HILL_ESTATE_V2_FROZEN_EXECUTION_PLAN_v1',operationId:OPERATION_ID,shardSize:64,maxShardsPerWave:128,maxParallelShards:8,sourceModeOrder:SOURCE_MODES,modes,waves,waveCount:waves.length,totalEligibleSeedCount:modes.reduce((s,x)=>s+x.eligibleSeedCount,0),totalConfigurationDenominator:modes.reduce((s,x)=>s+x.configurationDenominator,0)});plan.executionPlanDigest=sha256(plan);validateExecutionPlan(plan);if(outputFile)writeCanonicalJson(outputFile,plan);return plan}
if(process.argv[1]===fileURLToPath(import.meta.url))console.log(JSON.stringify(planMode({sourceMode:SOURCE_MODES[0],eligibleSeedCount:Number(process.argv[2]??0),configurationDenominator:Number(process.argv[2]??0)*36,eligibleSeedListDigest:'0'.repeat(64),terrainPartitionDigest:'1'.repeat(64)})))
