import crypto from 'node:crypto';
import {H_EARTH_PLANETARY_WORLD_FRAME,H_EARTH_PLANETARY_WORLD_FRAME_CONTRACT_ID,regionToHEarthPlanetPoint,getHEarthDerivedHorizonDistance} from '../../showroom/globe/h-earth/render/planetary-world-frame.js';
import {constructHEarthDistantContextGeometry,H_EARTH_PLANET_BODY_HORIZON_SHELL_ID} from '../../showroom/globe/h-earth/render/geometry-distant-context.js';
import {previewHEarthFunctionalLandscape} from '../../showroom/globe/h-earth/render/landscape-preview.js';
import {createHEarthFunctionalLandscapeNavigationState,proposeHEarthFunctionalLandscapeNavigation} from '../../showroom/globe/h-earth/functional-landscape/navigation.js';
import {createHEarthRun8ER3AFrameUniformPacket,evaluateHEarthRun8ER3AFrameUniformPacket} from '../../showroom/globe/h-earth/render/live-renderer-contract.run8e-r3a.js';
import {getHEarthOW01CanonicalLiveRenderPackageOccurrence} from '../../showroom/globe/h-earth/render/live-render-package.run8e-r2.canonical.js';
const OPERATION_ID='H_EARTH_SINGLE_SPHERICAL_WORLD_MANIFOLD_SUCCESSOR_20260819_001',PROTECTED_PARENT='217887b52ee4906c01a51c432cca02c5c6dbb16d',issues=[];
const diagnostics={localSphereChecks:0,formerBoundaryChecks:0,previewChecks:0,oceanChecks:0,fixedWorldChecks:0,cameraFrameChecks:0,adjacentCameraChecks:0,canonicalPackageChecks:0,maximumOceanRadius:0,maximumDerivedHorizon:0,maximumAdjacentCameraDisplacement:0,minimumLocalCurvatureFalloff:Infinity,worldHashA:null,worldHashB:null};
const fail=(condition,code)=>{if(!condition)issues.push(code)},finite=v=>typeof v==='number'&&Number.isFinite(v),hash=v=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex'),distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z),radial=v=>Math.hypot(v.x,v.z);
fail(H_EARTH_PLANETARY_WORLD_FRAME_CONTRACT_ID==='H_EARTH_SINGLE_SPHERICAL_WORLD_MANIFOLD_v1','SINGLE_SPHERICAL_FRAME_CONTRACT_MISMATCH');fail(H_EARTH_PLANETARY_WORLD_FRAME.exactSphereRadius===420000,'PLANET_RADIUS_DRIFT');fail(H_EARTH_PLANETARY_WORLD_FRAME.protectedTangentRadius===0&&H_EARTH_PLANETARY_WORLD_FRAME.transitionWidth===0,'PLANAR_LOCAL_PATCH_NOT_RETIRED');fail(H_EARTH_PLANETARY_WORLD_FRAME.layeredPlanarContinuationProhibited===true,'LAYERED_PLANAR_CONTINUATION_NOT_PROHIBITED');
for(const r of [40,120,360,780,1099,1100,1101,1699,1700,1701,3000,6000]){const q=regionToHEarthPlanetPoint({x:r,y:0,z:0}),expected=(H_EARTH_PLANETARY_WORLD_FRAME.exactSphereRadius)*Math.cos(r/H_EARTH_PLANETARY_WORLD_FRAME.exactSphereRadius)-H_EARTH_PLANETARY_WORLD_FRAME.exactSphereRadius;diagnostics.localSphereChecks++;fail(Math.abs(q.y-expected)<1e-8,`POINT_NOT_EXACT_SPHERE:${r}`);if(r>=360)diagnostics.minimumLocalCurvatureFalloff=Math.min(diagnostics.minimumLocalCurvatureFalloff,-q.y);if([1099,1100,1101,1699,1700,1701].includes(r))diagnostics.formerBoundaryChecks++}
fail(diagnostics.minimumLocalCurvatureFalloff>0,'LOCAL_PRESENTATION_REMAINS_PLANAR');
const dA=constructHEarthDistantContextGeometry({cameraWorld:{x:0,y:120,z:-40}}),dB=constructHEarthDistantContextGeometry({cameraWorld:{x:180,y:165,z:-220}});fail(dA?.ok===true,'DISTANT_CONTEXT_A_INVALID');fail(dB?.ok===true,'DISTANT_CONTEXT_B_INVALID');fail(dA?.planetBodyHorizonShellMaterialized===false,'SEPARATE_PLANET_BODY_SHELL_RETAINED');fail(dA?.separateVisiblePlanetBodySubstitute===false,'VISIBLE_PLANET_BODY_SUBSTITUTE_RETAINED');fail(dA?.singleContinuousOceanToHorizon===true,'CONTINUOUS_OCEAN_FLAG_MISSING');const oceanA=dA?.primitives?.find(p=>p.metadata?.farSurfaceClass==='OCEAN'),oceanB=dB?.primitives?.find(p=>p.metadata?.farSurfaceClass==='OCEAN'),landA=dA?.primitives?.find(p=>p.metadata?.farSurfaceClass==='LAND');fail(Boolean(oceanA)&&Boolean(landA)&&dA.primitives.length===2,'DISTANT_SURFACE_COUNT_INVALID');fail(Boolean(oceanB),'DISTANT_OCEAN_B_MISSING');if(oceanA&&oceanB){diagnostics.oceanChecks++;fail(oceanA.metadata?.singleContinuousOceanToHorizon===true,'OCEAN_NOT_SINGLE_CONTINUOUS_SURFACE');diagnostics.maximumOceanRadius=Math.max(...oceanA.geometry.vertices.map(radial));diagnostics.maximumDerivedHorizon=getHEarthDerivedHorizonDistance(240);fail(diagnostics.maximumOceanRadius>15000,'OCEAN_HORIZON_ENVELOPE_TOO_SHORT');fail(diagnostics.maximumOceanRadius>diagnostics.maximumDerivedHorizon,'OCEAN_DOES_NOT_COVER_ELEVATED_HORIZON');diagnostics.worldHashA=hash(oceanA.geometry.vertices);diagnostics.worldHashB=hash(oceanB.geometry.vertices);diagnostics.fixedWorldChecks++;fail(diagnostics.worldHashA===diagnostics.worldHashB,'OCEAN_WORLD_RECENTERED_FOR_CAMERA')}
const pA=previewHEarthFunctionalLandscape({cameraWorld:{x:0,y:120,z:-40}}),pB=previewHEarthFunctionalLandscape({cameraWorld:{x:180,y:165,z:-220}});fail(pA?.ok===true,'LANDSCAPE_PREVIEW_A_INVALID');fail(pB?.ok===true,'LANDSCAPE_PREVIEW_B_INVALID');if(pA?.ok&&pB?.ok){diagnostics.previewChecks++;for(const predicate of [pA.singleSphericalPresentationManifold===true,pA.planarLocalPresentationRetained===false,pA.localFarRepresentationSwitch===false,pA.separateVisiblePlanetBodySubstitute===false,pA.componentResults?.terrain?.primitive?.metadata?.singleSphericalPresentationManifold===true,(pA.componentResults?.shoreline?.primitives??[]).every(x=>x.metadata?.singleSphericalPresentationManifold===true)])fail(predicate,`PREVIEW_SINGLE_MANIFOLD_INVARIANT_FAILED:${diagnostics.previewChecks++}`);const signature=preview=>hash(preview.primitives.map(p=>({id:p.primitiveId,v:p.geometry.vertices,i:p.geometry.indices})));diagnostics.fixedWorldChecks++;fail(signature(pA)===signature(pB),'PREVIEW_WORLD_GEOMETRY_CHANGED_WITH_CAMERA')}
let nav=createHEarthFunctionalLandscapeNavigationState({waypointId:'COAST'});fail(nav?.ok===true,'NAVIGATION_INITIALIZATION_FAILED');if(nav?.ok===true){let state=nav.state,previousPacket=null;for(let i=1;i<=24;i++){const action=i%6===0?'TURN_RIGHT':i%4===0?'STRAFE_RIGHT':i%2===0?'MOVE_BACKWARD':'MOVE_FORWARD',proposal=proposeHEarthFunctionalLandscapeNavigation(state,{action,magnitude:action.startsWith('MOVE')||action.startsWith('STRAFE')?3:undefined,degrees:action.startsWith('TURN')?4:undefined});if(proposal?.ok===true)state=proposal.state;const packet=createHEarthRun8ER3AFrameUniformPacket({navigationState:state,viewport:{width:1280,height:720,pixelRatio:1},frameSequence:i}),evaluation=evaluateHEarthRun8ER3AFrameUniformPacket(packet);diagnostics.cameraFrameChecks++;fail(evaluation.eligible===true,`R3A_PACKET_INVALID:${i}:${evaluation.issues.join('|')}`);fail(packet.singleSphericalPresentationManifold===true&&packet.cameraAndWorldSharePlanetaryFrame===true,`CAMERA_WORLD_FRAME_SPLIT:${i}`);const expected=regionToHEarthPlanetPoint(packet.camera.localAuthoringPosition);fail(distance(expected,packet.camera.position)<1e-8,`CAMERA_NOT_PROJECTED_BY_WORLD_FRAME:${i}`);fail(packet.presentationCameraY>=packet.navigationCameraY-1e-9,`GEN325_CAMERA_FLOOR_REGRESSION:${i}`);if(previousPacket){const step=distance(previousPacket.camera.position,packet.camera.position);diagnostics.maximumAdjacentCameraDisplacement=Math.max(diagnostics.maximumAdjacentCameraDisplacement,step);diagnostics.adjacentCameraChecks++;fail(step<20,`ADJACENT_CAMERA_DISCONTINUITY:${i}:${step}`)}previousPacket=packet}}
const live=getHEarthOW01CanonicalLiveRenderPackageOccurrence();fail(live?.eligible===true,'CANONICAL_LIVE_PACKAGE_REJECTED');if(live?.eligible===true){diagnostics.canonicalPackageChecks++;fail(!(live.primitiveIds??[]).some(id=>id.includes('HORIZON_DEPTH_SHELL')),'CANONICAL_PACKAGE_RETAINS_OLD_SHELL');const farOcean=(live.drawRanges??[]).filter(r=>(r.primitiveIds??[]).includes('H_EARTH_WORLD_MANIFOLD:FAR_OCEAN_CONTINUATION'));fail(farOcean.length===1,'CANONICAL_PACKAGE_OCEAN_DRAW_RANGE_INVALID');diagnostics.canonicalPackageChecks++}
const receipt={schema:'H_EARTH_SINGLE_SPHERICAL_WORLD_MANIFOLD_RECEIPT_v1',operationId:OPERATION_ID,protectedParentHead:PROTECTED_PARENT,result:issues.length===0?'PASS':'FAIL',planetaryWorldFrameContractId:H_EARTH_PLANETARY_WORLD_FRAME_CONTRACT_ID,retiredPlanetBodyShellId:H_EARTH_PLANET_BODY_HORIZON_SHELL_ID,diagnostics,issues};receipt.receiptSha256=hash(receipt);process.stdout.write(JSON.stringify(receipt));if(issues.length)process.exitCode=1;
