import fs from 'node:fs';import {execFileSync} from 'node:child_process';
const arg=n=>{const i=process.argv.indexOf(n);if(i<0||!process.argv[i+1])throw new Error('MISSING_'+n.replace(/^--/,'').toUpperCase());return process.argv[i+1]};
const candidate=arg('--candidate-head'),holder=arg('--execution-holder'),output=arg('--output');
if(candidate!=='eb583cde58b05a01452f6a93f49381ba65cb5130')throw new Error('CANDIDATE_HEAD_NOT_AUTHORIZED');
const root=process.cwd(),work=process.env.RUNNER_TEMP+'/auren-c2-'+Date.now();fs.mkdirSync(work,{recursive:true});
execFileSync('git',['worktree','add','--detach',work,candidate],{cwd:root,stdio:'inherit'});
let result='FAIL',checks=[],failures=[];
try{const changed=execFileSync('git',['diff','--name-only','2f5a1c67ba49c5fa1c436d231cc7b04d2468497b',candidate],{cwd:root,encoding:'utf8'}).trim().split('\n').filter(Boolean);const allowed=new Set(['products/auren/auren.voice.js','products/auren/auren.chamber.js','products/auren/index.css','.github/live-qualification/verifiers/auren-c2-personality-performance.v1.mjs','.github/workflows/auren-c2-personality-performance-qualification.yml']);const bounded=changed.every(x=>allowed.has(x))&&!changed.some(x=>/^products\/auren\/auren\.room\./.test(x));checks.push({id:'C2_BOUNDED_DIFF',status:bounded?'PASS':'FAIL',evidence:{changed}});if(!bounded)failures.push('C2_BOUNDED_DIFF');const verifier=work+'/.github/live-qualification/verifiers/auren-c2-personality-performance.v1.mjs';if(!fs.existsSync(verifier))throw new Error('C2_VERIFIER_MISSING');execFileSync('node',['--check',verifier],{stdio:'inherit'});checks.push({id:'C2_VERIFIER_SYNTAX',status:'PASS'});result=failures.length?'FAIL':'PASS';}finally{try{execFileSync('git',['worktree','remove','--force',work],{cwd:root,stdio:'ignore'})}catch{}}
const receipt={schema:'AUREN_C2_STABLE_TRANSPORT_QUALIFICATION_RECEIPT_v1',result,operationId:'AUREN_C2_STABLE_TRANSPORT_QUALIFICATION_20260928_001',executionHolder:holder,candidateHead:candidate,checks,failures,sourceMutationPerformed:false,productMutationPerformed:false,branchCreated:false,mergePerformed:false,deploymentPerformed:false,releasePerformed:false,publicationPerformed:false};fs.writeFileSync(output,JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt,null,2));if(result!=='PASS')process.exitCode=1;
