#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { compileCanonicalPacket } from '../operation-intake/canonical-packet-compiler.v1.mjs';

function stable(value){if(Array.isArray(value))return value.map(stable);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(k=>[k,stable(value[k])]));return value}
function parseArgs(argv){const out={};for(let i=0;i<argv.length;i+=2){const k=argv[i],v=argv[i+1];if(!['--request-base64','--procedure-base64','--execution-holder','--output'].includes(k)||v===undefined)throw new Error('CLI_ARGUMENTS_NOT_CLOSED');out[k.slice(2)]=v}for(const k of ['request-base64','procedure-base64','execution-holder','output'])if(!out[k])throw new Error('CLI_ARGUMENTS_INCOMPLETE');return out}
function decodeJson(value,label){let text;try{text=Buffer.from(value,'base64').toString('utf8')}catch{throw new Error(label+'_BASE64_INVALID')}let parsed;try{parsed=JSON.parse(text)}catch{throw new Error(label+'_JSON_INVALID')}if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error(label+'_OBJECT_REQUIRED');return parsed}
function main(){const a=parseArgs(process.argv.slice(2));const compiled=compileCanonicalPacket(decodeJson(a['request-base64'],'REQUEST'),decodeJson(a['procedure-base64'],'PROCEDURE'));const payload=stable({schema:'CANONICAL_PACKET_COMPILER_EXECUTION_RECEIPT_v1',result:'PACKET_READY',executionHolder:a['execution-holder'],compilerReceipt:compiled.receipt,artifacts:{canonicalOperationRequest:compiled.request,canonicalConstructionProcedure:compiled.procedure,canonicalIntakeEnvelope:compiled.envelope,canonicalIntakeComment:compiled.comment},repositoryMutationPerformed:false,admissionAuthorityCreated:false,mutationAuthorityCreated:false,mergeAuthorityCreated:false,deploymentAuthorityCreated:false,releaseAuthorityCreated:false,publicationAuthorityCreated:false,authorityEffect:'NONE_PACKET_COMPILATION_ONLY'});fs.writeFileSync(path.resolve(a.output),JSON.stringify(payload,null,2)+'\n')}
const invoked=process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url);if(invoked){try{main()}catch(error){process.stderr.write(JSON.stringify({schema:'CANONICAL_PACKET_COMPILER_EXECUTION_FAILURE_v1',result:'FAIL_CLOSED',errorCode:error.code??error.message??'UNEXPECTED_FAILURE'})+'\n');process.exitCode=1}}
