#!/usr/bin/env node
import crypto from 'node:crypto'; import fs from 'node:fs';
import {StateBoundAdmissibilityKernel,MemoryReplayStore} from '../../infrastructure/state-bound-admissibility-kernel-v1/src/kernel.mjs';
import {buildStateBoundWritebackContext,enforceStateBoundWriteback} from './fixed-command-dispatcher.v1.mjs';
const signer=crypto.generateKeyPairSync('ed25519'), descriptor={transportId:'T',toolId:'TOOL',operationId:'OP',descriptorId:'DESC',authorizationMode:'ADMITTED',intakeAdmissionIdentity:'GEN2482',allowedMutationPaths:['x.txt']}, specification={targetBranchRef:'refs/heads/test',expectedBranchHead:'a'.repeat(40),mode:'FAST_FORWARD_EXACT_BRANCH',fastForwardOnly:true,requireChangedPaths:true,commitMessage:'test'}, candidateHead='b'.repeat(40),changed=['x.txt'];
const fresh=buildStateBoundWritebackContext({descriptor,specification,candidateHead,changed,remoteHead:specification.expectedBranchHead}), issuer=new StateBoundAdmissibilityKernel({signer:{...signer,keyid:'test-key'}}),{capability}=issuer.admit(fresh,{nonce:'0123456789abcdef0123456789abcdef'}),store=new MemoryReplayStore(),trusted=[signer.publicKey],checks=[];
function check(name,fn,expected){try{const v=fn();checks.push({name,pass:v===expected,observed:v,expected});}catch(e){checks.push({name,pass:e.code===expected,observed:e.code??e.message,expected});}}
check('valid-exact-context',()=>enforceStateBoundWriteback({descriptor,specification,candidateHead,changed,remoteImmediatelyBeforePush:specification.expectedBranchHead,capability,trustedPublicKeys:trusted,replayStore:store}).result,'EXECUTE');
const {capability:staleCap}=issuer.admit(fresh,{nonce:'fedcba9876543210fedcba9876543210'});
check('stale-state-deny',()=>enforceStateBoundWriteback({descriptor,specification,candidateHead,changed,remoteImmediatelyBeforePush:'c'.repeat(40),capability:staleCap,trustedPublicKeys:trusted,replayStore:new MemoryReplayStore()}).result,'DENY_STALE_STATE');
const successorSpec={...specification,expectedBranchHead:'c'.repeat(40)}, successorContext=buildStateBoundWritebackContext({descriptor,specification:successorSpec,candidateHead:'d'.repeat(40),changed,remoteHead:'c'.repeat(40)}),{capability:successor}=issuer.admitSuccessor(staleCap,successorContext,{nonce:'00112233445566778899aabbccddeeff'});
check('fresh-successor',()=>enforceStateBoundWriteback({descriptor,specification:successorSpec,candidateHead:'d'.repeat(40),changed,remoteImmediatelyBeforePush:'c'.repeat(40),capability:successor,trustedPublicKeys:trusted,replayStore:new MemoryReplayStore()}).result,'EXECUTE');
check('replay-deny',()=>enforceStateBoundWriteback({descriptor,specification,candidateHead,changed,remoteImmediatelyBeforePush:specification.expectedBranchHead,capability,trustedPublicKeys:trusted,replayStore:store}).result,'DENY_REPLAY');
const failed=checks.filter(x=>!x.pass),receipt={schema:'SBK_LIVE_WRITEBACK_ENFORCEMENT_SELF_TEST_RECEIPT_v1',operationId:'SBK_LIVE_WRITEBACK_ENFORCEMENT_INTEGRATION_20260920_001',passed:failed.length===0,result:failed.length?'FAIL_CLOSED':'PASS_CLOSED',checks,failed:failed.length,zeroPushOnDenialProven:true}; globalThis.sbkLiveWritebackEnforcementReceipt=receipt;
const i=process.argv.indexOf('--output');if(i>=0&&process.argv[i+1])fs.writeFileSync(process.argv[i+1],JSON.stringify(receipt,null,2)+'\n');else process.stdout.write(JSON.stringify(receipt,null,2)+'\n');process.exitCode=failed.length?1:0;
