#!/usr/bin/env node
import fs from 'node:fs';import cp from 'node:child_process';import path from 'node:path';
const C='6fa5041082a1133accb2cabbd0072e193c181ea9',P='preview/h-earth/corridor/38df744ba7402aabe7fd2eaee71b961a451350de/B/showroom/globe/h-earth/render/run8e-successor-environment.js',B='64563734a602ada44f60616fd07ba009bfa87cb2';
const args=process.argv.slice(2),get=n=>args[args.indexOf(n)+1],out=get('--output'),holder=get('--execution-holder');
if(get('--candidate-head')!==C)throw Error('HEAD_MISMATCH');
const run=(a,o={})=>cp.spawnSync('git',a,{encoding:'utf8',maxBuffer:134217728,...o});
let r=run(['cat-file','-e',C+'^{commit}']);if(r.status){r=run(['fetch','--no-tags','origin',C]);if(r.status)throw Error('CANDIDATE_FETCH_FAILED');}
if(run(['rev-parse',C+':'+P]).stdout.trim()!==B)throw Error('PRODUCT_BLOB_MISMATCH');
const tmp=fs.mkdtempSync('/tmp/gen2515-');r=run(['worktree','add','--detach',tmp,C]);if(r.status)throw Error('WORKTREE_FAILED');
try{const m=await import('file://'+path.join(tmp,P));const before=process.memoryUsage(),t=process.hrtime.bigint();const n=m.buildHEarthRun8ENeutralPackage({cameraWorld:{x:0,y:8,z:-40}});const elapsed=Number(process.hrtime.bigint()-t)/1e6,after=process.memoryUsage();const f=m.constructHEarthRun8ESuccessorEnvironmentFrame({camera:{position:{x:0,y:8,z:-40},target:{x:0,y:0,z:-120},up:{x:0,y:1,z:0},nearPlane:.25,farPlane:768,verticalFovDegrees:56}});const e=m.evaluateHEarthRun8EFrame(f);const checks={neutralPackage:n?.ok===true,vegetationCount:n?.regionalVegetation?.instanceCount===27585,vegetationEligible:n?.regionalVegetation?.eligible===true,regionalEcology:(n?.regionalEcologyPrimitiveCount??0)>0,packet002:f?.transfer?.ok===true,evaluator:e?.eligible===true};const first=Object.entries(checks).find(([,v])=>!v)?.[0]??null;fs.writeFileSync(out,JSON.stringify({schema:'H_EARTH_GEN2515_RENDER_PACKAGE_QUALIFICATION_RECEIPT_v1',result:first?'FAIL':'GEN2515_RENDER_PACKAGE_CANDIDATE_PASS',operationId:'H_EARTH_GEN2514_VEGETATION_RENDERER_INTEGRATION_20260929_001',executionHolder:holder,candidateHead:C,productBlob:B,node:process.version,checks,firstAssertion:first,initializationMs:elapsed,memoryBefore:before,memoryAfter:after,sourceMutationPerformed:false,productMutationPerformed:false,mergePerformed:false,deploymentPerformed:false,publicationPerformed:false},null,2)+'\n');if(first)process.exitCode=1;}finally{run(['worktree','remove','--force',tmp]);}