#!/usr/bin/env node
import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path'; import cp from 'node:child_process';
const SCHEMA='H_EARTH_EXACT_HEAD_MODULE_PARSER_RECEIPT_v1';
const run=(cmd,args,cwd)=>cp.spawnSync(cmd,args,{cwd,encoding:'utf8',maxBuffer:64*1024*1024});
const git=(cwd,args)=>{const r=run('git',args,cwd);if(r.status!==0)throw new Error('GIT:'+args.join(' ')+':'+r.stderr);return r.stdout.trim();};
const parseArgs=()=>{const a={};for(let i=2;i<process.argv.length;i+=2)a[process.argv[i].replace(/^--/,'')]=process.argv[i+1];return a;};
const write=(p,v)=>{fs.mkdirSync(path.dirname(path.resolve(p)),{recursive:true});fs.writeFileSync(path.resolve(p),JSON.stringify(v,null,2)+'\n');};
function resolveImport(from,spec){if(!spec.startsWith('.'))return null;const clean=spec.split('?')[0].split('#')[0];return path.posix.normalize(path.posix.join(path.posix.dirname(from),clean));}
function imports(source){return [...source.matchAll(/(?:import\s+(?:[\s\S]*?\s+from\s+)?|export\s+[\s\S]*?\s+from\s+|import\s*\()(['"])([^'"]+)\1/g)].map(m=>m[2]);}
function main(){const a=parseArgs(),root=process.cwd(),head=a['subject-head'],entry=a['entry-path'],out=a.output,holder=a['execution-holder'];let receipt={schema:SCHEMA,result:'FAIL_CLOSED',subjectHead:head,entryPath:entry,executionHolder:holder,checkedModules:[],firstFailure:null,productMutationPerformed:false,branchCreated:false,mergePerformed:false,deploymentPerformed:false};
try{if(!/^[0-9a-f]{40}$/.test(head))throw new Error('SUBJECT_HEAD_INVALID');if(!entry?.startsWith('showroom/globe/h-earth/'))throw new Error('ENTRY_PATH_INVALID');let r=run('git',['cat-file','-e',head+'^{commit}'],root);if(r.status!==0){r=run('git',['fetch','--no-tags','origin',head],root);if(r.status!==0)throw new Error('SUBJECT_HEAD_UNAVAILABLE');}
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'h-earth-module-parser-')),wt=path.join(tmp,'subject');try{git(root,['worktree','add','--detach',wt,head]);if(git(wt,['rev-parse','HEAD^{commit}'])!==head)throw new Error('HEAD_MISMATCH');const q=[entry],seen=new Set();while(q.length){const f=q.shift();if(seen.has(f))continue;seen.add(f);const abs=path.join(wt,f);if(!fs.existsSync(abs)){receipt.firstFailure={path:f,phase:'RESOLVE',error:'MODULE_NOT_FOUND'};break;}const source=fs.readFileSync(abs,'utf8');const check=run('node',['--experimental-default-type=module','--check',abs],wt);receipt.checkedModules.push({path:f,syntaxExitCode:check.status});if(check.status!==0){receipt.firstFailure={path:f,phase:'PARSE',error:(check.stderr||check.stdout).trim()};break;}for(const s of imports(source)){const n=resolveImport(f,s);if(n&&!seen.has(n))q.push(n);}}
if(!receipt.firstFailure){const imp=run('node',['--experimental-default-type=module','-e',"import('./"+entry+"').then(()=>process.exit(0)).catch(e=>{console.error(e.stack||e);process.exit(1)})"],wt);if(imp.status!==0)receipt.firstFailure={path:entry,phase:'INSTANTIATE',error:(imp.stderr||imp.stdout).trim()};}
receipt.result=receipt.firstFailure?'FAIL_CLOSED':'PASS_CLOSED';}finally{if(fs.existsSync(wt))run('git',['worktree','remove','--force',wt],root);}}catch(e){receipt.firstFailure=receipt.firstFailure||{path:null,phase:'HARNESS',error:e.message};}write(out,receipt);if(receipt.result!=='PASS_CLOSED')process.exitCode=1;}main();
