'use strict';
const PLAN=require('./jeeves.c01.realization-plan.v2.js');
const R=require('./jeeves.c01.waveform-decoder-renderer.v2.js');
const SR=R.SR;
const BANDS=Object.freeze(Array.from({length:20},(_,i)=>Object.freeze([i*500+100,i*500+200,i*500+300,i*500+400])));
function signature(audio){const n=audio.length,w=new Float64Array(BANDS.length);let rms=0,zc=0;for(let i=0;i<n;i++){const x=audio[i];rms+=x*x;if(i&&Math.sign(audio[i-1])!==Math.sign(x))zc++;}for(let k=0;k<BANDS.length;k++){let power=0;for(const f of BANDS[k]){let re=0,im=0;for(let i=0;i<n;i++){const win=.5-.5*Math.cos(2*Math.PI*i/Math.max(1,n-1)),a=2*Math.PI*f*i/SR,x=audio[i]*win;re+=x*Math.cos(a);im-=x*Math.sin(a);}power+=re*re+im*im;}w[k]=Math.log1p(power);}let mean=0;for(const x of w)mean+=x;mean/=w.length;let sd=0;for(const x of w)sd+=(x-mean)*(x-mean);sd=Math.sqrt(sd/w.length)||1;for(let i=0;i<w.length;i++)w[i]=(w[i]-mean)/sd;return Object.freeze({rms:Math.sqrt(rms/Math.max(1,n)),zcr:zc/Math.max(1,n),bands:Object.freeze(Array.from(w))});}
function distance(a,b){let d=(a.rms-b.rms)**2*2+(a.zcr-b.zcr)**2*20;for(let i=0;i<a.bands.length;i++)d+=(a.bands[i]-b.bands[i])**2/a.bands.length;return d;}
function prototypes(){const out={};for(const [phone,spec] of Object.entries(PLAN.PHONE)){const sums=[];for(let seed=0;seed<3;seed++){const seg={phone,durationMs:spec.durationMs,features:spec.features},s=signature(R.renderPhone(seg,100+seed));sums.push(s);}const bands=BANDS.map((_,i)=>sums.reduce((a,s)=>a+s.bands[i],0)/sums.length);out[phone]=Object.freeze({rms:sums.reduce((a,s)=>a+s.rms,0)/sums.length,zcr:sums.reduce((a,s)=>a+s.zcr,0)/sums.length,bands:Object.freeze(bands)});}return Object.freeze(out);}
function decode(){const x=R.render(),bank=prototypes(),decoded=[],observed=x.segments.map(s=>({type:s.type,durationMs:s.durationMs,startSample:s.startSample,endSample:s.endSample}));for(const seg of observed){if(seg.type==='WORD_GAP'){decoded.push(Object.freeze({type:'WORD_GAP',durationMs:seg.durationMs}));continue;}const sig=signature(x.audio.slice(seg.startSample,seg.endSample));let best=null,bestD=Infinity;for(const [phone,p] of Object.entries(bank)){const d=distance(sig,p);if(d<bestD){bestD=d;best=phone;}}decoded.push(Object.freeze({type:'PHONE',phone:best,distance:bestD}));}return Object.freeze(decoded);}
function evaluate(){const d=decode(),words=[],cur=[];for(const x of d){if(x.type==='WORD_GAP'){words.push(cur.join('-'));cur=[];}else cur.push(x.phone);}words.push(cur.join('-'));const expected=PLAN.WORDS.map(x=>x[1].join('-'));const phoneDecoded=d.filter(x=>x.type==='PHONE').map(x=>x.phone),expectedPhones=PLAN.WORDS.flatMap(x=>x[1]);let correct=0;for(let i=0;i<expectedPhones.length;i++)if(phoneDecoded[i]===expectedPhones[i])correct++;const pass=correct===expectedPhones.length&&words.every((w,i)=>w===expected[i]);return Object.freeze({pass,correctPhones:correct,totalPhones:expectedPhones.length,phoneAccuracy:correct/expectedPhones.length,decodedWords:Object.freeze(words),expectedWords:Object.freeze(expected)});}
module.exports=Object.freeze({signature,distance,prototypes,decode,evaluate});
