'use strict';
const BASE=require('./jeeves.c01.realization-plan.v2.js');
const SR=24000;
function clamp(x,a,b){return Math.max(a,Math.min(b,x));}
function hash01(seed,a,b){const x=Math.sin((seed+1)*19.191+(a+1)*12.9898+(b+1)*78.233)*43758.5453;return x-Math.floor(x);}
function coeff(freq,bw){const r=Math.exp(-Math.PI*bw/SR),th=2*Math.PI*freq/SR;return{b0:1-r,a1:2*r*Math.cos(th),a2:-r*r};}
function step(x,c,s){const y=c.b0*x+c.a1*s.y1+c.a2*s.y2;s.y2=s.y1;s.y1=y;return y;}
function parallel(src,F,B){const states=F.map(()=>({y1:0,y2:0})),out=new Float32Array(src.length);for(let i=0;i<src.length;i++){let y=0;for(let k=0;k<F.length;k++)y+=step(src[i],coeff(F[k],B[k]),states[k]);out[i]=y/F.length;}return out;}
function scaledFeatures(spec,formantScale){const f={...spec.features};for(const k of ['formant1Hz','formant2Hz','formant3Hz','nasalPoleHz','antiResonanceHz'])if(Number.isFinite(f[k]))f[k]*=formantScale;return f;}
function renderPhone(phone,durationMs,features,index,opt){const cls=BASE.PHONE[phone].class,f=features,n=Math.max(1,Math.round(durationMs*SR/1000)),src=new Float32Array(n),noise=new Float32Array(n);let phase=0;for(let i=0;i<n;i++){const q=i/Math.max(1,n-1),z=(hash01(opt.noiseSeed,index,i)-.5)*2,env=Math.min(1,i/(.006*SR),(n-i)/(.010*SR));noise[i]=z*env;phase=(phase+opt.f0Hz/SR)%1;const pulse=Math.max(0,Math.sin(2*Math.PI*phase));let x=f.voicing?(pulse*.55+z*.01):0;if(cls==='fricative')x+=z*.34;if(cls==='stop'){if(q<f.closureFraction)x*=.02;else if(q<f.closureFraction+.18)x+=z*.60*(1-(q-f.closureFraction)/.18);}src[i]=x*env;}let out;if(cls==='vowel'||cls==='approximant')out=parallel(src,[f.formant1Hz,f.formant2Hz,f.formant3Hz],[90,130,180]);else if(cls==='nasal')out=parallel(src,[f.nasalPoleHz,900*opt.formantScale],[90,180]);else if(cls==='fricative')out=parallel(src,[f.spectralCenterHz,Math.min(9000,f.spectralCenterHz+900)],[f.spectralBandwidthHz,1700]);else if(cls==='stop')out=parallel(src,[f.burstCenterHz,Math.min(9000,f.burstCenterHz+900)],[f.burstBandwidthHz,1500]);else out=src;if(cls==='vowel'||cls==='approximant')for(let i=0;i<n;i++)out[i]=out[i]*.85+src[i]*.15;if(cls==='fricative')for(let i=0;i<n;i++)out[i]+=noise[i]*.08;if(cls==='stop')for(let i=0;i<n;i++){const q=i/Math.max(1,n-1);if(q>=f.closureFraction&&q<f.closureFraction+.18)out[i]+=noise[i]*.12;}let peak=0;for(const x of out)peak=Math.max(peak,Math.abs(x));const g=peak>.5?.5/peak:1;for(let i=0;i<n;i++)out[i]=clamp(out[i]*g,-.8,.8);return out;}
function render(options={}){const opt={durationScale:options.durationScale||1,f0Hz:options.f0Hz||100,formantScale:options.formantScale||1,noiseSeed:options.noiseSeed||503};const parts=[];let pi=0;BASE.WORDS.forEach(([word,phones],wi)=>{for(const phone of phones){const spec=BASE.PHONE[phone];parts.push(renderPhone(phone,spec.durationMs*opt.durationScale,scaledFeatures(spec,opt.formantScale),pi++,opt));}if(wi<BASE.WORDS.length-1)parts.push(new Float32Array(Math.round(115*SR/1000)));});const n=parts.reduce((a,p)=>a+p.length,0),audio=new Float32Array(n);let at=0;for(const p of parts){audio.set(p,at);at+=p.length;}return Object.freeze({sampleRate:SR,audio,options:Object.freeze(opt)});}
module.exports=Object.freeze({SR,render,renderPhone});
