'use strict';
const PLAN=require('./jeeves.c01.realization-plan.v2.js');
const R=require('./jeeves.c01.waveform-decoder-renderer.v2.js');
const SR=R.SR;
const PROBES=[300,600,900,1200,1600,2200,3000,3800,4800,6200,7800,9500];
function detectWordRegions(audio){const min=Math.round(.080*SR),eps=1e-12,runs=[];let s=-1;for(let i=0;i<=audio.length;i++){const zero=i<audio.length&&Math.abs(audio[i])<=eps;if(zero&&s<0)s=i;if((!zero||i===audio.length)&&s>=0){const e=i;if(e-s>=min)runs.push([s,e]);s=-1;}}const interior=runs.filter(([a,b])=>a>0&&b<audio.length);if(interior.length!==2)return[];return[[0,interior[0][0]],[interior[0][1],interior[1][0]],[interior[1][1],audio.length]];}
function bandEnergy(buf,f){let re=0,im=0,n=buf.length;for(let i=0;i<n;i++){const w=.5-.5*Math.cos(2*Math.PI*i/Math.max(1,n-1)),a=2*Math.PI*f*i/SR,x=buf[i]*w;re+=x*Math.cos(a);im-=x*Math.sin(a);}return Math.log1p(re*re+im*im);}
function signature(buf){const bins=10,out=[buf.length/SR];for(let b=0;b<bins;b++){const a=Math.floor(b*buf.length/bins),e=Math.floor((b+1)*buf.length/bins),x=buf.slice(a,e);let ss=0,zc=0,hf=0;for(let i=0;i<x.length;i++){ss+=x[i]*x[i];if(i&&Math.sign(x[i-1])!==Math.sign(x[i]))zc++;if(i)hf+=(x[i]-x[i-1])**2;}out.push(Math.sqrt(ss/Math.max(1,x.length)),zc/Math.max(1,x.length),hf/Math.max(1,ss));}for(const f of PROBES)out.push(bandEnergy(buf,f));const start=31;let m=0;for(let i=start;i<out.length;i++)m+=out[i];m/=(out.length-start);let sd=0;for(let i=start;i<out.length;i++)sd+=(out[i]-m)**2;sd=Math.sqrt(sd/(out.length-start))||1;for(let i=start;i<out.length;i++)out[i]=(out[i]-m)/sd;return out;}
function renderWord(phones,seed){const parts=[];let len=0;for(let i=0;i<phones.length;i++){const p=phones[i],spec=PLAN.PHONE[p],seg={phone:p,durationMs:spec.durationMs,features:spec.features},a=R.renderPhone(seg,seed+i);parts.push(a);len+=a.length;}const out=new Float32Array(len);let at=0;for(const p of parts){out.set(p,at);at+=p.length;}return out;}
function proto(word,phones){const sigs=[0,1,2,3].map(k=>signature(renderWord(phones,200+k*41))),n=sigs[0].length,v=new Array(n).fill(0);for(const s of sigs)for(let i=0;i<n;i++)v[i]+=s[i]/sigs.length;return{word,v};}
function dist(a,b){let s=0;for(let i=0;i<a.length;i++){let w=1;if(i===0)w=8;else if(i<31)w=3;s+=w*(a[i]-b[i])**2;}return s/a.length;}
function evaluate(){const x=R.render(),regions=detectWordRegions(x.audio);if(regions.length!==3)return{pass:false,reason:'WORD_BOUNDARY_DETECTION_FAIL',regions};const ps=PLAN.WORDS.map(([w,p])=>proto(w,p)),decoded=[],scores=[];for(const[a,b]of regions){const s=signature(x.audio.slice(a,b)),row={};let best=null,bd=Infinity;for(const p of ps){const d=dist(s,p.v);row[p.word]=d;if(d<bd){bd=d;best=p.word;}}decoded.push(best);scores.push(row);}const expected=PLAN.WORDS.map(x=>x[0]);const direct=decoded.every((x,i)=>x===expected[i]);const margins=scores.map((r,i)=>{const own=r[expected[i]],others=Object.entries(r).filter(([k])=>k!==expected[i]).map(([,v])=>v);return Math.min(...others)-own;});const reversed=expected.slice().reverse(),rejectReverse=!decoded.every((x,i)=>x===reversed[i]);return Object.freeze({pass:direct&&margins.every(x=>x>0)&&rejectReverse,decoded:Object.freeze(decoded),expected:Object.freeze(expected),margins:Object.freeze(margins),scores:Object.freeze(scores),regions:Object.freeze(regions.map(([a,b])=>Object.freeze({start:a,end:b,durationSeconds:(b-a)/SR})))});}
module.exports=Object.freeze({detectWordRegions,signature,dist,evaluate});
