'use strict';
const PLAN=require('./jeeves.c01.realization-plan.v2.js');
const R=require('./jeeves.c01.robustness-renderer.v1.js');
const SR=R.SR;
const BANDS=Array.from({length:16},(_,i)=>250+i*300); const FRAMES=14;
function regions(audio){const win=Math.round(.010*SR),hop=Math.round(.005*SR),e=[];for(let s=0;s<audio.length;s+=hop){let q=0;for(let i=s;i<Math.min(audio.length,s+win);i++)q+=audio[i]*audio[i];e.push(Math.sqrt(q/Math.max(1,Math.min(audio.length,s+win)-s)));}const mx=Math.max(...e),thr=Math.max(1e-7,mx*.008);let active=e.map(x=>x>thr),runs=[],st=null;for(let i=0;i<=active.length;i++){if(i<active.length&&active[i]&&st===null)st=i;if((i===active.length||!active[i])&&st!==null){runs.push([st,i]);st=null;}}const merged=[];for(const r of runs){if(!merged.length||((r[0]-merged[merged.length-1][1])*hop/SR)>.065)merged.push(r);else merged[merged.length-1][1]=r[1];}return merged.filter(r=>(r[1]-r[0])*hop/SR>.15).map(r=>audio.slice(Math.max(0,r[0]*hop),Math.min(audio.length,r[1]*hop+win)));}
function frameSig(a){const out=[];for(let fi=0;fi<FRAMES;fi++){const s=Math.floor(fi*a.length/FRAMES),e=Math.max(s+1,Math.floor((fi+1)*a.length/FRAMES)),n=e-s;let rms=0,zc=0;for(let i=s;i<e;i++){rms+=a[i]*a[i];if(i>s&&Math.sign(a[i-1])!==Math.sign(a[i]))zc++;}const bands=[];for(const f of BANDS){let re=0,im=0;for(let i=s;i<e;i++){const j=i-s,w=.5-.5*Math.cos(2*Math.PI*j/Math.max(1,n-1)),q=2*Math.PI*f*j/SR,x=a[i]*w;re+=x*Math.cos(q);im-=x*Math.sin(q);}bands.push(Math.log1p(re*re+im*im));}let m=bands.reduce((x,y)=>x+y,0)/bands.length,sd=Math.sqrt(bands.reduce((x,y)=>x+(y-m)**2,0)/bands.length)||1;out.push({rms:Math.sqrt(rms/n),zcr:zc/n,bands:bands.map(x=>(x-m)/sd)});}return out;}
function dist(A,B){let total=0;for(let f=0;f<FRAMES;f++){let d=(A[f].rms-B[f].rms)**2*.5+(A[f].zcr-B[f].zcr)**2*4;for(let k=0;k<BANDS.length;k++){const wt=k<10?1:.35;d+=wt*(A[f].bands[k]-B[f].bands[k])**2/BANDS.length;}total+=d;}return total/FRAMES;}
function bank(){const variants=[{noiseSeed:503,durationScale:1},{noiseSeed:211,durationScale:1},{noiseSeed:887,durationScale:1}];const accum=PLAN.WORDS.map(([word])=>({word,sigs:[]}));for(const v of variants){const rr=regions(R.render({...v,f0Hz:100,formantScale:1}).audio);rr.forEach((r,i)=>accum[i].sigs.push(frameSig(r)));}return accum.map(x=>({word:x.word,s:x.sigs[0].map((_,f)=>({rms:x.sigs.reduce((a,s)=>a+s[f].rms,0)/x.sigs.length,zcr:x.sigs.reduce((a,s)=>a+s[f].zcr,0)/x.sigs.length,bands:BANDS.map((_,k)=>x.sigs.reduce((a,s)=>a+s[f].bands[k],0)/x.sigs.length)}))}));}
const CASES=[{id:'nominal',durationScale:1,f0Hz:100,formantScale:1,noiseSeed:503},{id:'duration-low',durationScale:.92,f0Hz:100,formantScale:1,noiseSeed:503},{id:'duration-high',durationScale:1.08,f0Hz:100,formantScale:1,noiseSeed:503},{id:'f0-low',durationScale:1,f0Hz:94,formantScale:1,noiseSeed:503},{id:'f0-high',durationScale:1,f0Hz:106,formantScale:1,noiseSeed:503},{id:'formant-low',durationScale:1,f0Hz:100,formantScale:.97,noiseSeed:503},{id:'formant-high',durationScale:1,f0Hz:100,formantScale:1.03,noiseSeed:503},{id:'noise-211',durationScale:1,f0Hz:100,formantScale:1,noiseSeed:211},{id:'noise-887',durationScale:1,f0Hz:100,formantScale:1,noiseSeed:887},{id:'corner-a',durationScale:.92,f0Hz:94,formantScale:.97,noiseSeed:211},{id:'corner-b',durationScale:1.08,f0Hz:106,formantScale:1.03,noiseSeed:887},{id:'cross-a',durationScale:.92,f0Hz:106,formantScale:1.03,noiseSeed:887},{id:'cross-b',durationScale:1.08,f0Hz:94,formantScale:.97,noiseSeed:211}];
function evaluate(){const B=bank(),exp=PLAN.WORDS.map(x=>x[0]),results=CASES.map(c=>{const rr=regions(R.render(c).audio),out=rr.map(r=>{const s=frameSig(r),scores=B.map(p=>({word:p.word,d:dist(s,p.s)})).sort((a,b)=>a.d-b.d);return {word:scores[0].word,margin:scores[1].d-scores[0].d};});const words=out.map(x=>x.word),margins=out.map(x=>x.margin);return {id:c.id,pass:rr.length===3&&words.every((w,i)=>w===exp[i])&&margins.every(x=>x>0),regions:rr.length,words,margins};});return {pass:results.every(x=>x.pass),passed:results.filter(x=>x.pass).length,cases:results.length,results};}
module.exports=Object.freeze({CASES,regions,evaluate});
