'use strict';
const PLAN=require('./jeeves.c01.realization-plan.v2.js');
const R=require('./jeeves.c01.robustness-renderer.v1.js');
const ROBUST=require('./jeeves.c01.open-variation-robustness.v2.js');
const SR=R.SR;
function zeroRuns(audio,eps=1e-9,minMs=60){const min=Math.round(minMs*SR/1000),runs=[];let s=null;for(let i=0;i<=audio.length;i++){const z=i<audio.length&&Math.abs(audio[i])<=eps;if(z&&s===null)s=i;if((i===audio.length||!z)&&s!==null){if(i-s>=min)runs.push({start:s,end:i,durationMs:(i-s)*1000/SR});s=null;}}return runs;}
function expectedGapStarts(){let samples=0,wordIndex=0;const starts=[];for(const [word,phones] of PLAN.WORDS){for(const phone of phones)samples+=Math.round(PLAN.PHONE[phone].durationMs*SR/1000);if(wordIndex<PLAN.WORDS.length-1){starts.push(samples);samples+=Math.round(115*SR/1000);}wordIndex++;}return starts;}
function evaluate(){const x=R.render({durationScale:1,f0Hz:100,formantScale:1,noiseSeed:503}),a=x.audio;let sum=0,peak=0,finite=true,clip=0;for(const v of a){if(!Number.isFinite(v))finite=false;sum+=v*v;peak=Math.max(peak,Math.abs(v));if(Math.abs(v)>=.799)clip++;}const rms=Math.sqrt(sum/Math.max(1,a.length)),runs=zeroRuns(a),starts=expectedGapStarts(),gapSamples=Math.round(115*SR/1000);const expectedGaps=starts.map(s=>({start:s,end:s+gapSamples}));const lexicalGapsExact=expectedGaps.every(g=>{for(let i=g.start;i<g.end;i++)if(a[i]!==0)return false;return true;});const longRunsAtExpectedOnly=runs.length===2&&runs.every((r,i)=>Math.abs(r.start-expectedGaps[i].start)<=1&&Math.abs(r.end-expectedGaps[i].end)<=1);const classes=new Set(Object.values(PLAN.PHONE).map(p=>p.class));const classCoverage=['vowel','approximant','nasal','fricative','stop'].every(c=>classes.has(c));const duration=a.length/SR;const robust=ROBUST.evaluate();const pass=finite&&clip===0&&peak>0&&peak<=.51&&rms>.005&&rms<.30&&duration>2&&duration<4&&lexicalGapsExact&&longRunsAtExpectedOnly&&classCoverage&&robust.pass;return Object.freeze({pass,sampleRate:SR,sampleCount:a.length,durationSeconds:duration,finite,peak,rms,clippedSamples:clip,longSilenceRuns:runs,lexicalGapsExact,longRunsAtExpectedOnly,classCoverage,phoneClasses:Object.freeze(Array.from(classes).sort()),robustness:{pass:robust.pass,passed:robust.passed,cases:robust.cases}});}
module.exports=Object.freeze({zeroRuns,expectedGapStarts,evaluate});
