import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {SOURCE_MODES,OPERATION_ID,CANDIDATE_BASE_HEAD,orientationDictionaryDigest,sha256,writeCanonicalJson,assert,assertPreflightHasNoScientificOutcome,stable} from './causal-evidence-adapter.v1.mjs';

const DOMAIN=Object.freeze({rows:256,columns:256,xMinimum:-256,xMaximum:256,zMinimum:-320,zMaximum:64});
const LINEAGE_CENTER=Object.freeze({x:80,z:-172});
const GEODESIC_CAP=144;
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const smoothstep=(a,b,v)=>{if(a===b)return v<a?0:1;const t=clamp((v-a)/(b-a),0,1);return t*t*(3-2*t)};
const smootherstep01=v=>{const t=clamp(v,0,1);return t*t*t*(t*(t*6-15)+10)};
const gaussian=(x,z,cx,cz,rx,rz,a)=>a*Math.exp(-(((x-cx)/rx)**2+((z-cz)/rz)**2)*1.6);
const baseShoreline=x=>-82+7.5*Math.sin(x/58)+2.75*Math.sin((x+31)/19);
function baseTerrain(x,z){x=clamp(x,-256,256);z=clamp(z,-256,64);const shoreline=baseShoreline(x),inland=shoreline-z,waterward=z-shoreline;if(waterward>0){const shallow=-.35-Math.min(waterward,28)*.018,open=-.85-Math.max(0,waterward-28)*.012,b=smoothstep(18,38,waterward);return shallow*(1-b)+open*b}const coast=.025*Math.max(0,inland),wet=-.22*Math.exp(-Math.max(0,inland)/16),dune=gaussian(x,z,6,shoreline-34,190,22,5.8),rolling=1.7*Math.sin((x+22)/48)*smoothstep(55,180,inland)+1.2*Math.sin((z+140)/29)*smoothstep(70,200,inland),hill=gaussian(x,z,72,-172,62,50,27),ridge=gaussian(x,z,145,-225,78,30,38),low=gaussian(x,z,-92,-152,70,58,-6.5),valley=gaussian(x,z,2,-198,44,82,-11.5),bluff=gaussian(x,z,188,-245,48,24,18);return coast+wet+dune+rolling+hill+ridge+low+valley+bluff}
const intervalEnvelope=(v,min,max,feather)=>smoothstep(min,min+feather,v)*(1-smoothstep(max-feather,max,v));
const rearTerrainLevel=x=>16+3.5*Math.sin((x+40)/76)+1.5*Math.sin((x-18)/31);
function successorBase(x,z){if(z>=-256)return baseTerrain(x,z);const boundary=baseTerrain(x,-256),eps=.01,derivative=(baseTerrain(x,-256+eps)-baseTerrain(x,-256))/eps,tangent=boundary+derivative*(z+256),progress=(-256-z)/64,blend=smootherstep01(progress);return tangent*(1-blend)+rearTerrainLevel(x)*blend}
function mountainContribution(x,z){if(x<-240||x>56||z<-312||z>-220)return 0;const xEnv=intervalEnvelope(x,-240,56,24),zEnv=intervalEnvelope(z,-312,-220,20),g=(v,c,r)=>Math.exp(-(((v-c)/r)**2)),ridgeZ=-266+7*Math.sin((x+104)/54)+3*Math.sin((x-12)/21),primary=62*xEnv*g(z,ridgeZ,22),summit=27*g(x,-92,38)*g(z,-271,17),secondary=24*g(x,-6,52)*g(z,-250,20),foothill=13*xEnv*zEnv,valley=15*g(x,-48,26)*g(z,-256,13);return zEnv*Math.max(0,primary+summit+secondary+foothill-valley)}
const canonicalElevation=v=>{const q=Math.round(v*16777216)/16777216;return Object.is(q,-0)?0:q};
function baselineElevation(x,z){return canonicalElevation(successorBase(x,z)+mountainContribution(x,z))}
const q5=v=>{const t=clamp(v,0,1);return t*t*t*(t*(t*6-15)+10)};
const windowQ5=(v,o0,i0,i1,o1)=>q5((v-o0)/(i0-o0))*q5((o1-v)/(o1-i1));
const longitudinalWindow=(u,half,feather)=>q5((half+feather-Math.abs(u))/feather);
const OPS=Object.freeze([{amplitude:3.5,centerX:44,centerZ:-168,operator:'ORIENTED_SADDLE',radiusU:14,radiusV:10,rotationDegrees:90},{centerX:36,centerZ:-178,feather:6,halfLength:18,halfWidth:7,height:3.5,operator:'RIDGE_FACE',rotationDegrees:90},{centerX:52,centerZ:-178,feather:6,halfLength:18,halfWidth:7,height:3.5,operator:'RIDGE_FACE',rotationDegrees:90},{depth:1,endFeatherWorldUnits:6,halfWidth:6,operator:'VALLEY_CORRIDOR',polyline:[[44,-164],[44,-176],[44,-188]]},{centerX:44,centerZ:-180,drop:4,feather:6,halfLength:12,halfWidth:10,operator:'FALL_FACE',rotationDegrees:-90},{centerX:44,centerZ:-192,depth:2,operator:'LOWER_BASIN',radiusU:14,radiusV:12,rotationDegrees:0},{depth:2.5,endFeatherWorldUnits:4,halfWidth:4,operator:'DRAINAGE_CUT',polyline:[[44,-192],[36,-196],[28,-200]]},{centerX:34,centerZ:-170,feather:4,halfLength:10,halfWidth:5,height:1,operator:'TERRACE_BAND',rotationDegrees:90},{centerX:54,centerZ:-170,feather:4,halfLength:10,halfWidth:5,height:1,operator:'TERRACE_BAND',rotationDegrees:90}]);
function oriented(x,z,o){const a=o.rotationDegrees*Math.PI/180,c=Math.cos(a),s=Math.sin(a),dx=x-o.centerX,dz=z-o.centerZ;return {u:c*dx+s*dz,v:-s*dx+c*dz}}
function nearestPolyline(x,z,p){let total=0,l=[];for(let i=0;i<p.length-1;i++){const n=Math.hypot(p[i+1][0]-p[i][0],p[i+1][1]-p[i][1]);l.push(n);total+=n}let cumulative=0,best=null;for(let i=0;i<p.length-1;i++){const[ax,az]=p[i],[bx,bz]=p[i+1],vx=bx-ax,vz=bz-az,ls=vx*vx+vz*vz,t=ls===0?0:clamp(((x-ax)*vx+(z-az)*vz)/ls,0,1),px=ax+t*vx,pz=az+t*vz,d=Math.hypot(x-px,z-pz),progress=total===0?0:(cumulative+t*l[i])/total;if(!best||d<best.distance)best={distance:d,progress,total};cumulative+=l[i]}return best}
function operationDelta(x,z,o){if(o.operator==='VALLEY_CORRIDOR'||o.operator==='DRAINAGE_CUT'){const n=nearestPolyline(x,z,o.polyline),f=o.endFeatherWorldUnits/n.total;return -o.depth*Math.exp(-1.6*(n.distance/o.halfWidth)**2)*q5(n.progress/f)*q5((1-n.progress)/f)}const {u,v}=oriented(x,z,o);switch(o.operator){case'ORIENTED_SADDLE':return o.amplitude*Math.exp(-1.6*((u/o.radiusU)**2+(v/o.radiusV)**2))*((v/o.radiusV)**2-(u/o.radiusU)**2);case'RIDGE_FACE':return o.height*Math.exp(-1.6*(v/o.halfWidth)**2)*longitudinalWindow(u,o.halfLength,o.feather);case'LOWER_BASIN':{const r=Math.max(0,1-((u/o.radiusU)**2+(v/o.radiusV)**2));return-o.depth*r**2}case'TERRACE_BAND':return o.height*longitudinalWindow(u,o.halfLength,o.feather)*Math.exp(-1.6*(v/o.halfWidth)**4);case'FALL_FACE':return-o.drop*q5((u+o.halfLength)/(2*o.halfLength))*longitudinalWindow(u,o.halfLength,o.feather)*Math.exp(-1.6*(v/o.halfWidth)**2);default:throw new Error(`UNKNOWN_OPERATOR:${o.operator}`)}}
function deltaElevation(x,z){let raw=0;for(const o of OPS)raw+=operationDelta(x,z,o);return windowQ5(x,24,32,64,72)*windowQ5(z,-200,-192,-164,-156)*clamp(raw,-12,18)}
export function sampleElevation(sourceMode,x,z){assert(SOURCE_MODES.includes(sourceMode),'SOURCE_MODE_INVALID',sourceMode);const y=baselineElevation(x,z);return sourceMode===SOURCE_MODES[1]?y+deltaElevation(x,z):y}
function nearestCenter(nodes){let best=null,bestD=Infinity;for(const n of nodes){const d=(n.worldX-LINEAGE_CENTER.x)**2+(n.worldZ-LINEAGE_CENTER.z)**2;if(d<bestD){best=n;bestD=d}}return best}
export function runCountOnlyPreflight({sourceMode,outputFile=null}={}){assert(SOURCE_MODES.includes(sourceMode),'SOURCE_MODE_INVALID',sourceMode);const {rows,columns,xMinimum,xMaximum,zMinimum,zMaximum}=DOMAIN,xStep=(xMaximum-xMinimum)/(columns-1),zStep=(zMaximum-zMinimum)/(rows-1),elev=new Float64Array(rows*columns);for(let r=0;r<rows;r++)for(let c=0;c<columns;c++){const x=xMinimum+c*xStep,z=zMinimum+r*zStep;elev[r*columns+c]=sampleElevation(sourceMode,x,z)}const at=(r,c)=>elev[Math.max(0,Math.min(rows-1,r))*columns+Math.max(0,Math.min(columns-1,c))],nodes=new Array(rows*columns),partitionHash=createHash('sha256');for(let r=0;r<rows;r++)for(let c=0;c<columns;c++){const nodeId=r*columns+c,worldX=xMinimum+c*xStep,worldZ=zMinimum+r*zStep,elevation=elev[nodeId],gx=(at(r,c+1)-at(r,c-1))/(2*xStep),gz=(at(r+1,c)-at(r-1,c))/(2*zStep),slopeDegrees=Math.atan(Math.hypot(gx,gz))*180/Math.PI,waterMembership=elevation<=0,traversableClass=waterMembership?'WATER':slopeDegrees<=25?'TRAVERSABLE':slopeDegrees<=38?'SCENIC_ONLY':'BARRIER';nodes[nodeId]={nodeId,row:r,column:c,worldX,worldZ,elevation,slopeDegrees,waterMembership,traversableClass};partitionHash.update(`${nodeId}|${worldX.toFixed(9)}|${worldZ.toFixed(9)}|${elevation.toFixed(9)}|${slopeDegrees.toFixed(6)}|${waterMembership?1:0}|${traversableClass}
`)}const center=nearestCenter(nodes),eligible=[];for(const n of nodes){const distanceFromCenter=Math.hypot(n.worldX-center.worldX,n.worldZ-center.worldZ);if(!n.waterMembership&&n.traversableClass==='TRAVERSABLE'&&distanceFromCenter<=GEODESIC_CAP)eligible.push(stable({nodeId:n.nodeId,row:n.row,column:n.column,worldX:n.worldX,worldZ:n.worldZ,slopeDegrees:n.slopeDegrees,distanceFromCenter,waterMembership:false,traversabilityResult:true,distancePredicateResult:true}))}eligible.sort((a,b)=>a.slopeDegrees-b.slopeDegrees||a.distanceFromCenter-b.distanceFromCenter||a.nodeId-b.nodeId);const records=eligible.map((n,canonicalSeedIndex)=>stable({canonicalSeedIndex,...n})),identityDomain={operationId:OPERATION_ID,candidateHead:CANDIDATE_BASE_HEAD,sourceMode,terrainPartitionDigest:partitionHash.digest('hex'),resolvedCenterNodeId:center.nodeId,eligibilityPredicateDigest:sha256({water:'elevation <= 0',traversable:'water false and slope <= 25',distance:'euclidean <= 144'}),orientationDictionaryDigest:orientationDictionaryDigest(),orderedSeedRecords:records},eligibleSeedListDigest=sha256(identityDomain),manifest=stable({schema:'H_EARTH_INTER_HILL_ESTATE_V2_ELIGIBLE_SEED_MANIFEST_v1',operationId:OPERATION_ID,candidateHead:CANDIDATE_BASE_HEAD,sourceMode,terrainPartitionDigest:identityDomain.terrainPartitionDigest,resolvedCenter:{nodeId:center.nodeId,row:center.row,column:center.column,worldX:center.worldX,worldZ:center.worldZ},eligibilityPredicateDigest:identityDomain.eligibilityPredicateDigest,orientationDictionaryDigest:identityDomain.orientationDictionaryDigest,eligibleSeedCount:records.length,configurationDenominator:records.length*36,firstEligibleNodeId:records[0]?.nodeId??null,finalEligibleNodeId:records.at(-1)?.nodeId??null,eligibleSeeds:records,eligibleSeedListDigest});assertPreflightHasNoScientificOutcome(manifest);if(outputFile)writeCanonicalJson(outputFile,manifest);return manifest}
if(process.argv[1]===fileURLToPath(import.meta.url)){const mode=process.argv[2]??SOURCE_MODES[0],out=process.argv[3]??null;const result=runCountOnlyPreflight({sourceMode:mode,outputFile:out});console.log(JSON.stringify({sourceMode:mode,eligibleSeedCount:result.eligibleSeedCount,configurationDenominator:result.configurationDenominator,eligibleSeedListDigest:result.eligibleSeedListDigest}))}
