(() => {
"use strict";

const items = [
 {id:"ai-entry",label:"AI Entry",title:"AI Entry",question:"How does a fresh AI workstream find the repository, project, state, and boundaries before acting?",signal:"ORIENT BEFORE MUTATION",status:"Demonstrated",summary:"Repository-resident entry instrumentation lets a fresh workstream recover project context and route ownership before substantive action.",mechanism:"The canonical AI entrypoint resolves the repository router, affected project, governing instructions and mutation-intent disposition. Conversation memory is not treated as repository authority.",boundary:"Orientation does not grant mutation, merge, deployment, release or product-semantic authority.",proof:"/evidence/#orientation"},
 {id:"control-plane",label:"Control Plane",title:"Control Plane",question:"How does human intent become an operation the system can reason about?",signal:"INTENT → BOUNDED OPERATION",status:"Operationally exercised",summary:"Natural-language direction is translated into explicit scope, exact state, roles, procedures, tests and stopping conditions before construction.",mechanism:"The control plane separates project routing, operation intake, construction procedure, execution carrier, qualification and continuation rather than collapsing them into one command.",boundary:"The control plane organizes work; it does not make subjective judgment automatically objective.",proof:"/evidence/#exact-state"},
 {id:"authority",label:"Authority",title:"Authority Separation",question:"How does capability remain separate from permission?",signal:"CAPABILITY ≠ AUTHORITY",status:"Demonstrated",summary:"Different components can transport, inspect, test or recover work without inheriting unrelated product authority.",mechanism:"Roles explicitly declare whether they may mutate, expand scope, repair, merge, deploy or release. Tool availability and successful execution do not widen those declarations.",boundary:"A successful test or carrier execution is not approval to merge or publish.",proof:"/evidence/#authority"},
 {id:"state-locks",label:"State + Locks",title:"Exact State & Locks",question:"How does work stay attached to the repository reality it was admitted against?",signal:"EXACT HEAD · SCOPE · LOCK",status:"Demonstrated",summary:"Operations are bound to exact repository state and bounded scope instead of relying on moving branch names or conversational assumptions.",mechanism:"Canonical intake records the exact governing commit, operation identity, lock scope, role boundaries, procedure identity and stop conditions. Advancement can force successor handling instead of silent continuation.",boundary:"Exact state improves reproducibility and continuity; it is not a blanket cryptographic-security claim.",proof:"/evidence/#exact-state"},
 {id:"recovery",label:"Recovery",title:"Multi-Agent Recovery",question:"How can one workstream help another without taking it over?",signal:"RECOVER WITHOUT AUTHORITY INFLATION",status:"Demonstrated",summary:"Bounded recovery allows one workstream to diagnose or repair an execution seam while preserving the original operation's product authority.",mechanism:"Recovery is treated as a separate scoped operation. The original workstream later re-resolves state and continues from the correct boundary rather than inheriting hidden session state.",boundary:"Recovery does not authorize an assisting workstream to redefine the product or silently replace the original lock.",proof:"/evidence/#recovery"},
 {id:"execution",label:"Execution",title:"Bounded Execution",question:"How is code allowed to execute without exposing an arbitrary command surface?",signal:"FIXED COMMAND · CLOSED WORLD",status:"Demonstrated",summary:"Authorized execution descriptors bind a known tool, exact inputs, allowed side effects and expected receipt schema.",mechanism:"The execution transport selects exactly one registered descriptor or fails closed. Arbitrary command fields, moving tooling refs and undeclared environment overrides are rejected by design.",boundary:"Execution transport performs the declared operation only; transportability does not create admissibility or release authority.",proof:"/evidence/#execution"},
 {id:"qualification",label:"Qualification",title:"Qualification",question:"How does the system distinguish 'it ran' from 'it is acceptable'?",signal:"EXECUTION ≠ COMPLETION",status:"Demonstrated",summary:"Candidate work is subjected to explicit positive and negative checks, runtime or presentation criteria, and fresh exact-head verification.",mechanism:"Qualification can include static validation, browser/runtime checks, failure-path testing, protected-surface verification and exact candidate binding. Required failures stop continuation.",boundary:"Passing qualification supports the bounded acceptance criteria; it does not establish defect-free software or external certification.",proof:"/evidence/#qualification"},
 {id:"native-3d",label:"Native 3D",title:"Browser-Native 3D",question:"How are spatial worlds built directly into the public estate?",signal:"HTML · JS · WEBGL · GLSL",status:"Live demonstrated surfaces",summary:"Diamond Gate Bridge uses repository-owned browser code and direct graphics technologies across multiple spatial public experiences.",mechanism:"World and object systems separate runtime, geometry, rendering, controls and product semantics so spatial experiences can evolve without one component absorbing every responsibility.",boundary:"Native construction is a demonstrated approach, not a claim that every future project must be framework-free or that native automatically means superior.",proof:"/evidence/#3d-construction"},
 {id:"artifact-pipeline",label:"Artifact Pipeline",title:"Exact Artifact Pipeline",question:"How can a finished binary move through the system without losing its identity?",signal:"APPROVED BYTES → VERIFIED BYTES",status:"Production demonstrated",summary:"The production pipeline can transport bounded binary chunks, reconstruct the exact artifact, verify its identity and carry the verified object into repository publication.",mechanism:"Artifact identity is bound with byte count and SHA-256. Reconstruction and repository identity are checked before the finished object is treated as the same approved artifact.",boundary:"Binary identity proves byte/provenance identity, not creative merit, factual truth or publication authority.",proof:"/evidence/#exact-artifact"},
 {id:"chapter-one",label:"Chapter One",title:"Chapter One · Complete Production Case",question:"What does the full system look like when it carries a real creative-production object?",signal:"65s MASTER → LIVE ESTATE",status:"Live production specimen",summary:"Chapter One connects creative intent, source media, editorial construction, master approval, exact artifact identity, governed transport and live presentation.",mechanism:"The exact 65-second production master is a useful public specimen because the visible film can be inspected first, then traced backward into the mechanisms that carried it into production.",boundary:"The case demonstrates an internal production lineage and exact artifact handling; it does not turn the film into external certification of the platform.",proof:"/evidence/#production"}
];

const root=document.querySelector("[data-carousel]"),ring=root?.querySelector("[data-ring]"),viewport=root?.querySelector("[data-viewport]"),tabs=root?.querySelector("[data-tabs]"),live=root?.querySelector("[data-live]"),title=root?.querySelector("[data-active-title]"),question=root?.querySelector("[data-active-question]");
if(!root||!ring||!viewport||!tabs)return;

const cards=[],state={index:0,angle:0,dragging:false,pointerId:null,startX:0,startAngle:0,lastX:0,lastTime:0,travel:0,velocity:0,inspecting:false,settling:false,timer:null,suppressClick:false};
const count=items.length,step=360/count,normalize=v=>((v%count)+count)%count,angleFor=i=>-normalize(i)*step,reduced=()=>matchMedia?.("(prefers-reduced-motion: reduce)")?.matches===true;
function radius(){const w=Math.max(320,viewport.clientWidth||root.clientWidth||960);if(w<520)return Math.max(250,Math.min(330,w*.78));if(w<820)return Math.max(330,Math.min(450,w*.62));return Math.max(470,Math.min(700,w*.52))}
function markup(item,i){return `<div class="surface"><button class="close" type="button" data-close hidden aria-label="Return to Orbit">↶ Return to Orbit</button><div class="card-top"><span class="ordinal">${String(i+1).padStart(2,"0")} / ${String(count).padStart(2,"0")}</span><span class="status">${item.status}</span></div><div class="card-body"><p class="kicker">Developer mechanism</p><h3>${item.title}</h3><p class="card-question">${item.question}</p><div class="signal">${item.signal}</div><button class="open" type="button" data-open>Inspect this mechanism</button><div class="inspection"><aside class="inspection-rail"><strong>${item.status}</strong><p>${item.summary}</p></aside><div class="inspection-detail"><p class="kicker">How it works</p><h4>${item.title}</h4><p>${item.mechanism}</p><div class="grid"><section><strong>Why it matters</strong><p>${item.summary}</p></section><section><strong>Boundary</strong><p>${item.boundary}</p></section></div><a class="proof-link" href="${item.proof}">View matching evidence →</a></div></div></div></div>`}
items.forEach((item,i)=>{const a=document.createElement("article");a.className="card";a.dataset.index=i;a.dataset.id=item.id;a.dataset.active=String(i===0);a.dataset.inspecting="false";a.innerHTML=markup(item,i);ring.append(a);cards.push(a);a.querySelector("[data-open]").addEventListener("click",e=>{e.stopPropagation();open(a)});a.querySelector("[data-close]").addEventListener("click",e=>{e.preventDefault();e.stopPropagation();close()})});
tabs.replaceChildren(...items.map((item,i)=>{const b=document.createElement("button");b.className="tab";b.type="button";b.role="tab";b.dataset.index=i;b.dataset.indexLabel=`${String(i+1).padStart(2,"0")}`;b.setAttribute("aria-selected",String(i===0));b.textContent=item.label;return b}));
function publish(reason){const item=items[state.index];root.dataset.activeId=item.id;live.textContent=`${item.label} · ${state.index+1} of ${count}`;title.textContent=item.title;question.textContent=item.question;history.replaceState(null,"",`#${item.id}`);dispatchEvent(new CustomEvent("PUBLIC_LEGITIMACY_CAROUSEL_CHANGED",{detail:{page:"developer",reason,id:item.id,index:state.index,inspecting:state.inspecting}}))}
function geometry(reason="geometry"){const r=radius();ring.style.setProperty("--ring-rotation",`${state.angle}deg`);cards.forEach((c,i)=>{c.style.transform=`rotateY(${i*step}deg) translateZ(${r}px)`;const on=i===state.index;c.dataset.active=String(on);c.setAttribute("aria-hidden",String(!on));c.querySelector("[data-open]").tabIndex=on&&!state.inspecting?0:-1});tabs.querySelectorAll("[data-index]").forEach((b,i)=>{const on=i===state.index;b.setAttribute("aria-selected",String(on));b.tabIndex=on?0:-1});publish(reason)}
function select(i,reason="select",focus=false){if(state.inspecting||state.settling)return;const n=normalize(i);if(n===state.index)return;const target=angleFor(n);state.settling=true;root.dataset.settling="true";ring.style.setProperty("--ring-rotation",`${target}deg`);const commit=()=>{state.index=n;state.angle=target;state.settling=false;root.dataset.settling="false";geometry(reason);if(focus)tabs.querySelector(`[data-index="${n}"]`)?.focus({preventScroll:true})};if(reduced())commit();else{clearTimeout(state.timer);state.timer=setTimeout(commit,620)}}
function open(card){if(state.inspecting||state.settling||Number(card.dataset.index)!==state.index)return;state.inspecting=true;root.dataset.inspecting="true";card.dataset.inspecting="true";card.querySelector("[data-close]").hidden=false;geometry("inspect");requestAnimationFrame(()=>card.querySelector("[data-close]")?.focus({preventScroll:true}))}
function close(){if(!state.inspecting)return;const card=cards[state.index];state.inspecting=false;root.dataset.inspecting="false";card.dataset.inspecting="false";card.querySelector("[data-close]").hidden=true;state.angle=angleFor(state.index);geometry("return-to-orbit");requestAnimationFrame(()=>card.querySelector("[data-open]")?.focus({preventScroll:true}))}
function snap(){const projected=state.angle+Math.max(-28,Math.min(28,state.velocity*95));state.index=normalize(Math.round(-projected/step));state.angle=angleFor(state.index);geometry("drag-snap")}
tabs.addEventListener("click",e=>{const b=e.target.closest("[data-index]");if(b)select(Number(b.dataset.index),"tab")});
tabs.addEventListener("keydown",e=>{if(!["ArrowLeft","ArrowRight","Home","End"].includes(e.key))return;e.preventDefault();if(e.key==="Home")select(0,"keyboard",true);else if(e.key==="End")select(count-1,"keyboard",true);else select(state.index+(e.key==="ArrowRight"?1:-1),"keyboard",true)});
ring.addEventListener("click",e=>{if(state.suppressClick){state.suppressClick=false;e.preventDefault();return}const card=e.target.closest(".card");if(!card)return;const i=Number(card.dataset.index);if(i!==state.index&&!state.inspecting&&!state.settling){select(i,"card");return}if(i===state.index&&!state.inspecting&&!state.settling&&!e.target.closest("button,a"))open(card)});
viewport.addEventListener("pointerdown",e=>{if(state.inspecting||state.settling||(e.pointerType==="mouse"&&e.button!==0)||e.target.closest("button,a"))return;state.dragging=true;state.pointerId=e.pointerId;state.startX=e.clientX;state.lastX=e.clientX;state.lastTime=performance.now();state.startAngle=state.angle;state.travel=0;state.velocity=0;viewport.dataset.dragging="true";viewport.setPointerCapture?.(e.pointerId)});
viewport.addEventListener("pointermove",e=>{if(!state.dragging||e.pointerId!==state.pointerId)return;const now=performance.now(),w=Math.max(320,viewport.clientWidth),d=e.clientX-state.startX;state.travel=Math.max(state.travel,Math.abs(d));state.angle=state.startAngle+(d/w)*190;const elapsed=Math.max(8,now-state.lastTime);state.velocity=(e.clientX-state.lastX)/elapsed;state.lastX=e.clientX;state.lastTime=now;ring.style.setProperty("--ring-rotation",`${state.angle}deg`)});
function finish(e){if(!state.dragging||e.pointerId!==state.pointerId)return;const tap=state.travel<7;state.dragging=false;viewport.dataset.dragging="false";viewport.releasePointerCapture?.(e.pointerId);state.pointerId=null;if(tap){state.angle=angleFor(state.index);geometry("tap");if(!e.target.closest("button,a"))open(cards[state.index]);return}state.suppressClick=true;snap()}
viewport.addEventListener("pointerup",finish);viewport.addEventListener("pointercancel",finish);
root.addEventListener("keydown",e=>{if(e.key==="Escape"&&state.inspecting){e.preventDefault();close();return}if(state.inspecting||state.settling||e.target.closest("[role=tablist]"))return;if(e.key==="ArrowLeft"||e.key==="ArrowRight"){e.preventDefault();select(state.index+(e.key==="ArrowRight"?1:-1),"stage-keyboard")}});
addEventListener("resize",()=>geometry("resize"),{passive:true});
const hash=location.hash.slice(1);const initial=items.findIndex(x=>x.id===hash);state.index=initial>=0?initial:0;state.angle=angleFor(state.index);geometry("init");
})();
