#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
export const INSTRUMENT_STATUS='RATIFIED_ACTIVE_FAIL_CLOSED';
export const GAP_ID='WORKFLOW_INSTRUMENT_LIFECYCLE_ADOPTION_RETIREMENT_SIGNAL_CONTINUITY';
export const REQUIRED=Object.freeze(['FULL_ACTIONS_SURFACE_INVENTORY','CURRENT_AUTHORITY_CLASSIFICATION','ZERO_JOB_AND_EXPECTED_FAILURE_SIGNAL_NORMALIZATION','PROTECTED_LIVE_WORKSTREAM_NONINTERFERENCE','CONTINUITY_PROOF_FOR_EACH_PHYSICAL_RETIREMENT_CLASS','POST_MERGE_OBSERVATION_PROOF']);
export const SIGNALS=Object.freeze({ZERO_JOB_FAILURE_SIGNAL:false,EXPECTED_RETIREMENT_COMPATIBILITY_FAILURE:false,LIVE_REQUIRED_CONTROL_PLANE_RESULT:true});
const stable=v=>Array.isArray(v)?v.map(stable):(v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v);
const fail=(code,detail=null)=>({pass:false,code,detail});
export function normalizeSignal(signal){if(!signal||typeof signal!=='object')return fail('SIGNAL_NORMALIZATION_INVALID','NOT_OBJECT');if(!Object.hasOwn(SIGNALS,signal.class))return fail('SIGNAL_NORMALIZATION_INVALID','UNKNOWN_CLASS');if(signal.class==='ZERO_JOB_FAILURE_SIGNAL'&&signal.executedJobCount!==0)return fail('SIGNAL_NORMALIZATION_INVALID','ZERO_JOB_COUNT_NONZERO');if(signal.class==='EXPECTED_RETIREMENT_COMPATIBILITY_FAILURE'&&signal.expectedRetirementMismatch!==true)return fail('SIGNAL_NORMALIZATION_INVALID','EXPECTED_RETIREMENT_MISMATCH_NOT_BOUND');if(signal.class==='LIVE_REQUIRED_CONTROL_PLANE_RESULT'&&signal.requiredSurface!==true)return fail('SIGNAL_NORMALIZATION_INVALID','REQUIRED_SURFACE_NOT_BOUND');return{pass:true,class:signal.class,countsAsLiveControlPlaneRegression:SIGNALS[signal.class]};}
export function verifyAssessment(input){if(!input||typeof input!=='object'||Array.isArray(input))return stable({schema:'WORKFLOW_LIFECYCLE_RETIREMENT_CONTINUITY_RECEIPT_v1',result:'FAIL_CLOSED',errorCode:'ASSESSMENT_INVALID'});if(input.schema!=='WORKFLOW_LIFECYCLE_RETIREMENT_CONTINUITY_ASSESSMENT_v1')return stable({schema:'WORKFLOW_LIFECYCLE_RETIREMENT_CONTINUITY_RECEIPT_v1',result:'FAIL_CLOSED',errorCode:'ASSESSMENT_SCHEMA_INVALID'});if(!/^[0-9a-f]{40}$/.test(input.governingHead??''))return stable({schema:'WORKFLOW_LIFECYCLE_RETIREMENT_CONTINUITY_RECEIPT_v1',result:'FAIL_CLOSED',errorCode:'GOVERNING_MAIN_MISMATCH'});if(input.gapId!==GAP_ID)return stable({schema:'WORKFLOW_LIFECYCLE_RETIREMENT_CONTINUITY_RECEIPT_v1',result:'FAIL_CLOSED',errorCode:'GAP_ID_MISMATCH'});const req={};for(const id of REQUIRED){const item=input.requirements?.[id];const pass=item?.status==='PASS'&&Array.isArray(item.evidence)&&item.evidence.length>0;req[id]={status:pass?'PASS':'FAIL',evidenceCount:Array.isArray(item?.evidence)?item.evidence.length:0};}const normalization=(input.signals??[]).map(normalizeSignal);const normalizationPass=normalization.every(x=>x.pass===true);const unresolvedConsumers=Number.isInteger(input.unresolvedConsumerCount)?input.unresolvedConsumerCount:-1;const authority=input.authorityEffects??{};const noAuthorityInflation=authority.physicalRetirementAuthorized===false&&authority.gapRegistryMutationAuthorized===false&&authority.mergeAuthorized===false&&authority.productMutationAuthorized===false&&authority.workflowMutationAuthorized===false;const allRequirements=REQUIRED.every(id=>req[id].status==='PASS');const pass=allRequirements&&normalizationPass&&unresolvedConsumers===0&&noAuthorityInflation;return stable({schema:'WORKFLOW_LIFECYCLE_RETIREMENT_CONTINUITY_RECEIPT_v1',instrumentStatus:INSTRUMENT_STATUS,result:pass?'PASS_CLOSED_ELIGIBLE':'FAIL_CLOSED',governingHead:input.governingHead,gapId:GAP_ID,requirements:req,normalization:{pass:normalizationPass,signals:normalization},unresolvedConsumerCount:unresolvedConsumers,authorityEffects:{...authority,noAuthorityInflation}});}
function args(argv){const out={};for(let i=0;i<argv.length;i+=2){const k=argv[i],v=argv[i+1];if(!['--assessment','--output'].includes(k)||v===undefined)throw new Error('CLI_ARGUMENT_INVALID');out[k.slice(2)]=v;}if(!out.assessment||!out.output)throw new Error('CLI_ARGUMENT_INCOMPLETE');return out;}
function main(){const a=args(process.argv.slice(2));const receipt=verifyAssessment(JSON.parse(fs.readFileSync(path.resolve(a.assessment),'utf8')));fs.mkdirSync(path.dirname(path.resolve(a.output)),{recursive:true});fs.writeFileSync(path.resolve(a.output),JSON.stringify(receipt,null,2)+'\n');if(receipt.result!=='PASS_CLOSED_ELIGIBLE')process.exitCode=1;}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))main();
