(() => {
  "use strict";

  const SOURCE_HOLD = "Architecture preserved · original controlling source under recovery";

  const families = [
    {
      id: "structure",
      label: "Structural Envelope",
      title: "Structural Envelope and Collapse",
      question: "What must be present, saturated, and functionally failed before collapse is qualified?",
      models: [
        { id:"envelope-451", title:"451 Structural Envelope", equation:"451 = 256 + 192 + 3", status:"Source confirmed", statement:"The full envelope joins burden, pressure, and the required coherence spine without confusing them.", practical:"A system can carry internal burden and external pressure while still depending on three required functions to remain coherent.", purpose:"Separate the complete structural envelope from the terminal saturation gate and the independent spine-failure threshold.", failure:"451 alone does not qualify collapse. Saturation and spine failure are tested separately.", limits:"This is a formal architecture, not empirical completion." },
        { id:"gate-448", title:"448 Saturation Gate", equation:"448 = 256 + 192", status:"Source hold", statement:"The saturation gate excludes the spine because the spine is tested for functional failure, not numerical saturation.", practical:"Every declared burden cell and pressure channel must reach the exact gate.", purpose:"Distinguish exact internal-plus-external saturation from the larger 451 envelope.", failure:"A partial or approximate saturation state does not satisfy the gate.", limits:SOURCE_HOLD },
        { id:"spine-minimum", title:"E / I / V Minimum Principle", equation:"W_d = min(E_d, I_d, V_d)", status:"Source confirmed", statement:"Required coherence is governed by the weakest spine axis, not by an average.", practical:"Apparent strength can be misleading when one part is carrying functions that belong elsewhere.", purpose:"Expose functional failure without allowing strong axes to compensate for a collapsed required axis.", failure:"Spine failure occurs when the minimum required axis reaches or falls below the domain-specific threshold ε.", limits:"Domain definitions and ε values must be frozen before empirical execution." },
        { id:"collapse-qualified", title:"Qualified Collapse Predicate", equation:"B256 ≥ 256 ∧ P192 ≥ 192 ∧ min(E, I, V) ≤ ε", status:"Source confirmed", statement:"Collapse requires simultaneous saturation of burden and pressure plus failure of the weakest required spine axis.", practical:"Qualification requires all declared conditions at the same evaluation state.", purpose:"Prevent elevated burden, elevated pressure, or isolated weakness from being mislabeled as fully qualified collapse.", failure:"The predicate is false when any required clause is false.", limits:"Diagnostic qualification does not establish universal empirical proof or causation." },
        { id:"membrane-61", title:"61 Admissibility Membrane", equation:"61 ∉ 451", status:"Source hold", statement:"Admissibility surrounds the architecture; it is not another component inside 451.", practical:"Not everything available should be allowed to enter a diagnosis, comparison, or claim.", purpose:"Preserve the boundary between model structure and the rules that govern entry.", failure:"Entry is held when admissibility conditions are not satisfied.", limits:SOURCE_HOLD },
        { id:"anchors-9", title:"Nine Basin Anchors", equation:"9 ∉ 451", status:"Source hold", statement:"The basin anchors orient a separate architecture and are not hidden inside 451.", practical:"Orientation points can organize a field without becoming burden, pressure, or coherence components.", purpose:"Prevent the basin-anchor architecture from being silently added to the collapse total.", failure:"The collapse predicate must not change merely because an anchor is present or absent.", limits:SOURCE_HOLD }
      ]
    },
    {
      id: "pressure",
      label: "Pressure / Capacity",
      title: "Pressure, Capacity, and Stability",
      question: "How does the architecture preserve pressure, usable capacity, stability, and hazard without hiding a zero?",
      models: [
        { id:"pressure-field", title:"Pressure Field", equation:"Π = G · X", status:"Source confirmed", statement:"Pressure is multiplicative: a missing required pressure term remains visible as zero.", practical:"Pressure is a declared relationship among required terms, not one vague feeling.", purpose:"Construct pressure without silently flooring or renaming a zero term.", failure:"If any required normalized pressure term is zero, Π remains zero.", limits:"The formula does not validate a pressure interpretation by itself." },
        { id:"capacity-field", title:"Usable Capacity", equation:"K = P · R · A · C", status:"Source confirmed", statement:"Capacity is a product of required functions; one unavailable factor destroys the composite.", practical:"A system may appear well supplied while one indispensable capacity is unavailable.", purpose:"Represent usable composite capacity without additive compensation.", failure:"Any required capacity factor at zero forces K to zero.", limits:"Factor meanings and bounds remain domain-specific." },
        { id:"pcr", title:"Pressure-to-Capacity Ratio", equation:"PCR = Π / max(K, εK)", status:"Source confirmed", statement:"The ratio compares pressure with protected usable capacity while preserving the reason a safety floor exists.", practical:"The same pressure can be manageable in one state and hazardous in another because usable capacity differs.", purpose:"Compare pressure with capacity without creating undefined division.", failure:"A small protected denominator can produce a high ratio, but PCR alone is not the SAFE_MODE trigger.", limits:"PCR is a diagnostic index, not proof of collapse or causation." },
        { id:"stability", title:"Stability Complement", equation:"S* = 1 / (1 + PCR)", status:"Source confirmed", statement:"Stability decreases continuously as the pressure-capacity ratio rises.", practical:"Stability is treated as remaining room to absorb pressure.", purpose:"Provide a bounded stability representation tied directly to PCR.", failure:"As PCR grows without bound, S* approaches zero.", limits:"A bounded score does not establish empirical calibration." },
        { id:"hazard", title:"Hazard Complement", equation:"H* = PCR / (1 + PCR)", status:"Source confirmed", statement:"Hazard rises from the same pressure-capacity relationship that reduces stability.", practical:"Hazard and stability are two readings of one declared relationship.", purpose:"Express normalized collapse-pressure mass without changing the underlying PCR architecture.", failure:"As PCR grows without bound, H* approaches one.", limits:"H* is not an independently validated probability of failure." },
        { id:"complement", title:"Stability–Hazard Identity", equation:"S* + H* = 1", status:"Source confirmed", statement:"The two outputs partition one declared mass rather than creating extra information.", practical:"Calling one side stability and the other hazard does not allow either side to exceed the whole.", purpose:"Keep stability and hazard algebraically linked and auditable.", failure:"Material deviation from one indicates an implementation or precision defect.", limits:"The identity validates arithmetic consistency, not empirical validity." },
        { id:"zero-aware", title:"Zero-Aware Multiplication", equation:"0 in required terms ⇒ product = 0", status:"Source confirmed", statement:"A required zero is preserved as collapse; it is never silently dropped to keep the product alive.", practical:"Missing or collapsed capacity cannot be disguised by unrelated strengths.", purpose:"Protect noncompensatory meaning during stable numerical implementation.", failure:"Dropping a zero falsely preserves pressure or capacity and invalidates the diagnostic.", limits:"Numerical stability does not authorize changing zero semantics." }
      ]
    },
    {
      id: "closure",
      label: "Closure / Flow",
      title: "Closure and System Flow",
      question: "How are material, energy, recovery, and unresolved residuals kept accountable?",
      models: [
        { id:"mass-ledger", title:"Industrial Closure Equation", equation:"M_in = M_out + M_dest + ΔM_inv ± ε", status:"Source confirmed", statement:"A closure claim must reconcile input, output, destruction, inventory change, and uncertainty.", practical:"A compliance statement is not enough when hazardous mass remains unaccounted for.", purpose:"Convert closure from rhetoric into an auditable mass balance.", failure:"Unaccounted mass remains a residual rather than being assigned to closure by assertion.", limits:"The equation does not prove a destruction technology performs as claimed." },
        { id:"residual-u", title:"Unaccounted Residual", equation:"U = M_in − (M_out + M_dest + ΔM_inv)", status:"Source confirmed", statement:"The unresolved residual is measured directly instead of hidden inside a closure label.", practical:"What cannot be accounted for remains an open question, not an automatic success.", purpose:"Expose unresolved hazardous mass as a measurable quantity.", failure:"A large absolute residual indicates that the ledger remains open.", limits:"The residual inherits every measurement and custody limitation in its component terms." },
        { id:"closure-threshold", title:"Closure Threshold", equation:"Closed if |U| ≤ 3ε · Open if |U| > 3ε", status:"Source confirmed", statement:"Closure is bounded by declared uncertainty rather than by a perfect-zero fiction.", practical:"A tiny difference within declared measurement uncertainty is not treated like a material unresolved loss.", purpose:"Create a transparent and falsifiable closure decision rule.", failure:"The ledger is open when |U| exceeds 3ε.", limits:"The threshold must be justified for the domain." },
        { id:"energy-loop", title:"Energy Loop Law", equation:"Storage → Release → Operate → Recover → Storage", status:"Source confirmed", statement:"A complete loop includes storage, release, operation, recovery, and return to storage.", practical:"A process is not circular merely because one stage can be repeated.", purpose:"Distinguish a complete operating loop from a partial sequence.", failure:"A loop remains open when energy, material, or reset obligations cannot return to storage.", limits:"A formal loop architecture is not final empirical validation." },
        { id:"useful-output", title:"Useful Output Condition", equation:"Useful_Output ≥ Total_Input + Losses + Reset_Costs", status:"Source confirmed", statement:"Reset costs belong inside the comparison; they cannot be externalized to make the loop appear productive.", practical:"A process that works once but cannot afford to reset is not a sustained closed loop.", purpose:"Prevent partial accounting from being presented as a closed productive loop.", failure:"The condition fails when useful output cannot cover the complete declared cost of operation and reset.", limits:"The inequality does not establish economic viability or field performance." }
      ]
    },
    {
      id: "method",
      label: "Method / Falsification",
      title: "Method, Resolution, and Falsification",
      question: "How are claims constructed, classified, challenged, and recorded without changing their evidence standing?",
      models: [
        { id:"first", title:"F.I.R.S.T. Research Method", equation:"Flow → Integrity → Reality → Structure → Test", status:"Page-native method", statement:"Research asks what changed, what remained intact, what evidence shows, what shaped the result, and what was tested.", practical:"The sequence keeps a conclusion from outrunning the observations, boundaries, and tests that support it.", purpose:"Provide a repeatable orientation for examining change, continuity, evidence, conditions, and execution.", failure:"A conclusion is held when one required question cannot be answered or is contradicted by the record.", limits:"The acronym organizes research; it does not validate a model by presentation." },
        { id:"integral-method", title:"Integral Scientific Method", equation:"Observe → Reduce → Falsify → Iterate → Terminate → Compress", status:"Method specification", statement:"Observe, reduce, falsify, iterate, terminate, and compress without granting certainty to survival alone.", practical:"A claim is allowed to collapse cleanly instead of being protected by explanation after explanation.", purpose:"Constrain inquiry so objectivity is not abandoned to preserve a favored claim.", failure:"The process terminates when continuation requires violating objectivity.", limits:"Method custody does not establish replication or empirical validation." },
        { id:"diagnostic-five", title:"Five-Diagnostic Classification Set", equation:"C.A.D. · C.T.D. · C.F.D. · I.M.D. · T.D.", status:"Frozen registration", statement:"Five named diagnostics preserve alignment, transparency, fragmentation, internal coherence, and trajectory.", practical:"A classification is more accountable when the questions are named before the answer is known.", purpose:"Apply predefined diagnostic rules uniformly without weighting, tuning, or post-hoc adjustment.", failure:"The method is not reliable when independent observers cannot converge under the same evidence.", limits:"Registration and files reviewed do not establish empirical validation." },
        { id:"abcd", title:"A–B–C–D Diagnostic Procedure", equation:"A → B → C → D", status:"Procedure only", statement:"Each letter constrains the next; skipping a stage invalidates the diagnosis.", practical:"A situation should not be labeled by trajectory before internal coherence and constraints are inspected.", purpose:"Force ordered examination before assigning a trajectory classification.", failure:"Skipping a stage invalidates the diagnosis.", limits:"The output is not prediction, prescription, causation, blame, or domain-specific interpretation." },
        { id:"falsification", title:"Formal Falsification Path", equation:"Define → Measure → Freeze → Score → Compare", status:"Executed retrospective route", statement:"Define the state, measure maneuverability, freeze the lead window, score narrowing, and compare against later outcomes.", practical:"A serious claim states what evidence would force revision or withdrawal, then preserves the result when the stronger comparator wins.", purpose:"Expose trajectory-narrowing claims to explicit disconfirmation rather than protecting the preferred operator.", failure:"The claim fails when narrowing does not precede failure, produces unacceptable errors, or disappears under strong comparators.", limits:"Execution of a retrospective route is not confirmatory validation or independent replication." },
        { id:"no-match", title:"No-Match Discipline", equation:"No match ⇒ no consumption", status:"Canonical method", statement:"Evidence is held with an explicit reason instead of being forced into an applicable slot.", practical:"A missing or incompatible record should remain unresolved rather than being made to fit.", purpose:"Protect the resolver and downstream claims from forced applicability.", failure:"Forced matching invalidates provenance and applicability.", limits:"A no-match result does not determine the real-world condition of the subject." },
        { id:"fixtures", title:"Synthetic Fixtures", equation:"Fixture pass ≠ empirical validation", status:"Contract test", statement:"Fixtures verify expected contract behavior; they do not become field evidence.", practical:"A model behaving correctly on constructed examples is not the same as succeeding in the world.", purpose:"Verify deterministic resolver and output-contract behavior.", failure:"A fixture failure identifies a contract or implementation defect.", limits:"Fixture success is not real telemetry, external replication, or empirical validation." }
      ]
    },
    {
      id: "maneuverability",
      label: "Maneuverability / IMI",
      title: "Intrinsic Maneuverability and Prospective Testing",
      question: "Can remaining room to move reveal something that current condition alone does not?",
      models: [
        { id:"condition-capacity", title:"Condition Is Not Capacity", equation:"same output ≠ same remaining routes", status:"Research proposition", statement:"Two systems can present similar current output while preserving very different amounts of admissible maneuvering room.", practical:"The instrument asks not only how a system looks now, but how many identity-preserving ways it can still move from here.", purpose:"Separate visible condition from endogenous capacity and available routes.", failure:"The proposition weakens if route-sensitive measures add no stable information beyond conventional condition variables.", limits:"This distinction is a research construct, not a universal empirical law." },
        { id:"imi-route", title:"Intrinsic Maneuverability Index", equation:"IMIτ(t) = ∏ aᵢ(t)", status:"Operational research instrument", statement:"For a specified trajectory, required constraints are converted into available maneuverability and combined noncompensatorily.", practical:"A single exhausted required factor can close a route even when other factors remain strong.", purpose:"Represent trajectory-specific room to maneuver while keeping required constraints explicit.", failure:"The instrument is not supported when factor definitions are unstable, route requirements are post-hoc, or strong comparators consistently dominate.", limits:"Factor mappings and route identity remain domain-specific and must be frozen before execution." },
        { id:"agricultural-temporal", title:"Agricultural Temporal Block", equation:"held-out: CS4 0.04564 · Mean4 0.04532", status:"Completed bounded result", statement:"In the frozen final 20 transitions, CS4 improved held-out RMSE versus current loss alone and current loss plus Varroa, but did not beat the additive Mean4 comparator.", practical:"The result supports a multidimensional increment while refusing to claim that multiplication itself has been distinguished.", purpose:"Test whether a constraint-state measure contains prospective information about next-quarter colony loss under a locked temporal split.", failure:"Paired uncertainty intervals included zero, and state fixed effects removed the advantage over current loss.", limits:"Retrospective locked stress test only; not confirmatory validation, independent replication, or multiplication-specific validation." },
        { id:"decisive-next-test", title:"The Decisive Next Test", equation:"maneuvering room + condition → prospective variance?", status:"Active frontier", statement:"The high-value question is whether admissible identity-preserving transitions explain prospective variation beyond conventional state and condition measures.", practical:"A breakthrough would require the route structure itself to survive strong comparators, held-out prediction, and independent replication—not merely produce an interesting score.", purpose:"Move from promising multidimensional signal toward a test of whether maneuvering room is genuinely informative in its own right.", failure:"The stronger claim is rejected if the route representation adds no reproducible prospective information after conventional variables and additive alternatives are included.", limits:"This threshold has not yet been crossed." }
      ]
    }
  ];

  globalThis.METHODS_MODELS_CAROUSEL_DATA = Object.freeze({
    contract: "METHODS_MODELS_SINGLE_AXIS_CAROUSEL_DATA_v2",
    sourceBlob: "research-state-20260822-imi-temporal",
    sourceCompletenessClaimed: false,
    scientificValidationClaimed: false,
    productAcceptanceGranted: false,
    families: Object.freeze(families.map(family => Object.freeze({ ...family, models: Object.freeze(family.models.map(Object.freeze)) })))
  });
})();
