#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import {discoverConsumers} from './consumer-discovery.v2.mjs';
export const INSTRUMENT_STATUS='RATIFIED_ACTIVE_FAIL_CLOSED_V2_EVIDENCE_BOUND';
export const GAP_ID='WORKFLOW_INSTRUMENT_LIFECYCLE_ADOPTION_RETIREMENT_SIGNAL_CONTINUITY';
export const REQUIRED=Object.freeze(['FULL_ACTIONS_SURFACE_INVENTORY','CURRENT_AUTHORITY_CLASSIFICATION','ZERO_JOB_AND_EXPECTED_FAILURE_SIGNAL_NORMALIZATION','PROTECTED_LIVE_WORKSTREAM_NONINTERFERENCE','CONTINUITY_PROOF_FOR_EACH_PHYSICAL_RETIREMENT_CLASS','POST_MERGE_OBSERVATION_PROOF']);
export const SIGNALS=Object.freeze({ZERO_JOB_FAILURE_SIGNAL:false,EXPECTED_RETIREMENT_COMPATIBILITY_FAILURE:false,LIVE_REQUIRED_CONTROL_PLANE_RESULT:true});
export const EVIDENCE_TYPES=Object.freeze({FULL_ACTIONS_SURFACE_INVENTORY:['ACTIONS_WORKFLOW_INVENTORY'],CURRENT_AUTHORITY_CLASSIFICATION:['REPOSITORY_BLOB','GITHUB_PR'],ZERO_JOB_AND_EXPECTED_FAILURE_SIGNAL_NORMALIZATION:['WORKFLOW_RUN_JOB_OBSERVATION','REPOSITORY_BLOB'],PROTECTED_LIVE_WORKSTREAM_NONINTERFERENCE:['REPOSITORY_BLOB','GITHUB_PR'],CONTINUITY_PROOF_FOR_EACH_PHYSICAL_RETIREMENT_CLASS:['GITHUB_PR','GITHUB_COMMIT','REPOSITORY_BLOB'],POST_MERGE_OBSERVATION_PROOF:['WORKFLOW_RUN_JOB_OBSERVATION','GITHUB_COMMIT']});
const stable=v=>Array.isArray(v)?v.map(stable):(v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v);
const sha256=v=>crypto.createHash('sha256').update(typeof v==='string'?v:JSON.stringify(stable(v))).digest('hex');
const fail=(errorCode,detail=null)=>stable({schema:'WORKFLOW_LIFECYCLE_RETIREMENT_CONTINUITY_RECEIPT_v2',instrumentStatus:INSTRUMENT_STATUS,result:'FAIL_CLOSED',errorCode,detail});
export function normalizeSignal(signal){if(!signal||typeof signal!=='object')return{pass:false,code:'SIGNAL_NORMALIZATION_INVALID'};if(!Object.hasOwn(SIGNALS,signal.class))return{pass:false,code:'SIGNAL_NORMALIZATION_INVALID'};if(signal.class==='ZERO_JOB_FAILURE_SIGNAL'&&signal.executedJobCount!==0)return{pass:false,code:'ZERO_JOB_COUNT_NONZERO'};if(signal.class==='EXPECTED_RETIREMENT_COMPATIBILITY_FAILURE'&&signal.expectedRetirementMismatch!==true)return{pass:false,code:'EXPECTED_RETIREMENT_MISMATCH_NOT_BOUND'};if(signal.class==='LIVE_REQUIRED_CONTROL_PLANE_RESULT'&&signal.requiredSurface!==true)return{pass:false,code:'REQUIRED_SURFACE_NOT_BOUND'};return{pass:true,class:signal.class,countsAsLiveControlPlaneRegression:SIGNALS[signal.class]};}
function assertionsValid(e){if(e.type==='ACTIONS_WORKFLOW_INVENTORY')return true;if(!Array.isArray(e.assertions)||e.assertions.length===0)return false;return e.assertions.every(a=>a&&typeof a==='object'&&['JSON_POINTER_EQUALS','TEXT_CONTAINS','CHANGED_PATH_PRESENT','CHANGED_PATH_ABSENT','COMMIT_PARENT_EQUALS','WORKFLOW_PATH_EQUALS','CONCLUSION_EQUALS'].includes(a.kind));}
function validateEvidenceShape(requirementId,e){if(!e||typeof e!=='object'||Array.isArray(e))return false;if(!EVIDENCE_TYPES[requirementId]?.includes(e.type)||e.predicate!==requirementId||!assertionsValid(e))return false;switch(e.type){case'ACTIONS_WORKFLOW_INVENTORY':return Number.isInteger(e.expectedCount)&&e.expectedCount>=0&&Array.isArray(e.workflowIds)&&e.workflowIds.length===e.expectedCount&&e.workflowIds.every(Number.isInteger)&&e.identitiesDigest===sha256([...e.workflowIds].sort((a,b)=>a-b));case'REPOSITORY_BLOB':return typeof e.path==='string'&&/^[0-9a-f]{40}$/.test(e.blobSha||'')&&/^[0-9a-f]{40}$/.test(e.ref||'');case'GITHUB_PR':return Number.isInteger(e.number)&&e.number>0&&/^[0-9a-f]{40}$/.test(e.expectedHead||'');case'GITHUB_COMMIT':return /^[0-9a-f]{40}$/.test(e.sha||'');case'WORKFLOW_RUN_JOB_OBSERVATION':return Number.isInteger(e.runId)&&e.runId>0&&Number.isInteger(e.executedJobCount)&&e.executedJobCount>=0&&/^[0-9a-f]{40}$/.test(e.expectedHead||'');default:return false;}}
export function verifyAssessmentStatic(input){if(!input||typeof input!=='object'||Array.isArray(input))return fail('ASSESSMENT_INVALID');if(input.schema!=='WORKFLOW_LIFECYCLE_RETIREMENT_CONTINUITY_ASSESSMENT_v2')return fail('ASSESSMENT_SCHEMA_INVALID');if(!/^[0-9a-f]{40}$/.test(input.governingHead||''))return fail('GOVERNING_MAIN_MISMATCH');if(input.gapId!==GAP_ID)return fail('GAP_ID_MISMATCH');if(Object.hasOwn(input,'unresolvedConsumerCount'))return fail('NAKED_UNRESOLVED_CONSUMER_COUNT_PROHIBITED');const requirements={};for(const id of REQUIRED){const item=input.requirements?.[id];const evidence=Array.isArray(item?.evidence)?item.evidence:[];const typed=evidence.length>0&&evidence.every(e=>validateEvidenceShape(id,e));requirements[id]={status:item?.status==='PASS'&&typed?'PASS':'FAIL',evidenceCount:evidence.length,typedEvidence:typed};}const normalization=(input.signals||[]).map(normalizeSignal);if(!normalization.length||normalization.some(x=>x.pass!==true))return fail('SIGNAL_NORMALIZATION_FAILED');const authority=input.authorityEffects||{};const noAuthorityInflation=authority.physicalRetirementAuthorized===false&&authority.gapRegistryMutationAuthorized===false&&authority.mergeAuthorized===false&&authority.productMutationAuthorized===false&&authority.workflowMutationAuthorized===false;if(!noAuthorityInflation)return fail('AUTHORITY_INFLATION');if(!input.consumerDiscovery||input.consumerDiscovery.schema!=='WORKFLOW_LIFECYCLE_CONSUMER_DISCOVERY_REQUEST_v2')return fail('CONSUMER_DISCOVERY_REQUIRED');if(!REQUIRED.every(id=>requirements[id].status==='PASS'))return fail('REQUIREMENT_EVIDENCE_INVALID',requirements);return stable({schema:'WORKFLOW_LIFECYCLE_RETIREMENT_CONTINUITY_RECEIPT_v2',instrumentStatus:INSTRUMENT_STATUS,result:'STRUCTURALLY_AUTHENTICATABLE',governingHead:input.governingHead,gapId:GAP_ID,requirements,normalization:{pass:true,signals:normalization},authorityEffects:{...authority,noAuthorityInflation}});}
async function api(url,token){const r=await fetch(url,{headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28'}});if(!r.ok)throw new Error(`GITHUB_API_${r.status}`);return r.json();}
function pointer(o,p){if(p==='')return o;if(typeof p!=='string'||!p.startsWith('/'))return undefined;return p.slice(1).split('/').reduce((v,k)=>v?.[k.replaceAll('~1','/').replaceAll('~0','~')],o);}
function assertContent(assertions,{json,text,changedPaths=[],parents=[],workflowPath=null,conclusion=null}){return assertions.every(a=>{switch(a.kind){case'JSON_POINTER_EQUALS':return JSON.stringify(pointer(json,a.pointer))===JSON.stringify(a.value);case'TEXT_CONTAINS':return typeof a.value==='string'&&text.includes(a.value);case'CHANGED_PATH_PRESENT':return changedPaths.includes(a.path);case'CHANGED_PATH_ABSENT':return !changedPaths.includes(a.path);case'COMMIT_PARENT_EQUALS':return parents.includes(a.sha);case'WORKFLOW_PATH_EQUALS':return workflowPath===a.path;case'CONCLUSION_EQUALS':return conclusion===a.value;default:return false;}});}
async function authenticateEvidence(e,{repository,token}){const base=`https://api.github.com/repos/${repository}`;switch(e.type){case'REPOSITORY_BLOB':{const f=await api(`${base}/contents/${e.path}?ref=${e.ref}`,token);if(f.sha!==e.blobSha||typeof f.content!=='string')return false;const text=Buffer.from(f.content.replace(/\s/g,''),'base64').toString('utf8');let json=null;try{json=JSON.parse(text)}catch{}return assertContent(e.assertions,{json,text});}case'GITHUB_COMMIT':{const c=await api(`${base}/commits/${e.sha}`,token);if(c.sha!==e.sha)return false;return assertContent(e.assertions,{json:c,text:JSON.stringify(c),changedPaths:(c.files||[]).map(f=>f.filename),parents:(c.parents||[]).map(p=>p.sha)});}case'GITHUB_PR':{const pr=await api(`${base}/pulls/${e.number}`,token);if(pr.head?.sha!==e.expectedHead)return false;const files=await api(`${base}/pulls/${e.number}/files?per_page=100`,token);return assertContent(e.assertions,{json:pr,text:JSON.stringify(pr),changedPaths:(files||[]).map(f=>f.filename)});}case'WORKFLOW_RUN_JOB_OBSERVATION':{const run=await api(`${base}/actions/runs/${e.runId}`,token);if(run.head_sha!==e.expectedHead)return false;const jobs=await api(`${base}/actions/runs/${e.runId}/jobs?per_page=100`,token);const executed=(jobs.jobs||[]).filter(j=>Array.isArray(j.steps)&&j.steps.length>0).length;if(executed!==e.executedJobCount)return false;return assertContent(e.assertions,{json:{run,jobs},text:JSON.stringify({run,jobs}),workflowPath:run.path,conclusion:run.conclusion});}case'ACTIONS_WORKFLOW_INVENTORY':{let page=1,ids=[];for(;;page++){const x=await api(`${base}/actions/workflows?per_page=100&page=${page}`,token);ids.push(...(x.workflows||[]).map(w=>w.id));if(!(x.workflows||[]).length||ids.length>=x.total_count)break;}ids=[...new Set(ids)].sort((a,b)=>a-b);return ids.length===e.expectedCount&&sha256(ids)===e.identitiesDigest&&JSON.stringify(ids)===JSON.stringify([...e.workflowIds].sort((a,b)=>a-b));}default:return false;}}
export async function verifyAssessment(input,{repository='smansfield635-create/smansfield635-create.github.io',token=process.env.GITHUB_TOKEN,repoRoot=process.cwd()}={}){const structural=verifyAssessmentStatic(input);if(structural.result!=='STRUCTURALLY_AUTHENTICATABLE')return structural;if(!token)return fail('GITHUB_TOKEN_REQUIRED');try{const main=await api(`https://api.github.com/repos/${repository}/git/ref/heads/main`,token);if(main.object?.sha!==input.governingHead)return fail('GOVERNING_MAIN_MISMATCH',{expected:input.governingHead,actual:main.object?.sha});}catch(e){return fail('GOVERNING_MAIN_AUTHENTICATION_ERROR',e.message);}for(const id of REQUIRED){for(const e of input.requirements[id].evidence){let ok=false;try{ok=await authenticateEvidence(e,{repository,token});}catch(error){return fail('EVIDENCE_AUTHENTICATION_ERROR',{requirement:id,type:e.type,message:error.message});}if(!ok)return fail('EVIDENCE_AUTHENTICATION_FAILED',{requirement:id,type:e.type});}}
 const d=input.consumerDiscovery;let actual;try{actual=discoverConsumers({repoRoot,governingHead:input.governingHead,searchRoots:d.searchRoots,tokens:d.tokens});}catch(e){return fail('CONSUMER_DISCOVERY_FAILED',e.message);}if(!d.expectedReceipt||d.expectedReceipt.receiptDigest!==actual.receiptDigest||d.expectedReceipt.scannedPathDigest!==actual.scannedPathDigest)return fail('CONSUMER_DISCOVERY_RECEIPT_MISMATCH');const allowed=new Set(d.allowedConsumers||[]),unresolved=actual.matchedConsumers.filter(m=>!allowed.has(m.path));if(unresolved.length)return fail('UNRESOLVED_CONSUMERS_PRESENT',unresolved.map(x=>x.path));return stable({...structural,result:'PASS_CLOSED_ELIGIBLE',consumerDiscovery:{receiptDigest:actual.receiptDigest,scannedPathDigest:actual.scannedPathDigest,scannedFileCount:actual.scannedFileCount,matchedConsumerCount:actual.matchedConsumers.length,unresolvedConsumerCount:0}});}
function parseArgs(argv){const o={};for(let i=0;i<argv.length;i+=2){const k=argv[i],v=argv[i+1];if(!['--assessment','--output','--repo-root','--repository'].includes(k)||v===undefined)throw new Error('CLI_ARGUMENT_INVALID');o[k.slice(2)]=v;}if(!o.assessment||!o.output)throw new Error('CLI_ARGUMENT_INCOMPLETE');return o;}
async function main(){const a=parseArgs(process.argv.slice(2));const input=JSON.parse(fs.readFileSync(path.resolve(a.assessment),'utf8'));const receipt=await verifyAssessment(input,{repoRoot:a['repo-root']||process.cwd(),repository:a.repository||'smansfield635-create/smansfield635-create.github.io'});fs.mkdirSync(path.dirname(path.resolve(a.output)),{recursive:true});fs.writeFileSync(path.resolve(a.output),JSON.stringify(receipt,null,2)+'\n');if(receipt.result!=='PASS_CLOSED_ELIGIBLE')process.exitCode=1;}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))main().catch(e=>{process.stderr.write(JSON.stringify(fail('UNEXPECTED_VERIFIER_FAILURE',e.message))+'\n');process.exitCode=1;});
