/* /laws/index.cosmos.js
   LAWS_COSMOS_ARCHCOIN_SCENE_FIELD_v5
   ARCHCOIN-density full-chamber background; decorative authority only.

   Preserves the established Laws Cosmos lifecycle, canvases, visibility,
   resize, reduced-motion, receipt, and teardown behavior. Changes are limited
   to field density, void geometry, masks, colors, and spacecraft visibility.
*/
(() => {
  "use strict";
  const G="DGB_LAWS_COSMOS",R="DGB_LAWS_COSMOS_RECEIPT",READY="DGB_LAWS_COSMOS_READY",FAIL="DGB_LAWS_COSMOS_FAILURE",DEAD="DGB_LAWS_COSMOS_DESTROYED";
  if(globalThis[G]?.initialized)return;
  const I={style:"laws-cosmos-runtime-style",layer:"laws-cosmos-layer",base:"laws-cosmos-canvas",spark:"laws-cosmos-sparkle-canvas",a:"laws-cosmos-spacecraft",b:"laws-cosmos-spacecraft-secondary"};
  const C={mobile:820,compact:560,min:52,max:108,area:6100,dustMin:0,dustMax:0,dustArea:12800,rogue:.125,candidates:8,hWarp:1.13,vWarp:.84,rJitter:.022,aJitter:.075,zig:.018,voidX:.225,voidY:.205,frame:125,seed:0x4c415753};
  const SAFE=["[data-laws-threshold-introduction]","[data-laws-panel]",".laws-value-deck",".laws-controller-panel",".laws-discovery__item",".laws-footer"];
  const MASKS=[{x:.24,y:.28,rx:.16,ry:.095,r:-.46,f:.22},{x:.76,y:.25,rx:.12,ry:.17,r:.31,f:.20},{x:.72,y:.73,rx:.18,ry:.105,r:-.19,f:.24},{x:.27,y:.77,rx:.105,ry:.15,r:.52,f:.20}];
  const COLORS=["255,248,224","154,217,225","234,208,131","170,155,224","255,248,224"],GOLD=Math.PI*(3-Math.sqrt(5));
  const S={initialized:false,destroyed:false,failed:false,reason:"",visible:!document.hidden,active:true,reduced:false,quality:1,w:0,h:0,dpr:1,root:null,layer:null,base:null,spark:null,bc:null,sc:null,stars:[],dust:[],live:[],safe:0,rogue:0,phy:0,draws:0,frames:0,burst:0,tick:0,resize:0,media:null,observer:null,hnd:{}};
  const api={initialized:false,start:()=>schedule(true),stop,destroy,resize:(x)=>resize(x||"manual"),setQuality,receipt:()=>Object.freeze(receipt())};globalThis[G]=api;
  const clamp=(v,a,b)=>Math.min(b,Math.max(a,v)),between=(r,a,b)=>a+r()*(b-a);
  function hash(v){let x=v>>>0;x^=x>>>16;x=Math.imul(x,0x7feb352d);x^=x>>>15;x=Math.imul(x,0x846ca68b);return(x^(x>>>16))>>>0}
  function rng(seed){let v=seed>>>0;return()=>{v+=0x6d2b79f5;let x=v;x=Math.imul(x^(x>>>15),x|1);x^=x+Math.imul(x^(x>>>7),x|61);return((x^(x>>>14))>>>0)/4294967296}}
  function receipt(x={}){return{contract:"LAWS_COSMOS_ARCHCOIN_SCENE_FIELD_v5",sourceModel:"ARCHCOIN_FIBONACCI_PHYLLOTAXIS_FIELD_v1",renderingModel:"static-full-viewport-base-burst-only-overlay",geometryModel:"golden-angle-square-root-jitter-elliptical-void-masked",lawsIdentityPreserved:true,fullViewportCoverage:true,archcoinDensityParity:true,strictCentralVoid:true,initialized:S.initialized,destroyed:S.destroyed,failed:S.failed,failureReason:S.reason,reducedMotion:S.reduced,width:S.w,height:S.h,pixelRatio:S.dpr,quality:S.quality,starCount:S.stars.length,dustCount:S.dust.length,rogueCount:S.rogue,phyllotaxisCount:S.phy,safeRegionCount:S.safe,baseDrawCount:S.draws,sparkleFrameCount:S.frames,sparkleFrameIntervalMs:C.frame,continuousCanvasAnimation:false,requestAnimationFrameUsed:false,dualSpacecraftPreserved:false,ownsNavigation:false,ownsWorldGeometry:false,ownsProjection:false,ownsControllerState:false,ownsInteraction:false,ownsPlanet:false,ownsLawContent:false,visualPassClaimed:false,...x}}
  function publish(x={}){const o=Object.freeze(receipt(x));globalThis[R]=o;if(S.root){S.root.dataset.lawsCosmosStatus=S.failed?"held":S.initialized?"available":"pending";S.root.dataset.lawsCosmosRunning=String(canRun());S.root.dataset.lawsCosmosModel=o.renderingModel;S.root.dataset.lawsCosmosContract=o.contract;S.root.dataset.lawsCosmosArchcoinDensityParity="true";S.root.dataset.lawsCosmosStrictCentralVoid="true";S.root.dataset.lawsCosmosReceipt=JSON.stringify(o)}return o}
  function style(){let e=document.getElementById(I.style);if(!e){e=document.createElement("style");e.id=I.style;document.head.append(e)}e.textContent=`body>#${I.layer}{position:fixed;inset:0;z-index:1;overflow:hidden;pointer-events:none;contain:strict;isolation:isolate;background:radial-gradient(ellipse at 50% -10%,rgba(127,147,255,.15),transparent 48%),radial-gradient(ellipse at 108% 42%,rgba(124,220,255,.11),transparent 44%),radial-gradient(ellipse at 52% 112%,rgba(243,217,139,.10),transparent 47%),radial-gradient(ellipse at -10% 55%,rgba(255,157,99,.09),transparent 43%),radial-gradient(ellipse at 50% 50%,transparent 22%,rgba(2,4,10,.24) 100%)}body>#${I.layer} canvas{position:absolute;inset:0;width:100%;height:100%;display:block;mix-blend-mode:screen}#${I.base}{z-index:1;opacity:.93}#${I.spark}{z-index:2}.laws-cosmos-craft{display:none!important}@media(max-width:820px){#${I.base}{opacity:.86}}@media(max-width:560px){#${I.base}{opacity:.78}}@media(prefers-reduced-motion:reduce){#${I.spark}{display:none!important}}`}
  function node(tag,id){const e=document.createElement(tag);e.id=id;e.setAttribute("aria-hidden","true");return e}
  function craft(id,alt){const e=document.createElementNS("http://www.w3.org/2000/svg","svg");e.id=id;e.classList.add("laws-cosmos-craft");e.setAttribute("viewBox","0 0 120 54");e.setAttribute("aria-hidden","true");e.innerHTML=alt?'<path d="M4 29 38 18 72 5 91 21 116 27 91 33 72 49 38 36Z" fill="rgba(127,147,255,.20)" stroke="rgba(190,178,255,.68)" stroke-width="2"/>':'<path d="M3 28 34 17 70 3 94 20 117 27 94 34 70 51 34 37Z" fill="rgba(124,220,255,.17)" stroke="rgba(243,217,139,.72)" stroke-width="2"/>';return e}
  function surfaces(){S.root=document.querySelector("[data-laws-root]");if(!S.root)throw Error("LAWS_COSMOS_ROOT_NOT_FOUND");S.layer=document.getElementById(I.layer)||node("div",I.layer);S.base=document.getElementById(I.base)||node("canvas",I.base);S.spark=document.getElementById(I.spark)||node("canvas",I.spark);const a=document.getElementById(I.a)||craft(I.a,false),b=document.getElementById(I.b)||craft(I.b,true);for(const e of[S.base,S.spark,a,b])if(!e.isConnected)S.layer.append(e);if(!S.layer.isConnected)document.body.prepend(S.layer);S.bc=S.base.getContext("2d",{alpha:true,desynchronized:true});S.sc=S.spark.getContext("2d",{alpha:true,desynchronized:true});if(!S.bc||!S.sc)throw Error("LAWS_COSMOS_CONTEXT_UNAVAILABLE")}
  function regions(){const p=S.w<=C.mobile?14:24,a=[];for(const q of SAFE)for(const e of document.querySelectorAll(q)){const s=getComputedStyle(e),b=e.getBoundingClientRect();if(s.display==="none"||s.visibility==="hidden"||+s.opacity<=.01||b.width<=1||b.height<=1||b.bottom<0||b.top>S.h)continue;a.push({l:Math.max(0,b.left-p),t:Math.max(0,b.top-p),r:Math.min(S.w,b.right+p),b:Math.min(S.h,b.bottom+p)})}S.safe=a.length;return a}
  const inside=(x,y,a)=>a.some(r=>x>=r.l&&x<=r.r&&y>=r.t&&y<=r.b);
  function maskDistance(x,y,m){const c=Math.cos(m.r),s=Math.sin(m.r),dx=x-m.x,dy=y-m.y,rx=dx*c+dy*s,ry=-dx*s+dy*c;return Math.sqrt(rx*rx/(m.rx*m.rx)+ry*ry/(m.ry*m.ry))}
  function masked(x,y,r,rogue){for(const m of MASKS){const d=maskDistance(x,y,m);if(d>=1+m.f)continue;if(d<=1){if(!rogue||r()<.84)return true;continue}if(r()<(1-(d-1)/m.f)*(rogue?.48:.82))return true}return false}
  function central(x,y){const dx=(x-.5)/C.voidX,dy=(y-.5)/C.voidY;return dx*dx+dy*dy<1}
  function color(r,x,y){const w=[Math.max(0,.72-y),Math.max(0,x-.28),Math.max(0,y-.28),Math.max(0,.72-x)];let n=r()*w.reduce((a,b)=>a+b,0);for(let i=0;i<4;i++){n-=w[i];if(n<=0)return COLORS[i]}return COLORS[4]}
  function build(){const area=S.w*S.h,m=S.w<=C.compact?.70:S.w<=C.mobile?.84:1,d=S.quality*m,n=clamp(Math.floor(area/C.area*d),C.min,C.max),dn=0,r=rng(hash(C.seed^Math.round(S.w*7)^(Math.round(S.h*7)<<1)^Math.round(S.quality*1000))),safe=regions(),stars=[];let rogueCount=0,phy=0;for(let i=0;i<n*C.candidates&&stars.length<n;i++){const f=(i+1.5)/(n*C.candidates),rad=Math.sqrt(f)*.70,ang=i*GOLD+between(r,-C.aJitter,C.aJitter),zig=(i%2?1:-1)*C.zig;let x=.5+Math.cos(ang)*(rad+zig)*C.hWarp+between(r,-C.rJitter,C.rJitter),y=.5+Math.sin(ang)*(rad-zig)*C.vWarp+between(r,-C.rJitter,C.rJitter),rogue=r()<C.rogue;if(rogue){x=between(r,.014,.986);y=between(r,.014,.986)}if(x<.014||x>.986||y<.014||y>.986||central(x,y)||masked(x,y,r,rogue))continue;const px=x*S.w,py=y*S.h;if(inside(px,py,safe)&&r()<(rogue?.48:.76))continue;const z=Math.pow(r(),1.55);stars.push({x:px,y:py,z,size:between(r,.50,1.58)*(.62+z*.78),alpha:between(r,.27,.82)*(.68+z*.42),color:color(r,x,y)});rogue?rogueCount++:phy++}S.stars=stars;S.rogue=rogueCount;S.phy=phy;S.dust=Array.from({length:dn},()=>({x:between(r,0,S.w),y:between(r,0,S.h),size:between(r,.28,.92),alpha:between(r,.025,.14),color:r()<.24?"168,140,255":"179,205,224"}));S.live=[]}
  function size(e,c){e.width=Math.max(1,Math.round(S.w*S.dpr));e.height=Math.max(1,Math.round(S.h*S.dpr));e.style.width=`${S.w}px`;e.style.height=`${S.h}px`;c.setTransform(S.dpr,0,0,S.dpr,0,0)}
  function draw(){const c=S.bc;c.clearRect(0,0,S.w,S.h);for(const v of S.dust){c.fillStyle=`rgba(${v.color},${v.alpha})`;c.beginPath();c.arc(v.x,v.y,v.size,0,Math.PI*2);c.fill()}for(const v of S.stars){if(v.z>.74){c.fillStyle=`rgba(${v.color},${v.alpha*.12})`;c.beginPath();c.arc(v.x,v.y,v.size*2.7,0,Math.PI*2);c.fill()}c.fillStyle=`rgba(${v.color},${clamp(v.alpha,.08,.94)})`;c.beginPath();c.arc(v.x,v.y,v.size,0,Math.PI*2);c.fill()}S.draws++}
  const clear=()=>S.sc?.clearRect(0,0,S.w,S.h),canRun=()=>S.initialized&&!S.destroyed&&!S.failed&&S.visible&&S.active&&!S.reduced;
  function stop(){clearTimeout(S.burst);clearTimeout(S.tick);S.burst=S.tick=0;S.live=[];clear()}
  function schedule(first=false){if(!canRun()||S.burst||S.tick||S.live.length||!S.stars.length)return;const r=rng(hash(C.seed^Date.now()));S.burst=setTimeout(()=>{S.burst=0;burst()},first?between(r,2800,4600):between(r,1500,3200))}
  function burst(){if(!canRun())return;const r=rng(hash(C.seed^Math.round(performance.now()))),pool=S.stars.filter(v=>v.z>.42&&v.alpha>.36),count=r()<.24?2:1;S.live=[];for(let i=0;i<count;i++){const star=pool[Math.floor(r()*pool.length)];if(star)S.live.push({star,start:performance.now(),duration:between(r,620,980),reach:clamp(star.size*between(r,4.8,8.4),5,16),alpha:between(r,.58,.94)})}paint(performance.now());next()}
  function next(){if(canRun()&&!S.tick&&S.live.length)S.tick=setTimeout(()=>{S.tick=0;frame()},C.frame)}
  function frame(){if(!canRun()){stop();return}const now=performance.now();S.live=S.live.filter(v=>now-v.start<v.duration);paint(now);if(S.live.length)next();else{clear();schedule()}}
  function paint(now){const c=S.sc;c.clearRect(0,0,S.w,S.h);c.lineCap="round";for(const v of S.live){const p=clamp((now-v.start)/v.duration,0,1),pulse=Math.sin(p*Math.PI),a=v.alpha*Math.pow(pulse,2.15),reach=v.reach*(.64+pulse*.82),s=v.star;c.strokeStyle=`rgba(${s.color},${a})`;c.lineWidth=.74;c.beginPath();c.moveTo(s.x-reach,s.y);c.lineTo(s.x+reach,s.y);c.moveTo(s.x,s.y-reach);c.lineTo(s.x,s.y+reach);c.stroke()}S.frames++}
  function resize(reason="resize"){if(!S.layer)return false;const w=Math.max(1,innerWidth||document.documentElement.clientWidth||1),h=Math.max(1,innerHeight||document.documentElement.clientHeight||1),d=clamp(devicePixelRatio||1,1,w<=C.mobile?1:1.25);if(w===S.w&&h===S.h&&d===S.dpr&&reason!=="scroll")return false;S.w=w;S.h=h;S.dpr=d;size(S.base,S.bc);size(S.spark,S.sc);build();draw();clear();publish({lastAction:`field-${reason}`});return true}
  function evaluate(reason){S.reduced=Boolean(S.media?.matches||S.root?.dataset?.reducedMotion==="true");if(canRun())schedule(true);else stop();publish({lastAction:reason});return canRun()}
  function bind(){S.media=globalThis.matchMedia?.("(prefers-reduced-motion: reduce)")||null;S.hnd.visibility=()=>{S.visible=!document.hidden;evaluate("visibility-change")};S.hnd.hide=()=>{S.active=false;stop()};S.hnd.show=()=>{S.active=true;evaluate("pageshow")};S.hnd.resize=()=>{clearTimeout(S.resize);S.resize=setTimeout(()=>resize("resize"),120)};S.hnd.motion=()=>evaluate("motion-change");document.addEventListener("visibilitychange",S.hnd.visibility,{passive:true});globalThis.addEventListener("pagehide",S.hnd.hide,{passive:true});globalThis.addEventListener("pageshow",S.hnd.show,{passive:true});globalThis.addEventListener("resize",S.hnd.resize,{passive:true});S.media?.addEventListener?.("change",S.hnd.motion);if("MutationObserver"in globalThis){S.observer=new MutationObserver(()=>evaluate("root-motion-change"));S.observer.observe(S.root,{attributes:true,attributeFilter:["data-reduced-motion"]})}}
  function unbind(){document.removeEventListener("visibilitychange",S.hnd.visibility);globalThis.removeEventListener("pagehide",S.hnd.hide);globalThis.removeEventListener("pageshow",S.hnd.show);globalThis.removeEventListener("resize",S.hnd.resize);S.media?.removeEventListener?.("change",S.hnd.motion);S.observer?.disconnect?.()}
  function setQuality(v){const n=clamp(Number(v),.62,1);if(!Number.isFinite(n)||Math.abs(n-S.quality)<.02)return false;S.quality=n;build();draw();clear();publish({lastAction:"quality-updated"});return true}
  function destroy(){if(S.destroyed)return true;stop();clearTimeout(S.resize);unbind();S.layer?.remove();document.getElementById(I.style)?.remove();S.destroyed=true;S.initialized=false;api.initialized=false;publish({lastAction:"destroyed"});globalThis.dispatchEvent(new CustomEvent(DEAD,{detail:Object.freeze(receipt())}));return true}
  function fail(e){if(S.failed)return;S.failed=true;S.reason=e instanceof Error?e.message:String(e);stop();publish({lastAction:"failure"});globalThis.dispatchEvent(new CustomEvent(FAIL,{detail:Object.freeze({reason:S.reason})}))}
  function init(){try{style();surfaces();bind();S.initialized=true;api.initialized=true;resize("initialization");evaluate("initialized");const o=publish({lastAction:"ready"});globalThis.dispatchEvent(new CustomEvent(READY,{detail:o}))}catch(e){fail(e)}}
  document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init,{once:true}):init();
})();
