/* TARGET FILE: /laws/index.cosmos.js */
/* LAWS_COSMOS_FOUR_CHAMBER_INTEGRATIVE_SKY_v3 */
(() => {
"use strict";
const G="DGB_LAWS_COSMOS",R="DGB_LAWS_COSMOS_RECEIPT",EV={ready:"DGB_LAWS_COSMOS_READY",fail:"DGB_LAWS_COSMOS_FAILURE",dead:"DGB_LAWS_COSMOS_DESTROYED"},I={style:"laws-cosmos-runtime-style",layer:"laws-cosmos-layer",base:"laws-cosmos-canvas",spark:"laws-cosmos-sparkle-canvas",a:"laws-cosmos-spacecraft",b:"laws-cosmos-spacecraft-secondary"},SAFE=["[data-laws-threshold-introduction]","[data-laws-orbit-scene]","[data-laws-panel]","[data-laws-scene-field]",".laws-value-deck",".laws-controller-panel",".laws-discovery__item",".laws-footer"],COL=["127,147,255","124,220,255","243,217,139","255,157,99"],C={mobile:820,compact:560,min:116,max:248,area:7600,dustMin:34,dustMax:94,dustArea:19500,frame:125,seed:0x4c415753};
if(globalThis[G]?.initialized)return;
const S={initialized:false,destroyed:false,failed:false,reason:"",visible:!document.hidden,active:true,reduced:false,quality:1,w:0,h:0,dpr:1,root:null,layer:null,base:null,spark:null,bc:null,sc:null,stars:[],dust:[],live:[],safe:0,draws:0,frames:0,burst:0,tick:0,resize:0,scroll:0,media:null,observer:null,h:{}};
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v)),hash=v=>{let x=v>>>0;x^=x>>>16;x=Math.imul(x,0x7feb352d);x^=x>>>15;x=Math.imul(x,0x846ca68b);return(x^(x>>>16))>>>0},rng=seed=>{let v=seed>>>0;return()=>{v+=0x6d2b79f5;let x=v;x=Math.imul(x^(x>>>15),x|1);x^=x+Math.imul(x^(x>>>7),x|61);return((x^(x>>>14))>>>0)/4294967296}},between=(r,a,b)=>a+r()*(b-a),gold=Math.PI*(3-Math.sqrt(5));
function receipt(x={}){return{contract:"LAWS_COSMOS_FOUR_CHAMBER_INTEGRATIVE_SKY_v3",sourceModels:["ARCHCOIN_FIBONACCI_PHYLLOTAXIS_FIELD_v1","SHOWROOM_COSMOS_HARDENED_v2_IRREGULAR_STARFIELD_DUAL_SPACECRAFT","MAIN_COMPASS_FIXED_CENTER_HIERARCHY","LAWS_SEMANTIC_CONTENT_SAFE_SKY"],renderingModel:"static-full-sky-base-burst-only-overlay",initialized:S.initialized,destroyed:S.destroyed,failed:S.failed,failureReason:S.reason,reducedMotion:S.reduced,width:S.w,height:S.h,pixelRatio:S.dpr,quality:S.quality,starCount:S.stars.length,dustCount:S.dust.length,protectedRegionCount:S.safe,baseDrawCount:S.draws,sparkleFrameCount:S.frames,fullViewportCoverage:true,contentSafeRegions:true,fourDirectionalLawAtmospheres:true,dualSpacecraft:true,continuousCanvasAnimation:false,requestAnimationFrameUsed:false,sparkleFrameIntervalMs:C.frame,ownsNavigation:false,ownsWorldGeometry:false,ownsProjection:false,ownsControllerState:false,ownsInteraction:false,ownsLawContent:false,visualPassClaimed:false,...x}}
function pub(x={}){const o=Object.freeze(receipt(x));globalThis[R]=o;if(S.root){S.root.dataset.lawsCosmosStatus=S.failed?"held":S.initialized?"available":"pending";S.root.dataset.lawsCosmosRunning=String(canRun());S.root.dataset.lawsCosmosModel=o.renderingModel;S.root.dataset.lawsCosmosReceipt=JSON.stringify(o)}return o}
function css(){let e=document.getElementById(I.style);if(!e){e=document.createElement("style");e.id=I.style;document.head.append(e)}e.textContent=`body>#${I.layer}{position:fixed;inset:0;z-index:1;overflow:hidden;pointer-events:none;contain:strict;isolation:isolate;background:radial-gradient(ellipse at 50% -8%,rgba(127,147,255,.11),transparent 47%),radial-gradient(ellipse at 108% 44%,rgba(124,220,255,.09),transparent 43%),radial-gradient(ellipse at 52% 112%,rgba(243,217,139,.09),transparent 46%),radial-gradient(ellipse at -10% 54%,rgba(255,157,99,.075),transparent 42%),radial-gradient(ellipse at 50% 50%,transparent 28%,rgba(2,4,10,.2) 100%)}body>#${I.layer} canvas{position:absolute;inset:0;width:100%;height:100%;display:block;mix-blend-mode:screen}body>#${I.layer}>#${I.base}{z-index:1;opacity:.78}body>#${I.layer}>#${I.spark}{z-index:2}.laws-cosmos-craft{position:absolute;z-index:3;width:clamp(24px,3.5vw,52px);opacity:.3;filter:drop-shadow(0 0 8px rgba(124,220,255,.2))}#${I.a}{right:7vw;top:18vh;transform:rotate(-8deg)}#${I.b}{left:6vw;bottom:16vh;transform:scale(.75) rotate(12deg)}@media(max-width:820px){body>#${I.layer}>#${I.base}{opacity:.66}}@media(max-width:560px){body>#${I.layer}>#${I.base}{opacity:.54}}@media(prefers-reduced-motion:reduce){body>#${I.layer}>#${I.spark}{display:none!important}.laws-cosmos-craft{opacity:.18}}`}
function node(tag,id){const e=document.createElement(tag);e.id=id;e.setAttribute("aria-hidden","true");return e}
function craft(id,alt){const e=document.createElementNS("http://www.w3.org/2000/svg","svg");e.id=id;e.classList.add("laws-cosmos-craft");e.setAttribute("viewBox","0 0 120 54");e.setAttribute("aria-hidden","true");e.innerHTML=alt?'<path d="M4 29 38 18 72 5 91 21 116 27 91 33 72 49 38 36Z" fill="rgba(127,147,255,.22)" stroke="rgba(190,178,255,.68)" stroke-width="2"/>':'<path d="M3 28 34 17 70 3 94 20 117 27 94 34 70 51 34 37Z" fill="rgba(124,220,255,.18)" stroke="rgba(243,217,139,.72)" stroke-width="2"/>';return e}
function surfaces(){S.root=document.querySelector("[data-laws-root]");if(!S.root)throw Error("LAWS_COSMOS_ROOT_NOT_FOUND");S.layer=document.getElementById(I.layer)||node("div",I.layer);S.base=document.getElementById(I.base)||node("canvas",I.base);S.spark=document.getElementById(I.spark)||node("canvas",I.spark);const a=document.getElementById(I.a)||craft(I.a,false),b=document.getElementById(I.b)||craft(I.b,true);for(const e of[S.base,S.spark,a,b])if(!e.isConnected)S.layer.append(e);if(!S.layer.isConnected)document.body.prepend(S.layer);S.bc=S.base.getContext("2d",{alpha:true,desynchronized:true});S.sc=S.spark.getContext("2d",{alpha:true,desynchronized:true});if(!S.bc||!S.sc)throw Error("LAWS_COSMOS_CONTEXT_UNAVAILABLE")}
function regions(){const p=S.w<=C.mobile?18:30,a=[];for(const q of SAFE)for(const e of document.querySelectorAll(q)){const s=getComputedStyle(e),b=e.getBoundingClientRect();if(s.display==="none"||s.visibility==="hidden"||+s.opacity<=.01||b.width<=1||b.height<=1||b.bottom<0||b.top>S.h)continue;a.push({l:Math.max(0,b.left-p),t:Math.max(0,b.top-p),r:Math.min(S.w,b.right+p),b:Math.min(S.h,b.bottom+p)})}S.safe=a.length;return a}
const inside=(x,y,a)=>a.some(r=>x>=r.l&&x<=r.r&&y>=r.t&&y<=r.b);
function build(){const area=S.w*S.h,m=S.w<=C.compact?.72:S.w<=C.mobile?.86:1,d=S.quality*m,n=clamp(Math.floor(area/C.area*d),C.min,C.max),dn=clamp(Math.floor(area/C.dustArea*d),C.dustMin,C.dustMax),r=rng(hash(C.seed^Math.round(S.w*7)^(Math.round(S.h*7)<<1)^Math.round(S.quality*1000))),safe=regions(),stars=[];for(let i=0;i<n*14&&stars.length<n;i++){const f=(i+1.4)/(n*14),rad=Math.sqrt(f)*.72,ang=i*gold+between(r,-.09,.09);let x=S.w*(.5+Math.cos(ang)*rad*.78)+between(r,-12,12),y=S.h*(.5+Math.sin(ang)*rad*.66)+between(r,-10,10),rogue=r()<.14;if(rogue){x=between(r,4,S.w-4);y=between(r,4,S.h-4)}if(x<4||x>S.w-4||y<4||y>S.h-4||(inside(x,y,safe)&&r()<(rogue?.72:.88)))continue;const z=Math.pow(r(),1.45),nx=x/Math.max(1,S.w),ny=y/Math.max(1,S.h),weights=[Math.max(0,.72-ny),Math.max(0,nx-.28),Math.max(0,ny-.28),Math.max(0,.72-nx)];let q=r()*weights.reduce((a,b)=>a+b,0),color=COL[0];for(let j=0;j<4;j++){q-=weights[j];if(q<=0){color=COL[j];break}}stars.push({x,y,z,size:between(r,.42,1.52)*(.58+z*.84),alpha:between(r,.22,.78)*(.66+z*.44),color})}S.stars=stars;S.dust=Array.from({length:dn},()=>({x:between(r,0,S.w),y:between(r,0,S.h),size:between(r,.3,.86),alpha:between(r,.035,.15),color:r()<.22?"168,140,255":"179,205,224"}));S.live=[]}
function size(e,c){e.width=Math.max(1,Math.round(S.w*S.dpr));e.height=Math.max(1,Math.round(S.h*S.dpr));e.style.width=`${S.w}px`;e.style.height=`${S.h}px`;c.setTransform(S.dpr,0,0,S.dpr,0,0)}
function draw(){const c=S.bc;c.clearRect(0,0,S.w,S.h);for(const v of S.dust){c.fillStyle=`rgba(${v.color},${v.alpha})`;c.beginPath();c.arc(v.x,v.y,v.size,0,Math.PI*2);c.fill()}for(const v of S.stars){if(v.z>.72){c.fillStyle=`rgba(${v.color},${v.alpha*.11})`;c.beginPath();c.arc(v.x,v.y,v.size*3.1,0,Math.PI*2);c.fill()}c.fillStyle=`rgba(${v.color},${clamp(v.alpha,.06,.92)})`;c.beginPath();c.arc(v.x,v.y,v.size,0,Math.PI*2);c.fill()}S.draws++}
const clear=()=>S.sc?.clearRect(0,0,S.w,S.h);
function resize(reason="resize"){if(!S.layer)return false;const w=Math.max(1,innerWidth||document.documentElement.clientWidth||1),h=Math.max(1,innerHeight||document.documentElement.clientHeight||1),d=clamp(devicePixelRatio||1,1,w<=C.mobile?1:1.25);if(w===S.w&&h===S.h&&d===S.dpr&&reason!=="scroll")return false;S.w=w;S.h=h;S.dpr=d;size(S.base,S.bc);size(S.spark,S.sc);build();draw();clear();pub({lastAction:`field-${reason}`});return true}
const canRun=()=>S.initialized&&!S.destroyed&&!S.failed&&S.visible&&S.active&&!S.reduced;
function stop(){clearTimeout(S.burst);clearTimeout(S.tick);S.burst=S.tick=0;S.live=[];clear()}
function schedule(first=false){if(!canRun()||S.burst||S.tick||S.live.length||!S.stars.length)return;const r=rng(hash(C.seed^Date.now()));S.burst=setTimeout(()=>{S.burst=0;burst()},first?between(r,1800,3600):between(r,1700,4200))}
function burst(){if(!canRun())return;const r=rng(hash(C.seed^Math.round(performance.now()))),pool=S.stars.filter(v=>v.z>.44&&v.alpha>.35),count=r()<.23?2:1;S.live=[];for(let i=0;i<count;i++){const star=pool[Math.floor(r()*pool.length)];if(star)S.live.push({star,start:performance.now(),duration:between(r,680,1080),reach:clamp(star.size*between(r,4.2,7.4),4.5,13),alpha:between(r,.58,.96)})}paint(performance.now());next()}
function next(){if(canRun()&&!S.tick&&S.live.length)S.tick=setTimeout(()=>{S.tick=0;frame()},C.frame)}
function frame(){if(!canRun()){stop();return}const now=performance.now();S.live=S.live.filter(v=>now-v.start<v.duration);paint(now);if(S.live.length)next();else{clear();schedule()}}
function paint(now){const c=S.sc;c.clearRect(0,0,S.w,S.h);c.lineCap="round";for(const v of S.live){const p=clamp((now-v.start)/v.duration,0,1),pulse=Math.sin(p*Math.PI),alpha=v.alpha*Math.pow(pulse,2.1),reach=v.reach*(.68+pulse*.72),s=v.star;c.strokeStyle=`rgba(${s.color},${alpha})`;c.lineWidth=.72;c.beginPath();c.moveTo(s.x-reach,s.y);c.lineTo(s.x+reach,s.y);c.moveTo(s.x,s.y-reach);c.lineTo(s.x,s.y+reach);c.stroke()}S.frames++}
function evaluate(reason){S.reduced=Boolean(S.media?.matches||S.root?.dataset?.reducedMotion==="true");if(canRun())schedule(true);else stop();pub({lastAction:reason});return canRun()}
function bind(){S.media=globalThis.matchMedia?.("(prefers-reduced-motion: reduce)")||null;S.h.visibility=()=>{S.visible=!document.hidden;evaluate("visibility-change")};S.h.hide=()=>{S.active=false;stop()};S.h.show=()=>{S.active=true;evaluate("pageshow")};S.h.resize=()=>{clearTimeout(S.resize);S.resize=setTimeout(()=>resize("resize"),120)};S.h.scroll=()=>{clearTimeout(S.scroll);S.scroll=setTimeout(()=>resize("scroll"),140)};S.h.motion=()=>evaluate("motion-change");document.addEventListener("visibilitychange",S.h.visibility,{passive:true});globalThis.addEventListener("pagehide",S.h.hide,{passive:true});globalThis.addEventListener("pageshow",S.h.show,{passive:true});globalThis.addEventListener("resize",S.h.resize,{passive:true});globalThis.addEventListener("scroll",S.h.scroll,{passive:true});S.media?.addEventListener?.("change",S.h.motion);if("MutationObserver"in globalThis){S.observer=new MutationObserver(()=>evaluate("root-motion-change"));S.observer.observe(S.root,{attributes:true,attributeFilter:["data-reduced-motion"]})}}
function unbind(){document.removeEventListener("visibilitychange",S.h.visibility);globalThis.removeEventListener("pagehide",S.h.hide);globalThis.removeEventListener("pageshow",S.h.show);globalThis.removeEventListener("resize",S.h.resize);globalThis.removeEventListener("scroll",S.h.scroll);S.media?.removeEventListener?.("change",S.h.motion);S.observer?.disconnect?.()}
function setQuality(v){const n=clamp(Number(v),.62,1);if(!Number.isFinite(n)||Math.abs(n-S.quality)<.02)return false;S.quality=n;build();draw();clear();pub({lastAction:"quality-updated"});return true}
function destroy(){if(S.destroyed)return true;stop();clearTimeout(S.resize);clearTimeout(S.scroll);unbind();S.layer?.remove();document.getElementById(I.style)?.remove();S.destroyed=true;S.initialized=false;api.initialized=false;pub({lastAction:"destroyed"});globalThis.dispatchEvent(new CustomEvent(EV.dead,{detail:Object.freeze(receipt())}));return true}
function fail(e){S.failed=true;S.reason=e instanceof Error?e.message:String(e);stop();pub({lastAction:"failure"});globalThis.dispatchEvent(new CustomEvent(EV.fail,{detail:Object.freeze({message:S.reason})}))}
const api={initialized:false,start:()=>evaluate("manual-start"),stop:()=>{stop();pub({lastAction:"manual-stop"});return true},resize:()=>resize("manual"),setQuality,destroy,receipt:()=>Object.freeze(receipt())};globalThis[G]=api;
function init(){try{css();surfaces();bind();resize("initialize");S.initialized=true;api.initialized=true;pub({lastAction:"initialized"});evaluate("initialized");globalThis.dispatchEvent(new CustomEvent(EV.ready,{detail:Object.freeze(receipt())}))}catch(e){fail(e)}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();
