/**
 * H-Earth terrain-supported navigation successor.
 * Ordinary ground traversal derives camera Y from the exact presented terrain.
 */
import { H_EARTH_3D_CAMERA_CAPACITY } from '../capacity.js';
import { sampleHEarthTerrainField } from '../../../../h-earth-3d/terrain/h-earth.terrain-field.js';
import { H_EARTH_FUNCTIONAL_LANDSCAPE_REALIZATION_PLAN } from '../../../../h-earth-3d/integration/h-earth.landscape-realization-planner.js';
import {
  H_EARTH_VISIBLE_TERRAIN_CLEARANCE_CONTRACT_ID,
  H_EARTH_VISIBLE_TERRAIN_CLEARANCE_PROTECTED_FLOOR,
  sampleHEarthVisibleTerrainClearanceSurface,
  sampleHEarthVisibleTerrainClearanceEnvelope
} from './visible-terrain-clearance.js';

const freeze=(v,s=new WeakSet())=>{if(v===null||typeof v!=='object'||Object.isFrozen(v)||s.has(v))return v;s.add(v);Object.values(v).forEach(x=>freeze(x,s));return Object.freeze(v)};
const finite=v=>typeof v==='number'&&Number.isFinite(v);
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const norm=d=>{let x=d%360;if(x>180)x-=360;if(x<-180)x+=360;return x};

export const H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_CONTRACT_ID='H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_PROPOSAL_RUN_6F_v1';
export const H_EARTH_TERRAIN_RELATIVE_CAMERA_CLEARANCE_SUCCESSOR_CONTRACT_ID='H_EARTH_TERRAIN_SUPPORTED_LOCOMOTION_GEN324_v1';
export const H_EARTH_TERRAIN_SUPPORTED_LOCOMOTION_CONTRACT_ID='H_EARTH_TERRAIN_SUPPORTED_LOCOMOTION_GEN324_v1';
export const H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_PROFILE=freeze({
  contractId:H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_CONTRACT_ID,
  cameraClearanceSuccessorContractId:H_EARTH_TERRAIN_RELATIVE_CAMERA_CLEARANCE_SUCCESSOR_CONTRACT_ID,
  terrainSupportedLocomotionContractId:H_EARTH_TERRAIN_SUPPORTED_LOCOMOTION_CONTRACT_ID,
  visibleTerrainClearanceContractId:H_EARTH_VISIBLE_TERRAIN_CLEARANCE_CONTRACT_ID,
  protectedGeographicFloor:H_EARTH_VISIBLE_TERRAIN_CLEARANCE_PROTECTED_FLOOR,
  eyeHeight:2.25,minimumTerrainClearance:1.6,hardTerrainSupportOffset:2.25,
  sweptTerrainSampleSpacing:0.35,movementStepWorldUnits:5,maximumMovementIntentWorldUnits:12,
  lookAheadClearanceDistance:6,clearanceFootprintRadius:1.25,lookDistanceWorldUnits:18,
  turnStepDegrees:6,pitchStepDegrees:4,pitchMinimumDegrees:-42,pitchMaximumDegrees:32,
  verticalFovMinimumDegrees:H_EARTH_3D_CAMERA_CAPACITY.futureControllerCapacity.verticalFovDegrees.minimum,
  verticalFovMaximumDegrees:H_EARTH_3D_CAMERA_CAPACITY.futureControllerCapacity.verticalFovDegrees.maximum,
  nearPlane:H_EARTH_3D_CAMERA_CAPACITY.initialProjectionCandidate.nearPlane,
  farPlane:H_EARTH_3D_CAMERA_CAPACITY.initialProjectionCandidate.farPlane,
  selectionProjectionModel:'CHUNK_LOCAL_NEAREST_AVAILABLE_TERRAIN_MEMBER',
  authority:freeze({emitsCameraProposal:true,validatesTerrainClearance:true,retainsLastLawfulStateForRecovery:true,samplesPresentedTerrainRepresentation:true,terrainSupportedLocomotion:true,ownsCanonicalCameraState:false,ownsTerrainField:false,ownsVisibleRelief:false,ownsGeography:false,ownsTopology:false,ownsNavigationScale:false,ownsSemanticAddressIdentity:false,ownsCollisionOrPhysics:false,ownsRenderer:false})
});

export const H_EARTH_FUNCTIONAL_LANDSCAPE_WAYPOINTS=freeze({
  COAST:{waypointId:'COAST',label:'Coastal entry',position:{x:0,z:-96},yawDegrees:0,pitchDegrees:-8},
  BERM:{waypointId:'BERM',label:'Coastal berm',position:{x:0,z:-132},yawDegrees:0,pitchDegrees:-7},
  LOWLAND:{waypointId:'LOWLAND',label:'Lowland',position:{x:-42,z:-158},yawDegrees:-18,pitchDegrees:-6},
  HILL:{waypointId:'HILL',label:'Navigable hill',position:{x:72,z:-172},yawDegrees:18,pitchDegrees:-8},
  RIDGE:{waypointId:'RIDGE',label:'Ridge or bluff',position:{x:145,z:-225},yawDegrees:12,pitchDegrees:-10}
});

const terrainChunks=()=>H_EARTH_FUNCTIONAL_LANDSCAPE_REALIZATION_PLAN.chunks.filter(c=>c.terrainMemberAddressIds.length>0&&c.physicalRole.includes('TERRAIN'));
export function resolveHEarthNavigableTerrainChunk(x,z){if(!finite(x)||!finite(z))return null;const e=1e-8;return terrainChunks().filter(c=>x>=c.worldBounds.xMin-e&&x<=c.worldBounds.xMax+e&&z>=c.worldBounds.zMin-e&&z<=c.worldBounds.zMax+e).sort((a,b)=>a.chunkId.localeCompare(b.chunkId))[0]??null;}
function parseAddress(a){const m=/:R(\d+):C(\d+)$/.exec(a);return m?{address:a,row:Number(m[1]),column:Number(m[2])}:null;}
function semantic(chunk,x,z){const c=chunk.terrainMemberAddressIds.map(parseAddress).filter(Boolean);if(!c.length)return{selectedSemanticAddressId:null};const xp=clamp((x-chunk.worldBounds.xMin)/Math.max(1e-8,chunk.worldBounds.xMax-chunk.worldBounds.xMin),0,.999999),zp=clamp((z-chunk.worldBounds.zMin)/Math.max(1e-8,chunk.worldBounds.zMax-chunk.worldBounds.zMin),0,.999999),tc=chunk.addressRange.columnMin+Math.floor(xp*4),tr=chunk.addressRange.rowMin+Math.floor(zp*4);return{selectedSemanticAddressId:[...c].sort((a,b)=>(Math.abs(a.row-tr)+Math.abs(a.column-tc))-(Math.abs(b.row-tr)+Math.abs(b.column-tc))||a.address.localeCompare(b.address))[0].address};}
function resolvePosition(x,z,yaw=0){const chunk=resolveHEarthNavigableTerrainChunk(x,z);if(!chunk)return{eligible:false,issues:['NO_NAVIGABLE_TERRAIN_CHUNK']};const canonical=sampleHEarthTerrainField(x,z),surface=sampleHEarthVisibleTerrainClearanceSurface(x,z);if(canonical?.valid!==true||surface?.valid!==true)return{eligible:false,issues:['PRESENTED_TERRAIN_SAMPLE_INVALID']};const p=H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_PROFILE,envelope=sampleHEarthVisibleTerrainClearanceEnvelope(x,z,{yawDegrees:yaw,lookAheadDistance:p.lookAheadClearanceDistance,lateralRadius:p.clearanceFootprintRadius});if(envelope?.valid!==true)return{eligible:false,issues:['VISIBLE_TERRAIN_CLEARANCE_SAMPLE_INVALID']};const support=surface.visibleElevation+p.hardTerrainSupportOffset,clearance=envelope.visibleElevation+p.minimumTerrainClearance,eye=envelope.visibleElevation+p.eyeHeight,y=Math.max(support,clearance,eye),sel=semantic(chunk,x,z);return{eligible:true,position:{x,y,z},terrainElevation:surface.visibleElevation,visibleTerrainElevation:surface.visibleElevation,clearanceReferenceElevation:envelope.visibleElevation,canonicalTerrainElevation:canonical.elevation,minimumCameraY:Math.max(support,clearance),targetCameraY:y,clearance:y-surface.visibleElevation,chunkId:chunk.chunkId,physicalRole:chunk.physicalRole,formationIds:chunk.formationIds,selectedSemanticAddressId:sel.selectedSemanticAddressId,selectionProjectionModel:p.selectionProjectionModel,terrainSupported:true,issues:[]};}
function sweep(state,x,z,yaw){const p=H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_PROFILE,dx=x-state.position.x,dz=z-state.position.z,d=Math.hypot(dx,dz),n=Math.max(1,Math.ceil(d/p.sweptTerrainSampleSpacing));let last=null;for(let i=1;i<=n;i++){const t=i/n,r=resolvePosition(state.position.x+dx*t,state.position.z+dz*t,yaw);if(!r.eligible)return{eligible:false,issues:r.issues,sampleCount:i-1};last=r;}return{eligible:true,result:last??resolvePosition(x,z,yaw),sampleCount:n};}
function stateFrom(r,{yaw,pitch,fov,sequence,action,accepted=true,rejectionReason=null,previousY=null,swept=0}){return freeze({contractId:H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_CONTRACT_ID,cameraClearanceSuccessorContractId:H_EARTH_TERRAIN_RELATIVE_CAMERA_CLEARANCE_SUCCESSOR_CONTRACT_ID,terrainSupportedLocomotionContractId:H_EARTH_TERRAIN_SUPPORTED_LOCOMOTION_CONTRACT_ID,stateId:`H_EARTH_NAVIGATION_STATE_${String(sequence).padStart(4,'0')}`,sequence,action,accepted,recovered:false,rejectionReason,position:r.position,yawDegrees:norm(yaw),pitchDegrees:clamp(pitch,H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_PROFILE.pitchMinimumDegrees,H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_PROFILE.pitchMaximumDegrees),verticalFovDegrees:clamp(fov,H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_PROFILE.verticalFovMinimumDegrees,H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_PROFILE.verticalFovMaximumDegrees),terrainElevation:r.terrainElevation,visibleTerrainElevation:r.visibleTerrainElevation,clearanceReferenceElevation:r.clearanceReferenceElevation,canonicalTerrainElevation:r.canonicalTerrainElevation,minimumCameraY:r.minimumCameraY,targetCameraY:r.targetCameraY,clearance:r.clearance,verticalResponseMode:'HARD_TERRAIN_SUPPORT',verticalDelta:finite(previousY)?r.position.y-previousY:0,verticalAcceleration:0,clearanceSurfaceContractId:H_EARTH_VISIBLE_TERRAIN_CLEARANCE_CONTRACT_ID,protectedGeographicFloor:H_EARTH_VISIBLE_TERRAIN_CLEARANCE_PROTECTED_FLOOR,chunkId:r.chunkId,physicalRole:r.physicalRole,formationIds:r.formationIds,selectedSemanticAddressId:r.selectedSemanticAddressId,selectionProjectionModel:r.selectionProjectionModel,terrainClearanceReceiptId:`H_EARTH_VISIBLE_TERRAIN_CLEARANCE_RECEIPT_${String(sequence).padStart(4,'0')}`,terrainSupported:true,sweptTerrainSupportSampleCount:swept,canonicalCameraStateAuthority:false,collisionOrPhysicsClaim:false,geographyAuthorityCreated:false,topologyAuthorityCreated:false,navigationScaleAuthorityCreated:false});}
export function createHEarthFunctionalLandscapeNavigationState({waypointId='COAST'}={}){const w=H_EARTH_FUNCTIONAL_LANDSCAPE_WAYPOINTS[waypointId]??H_EARTH_FUNCTIONAL_LANDSCAPE_WAYPOINTS.COAST,r=resolvePosition(w.position.x,w.position.z,w.yawDegrees);if(!r.eligible)return freeze({ok:false,status:'INITIAL_NAVIGATION_STATE_REJECTED',issues:r.issues});return freeze({ok:true,status:'INITIAL_NAVIGATION_STATE_COMPLETE',state:stateFrom(r,{yaw:w.yawDegrees,pitch:w.pitchDegrees,fov:56,sequence:1,action:`GOTO_WAYPOINT:${w.waypointId}`}),issues:[]});}
function delta(state,action,m){const y=state.yawDegrees*Math.PI/180,f={x:Math.sin(y),z:-Math.cos(y)},r={x:Math.cos(y),z:Math.sin(y)};if(action==='MOVE_FORWARD')return{x:f.x*m,z:f.z*m};if(action==='MOVE_BACKWARD')return{x:-f.x*m,z:-f.z*m};if(action==='STRAFE_LEFT')return{x:-r.x*m,z:-r.z*m};if(action==='STRAFE_RIGHT')return{x:r.x*m,z:r.z*m};return{x:0,z:0};}
export function proposeHEarthFunctionalLandscapeNavigation(current,intent={}){if(!current||current.contractId!==H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_CONTRACT_ID)return freeze({ok:false,status:'NAVIGATION_PROPOSAL_REJECTED',state:current??null,issues:['CURRENT_NAVIGATION_STATE_INVALID']});const p=H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_PROFILE,action=typeof intent.action==='string'?intent.action:'NO_OP',sequence=current.sequence+1;if(action==='RESET'){const r=createHEarthFunctionalLandscapeNavigationState();return freeze({ok:r.ok,status:r.ok?'NAVIGATION_RESET_COMPLETE':'NAVIGATION_RESET_FAILED',state:r.ok?stateFrom(resolvePosition(r.state.position.x,r.state.position.z,r.state.yawDegrees),{yaw:r.state.yawDegrees,pitch:r.state.pitchDegrees,fov:r.state.verticalFovDegrees,sequence,action,previousY:current.position.y}):current,issues:r.issues});}let x=current.position.x,z=current.position.z,yaw=current.yawDegrees,pitch=current.pitchDegrees,fov=current.verticalFovDegrees;if(action==='GOTO_WAYPOINT'){const w=H_EARTH_FUNCTIONAL_LANDSCAPE_WAYPOINTS[intent.waypointId];if(!w)return freeze({ok:false,status:'NAVIGATION_WAYPOINT_REJECTED',state:current,issues:['UNKNOWN_WAYPOINT']});x=w.position.x;z=w.position.z;yaw=w.yawDegrees;pitch=w.pitchDegrees;}else if(['MOVE_FORWARD','MOVE_BACKWARD','STRAFE_LEFT','STRAFE_RIGHT'].includes(action)){const m=clamp(finite(intent.magnitude)?Math.abs(intent.magnitude):p.movementStepWorldUnits,0,p.maximumMovementIntentWorldUnits),d=delta(current,action,m);x+=d.x;z+=d.z;}else if(action==='TURN_LEFT')yaw-=clamp(finite(intent.degrees)?Math.abs(intent.degrees):p.turnStepDegrees,0,8);else if(action==='TURN_RIGHT')yaw+=clamp(finite(intent.degrees)?Math.abs(intent.degrees):p.turnStepDegrees,0,8);else if(action==='PITCH_UP')pitch+=clamp(finite(intent.degrees)?Math.abs(intent.degrees):p.pitchStepDegrees,0,8);else if(action==='PITCH_DOWN')pitch-=clamp(finite(intent.degrees)?Math.abs(intent.degrees):p.pitchStepDegrees,0,8);else if(action==='ZOOM_IN')fov-=clamp(finite(intent.degrees)?Math.abs(intent.degrees):3,0,6);else if(action==='ZOOM_OUT')fov+=clamp(finite(intent.degrees)?Math.abs(intent.degrees):3,0,6);else if(action==='SET_CAMERA_POSITION'){x=intent.position?.x;z=intent.position?.z;}const moved=Math.hypot(x-current.position.x,z-current.position.z)>1e-9,s=moved?sweep(current,x,z,yaw):null,r=moved?(s.eligible?s.result:null):resolvePosition(x,z,yaw);if(!r?.eligible)return freeze({ok:false,status:'NAVIGATION_PROPOSAL_REJECTED_STATE_PRESERVED',state:current,issues:s?.issues??r?.issues??['TERRAIN_SUPPORT_REJECTED']});return freeze({ok:true,status:'NAVIGATION_PROPOSAL_ACCEPTED',state:stateFrom(r,{yaw,pitch,fov,sequence,action,previousY:current.position.y,swept:s?.sampleCount??0}),issues:[]});}
export function createHEarthFunctionalLandscapeCamera(state){if(!state||state.contractId!==H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_CONTRACT_ID)return null;const yaw=state.yawDegrees*Math.PI/180,pitch=state.pitchDegrees*Math.PI/180,h=Math.cos(pitch),d=H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_PROFILE.lookDistanceWorldUnits,dir={x:Math.sin(yaw)*h,y:Math.sin(pitch),z:-Math.cos(yaw)*h};return freeze({position:freeze({...state.position}),target:freeze({x:state.position.x+dir.x*d,y:state.position.y+dir.y*d,z:state.position.z+dir.z*d}),up:freeze({x:0,y:1,z:0}),verticalFovDegrees:state.verticalFovDegrees,nearPlane:H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_PROFILE.nearPlane,farPlane:H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_PROFILE.farPlane,sourceCapacityContractId:'H_EARTH_3D_CAPACITY_FILE_RENEWAL_STEP_034O_3_GROUND_OBSERVER_CAMERA_CAPACITY_v5',cameraAuthority:'SUCCESSOR_COMPOSITOR_ACCEPTED_NAVIGATION_PROPOSAL',terrainClearanceReceiptId:state.terrainClearanceReceiptId,visibleTerrainClearanceContractId:state.clearanceSurfaceContractId});}
export function evaluateHEarthFunctionalLandscapeNavigationState(state){const issues=[];if(!state||state.contractId!==H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_CONTRACT_ID)issues.push('NAVIGATION_STATE_INVALID');else{const r=resolvePosition(state.position.x,state.position.z,state.yawDegrees);if(!r.eligible)issues.push(...r.issues);else if(state.position.y<r.minimumCameraY-1e-8||state.position.y<r.terrainElevation+H_EARTH_FUNCTIONAL_LANDSCAPE_NAVIGATION_PROFILE.hardTerrainSupportOffset-1e-8)issues.push('CAMERA_BELOW_PRESENTED_TERRAIN_SUPPORT');if(!state.selectedSemanticAddressId)issues.push('SEMANTIC_SELECTION_MISSING');if(state.terrainSupported!==true)issues.push('TERRAIN_SUPPORT_FLAG_MISSING');}return freeze({eligible:issues.length===0,status:issues.length?'NAVIGATION_STATE_FAIL':'NAVIGATION_STATE_PASS',issues});}
