const canvas=document.querySelector('#scene');
const statusNode=document.querySelector('#status');
const returnButton=document.querySelector('#return');
const story=document.querySelector('#story');
const storyKind=document.querySelector('#story-kind');
const storyTitle=document.querySelector('#story-title');
const storyCopy=document.querySelector('#story-copy');
const storyMore=document.querySelector('#story-more');
const fatal=document.querySelector('#fatal');
const world=document.querySelector('.world');
const gl=canvas.getContext('webgl2',{antialias:true,alpha:false,powerPreference:'high-performance'});
if(!gl){fatal.classList.add('show');throw new Error('WEBGL2_UNAVAILABLE');}

const style=document.createElement('style');
style.textContent=`.signal-layer{position:absolute;inset:0;z-index:6;pointer-events:none}.signal{position:absolute;transform:translate(-50%,-50%);pointer-events:auto;border:0;background:transparent;color:#fff;cursor:pointer;padding:22px}.signal::before{content:"";display:block;width:10px;height:10px;border-radius:50%;margin:auto;background:#f5d889;box-shadow:0 0 0 5px rgba(245,216,137,.12),0 0 26px 8px rgba(245,216,137,.34);animation:signalPulse 2.8s ease-in-out infinite}.signal span{display:block;margin-top:7px;padding:.35rem .52rem;border:1px solid rgba(255,255,255,.17);border-radius:999px;background:rgba(4,16,20,.58);backdrop-filter:blur(8px);font-size:.64rem;font-weight:800;letter-spacing:.04em;white-space:nowrap;opacity:0;transform:translateY(3px);transition:.2s ease}.signal:hover span,.signal:focus-visible span{opacity:1;transform:none}.signal:focus-visible{outline:none}.signal.visited::before{background:#a8e7d1;box-shadow:0 0 0 5px rgba(168,231,209,.1),0 0 22px 7px rgba(168,231,209,.28)}.signal[hidden]{display:none}@keyframes signalPulse{0%,100%{transform:scale(.82);opacity:.72}50%{transform:scale(1.15);opacity:1}}@media(prefers-reduced-motion:reduce){.signal::before{animation:none}}`;
document.head.appendChild(style);
const signalLayer=document.createElement('div');signalLayer.className='signal-layer';world.appendChild(signalLayer);

const COAST=[[-520,-40],[-760,-80],[-980,-180],[-1180,-340],[-1500,-520],[-1660,-720],[-1500,-900],[-1260,-850],[-1080,-700],[-1180,-1010],[-1380,-1260],[-1510,-1490],[-1370,-1710],[-1080,-1880],[-760,-1990],[-470,-1910],[-190,-2050],[120,-2010],[390,-2160],[650,-2050],[760,-1850],[1040,-1700],[1370,-1800],[1650,-1600],[1760,-1360],[1580,-1260],[1350,-1220],[1140,-1100],[900,-1040],[690,-900],[560,-700],[760,-430]];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const mix=(a,b,t)=>a+(b-a)*t;
const smooth=t=>t*t*(3-2*t);
const ease=t=>t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;
const add=(a,b)=>a.map((v,i)=>v+b[i]);
const sub=(a,b)=>a.map((v,i)=>v-b[i]);
const scale=(a,s)=>a.map(v=>v*s);
const dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const norm=a=>{const l=Math.hypot(...a)||1;return scale(a,1/l)};
const bezier=(a,b,c,d,t)=>{const q=1-t;return a.map((_,i)=>q*q*q*a[i]+3*q*q*t*b[i]+3*q*t*t*c[i]+t*t*t*d[i]);};
function shorelineZ(x){const pts=COAST.filter(p=>p[0]>=-1180&&p[0]<=1180).sort((a,b)=>a[0]-b[0]);if(x<=pts[0][0])return pts[0][1];if(x>=pts.at(-1)[0])return pts.at(-1)[1];for(let i=0;i<pts.length-1;i++)if(x>=pts[i][0]&&x<=pts[i+1][0]){const t=(x-pts[i][0])/(pts[i+1][0]-pts[i][0]);return mix(pts[i][1],pts[i+1][1],smooth(t));}return-900;}
function terrainHeight(x,z){const shore=shorelineZ(x)*.42+250,inland=shore-z,beach=clamp(inland/150,0,1),macro=24*Math.sin(x*.004)+15*Math.cos(z*.006)+9*Math.sin((x+z)*.011),rise=Math.max(0,inland)*.055,dune=beach*(6*Math.sin(x*.026)+4*Math.cos(z*.034));return inland<0?-5:2+rise+macro+dune;}
const VS=`#version 300 es\nprecision highp float;layout(location=0) in vec3 aPos;layout(location=1) in vec3 aNormal;uniform mat4 uVP;out vec3 vPos;out vec3 vNormal;out float vH;void main(){vPos=aPos;vNormal=aNormal;vH=aPos.y;gl_Position=uVP*vec4(aPos,1.0);}`;
const FS=`#version 300 es\nprecision highp float;in vec3 vPos;in vec3 vNormal;in float vH;uniform vec3 uEye;uniform float uTime;uniform int uWater;out vec4 outColor;void main(){if(uWater==1){float r=.5+.5*sin(vPos.x*.035+uTime*1.3)+.25*sin(vPos.z*.047-uTime*.8);vec3 c=mix(vec3(.045,.25,.31),vec3(.13,.48,.55),r*.35);float fres=pow(1.0-max(dot(normalize(vNormal),normalize(uEye-vPos)),0.0),3.0);outColor=vec4(c+vec3(.16,.25,.25)*fres,1.0);return;}vec3 n=normalize(vNormal);vec3 light=normalize(vec3(.35,.82,.28));float d=.42+.58*max(dot(n,light),0.0);float sand=smoothstep(-1.0,13.0,vH)*(1.0-smoothstep(18.0,42.0,vH));vec3 rock=mix(vec3(.12,.24,.18),vec3(.25,.34,.22),smoothstep(25.0,120.0,vH));vec3 c=mix(rock,vec3(.67,.58,.39),sand);c*=d;float haze=clamp(length(vPos.xz)/2200.0,0.0,.65);c=mix(c,vec3(.43,.62,.61),haze*.32);outColor=vec4(c,1.0);}`;
function makeProgram(vs,fs){const compile=(type,src)=>{const sh=gl.createShader(type);gl.shaderSource(sh,src);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(sh));return sh};const p=gl.createProgram();gl.attachShader(p,compile(gl.VERTEX_SHADER,vs));gl.attachShader(p,compile(gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));return p;}
const program=makeProgram(VS,FS);
function perspective(fov,aspect,near,far){const f=1/Math.tan(fov/2),nf=1/(near-far);return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0]);}
function lookAt(eye,target,up=[0,1,0]){const z=norm(sub(eye,target)),x=norm(cross(up,z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1]);}
function mul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o;}
function project(p,m,w,h){const [x,y,z]=p,cx=m[0]*x+m[4]*y+m[8]*z+m[12],cy=m[1]*x+m[5]*y+m[9]*z+m[13],cz=m[2]*x+m[6]*y+m[10]*z+m[14],cw=m[3]*x+m[7]*y+m[11]*z+m[15];if(cw<=0)return null;const nx=cx/cw,ny=cy/cw,nz=cz/cw;if(nx<-1.2||nx>1.2||ny<-1.2||ny>1.2||nz<-1.2||nz>1.2)return null;return[(nx*.5+.5)*w,(1-(ny*.5+.5))*h,cw];}
function meshTerrain(){const N=150,z0=-1200,z1=280,verts=[],idx=[];for(let j=0;j<=N;j++){const z=mix(z0,z1,j/N);for(let i=0;i<=N;i++){const x=mix(-1050,1050,i/N),y=terrainHeight(x,z),eps=3,dx=terrainHeight(x+eps,z)-terrainHeight(x-eps,z),dz=terrainHeight(x,z+eps)-terrainHeight(x,z-eps),n=norm([-dx,2*eps,-dz]);verts.push(x,y,z,...n);}}const row=N+1;for(let j=0;j<N;j++)for(let i=0;i<N;i++){const a=j*row+i,b=a+1,c=a+row,d=c+1;idx.push(a,c,b,b,c,d);}return{verts:new Float32Array(verts),idx:new Uint32Array(idx)};}
function meshWater(){return{verts:new Float32Array([-1250,-2,-1550,0,1,0,1250,-2,-1550,0,1,0,-1250,-2,420,0,1,0,1250,-2,420,0,1,0]),idx:new Uint32Array([0,2,1,1,2,3])};}
function makeVAO(mesh){const vao=gl.createVertexArray();gl.bindVertexArray(vao);const vb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,vb);gl.bufferData(gl.ARRAY_BUFFER,mesh.verts,gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,3,gl.FLOAT,false,24,12);const ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,mesh.idx,gl.STATIC_DRAW);return{vao,count:mesh.idx.length};}
const terrain=makeVAO(meshTerrain()),water=makeVAO(meshWater());
const D=(id,x,z,eye,look,data)=>({id,pos:[x,terrainHeight(x,z)+data.height,z],eye,look,...data});
const DESTINATIONS=[
D('crossing',-690,-300,[-500,160,-55],[-690,22,-315],{height:34,signal:'Something happened here',kind:'The shore remembers',title:'The Crossing',copy:'The first team crossed into Mirrorland. The return path never opened. What began as discovery became a responsibility no one could hand back.',more:['Dextrion found the anomaly from Earth. Others crossed because the possibility mattered enough to risk the unknown.','The failure of the return path changed every decision that followed. Mirrorland stopped being somewhere they could visit and became somewhere they had to prepare.'],connections:['dextrion','manor','clock']}),
D('dextrion',-920,-500,[-720,175,-210],[-920,30,-515],{height:44,signal:'A transmission from Earth',kind:'A voice from the other side',title:'Dextrion',copy:'He opened the path and stayed behind. Every person sent through the one-way crossing remains part of the choice he made.',more:['His Earth-side lab becomes command center, workshop and countdown room. He cannot enter the world he is responsible for helping save.','His problem is no longer whether the anomaly is real. It is whether the door can become something more than a wound.'],connections:['crossing','manor','clock']}),
D('alaric',-210,-575,[25,130,-300],[-210,35,-575],{height:42,signal:'Someone is watching the route',kind:'Trust the warning before the proof',title:'Alaric',copy:'He reads danger before proof arrives. Waiting until everyone agrees can mean waiting until the safe route is already gone.',more:['Alaric carries orientation as responsibility. He studies what changes first: routes, pressure, silence, the things people ignore because they have not become obvious yet.','His conflict is simple to state and difficult to live with: how do you ask people to trust a warning they cannot yet see?'],connections:['tarian','soren','crossing']}),
D('tarian',115,-360,[300,125,-125],[115,30,-365],{height:38,signal:'The waterline is changing',kind:'Survival has a physical limit',title:'Tarian',copy:'He keeps the mission physically honest. A future is meaningless if the people trying to reach it cannot keep standing.',more:['Water, movement and endurance are not background systems to him. They are the difference between a plan that exists and people who can survive long enough to carry it.','When ambition outruns the body, Tarian is the one who notices the cost.'],connections:['alaric','manor','soren']}),
D('manor',430,-820,[625,190,-520],[430,70,-820],{height:96,signal:'A light farther inland',kind:'The first standing anchor',title:'Mirror Manor',copy:'The Manor stands because the crossing became permanent. Shelter is not the end of the problem. It is where preparation begins.',more:['The people who crossed needed more than protection from weather. They needed a place capable of holding knowledge, people and decisions while the world around them was still becoming known.','The Manor can protect, but protection can become isolation. The question is whether a sanctuary can remain connected to the world it was built to help.'],connections:['tarian','elara','auren','jeeves','clock']}),
D('elara',760,-650,[915,145,-395],[760,34,-650],{height:40,signal:'A signal beyond the dunes',kind:'A future has to become visible',title:'Elara',copy:'She makes a possible future visible before the world believes in it. Hope has to become something people can actually see.',more:['Visibility is not decoration. It changes what people believe is reachable. Elara carries that burden every time she makes possibility public.','But exposure has a cost. Showing people the future can also show danger where to look.'],connections:['manor','soren','clock']}),
D('soren',690,-1010,[820,180,-720],[690,45,-1010],{height:52,signal:'The ground does not agree',kind:'Damage does not become progress by renaming it',title:'Soren',copy:'He refuses fake restoration. Saving a world by hiding what was damaged only prepares the next collapse.',more:['Soren looks for the hidden cost: contamination, displaced pressure, the consequence everyone wants to call acceptable because the alternative is inconvenient.','His severity exists for a reason. A repaired surface is not the same thing as a healed system.'],connections:['alaric','tarian','elara','clock']}),
D('auren',250,-980,[420,165,-700],[250,55,-980],{height:58,signal:'A path toward shelter',kind:'Protection can become a cage',title:'Auren Vale',copy:'He keeps the Manor from becoming a beautiful cage. Every protected life makes the sanctuary more necessary—and harder to keep hidden.',more:['Auren turns land, rooms, misdirection and stewardship into protection. His gift is custody; his danger is overprotection.','The question surrounding him is whether safety can remain open enough to serve the people it was meant to protect.'],connections:['manor','jeeves','clock']}),
D('jeeves',520,-930,[680,150,-650],[520,62,-930],{height:72,signal:'The house is listening',kind:'Not every truth belongs at the door',title:'Jeeves',copy:'He decides how much the Manor reveals at once. Too much truth can break people. Too little can send them into the wrong room.',more:['The Manor is more than architecture when knowledge itself can overwhelm. Jeeves turns complexity into thresholds people can survive.','His problem is not secrecy for its own sake. It is timing: what must someone know now, and what can wait until they are ready?'],connections:['manor','auren','clock']}),
D('clock',930,-1080,[1065,220,-735],[930,52,-1080],{height:60,signal:'The horizon is still moving',kind:'Time is not waiting for agreement',title:'The Clock',copy:'The transition will happen. Preparation is the variable. What this world becomes is not separate from what eventually happens to Earth.',more:['Mirrorland is not an escape from consequence. It is a place where possible futures can become visible before they harden.','ZIONTS is consequence. H-Earth is survival. Audralia is possibility. The responsibility is deciding which direction people are willing to build toward.'],connections:['crossing','dextrion','manor','elara','soren']}),
D('remote',-430,-940,[-250,165,-690],[-430,48,-940],{height:48,signal:'Lights beyond the estate',kind:'Survival has to travel',title:'Beyond the Manor',copy:'If what works here cannot leave the estate, the Manor is only a bunker. Survival has to become something communities can carry elsewhere.',more:['The remote teams turn isolated restoration into distributed response. They carry what is learned here into places without the Manor’s protection.','The story gets larger at this boundary: the future cannot be saved from one house.'],connections:['manor','tarian','clock']})];
const byId=new Map(DESTINATIONS.map(d=>[d.id,d]));
const visited=new Set();
const ORBIT={eye:[0,365,590],look:[70,24,-660]};
let camera={eye:[...ORBIT.eye],look:[...ORBIT.look]},active=null,transition=null;
for(const d of DESTINATIONS){const b=document.createElement('button');b.type='button';b.className='signal';b.dataset.id=d.id;b.setAttribute('aria-label',d.signal);b.innerHTML=`<span>${d.signal}</span>`;b.addEventListener('click',()=>travelTo(d));signalLayer.appendChild(b);d.button=b;}
function setStory(d){storyMore.innerHTML='';if(!d){story.classList.remove('show');return;}storyKind.textContent=d.kind;storyTitle.textContent=d.title;storyCopy.textContent=d.copy;for(const p of d.more||[]){const el=document.createElement('p');el.textContent=p;storyMore.appendChild(el);}if(d.connections?.length){const wrap=document.createElement('div');wrap.className='connections';for(const id of d.connections){const target=byId.get(id);if(!target)continue;const b=document.createElement('button');b.type='button';b.textContent=target.title;b.addEventListener('click',()=>travelTo(target,true));wrap.appendChild(b);}storyMore.appendChild(wrap);}story.classList.add('show');visited.add(d.id);d.button.classList.add('visited');}
function travelTo(d,fromConnection=false){if(transition||d===active&&!fromConnection)return;setStory(null);returnButton.classList.remove('show');active=d;statusNode.textContent=`Following ${d.signal.toLowerCase()}`;const start={eye:[...camera.eye],look:[...camera.look]},end={eye:d.eye,look:d.look},dir=norm(sub(end.eye,start.eye)),side=norm(cross(dir,[0,1,0])),distance=Math.hypot(...sub(end.eye,start.eye));transition={start:performance.now(),duration:clamp(1900+distance*.9,2200,3200),from:start,to:end,c1Eye:add(add(start.eye,scale(side,95)),[0,145,0]),c2Eye:add(add(end.eye,scale(side,-65)),[0,70,0]),returning:false};}
function returnOrbit(){if(transition)return;setStory(null);statusNode.textContent='Returning to the coast';const start={eye:[...camera.eye],look:[...camera.look]},end=ORBIT,dir=norm(sub(end.eye,start.eye)),side=norm(cross(dir,[0,1,0]));transition={start:performance.now(),duration:2450,from:start,to:end,c1Eye:add(add(start.eye,scale(side,-85)),[0,125,0]),c2Eye:add(add(end.eye,scale(side,60)),[0,72,0]),returning:true};returnButton.classList.remove('show');}
returnButton.addEventListener('click',returnOrbit);
function updateTransition(now){if(!transition)return;const t=clamp((now-transition.start)/transition.duration,0,1),e=ease(t);camera.eye=bezier(transition.from.eye,transition.c1Eye,transition.c2Eye,transition.to.eye,e);camera.look=bezier(transition.from.look,add(transition.from.look,[0,60,0]),add(transition.to.look,[0,30,0]),transition.to.look,e);if(t>=1){const returning=transition.returning;transition=null;if(returning){active=null;statusNode.textContent=visited.size?`Orbit · ${visited.size} discoveries found`:'Orbit · survey the coast';}else{statusNode.textContent=`You found ${active.title}`;returnButton.classList.add('show');setStory(active);}}}
function resize(){const dpr=Math.min(1.55,devicePixelRatio||1),w=Math.max(1,Math.round(innerWidth*dpr)),h=Math.max(1,Math.round(innerHeight*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}gl.viewport(0,0,w,h);return{w,h,dpr};}
function draw(mesh,waterFlag,vp,time){gl.useProgram(program);gl.uniformMatrix4fv(gl.getUniformLocation(program,'uVP'),false,vp);gl.uniform3fv(gl.getUniformLocation(program,'uEye'),camera.eye);gl.uniform1f(gl.getUniformLocation(program,'uTime'),time);gl.uniform1i(gl.getUniformLocation(program,'uWater'),waterFlag);gl.bindVertexArray(mesh.vao);gl.drawElements(gl.TRIANGLES,mesh.count,gl.UNSIGNED_INT,0);}
function updateSignals(vp){const cssW=innerWidth,cssH=innerHeight;for(const d of DESTINATIONS){const p=project(d.pos,vp,cssW,cssH);if(!p||transition){d.button.hidden=true;continue;}d.button.hidden=false;d.button.style.left=`${p[0]}px`;d.button.style.top=`${p[1]}px`;d.button.style.opacity=active&&active!==d?'.28':'1';}}
function render(now){const {w,h}=resize();updateTransition(now);const vp=mul(perspective(52*Math.PI/180,w/h,1,5000),lookAt(camera.eye,camera.look));gl.enable(gl.DEPTH_TEST);gl.disable(gl.BLEND);gl.clearColor(.28,.55,.63,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);draw(water,1,vp,now*.001);draw(terrain,0,vp,now*.001);updateSignals(vp);requestAnimationFrame(render);}
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&active&&!transition)returnOrbit();});
requestAnimationFrame(render);