/** Independent read-only qualification of landscape identity presentation. */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {getHEarthRun8ER2ImmutableLiveRenderPackage,getHEarthRun8ER2VegetationWorldTruthPlan} from '../../showroom/globe/h-earth/render/live-render-package.run8e-r2.js';
import {buildHEarthLandscapeCoverPlan,buildHEarthLandscapeCoverBatch,H_EARTH_LANDSCAPE_COVER as limits} from '../../showroom/globe/h-earth/render/geometry-landscape-cover.js';
import {H_EARTH_GEN311_ESTATE_PLACEMENT_POLICY as estate,sampleHEarthGen311PlacementStructureDisposition} from '../environment/h-earth.gen2514-qualified-placement-authority.js';
import {sampleHEarthRun8CSuccessorSurfaceMaterial} from '../environment/h-earth.gen2514-qualified-surface-material.run8c.js';
import {H_EARTH_OASIS_FOLIAGE_SAMPLE as oasis} from '../../showroom/globe/h-earth/render/grass-lowland-trial.js';
const args=process.argv.slice(2),arg=k=>{const i=args.indexOf(k);return i<0?null:args[i+1];};
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const digest=v=>createHash('sha256').update(typeof v==='string'||Buffer.isBuffer(v)?v:JSON.stringify(v)).digest('hex');
const sourcePaths=['showroom/globe/h-earth/render/grass-lowland-trial.js','showroom/globe/h-earth/render/geometry-landscape-sector.p2.js','h-earth-3d/environment/h-earth.gen2514-qualified-placement-authority.js','h-earth-3d/environment/h-earth.gen2514-qualified-surface-material.run8c.js'];
const sourceDigests={};
for(const p of sourcePaths){const bytes=fs.readFileSync(path.join(root,p));sourceDigests[p]=digest(bytes);if(arg('--baseline')&&arg('--git-repository')){const baseline=execFileSync('git',['-C',arg('--git-repository'),'show',`${arg('--baseline')}:${p}`],{maxBuffer:16*1024*1024});assert.equal(digest(bytes),digest(baseline),`ACCEPTED_SOURCE_DRIFT:${p}`);}}
const candidateSourceDigests=Object.fromEntries(['showroom/globe/h-earth/render/geometry-landscape-cover.js','showroom/globe/h-earth/render/live-render-package.run8e-r2.js','h-earth-3d/validation/h-earth.landscape-identity.v1.mjs'].map(p=>[p,digest(fs.readFileSync(path.join(root,p)))]));
if(arg('--candidate-head')){assert(/^[a-f0-9]{40}$/.test(arg('--candidate-head')),'EXACT_CANDIDATE_SHA_REQUIRED');assert(arg('--git-repository'),'CANDIDATE_OBJECT_REPOSITORY_REQUIRED');for(const [p,sha] of Object.entries({...sourceDigests,...candidateSourceDigests})){const bytes=execFileSync('git',['-C',arg('--git-repository'),'show',`${arg('--candidate-head')}:${p}`],{maxBuffer:16*1024*1024});assert.equal(sha,digest(bytes),`EXECUTED_CANDIDATE_BYTES_MISMATCH:${p}`);}}
const start=performance.now(),pkg=getHEarthRun8ER2ImmutableLiveRenderPackage({deferVegetation:true}),packageMs=performance.now()-start;
const planStart=performance.now(),plan=buildHEarthLandscapeCoverPlan(pkg),planMs=performance.now()-planStart;
for(const order of ['REVERSE','CHUNKED'])assert.equal(digest(buildHEarthLandscapeCoverPlan(pkg,{order})),digest(plan),`PLAN_ORDER_DRIFT:${order}`);
assert.equal(new Set(plan.placements.map(p=>p.id)).size,plan.tuftCount,'DUPLICATE_PLACEMENT_ID');
assert(plan.tuftCount>0&&plan.tuftCount<=8192);assert.equal(plan.maximumTriangles,plan.tuftCount*24);assert(plan.maximumTriangles<=196608);assert.equal(plan.batchCounts.length,108);assert(plan.batchCounts.every(n=>n<=128));assert.equal(plan.cameraIndependent,true);assert.equal(plan.canonicalPopulationChanged,false);
// Independent geometry implementation: cross-product normal and barycentric area
// interpolation, using 32m buckets rather than the runtime's 16m sampler.
const triangles=new Map(),bins=new Map(),water=[];
for(const span of pkg.primitiveSpans){if(span.role!=='TERRAIN'&&!span.primitiveId.includes('FAR_OCEAN_CONTINUATION'))continue;
 for(let offset=span.indexStart;offset<span.indexStart+span.indexCount;offset+=3){const v=[0,1,2].map(k=>{const i=pkg.buffers.indices[offset+k]*3;return {x:Math.fround(pkg.buffers.positions[i]),y:Math.fround(pkg.buffers.positions[i+1]),z:Math.fround(pkg.buffers.positions[i+2])};});const t={id:offset/3,primitive:span.primitiveId,v};if(span.role!=='TERRAIN'){water.push(t);continue;}triangles.set(t.id,t);const xs=v.map(p=>p.x),zs=v.map(p=>p.z);for(let z=Math.floor(Math.min(...zs)/32);z<=Math.floor(Math.max(...zs)/32);z++)for(let x=Math.floor(Math.min(...xs)/32);x<=Math.floor(Math.max(...xs)/32);x++){const key=`${x},${z}`;if(!bins.has(key))bins.set(key,[]);bins.get(key).push(t);}}
}
function interpolate(t,x,z){const [a,b,c]=t.v,den=(b.x-a.x)*(c.z-a.z)-(b.z-a.z)*(c.x-a.x);if(Math.abs(den)<1e-12)return null;const bWeight=((x-a.x)*(c.z-a.z)-(z-a.z)*(c.x-a.x))/den,cWeight=((b.x-a.x)*(z-a.z)-(b.z-a.z)*(x-a.x))/den,aWeight=1-bWeight-cWeight;if(Math.min(aWeight,bWeight,cWeight)<-1e-7)return null;const dx=b.x-a.x,dy=b.y-a.y,dz=b.z-a.z,ex=c.x-a.x,ey=c.y-a.y,ez=c.z-a.z,nx=dy*ez-dz*ey,ny=dz*ex-dx*ez,nz=dx*ey-dy*ex;return {y:aWeight*a.y+bWeight*b.y+cWeight*c.y,slope:Math.abs(ny)>1e-12?Math.hypot(nx,nz)/Math.abs(ny):Infinity};}
function support(x,z){for(const t of bins.get(`${Math.floor(x/32)},${Math.floor(z/32)}`)??[]){const hit=interpolate(t,x,z);if(hit)return {...hit,triangle:t};}return null;}
function distance(x,z,a,b){const dx=b.x-a.x,dz=b.z-a.z,den=dx*dx+dz*dz,t=den?Math.max(0,Math.min(1,((x-a.x)*dx+(z-a.z)*dz)/den)):0;return Math.hypot(x-a.x-t*dx,z-a.z-t*dz);}
function clear(x,z,r=0){for(const b of [estate.manorCore,estate.gardens,estate.outbuildingProposal,estate.acceptedEnvelope])assert(Math.hypot(x-Math.max(b.minX,Math.min(b.maxX,x)),z-Math.max(b.minZ,Math.min(b.maxZ,z)))>r,'ESTATE_RECTANGLE_OVERLAP');for(let i=1;i<estate.footRoute.length;i++)assert(distance(x,z,estate.footRoute[i-1],estate.footRoute[i])>estate.footRouteRadius+r,'ESTATE_WALKING_ROUTE_OVERLAP');assert(distance(x,z,{x:-145,z:-194},{x:-145,z:-230})>1.5+r,'WOODLAND_WALKING_OVERLAP');const reservation=sampleHEarthGen311PlacementStructureDisposition(x,z);assert.equal(reservation.hardExclusions.length,0);assert.equal(reservation.planningHolds.length,0);}
let roots=0,tufts=0,vertices=0,indices=0,maxGroundError=0,maxBatchMs=0,waterChecked=0;
const batches=[],rejections=[],ids=new Set(),patchCounts={};
for(const p of plan.placements){clear(p.x,p.z,.8);assert(!(p.x>=oasis.minX-.8&&p.x<=oasis.maxX+.8&&p.z>=oasis.minZ-.8&&p.z<=oasis.maxZ+.8),'ACCEPTED_OASIS_OVERLAP');assert(Math.hypot((p.x+141)/33,(p.z+226)/32)>1.25+.8/32,'ACCEPTED_WOODLAND_OVERLAP');}
for(let i=0;i<108;i++){const tick=performance.now(),batch=buildHEarthLandscapeCoverBatch(pkg,i,{plan});maxBatchMs=Math.max(maxBatchMs,performance.now()-tick);assert.equal(batch.batchIndex,i);assert.equal(batch.triangleCount,batch.primitives.length*24);assert.equal(batch.vertexCount,batch.primitives.length*28);assert.equal(batch.canonicalPopulationChanged,false);rejections.push(...batch.rejections);batches.push({index:i,tufts:batch.tuftCount,sha256:digest(batch)});
 for(const primitive of batch.primitives){assert(!ids.has(primitive.primitiveId),'DUPLICATE_FAN_ID');ids.add(primitive.primitiveId);assert.equal(primitive.geometry.vertices.length,28);assert.equal(primitive.geometry.indices.length,72);assert(primitive.geometry.indices.every(n=>Number.isInteger(n)&&n>=0&&n<28));const foliage=primitive.metadata.oasisFoliage;assert.equal(foliage.bladeCount,4);assert.equal(foliage.rootPoints.length,12);assert.equal(foliage.fanRecipe,'COMPACT_LEAF_7_VERTICES_6_TRIANGLES_PERPENDICULAR_FAN_v1');assert.equal(primitive.metadata.landscapeIdentity.sourceRecipe,'ACCEPTED_WOODLAND_FOUR_BLADE_FAN');assert.equal(primitive.metadata.landscapeIdentity.batchIndex,i);const patch=primitive.metadata.landscapeIdentity.patch;patchCounts[patch]=(patchCounts[patch]??0)+1;
  for(const witness of foliage.rootPoints){const v=primitive.geometry.vertices[witness.vertexIndex];assert(v&&[v.x,v.y,v.z].every(Number.isFinite));const direct=triangles.get(witness.triangleId);assert(direct,'ROOT_TRIANGLE_MISSING');assert.equal(direct.primitive,witness.terrainPrimitiveId,'ROOT_PRIMITIVE_MISMATCH');const hit=interpolate(direct,v.x,v.z),brute=support(v.x,v.z);assert(hit&&brute,'ROOT_SUPPORT_MISSING');assert(hit.slope<=.45+1e-12,'ROOT_SLOPE_EXCEEDED');const error=Math.abs(v.y-hit.y);maxGroundError=Math.max(maxGroundError,error);assert(error<=.0001,'ROOT_GROUNDING_ERROR');assert(Math.abs(v.y-brute.y)<=.0001,'ROOT_INDEPENDENT_TRIANGLE_ERROR');clear(v.x,v.z);const m=sampleHEarthRun8CSuccessorSurfaceMaterial(v.x,v.z);assert(m.valid&&['LOWLAND_SOIL','COASTAL_SOIL'].includes(m.surfaceClass)&&m.soilDepth>=.20,'ROOT_HABITAT_EXCLUDED');for(const obstacle of pkg.landscapeCoverFootprints??[])assert(Math.hypot(v.x-obstacle.x,v.z-obstacle.z)>=obstacle.radius+.8-1e-7,'ROOT_OBSTACLE_OVERLAP');for(const t of water){const w=interpolate(t,v.x,v.z);if(w){assert(v.y>=w.y-.0001,'DRY_FAN_SUBMERGED');waterChecked++;break;}}roots++;}
  for(const v of primitive.geometry.vertices){assert([v.x,v.y,v.z].every(Number.isFinite));clear(v.x,v.z);assert(v.x>=limits.bounds.minX+1&&v.x<=limits.bounds.maxX-1&&v.z>=limits.bounds.minZ+1&&v.z<=limits.bounds.maxZ-1,'FAN_OUTSIDE_RENDERED_DOMAIN');}tufts++;vertices+=28;indices+=72;
 }
}
assert(tufts>0&&tufts<=plan.tuftCount);assert(tufts<=8192&&indices/3<=196608);assert.equal(roots,tufts*12);assert.equal(ids.size,tufts);assert.equal(tufts+rejections.length,plan.tuftCount);
let worldTruth=null;
if(args.includes('--world-truth')){const truth=getHEarthRun8ER2VegetationWorldTruthPlan();assert.equal(truth.instanceCount,27585);assert.equal(truth.batches.length,108);assert.equal(truth.droppedPlacementCount,0);worldTruth={instanceCount:truth.instanceCount,batchCount:truth.batches.length,droppedPlacementCount:truth.droppedPlacementCount};}
const report={schema:'H_EARTH_LANDSCAPE_IDENTITY_MECHANICAL_QUALIFICATION_v1',result:'PASS',executedHead:arg('--candidate-head'),baseline:arg('--baseline'),sourceDigests,candidateSourceDigests,planDigest:digest(plan),geometryDigest:digest(batches),candidateCount:plan.candidateCount,plannedTufts:plan.tuftCount,constructedTufts:tufts,rootCollarRejections:rejections.length,roots,vertices,triangles:indices/3,maxGroundError,waterChecked,patchCounts,batches,planOrderVariants:3,independentFloat32Grounding:true,reservationAndWalkingClearances:true,acceptedRecipesUnchanged:Boolean(arg('--baseline')&&arg('--git-repository')),worldTruth,timing:{rawPackageMs:packageMs,planMs,maxBatchMs,totalMs:performance.now()-start},browserReadiness:'SEPARATE_EXACT_HEAD_REQUIRED',physicalDeviceAcceptance:'NOT_ESTABLISHED',productMutationPerformed:false,mergePerformed:false,deploymentPerformed:false};
if(arg('--output'))fs.writeFileSync(arg('--output'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
