import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { buildHEarthRun8ER3F2SignedOfflinePackage } from './h-earth.run8e-r3f2.signed-offline-package.builder.mjs';
import { H_EARTH_RUN_8E_R3F2_P1_CONTRACT } from '../control-plane/run-8/recovery/h-earth.run8e-r3f2-p1.immutable-preview-occurrence-contract.js';
import { H_EARTH_RUN_8E_R3F2_P2_CONTROL, evaluateHEarthRun8ER3F2P2Control } from '../control-plane/run-8/recovery/h-earth.run8e-r3f2-p2.exact-preview-package-materialization.js';
import { loadHEarthRepositoryRegistryValidatorDependencies } from '../registry/h-earth.repository-registry.validator-engine.loader.js';
import { H_EARTH_RUN_8E_R3F2_P2_NODE, H_EARTH_RUN_8E_R3F2_P2_PATHS } from '../registry/accepted-amendments/h-earth.repository-registry.run8e-r3f2-p2-exact-preview-package-materialization.js';

const assert = (condition, code) => { if (!condition) throw new Error(code); };
const sha256 = (value) => `sha256:${crypto.createHash('sha256').update(value).digest('hex')}`;
const gitBlobSha1 = (value) => crypto.createHash('sha1').update(`blob ${value.length}\0`).update(value).digest('hex');
const stable = (value) => value === null || typeof value !== 'object'
  ? JSON.stringify(value)
  : Array.isArray(value)
    ? `[${value.map(stable).join(',')}]`
    : `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stable(value[key])}`).join(',')}}`;

const PREVIEW_ROOT = 'preview/h-earth/run8e/r3f2/sha256-3020154361523cf19113e4c759c234a6c74ff5a493b8e47124ca59470da7a234';
const OUTPUT_DIRECTORY = process.env.H_EARTH_RUN8E_R3F2_P2_OUTPUT ?? '/tmp/h-earth-run8e-r3f2-p2';
const SCHEMA_TEXT = Buffer.from('ewogICIkc2NoZW1hIjogImh0dHBzOi8vanNvbi1zY2hlbWEub3JnL2RyYWZ0LzIwMjAtMTIvc2NoZW1hIiwKICAiJGlkIjogImh0dHBzOi8vZGlhbW9uZGdhdGVicmlkZ2UuY29tL3ByZXZpZXcvaC1lYXJ0aC9ydW44ZS9yM2YyL3NoYTI1Ni0zMDIwMTU0MzYxNTIzY2YxOTExM2U0Yzc1OWMyMzRhNmM3NGZmNWE0OTNiOGU0NzEyNGNhNTk0NzBkYTdhMjM0L2RldmljZS1ldmlkZW5jZS1yZWNlaXB0LnNjaGVtYS5qc29uIiwKICAidGl0bGUiOiAiSC1FYXJ0aCBSdW4gOEUgUjNGMiBwaHlzaWNhbCByZWZlcmVuY2UtZGV2aWNlIGV2aWRlbmNlIHJlY2VpcHQiLAogICJkZXNjcmlwdGlvbiI6ICJOb3JtYWxpemVkIGV2aWRlbmNlLXJlY2VpcHQgc2NoZW1hIGZvciB0aGUgaW1tdXRhYmxlIG5vbi1wcm9kdWN0aW9uIFIzRjIgY2FuZGlkYXRlLiBJdCBkb2VzIG5vdCBpdHNlbGYgZXN0YWJsaXNoIHBoeXNpY2FsIGFjY2VwdGFuY2UuIiwKICAidHlwZSI6ICJvYmplY3QiLAogICJyZXF1aXJlZCI6IFsKICAgICJjYW5kaWRhdGVJZCIsCiAgICAicHJldmlld1VybCIsCiAgICAicGFja2FnZVNoYTI1NiIsCiAgICAicHJldmlld01hbmlmZXN0RGlnZXN0IiwKICAgICJzZXJ2ZWRBc3NldElkZW50aXRpZXMiLAogICAgInNlc3Npb25JZGVudGlmaWVyIiwKICAgICJ1c2VyQWdlbnQiLAogICAgInZpZXdwb3J0IiwKICAgICJkZXZpY2VQaXhlbFJhdGlvIiwKICAgICJvcmllbnRhdGlvbiIsCiAgICAid2ViZ2xWZXJzaW9uIiwKICAgICJncHVSZW5kZXJlckluZm9ybWF0aW9uV2hlbkF2YWlsYWJsZSIsCiAgICAiY29udGV4dENyZWF0aW9uQ291bnQiLAogICAgInJlbmRlcmVySW5pdGlhbGl6YXRpb25Db3VudCIsCiAgICAiYnVmZmVyVXBsb2FkQ291bnQiLAogICAgInZpc2libGVGcmFtZUNvdW50IiwKICAgICJuYXZpZ2F0aW9uUHJvcG9zYWxDb3VudCIsCiAgICAibWF4aW11bVJlc3BvbnNlVGltZU1zIiwKICAgICJ3b3JsZFJlYnVpbGRDb3VudCIsCiAgICAiY29udGV4dExvc3NDb3VudCIsCiAgICAiY29udGV4dFJlc3RvcmF0aW9uQ291bnQiLAogICAgInNlc3Npb25TdGFydCIsCiAgICAic2Vzc2lvbkVuZCIKICBdLAogICJwcm9wZXJ0aWVzIjogewogICAgImNhbmRpZGF0ZUlkIjogewogICAgICAiY29uc3QiOiAiSF9FQVJUSF9SVU44RV9SM0YyX0NBTkRJREFURV9TSEEyNTZfMzAyMDE1NDM2MTUyM0NGMTkxMTNFNEM3NTlDMjM0QTZDNzRGRjVBNDkzQjhFNDcxMjRDQTU5NDcwREE3QTIzNCIKICAgIH0sCiAgICAicHJldmlld1VybCI6IHsKICAgICAgInR5cGUiOiAic3RyaW5nIiwKICAgICAgImZvcm1hdCI6ICJ1cmkiLAogICAgICAicGF0dGVybiI6ICIvcHJldmlldy9oLWVhcnRoL3J1bjhlL3IzZjIvc2hhMjU2LTMwMjAxNTQzNjE1MjNjZjE5MTEzZTRjNzU5YzIzNGE2Yzc0ZmY1YTQ5M2I4ZTQ3MTI0Y2E1OTQ3MGRhN2EyMzQvPyQiCiAgICB9LAogICAgInBhY2thZ2VTaGEyNTYiOiB7CiAgICAgICJjb25zdCI6ICJzaGEyNTY6MzAyMDE1NDM2MTUyM2NmMTkxMTNlNGM3NTljMjM0YTZjNzRmZjVhNDkzYjhlNDcxMjRjYTU5NDcwZGE3YTIzNCIKICAgIH0sCiAgICAicHJldmlld01hbmlmZXN0RGlnZXN0IjogewogICAgICAidHlwZSI6ICJzdHJpbmciLAogICAgICAicGF0dGVybiI6ICJec2hhMjU2OlswLTlhLWZdezY0fSQiCiAgICB9LAogICAgInNlcnZlZEFzc2V0SWRlbnRpdGllcyI6IHsKICAgICAgInR5cGUiOiAiYXJyYXkiLAogICAgICAibWluSXRlbXMiOiAzLAogICAgICAiaXRlbXMiOiB7CiAgICAgICAgInR5cGUiOiAib2JqZWN0IiwKICAgICAgICAicmVxdWlyZWQiOiBbCiAgICAgICAgICAicmVsYXRpdmVQYXRoIiwKICAgICAgICAgICJjb250ZW50U2hhMjU2IiwKICAgICAgICAgICJieXRlQ291bnQiCiAgICAgICAgXSwKICAgICAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAgICJyZWxhdGl2ZVBhdGgiOiB7CiAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIKICAgICAgICAgIH0sCiAgICAgICAgICAiY29udGVudFNoYTI1NiI6IHsKICAgICAgICAgICAgInR5cGUiOiAic3RyaW5nIiwKICAgICAgICAgICAgInBhdHRlcm4iOiAiXnNoYTI1NjpbMC05YS1mXXs2NH0kIgogICAgICAgICAgfSwKICAgICAgICAgICJnaXRCbG9iU2hhMSI6IHsKICAgICAgICAgICAgInR5cGUiOiBbCiAgICAgICAgICAgICAgInN0cmluZyIsCiAgICAgICAgICAgICAgIm51bGwiCiAgICAgICAgICAgIF0sCiAgICAgICAgICAgICJwYXR0ZXJuIjogIl5bMC05YS1mXXs0MH0kIgogICAgICAgICAgfSwKICAgICAgICAgICJieXRlQ291bnQiOiB7CiAgICAgICAgICAgICJ0eXBlIjogImludGVnZXIiLAogICAgICAgICAgICAibWluaW11bSI6IDAKICAgICAgICAgIH0KICAgICAgICB9LAogICAgICAgICJhZGRpdGlvbmFsUHJvcGVydGllcyI6IHRydWUKICAgICAgfQogICAgfSwKICAgICJzZXNzaW9uSWRlbnRpZmllciI6IHsKICAgICAgInR5cGUiOiAic3RyaW5nIiwKICAgICAgIm1pbkxlbmd0aCI6IDEKICAgIH0sCiAgICAidXNlckFnZW50IjogewogICAgICAidHlwZSI6ICJzdHJpbmciLAogICAgICAibWluTGVuZ3RoIjogMQogICAgfSwKICAgICJ2aWV3cG9ydCI6IHsKICAgICAgInR5cGUiOiAib2JqZWN0IiwKICAgICAgInJlcXVpcmVkIjogWwogICAgICAgICJ3aWR0aENzc1B4IiwKICAgICAgICAiaGVpZ2h0Q3NzUHgiCiAgICAgIF0sCiAgICAgICJwcm9wZXJ0aWVzIjogewogICAgICAgICJ3aWR0aENzc1B4IjogewogICAgICAgICAgInR5cGUiOiAibnVtYmVyIiwKICAgICAgICAgICJleGNsdXNpdmVNaW5pbXVtIjogMAogICAgICAgIH0sCiAgICAgICAgImhlaWdodENzc1B4IjogewogICAgICAgICAgInR5cGUiOiAibnVtYmVyIiwKICAgICAgICAgICJleGNsdXNpdmVNaW5pbXVtIjogMAogICAgICAgIH0KICAgICAgfSwKICAgICAgImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjogdHJ1ZQogICAgfSwKICAgICJkZXZpY2VQaXhlbFJhdGlvIjogewogICAgICAidHlwZSI6ICJudW1iZXIiLAogICAgICAiZXhjbHVzaXZlTWluaW11bSI6IDAKICAgIH0sCiAgICAib3JpZW50YXRpb24iOiB7CiAgICAgICJvbmVPZiI6IFsKICAgICAgICB7CiAgICAgICAgICAidHlwZSI6ICJzdHJpbmciCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAidHlwZSI6ICJhcnJheSIsCiAgICAgICAgICAibWluSXRlbXMiOiAxLAogICAgICAgICAgIml0ZW1zIjogewogICAgICAgICAgICAidHlwZSI6ICJzdHJpbmciCiAgICAgICAgICB9CiAgICAgICAgfQogICAgICBdCiAgICB9LAogICAgIndlYmdsVmVyc2lvbiI6IHsKICAgICAgInR5cGUiOiAic3RyaW5nIiwKICAgICAgIm1pbkxlbmd0aCI6IDEKICAgIH0sCiAgICAiZ3B1UmVuZGVyZXJJbmZvcm1hdGlvbldoZW5BdmFpbGFibGUiOiB7CiAgICAgICJ0eXBlIjogWwogICAgICAgICJzdHJpbmciLAogICAgICAgICJudWxsIgogICAgICBdCiAgICB9LAogICAgImNvbnRleHRDcmVhdGlvbkNvdW50IjogewogICAgICAidHlwZSI6ICJpbnRlZ2VyIiwKICAgICAgIm1pbmltdW0iOiAwCiAgICB9LAogICAgInJlbmRlcmVySW5pdGlhbGl6YXRpb25Db3VudCI6IHsKICAgICAgInR5cGUiOiAiaW50ZWdlciIsCiAgICAgICJtaW5pbXVtIjogMAogICAgfSwKICAgICJidWZmZXJVcGxvYWRDb3VudCI6IHsKICAgICAgInR5cGUiOiAiaW50ZWdlciIsCiAgICAgICJtaW5pbXVtIjogMAogICAgfSwKICAgICJ2aXNpYmxlRnJhbWVDb3VudCI6IHsKICAgICAgInR5cGUiOiAiaW50ZWdlciIsCiAgICAgICJtaW5pbXVtIjogMAogICAgfSwKICAgICJuYXZpZ2F0aW9uUHJvcG9zYWxDb3VudCI6IHsKICAgICAgInR5cGUiOiAiaW50ZWdlciIsCiAgICAgICJtaW5pbXVtIjogMAogICAgfSwKICAgICJtYXhpbXVtUmVzcG9uc2VUaW1lTXMiOiB7CiAgICAgICJ0eXBlIjogIm51bWJlciIsCiAgICAgICJtaW5pbXVtIjogMAogICAgfSwKICAgICJ3b3JsZFJlYnVpbGRDb3VudCI6IHsKICAgICAgInR5cGUiOiAiaW50ZWdlciIsCiAgICAgICJtaW5pbXVtIjogMAogICAgfSwKICAgICJjb250ZXh0TG9zc0NvdW50IjogewogICAgICAidHlwZSI6ICJpbnRlZ2VyIiwKICAgICAgIm1pbmltdW0iOiAwCiAgICB9LAogICAgImNvbnRleHRSZXN0b3JhdGlvbkNvdW50IjogewogICAgICAidHlwZSI6ICJpbnRlZ2VyIiwKICAgICAgIm1pbmltdW0iOiAwCiAgICB9LAogICAgInNlc3Npb25TdGFydCI6IHsKICAgICAgInR5cGUiOiAic3RyaW5nIiwKICAgICAgImZvcm1hdCI6ICJkYXRlLXRpbWUiCiAgICB9LAogICAgInNlc3Npb25FbmQiOiB7CiAgICAgICJ0eXBlIjogInN0cmluZyIsCiAgICAgICJmb3JtYXQiOiAiZGF0ZS10aW1lIgogICAgfQogIH0sCiAgImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjogdHJ1ZSwKICAieC1oLWVhcnRoLWJvdW5kYXJpZXMiOiB7CiAgICAicGh5c2ljYWxBY2NlcHRhbmNlRW1iZWRkZWQiOiBmYWxzZSwKICAgICJicm9hZGVyTW9iaWxlQWNjZXB0YW5jZUVtYmVkZGVkIjogZmFsc2UsCiAgICAicHJvZHVjdGlvbkRlcGxveW1lbnQiOiBmYWxzZSwKICAgICJub3JtYWxpemF0aW9uTWF5T2NjdXJBdEV2aWRlbmNlQWRtaXNzaW9uIjogdHJ1ZQogIH0KfQo=', 'base64').toString('utf8');
const MANIFEST_TEXT = Buffer.from('ewogICJzZWxmSWRlbnRpdHkiOiB7CiAgICAiaWRlbnRpdHlDbGFzcyI6ICJTSEEyNTZfT0ZfQ0FOT05JQ0FMX01BTklGRVNUX1BBWUxPQURfRVhDTFVESU5HX1NFTEZfSURFTlRJVFkiLAogICAgImNhbm9uaWNhbGl6YXRpb24iOiAiVVRGOF9KU09OX1NPUlRFRF9LRVlTX0NPTVBBQ1QiLAogICAgImNhbm9uaWNhbFBheWxvYWRTaGEyNTYiOiAic2hhMjU2OmUyZTFhZWM0NzhhMmEzOTFmMjllMzJjOTgzYzU2NDA4Y2ZhZDQyZmU1YzQ3MDkzYjA3ZGFkNWU1ZWU4NDU5MWUiCiAgfSwKICAibWFuaWZlc3RJZCI6ICJIX0VBUlRIX1JVTl84RV9SM0YyX1AyX0VYQUNUX1BSRVZJRVdfUEFDS0FHRV9NQU5JRkVTVF92MSIsCiAgIm1hbmlmZXN0VmVyc2lvbiI6ICIxLjAuMCIsCiAgIm9jY3VycmVuY2VDbGFzcyI6ICJNQVRFUklBTElaRURfTk9UX1BVQkxJU0hFRCIsCiAgIm5vblByb2R1Y3Rpb24iOiB0cnVlLAogICJjYW5kaWRhdGVJZCI6ICJIX0VBUlRIX1JVTjhFX1IzRjJfQ0FORElEQVRFX1NIQTI1Nl8zMDIwMTU0MzYxNTIzQ0YxOTExM0U0Qzc1OUMyMzRBNkM3NEZGNUE0OTNCOEU0NzEyNENBNTk0NzBEQTdBMjM0IiwKICAicHJldmlld1BhdGgiOiAiL3ByZXZpZXcvaC1lYXJ0aC9ydW44ZS9yM2YyL3NoYTI1Ni0zMDIwMTU0MzYxNTIzY2YxOTExM2U0Yzc1OWMyMzRhNmM3NGZmNWE0OTNiOGU0NzEyNGNhNTk0NzBkYTdhMjM0LyIsCiAgInBhY2thZ2VJZGVudGl0eSI6IHsKICAgICJwYWNrYWdlSGVhZCI6ICJmY2RjYjRlODBhOThhODY3NzNkNTI3NjQ0N2I4ODBlZmRlMjA5OWM5IiwKICAgICJwYWNrYWdlU2hhMjU2IjogInNoYTI1NjozMDIwMTU0MzYxNTIzY2YxOTExM2U0Yzc1OWMyMzRhNmM3NGZmNWE0OTNiOGU0NzEyNGNhNTk0NzBkYTdhMjM0IiwKICAgICJwYWNrYWdlQnl0ZUNvdW50IjogMTIxMzU5NywKICAgICJwYWNrYWdlTWFuaWZlc3RTaGEyNTYiOiAic2hhMjU2OmM3NGQ3MWMxMTE1YjViMTIyZDNkMTJlNTYwMTQwMDJiZDE1MjAxYzA1YWYyNWI3ZDAyN2U4ZDlhZDg4ZjcxNzQiLAogICAgInNvdXJjZUhlYWQiOiAiNTQ4NjcyYWU5OWNkNDA2ODA1ZjBjOGNhNTc2Y2M2NTBiYWY3ZWQxOCIsCiAgICAicHVibGljSHRtbEdpdEJsb2IiOiAiMGRhZWRmNjFmN2UxOWFmMDk1ZjRkYjVmYzQ3NTYzYTljZDc4NjgzNyIsCiAgICAicHVibGljT3JjaGVzdHJhdG9yR2l0QmxvYiI6ICIyYjBhOTE2YjNhNmQxMWRhODQzMTY5MjVmOGFiZDhhM2ExNDQ3NDQ1IiwKICAgICJmdW5jdGlvbmFsQ3NzR2l0QmxvYiI6ICI0ODExNDg0MTZhOGQwNDY2ZTc2YzRjYjJlY2E3YTY3ZDg5MzJhMjQyIiwKICAgICJwdWJsaWNTaGVsbENzc0dpdEJsb2IiOiAiZjIwOGI3ZjExMDk2YTdiZjVkYTI4MjIyNjkwM2FjNjM0YzFlYWIwMSIKICB9LAogICJzZXJ2ZWRGaWxlU2V0TGF3IjogewogICAgImV4YWN0RmlsZUNvdW50IjogMywKICAgICJleHRlcm5hbFJ1bnRpbWVSZXF1ZXN0Q291bnRBbGxvd2VkIjogMCwKICAgICJtdXRhYmxlTWFpbkRlcGVuZGVuY3lDb3VudEFsbG93ZWQiOiAwLAogICAgInVuZGVjbGFyZWRSdW50aW1lRGVwZW5kZW5jeUNvdW50QWxsb3dlZCI6IDAsCiAgICAic2VydmljZVdvcmtlckFsbG93ZWQiOiBmYWxzZQogIH0sCiAgInNlcnZlZEZpbGVzIjogWwogICAgewogICAgICAicmVsYXRpdmVQYXRoIjogImluZGV4Lmh0bWwiLAogICAgICAicm9sZSI6ICJFWEFDVF9WQUxJREFURURfU0VMRl9DT05UQUlORURfQ0FORElEQVRFIiwKICAgICAgInJ1bnRpbWVEZXBlbmRlbmN5IjogdHJ1ZSwKICAgICAgImJ5dGVDb3VudCI6IDEyMTM1OTcsCiAgICAgICJjb250ZW50U2hhMjU2IjogInNoYTI1NjozMDIwMTU0MzYxNTIzY2YxOTExM2U0Yzc1OWMyMzRhNmM3NGZmNWE0OTNiOGU0NzEyNGNhNTk0NzBkYTdhMjM0IiwKICAgICAgImdpdEJsb2JTaGExIjogImM1MTI3ZTJkNGQ5ZDM1NTgyMzBhOGVjY2Q3NTdkYWRlNzRkNmQ4YzMiCiAgICB9LAogICAgewogICAgICAicmVsYXRpdmVQYXRoIjogImRldmljZS1ldmlkZW5jZS1yZWNlaXB0LnNjaGVtYS5qc29uIiwKICAgICAgInJvbGUiOiAiUEhZU0lDQUxfU0VTU0lPTl9OT1JNQUxJWkVEX0VWSURFTkNFX1NDSEVNQSIsCiAgICAgICJydW50aW1lRGVwZW5kZW5jeSI6IGZhbHNlLAogICAgICAiYnl0ZUNvdW50IjogNDU4NiwKICAgICAgImNvbnRlbnRTaGEyNTYiOiAic2hhMjU2OjA0Y2U1ZWM4NmYxMDJmYjc2NDZiMDJhZDE5YTNmODYyYjhlNjM3MGRjZGM5NzFkYzI1MmQ2YmM2MDdlM2QxOGEiLAogICAgICAiZ2l0QmxvYlNoYTEiOiAiOTg3MjY4ZjM4ZmM4YjZkYjZmMTliOTgyY2M4Mzg2NDM5YWEwZGU0OCIKICAgIH0sCiAgICB7CiAgICAgICJyZWxhdGl2ZVBhdGgiOiAicHJldmlldy1tYW5pZmVzdC5qc29uIiwKICAgICAgInJvbGUiOiAiU0VSVkVEX0ZJTEVfQU5EX0NBTkRJREFURV9JREVOVElUWV9NQU5JRkVTVCIsCiAgICAgICJydW50aW1lRGVwZW5kZW5jeSI6IGZhbHNlLAogICAgICAiaWRlbnRpdHlDbGFzcyI6ICJDQU5PTklDQUxfTUFOSUZFU1RfUEFZTE9BRF9TSEEyNTZfUExVU19SRVBPU0lUT1JZX0dJVF9CTE9CX0NVU1RPRFkiLAogICAgICAiY29udGVudElkZW50aXR5UmVmZXJlbmNlIjogIiMvc2VsZklkZW50aXR5IgogICAgfQogIF0sCiAgImlkZW50aXR5RXhwb3N1cmUiOiBbCiAgICB7CiAgICAgICJyZXF1aXJlbWVudCI6ICJOT05fUFJPRFVDVElPTl9MQUJFTCIsCiAgICAgICJzdXJmYWNlIjogImluZGV4Lmh0bWwgc2V0dXAgdGV4dCBhbmQgbWFuaWZlc3Qgbm9uUHJvZHVjdGlvbj10cnVlIgogICAgfSwKICAgIHsKICAgICAgInJlcXVpcmVtZW50IjogIkNBTkRJREFURV9JRCIsCiAgICAgICJzdXJmYWNlIjogInByZXZpZXctbWFuaWZlc3QuanNvbiBhbmQgUDcgaGFuZG9mZiIKICAgIH0sCiAgICB7CiAgICAgICJyZXF1aXJlbWVudCI6ICJQQUNLQUdFX1NIQTI1NiIsCiAgICAgICJzdXJmYWNlIjogImhhc2hlZCBVUkwgcGF0aCBhbmQgcHJldmlldy1tYW5pZmVzdC5qc29uIgogICAgfSwKICAgIHsKICAgICAgInJlcXVpcmVtZW50IjogIlBBQ0tBR0VfSEVBRCIsCiAgICAgICJzdXJmYWNlIjogImluZGV4Lmh0bWwgZW1iZWRkZWQgcGFja2FnZSBtZXRhZGF0YSBhbmQgcHJldmlldy1tYW5pZmVzdC5qc29uIgogICAgfSwKICAgIHsKICAgICAgInJlcXVpcmVtZW50IjogIlNPVVJDRV9IRUFEIiwKICAgICAgInN1cmZhY2UiOiAiaW5kZXguaHRtbCBlbWJlZGRlZCBwYWNrYWdlIG1ldGFkYXRhIGFuZCBwcmV2aWV3LW1hbmlmZXN0Lmpzb24iCiAgICB9LAogICAgewogICAgICAicmVxdWlyZW1lbnQiOiAiVEVTVF9TRVNTSU9OX0lERU5USUZJRVIiLAogICAgICAic3VyZmFjZSI6ICJpbmRleC5odG1sIGdlbmVyYXRlZCBldmlkZW5jZUlkIGFuZCBub3JtYWxpemVkIHJlY2VpcHQgc2Vzc2lvbklkZW50aWZpZXIiCiAgICB9CiAgXSwKICAiZGVsaXZlcnlJbnRlbnQiOiB7CiAgICAiaHR0cHNSZXF1aXJlZCI6IHRydWUsCiAgICAiY2FjaGVDb250cm9sIjogInB1YmxpYywgbWF4LWFnZT0zMTUzNjAwMCwgaW1tdXRhYmxlIiwKICAgICJ4Um9ib3RzVGFnIjogIm5vaW5kZXgsIG5vZm9sbG93LCBub2FyY2hpdmUiLAogICAgInB1YmxpY2F0aW9uQ29uZmlndXJhdGlvbkNyZWF0ZWQiOiBmYWxzZSwKICAgICJuZXR3b3JrUHVibGljYXRpb25QZXJmb3JtZWQiOiBmYWxzZSwKICAgICJwcmV2aWV3VXJsSXNzdWVkIjogZmFsc2UKICB9LAogICJib3VuZGFyaWVzIjogewogICAgInNob3dyb29tTXV0YXRlZCI6IGZhbHNlLAogICAgInB1YmxpY0xpdmVIRWFydGhDaGFuZ2VkIjogZmFsc2UsCiAgICAibWFpbkNoYW5nZWQiOiBmYWxzZSwKICAgICJyZWNvdmVyeVN0YWNrTWVyZ2VkIjogZmFsc2UsCiAgICAicHJvZHVjdGlvbkRlcGxveW1lbnQiOiBmYWxzZSwKICAgICJwaHlzaWNhbFJlZmVyZW5jZURldmljZUV4ZWN1dGVkIjogZmFsc2UsCiAgICAiYnJvYWRlck1vYmlsZUV4ZWN1dGVkIjogZmFsc2UsCiAgICAicnVuOEVQYXNzQ2xvc2VkIjogZmFsc2UKICB9Cn0K', 'base64').toString('utf8');

fs.mkdirSync(OUTPUT_DIRECTORY, { recursive: true });
const control = evaluateHEarthRun8ER3F2P2Control();
assert(control.eligible === true, `P2_CONTROL_REJECTED:${control.issues.join(',')}`);
assert(H_EARTH_RUN_8E_R3F2_P1_CONTRACT.currentStatus === 'PASS_CLOSED', 'P2_P1_NOT_PASS_CLOSED');

const built = await buildHEarthRun8ER3F2SignedOfflinePackage({
  outputDirectory: OUTPUT_DIRECTORY,
  packageHead: H_EARTH_RUN_8E_R3F2_P2_CONTROL.candidateIdentity.packageHead
});
const packageBytes = Buffer.from(built.packageDocument, 'utf8');
assert(packageBytes.length === 1213597, 'P2_BUILT_PACKAGE_BYTE_COUNT_MISMATCH');
assert(sha256(packageBytes) === H_EARTH_RUN_8E_R3F2_P2_CONTROL.candidateIdentity.packageSha256, 'P2_BUILT_PACKAGE_SHA256_MISMATCH');
assert(gitBlobSha1(packageBytes) === 'c5127e2d4d9d3558230a8eccd757dade74d6d8c3', 'P2_BUILT_PACKAGE_GIT_BLOB_MISMATCH');
assert(!/<script\b[^>]*\bsrc\s*=/i.test(built.packageDocument), 'P2_EXTERNAL_SCRIPT_REFERENCE_PRESENT');
assert(!/<link\b[^>]*\bhref\s*=/i.test(built.packageDocument), 'P2_EXTERNAL_STYLESHEET_REFERENCE_PRESENT');
assert(!/<iframe\b[^>]*\bsrc\s*=/i.test(built.packageDocument), 'P2_EXTERNAL_IFRAME_REFERENCE_PRESENT');
assert(!/\bfetch\s*\(/.test(built.packageDocument), 'P2_RUNTIME_FETCH_PRESENT');

fs.mkdirSync(PREVIEW_ROOT, { recursive: true });
fs.writeFileSync(path.join(PREVIEW_ROOT, 'index.html'), packageBytes);
fs.writeFileSync(path.join(PREVIEW_ROOT, 'preview-manifest.json'), MANIFEST_TEXT);
fs.writeFileSync(path.join(PREVIEW_ROOT, 'device-evidence-receipt.schema.json'), SCHEMA_TEXT);

const expectedFiles = H_EARTH_RUN_8E_R3F2_P2_CONTROL.materializedPreviewTree.files;
const actualNames = fs.readdirSync(PREVIEW_ROOT).sort();
assert(JSON.stringify(actualNames) === JSON.stringify(expectedFiles.map((file) => file.relativePath).sort()), 'P2_PREVIEW_TREE_FILE_SET_MISMATCH');
const actualFiles = expectedFiles.map((expected) => {
  const repositoryPath = path.join(PREVIEW_ROOT, expected.relativePath);
  const bytes = fs.readFileSync(repositoryPath);
  const actual = {
    relativePath: expected.relativePath,
    repositoryPath: `/${repositoryPath}`,
    byteCount: bytes.length,
    contentSha256: sha256(bytes),
    gitBlobSha1: gitBlobSha1(bytes)
  };
  assert(actual.byteCount === expected.byteCount, `P2_FILE_BYTE_COUNT_MISMATCH:${expected.relativePath}`);
  assert(actual.contentSha256 === expected.contentSha256, `P2_FILE_SHA256_MISMATCH:${expected.relativePath}`);
  assert(actual.gitBlobSha1 === expected.gitBlobSha1, `P2_FILE_GIT_BLOB_MISMATCH:${expected.relativePath}`);
  return actual;
});

const manifest = JSON.parse(MANIFEST_TEXT);
const { selfIdentity, ...manifestPayload } = manifest;
assert(sha256(Buffer.from(stable(manifestPayload))) === selfIdentity.canonicalPayloadSha256, 'P2_MANIFEST_CANONICAL_PAYLOAD_DIGEST_MISMATCH');
assert(manifest.occurrenceClass === 'MATERIALIZED_NOT_PUBLISHED' && manifest.nonProduction === true, 'P2_MANIFEST_OCCURRENCE_CLASS_INVALID');
assert(manifest.servedFileSetLaw.exactFileCount === 3, 'P2_MANIFEST_FILE_COUNT_INVALID');
assert(manifest.servedFileSetLaw.externalRuntimeRequestCountAllowed === 0, 'P2_MANIFEST_EXTERNAL_REQUEST_LAW_INVALID');
assert(manifest.deliveryIntent.publicationConfigurationCreated === false && manifest.deliveryIntent.networkPublicationPerformed === false && manifest.deliveryIntent.previewUrlIssued === false, 'P2_MANIFEST_PUBLICATION_BOUNDARY_INVALID');
const schema = JSON.parse(SCHEMA_TEXT);
assert(JSON.stringify(schema.required) === JSON.stringify(H_EARTH_RUN_8E_R3F2_P1_CONTRACT.deviceEvidenceReceiptRequiredFields), 'P2_SCHEMA_REQUIRED_FIELDS_MISMATCH');
assert(schema['x-h-earth-boundaries'].physicalAcceptanceEmbedded === false, 'P2_SCHEMA_PHYSICAL_ACCEPTANCE_EMBEDDED');

const registry = loadHEarthRepositoryRegistryValidatorDependencies();
assert(registry.identityVerified === true, 'P2_REGISTRY_IDENTITY_FAILED');
const registeredNode = registry.registryFacade.getHEarthRepositoryRegistryNode(H_EARTH_RUN_8E_R3F2_P2_NODE.nodeId);
assert(registeredNode?.nodeId === H_EARTH_RUN_8E_R3F2_P2_NODE.nodeId, 'P2_REGISTRY_NODE_MISSING');
for (const repositoryPath of H_EARTH_RUN_8E_R3F2_P2_PATHS) {
  const resolution = registry.registryFacade.resolveHEarthRepositoryRegistryPath(repositoryPath);
  assert(resolution?.resolved === true, `P2_REGISTRY_PATH_UNRESOLVED:${repositoryPath}`);
}

const receipt = {
  receiptType: 'H_EARTH_RUN_8E_R3F2_P2_MATERIALIZATION_VALIDATION_RECEIPT',
  eligible: true,
  status: 'RUN_8E_R3F2_P2_MATERIALIZATION_VALIDATION_PASS',
  checkpointId: H_EARTH_RUN_8E_R3F2_P2_CONTROL.checkpointId,
  branch: H_EARTH_RUN_8E_R3F2_P2_CONTROL.branch,
  eventHead: process.env.GITHUB_SHA ?? null,
  materializedHead: process.env.H_EARTH_RUN8E_R3F2_P2_MATERIALIZED_HEAD ?? null,
  predecessor: H_EARTH_RUN_8E_R3F2_P2_CONTROL.predecessor,
  candidateIdentity: H_EARTH_RUN_8E_R3F2_P2_CONTROL.candidateIdentity,
  previewTree: {
    root: `/${PREVIEW_ROOT}/`,
    exactFileCount: actualFiles.length,
    files: actualFiles,
    manifestCanonicalPayloadSha256: manifest.selfIdentity.canonicalPayloadSha256,
    normalizedReceiptRequiredFieldCount: schema.required.length,
    externalRuntimeRequestCount: 0,
    mutableMainDependencyCount: 0,
    undeclaredRuntimeDependencyCount: 0
  },
  registryAudit: {
    identityVerified: registry.identityVerified,
    nodeId: registeredNode.nodeId,
    registeredPathCount: H_EARTH_RUN_8E_R3F2_P2_PATHS.length,
    allPathsResolved: true,
    loaderReadOnly: registry.boundary.readOnly
  },
  boundaries: {
    previewFilesMaterialized: true,
    deploymentConfigurationCreated: false,
    networkPublicationPerformed: false,
    previewUrlIssued: false,
    showroomMutated: false,
    publicLiveHEarthChanged: false,
    mainChanged: false,
    recoveryStackMerged: false,
    productionDeployment: false,
    physicalReferenceDeviceExecuted: false,
    broaderMobileExecuted: false,
    run8EPassClosed: false
  },
  nextCheckpoint: H_EARTH_RUN_8E_R3F2_P2_CONTROL.nextCheckpoint,
  stoppingBoundary: H_EARTH_RUN_8E_R3F2_P2_CONTROL.stoppingBoundary,
  issues: []
};
fs.writeFileSync(path.join(OUTPUT_DIRECTORY, 'h-earth.run8e-r3f2-p2.materialization-validation.receipt.json'), `${JSON.stringify(receipt, null, 2)}\n`);
console.log(JSON.stringify(receipt, null, 2));
