import{readFile}from'node:fs/promises';import{createHash}from'node:crypto';import{pathToFileURL}from'node:url';
const [root,file]=process.argv.slice(2);if(!root||!file)throw new Error('ROOT_AND_RGBA_REQUIRED');const M=await import(pathToFileURL(root+'/h-earth-3d/environment/h-earth.semantic-material-field.phase2.js').href+'?q='+Date.now()),b=new Uint8Array(await readFile(file)),W=1024,H=1024,D={xmin:-256,xmax:256,zmin:-320,zmax:64};if(b.length!==W*H*4)throw new Error('BYTE_LENGTH');
const sha=createHash('sha256').update(b).digest('hex'),ix=(x,z)=>[Math.round((x-D.xmin)/(D.xmax-D.xmin)*(W-1)),Math.round((z-D.zmin)/(D.zmax-D.zmin)*(H-1))],px=(x,z)=>{const[u,v]=ix(x,z),i=(v*W+u)*4;return[...b.slice(i,i+4)]};
const WIT=[['WET_SHORELINE_SAND',0,-82],['DRY_SAND_BACKSHORE',0,-104],['LOWLAND_SOIL_GROUNDCOVER',-92,-152],['DRAINAGE_SEDIMENT_MOIST_GROUND',-48,-150],['FOOTHILL_SOIL_STONE',-42,-184],['EXPOSED_MOUNTAIN_ROCK',86,-235]];
const witnesses=WIT.map(([family,x,z])=>{const s=M.sampleHEarthPhase2SemanticMaterial(x,z),rgba=px(x,z),expected=[...s.rgb.map(v=>Math.round(Math.max(0,Math.min(1,v))*255)),Math.round(s.wetness*255)],delta=Math.max(...rgba.map((v,i)=>Math.abs(v-expected[i])));return{family,x,z,rgba,expected,maxByteDelta:delta}});
const d=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1],a[2]-b[2]),seps=[];for(let i=0;i<witnesses.length;i++)for(let j=i+1;j<witnesses.length;j++)seps.push(d(witnesses[i].rgba,witnesses[j].rgba));
const transitions=[...Array(33)].map((_,i)=>px(0,-82-i*3)),transitionMax=Math.max(...transitions.slice(1).map((v,i)=>d(v,transitions[i])));
const spatial=[2,4,8,16,32].map(world=>{let sum=0,n=0;for(const [,x,z]of WIT){sum+=d(px(x,z),px(x+world,z));n++;}return{worldUnits:world,meanWitnessRgbDistance:sum/n}});
let data=b,w=W,h=H,mips=[];while(w>=32&&h>=32){let s=0,s2=0,n=0;for(let i=0;i<data.length;i+=4){const l=.2126*data[i]+.7152*data[i+1]+.0722*data[i+2];s+=l;s2+=l*l;n++;}const mean=s/n;mips.push({width:w,height:h,luminanceStd:Math.sqrt(s2/n-mean*mean)});const nw=w>>1,nh=h>>1,next=new Uint8Array(nw*nh*4);for(let y=0;y<nh;y++)for(let x=0;x<nw;x++)for(let k=0;k<4;k++){let q=0;for(let yy=0;yy<2;yy++)for(let xx=0;xx<2;xx++)q+=data[((y*2+yy)*w+(x*2+xx))*4+k];next[(y*nw+x)*4+k]=Math.round(q/4)}data=next;w=nw;h=nh;}
const issues=[];if(witnesses.some(x=>x.maxByteDelta>1))issues.push('CLASSIFIER_BAKE_CORRESPONDENCE');if(Math.min(...seps)<12)issues.push('FAMILY_SEPARATION_WEAK');if(transitionMax>100)issues.push('TRANSITION_DISCONTINUITY');if(mips.at(-1).luminanceStd<2)issues.push('MIP_CONTRAST_COLLAPSE');
console.log(JSON.stringify({receiptType:'H_EARTH_PHASE2_SEMANTIC_MATERIAL_ASSET_QUALIFICATION_v1',eligible:issues.length===0,sha256:sha,byteLength:b.length,witnesses,minimumWitnessRgbSeparation:Math.min(...seps),transitionMaximumStep:transitionMax,spatial,mips,issues},null,2));if(issues.length)process.exitCode=1;
