import{pathToFileURL}from'node:url';const root=process.argv[2]||'.',imp=p=>import(pathToFileURL(root+'/'+p).href+'?m='+Date.now());
const C=await imp('h-earth-3d/terrain/h-earth.terrain-field.js'),R=await imp('h-earth-3d/terrain/h-earth.successor-terrain-field.run8b.js'),L=await imp('showroom/globe/h-earth/render/landscape-preview.js');
const preview=L.H_EARTH_FUNCTIONAL_LANDSCAPE_NEUTRAL_PREVIEW,g=preview.componentResults.terrain.primitive.geometry;
const witnesses=[['MOUNTAIN',86,-235],['FOOTHILL',-12,-176],['VALLEY_DRAINAGE',2,-198],['PLAIN_LOWLAND',-92,-152],['COAST_SHORE',0,-96]];
const bary=(a,b,c,x,z)=>{const d=(b.z-c.z)*(a.x-c.x)+(c.x-b.x)*(a.z-c.z),u=((b.z-c.z)*(x-c.x)+(c.x-b.x)*(z-c.z))/d,v=((c.z-a.z)*(x-c.x)+(a.x-c.x)*(z-c.z))/d,w=1-u-v;return[u,v,w,a.y*u+b.y*v+c.y*w]};
const presented=(x,z)=>{for(let o=0;o<g.indices.length;o+=3){const q=g.indices.slice(o,o+3).map(i=>g.vertices[i]),[a,b,c]=q;if(x<Math.min(a.x,b.x,c.x)-1e-8||x>Math.max(a.x,b.x,c.x)+1e-8||z<Math.min(a.z,b.z,c.z)-1e-8||z>Math.max(a.z,b.z,c.z)+1e-8)continue;const [u,v,w,y]=bary(a,b,c,x,z);if(u>=-1e-8&&v>=-1e-8&&w>=-1e-8)return y;}return null};
const localRelief=(x,z,r)=>{const vals=[];for(const [dx,dz]of [[0,0],[r,0],[-r,0],[0,r],[0,-r],[r,r],[r,-r],[-r,r],[-r,-r]])vals.push(C.sampleHEarthTerrainElevation(x+dx,z+dz));return Math.max(...vals)-Math.min(...vals)};
const rows=witnesses.map(([terrainClass,x,z])=>{const c=C.sampleHEarthTerrainField(x,z),r=R.sampleHEarthRun8BSuccessorTerrainField(x,z),p=presented(x,z);return{terrainClass,x,z,canonicalElevation:c.elevation,run8bElevation:r.elevation,canonicalToRun8bDelta:r.elevation-c.elevation,presentedElevation:p,run8bToPresentedDelta:p-r.elevation,slope:c.slope,curvature:c.curvature,localRelief:{r8:localRelief(x,z,8),r16:localRelief(x,z,16),r32:localRelief(x,z,32)},regionalArticulation:{landformClass:r.regionalArticulation.landformClass,ridge:r.regionalArticulation.ridgeSignal,valley:r.regionalArticulation.valleySignal,foothill:r.regionalArticulation.foothillSignal,pass:r.regionalArticulation.passSignal,watershed:r.regionalArticulation.watershedSignal,gradient:r.regionalArticulation.gradientMagnitude}}});
console.log(JSON.stringify({receiptType:'H_EARTH_PHASE1_FIVE_CLASS_RELIEF_MEASUREMENT_v1',adaptiveCBaseline:true,rows,productMutation:false},null,2));
