import{readFile}from'node:fs/promises';import{createHash}from'node:crypto';
const file=process.argv[2];if(!file)throw new Error('RGBA_FILE_REQUIRED');const b=new Uint8Array(await readFile(file)),W=1024,H=1024;if(b.length!==W*H*4)throw new Error('BYTE_LENGTH_INVALID');
const expected='28f801f8e5f7b82433f3e0f742cb8292d918ff33b1696c524d0762830c42e15f',sha=createHash('sha256').update(b).digest('hex');if(sha!==expected)throw new Error('SHA_MISMATCH:'+sha);
const ch=[0,1,2,3].map(k=>{let n=0,s=0,s2=0,min=255,max=0;const hist=new Set();for(let i=k;i<b.length;i+=4){const v=b[i];n++;s+=v;s2+=v*v;min=Math.min(min,v);max=Math.max(max,v);hist.add(v)}const mean=s/n;return{min,max,mean,std:Math.sqrt(s2/n-mean*mean),unique:hist.size}});
const px=(x,y)=>{const i=(y*W+x)*4;return[b[i],b[i+1],b[i+2],b[i+3]]};
const domain={xmin:-256,xmax:256,zmin:-320,zmax:64},uv=(x,z)=>[Math.max(0,Math.min(W-1,Math.round((x-domain.xmin)/(domain.xmax-domain.xmin)*(W-1)))),Math.max(0,Math.min(H-1,Math.round((z-domain.zmin)/(domain.zmax-domain.zmin)*(H-1))))];
const witnesses=[['COAST',0,-96],['LOWLAND',-92,-152],['DRAINAGE',-48,-150],['FOOTHILL',-42,-184],['MOUNTAIN',86,-235]].map(([role,x,z])=>{const[u,v]=uv(x,z);return{role,x,z,texel:[u,v],rgba:px(u,v)}});
const scales=[2,4,8,16,32].map(world=>{const dx=Math.max(1,Math.round(world/(domain.xmax-domain.xmin)*(W-1))),dz=Math.max(1,Math.round(world/(domain.zmax-domain.zmin)*(H-1)));let sum=0,n=0,max=0;for(let y=0;y<H;y+=32)for(let x=0;x<W;x+=32){const a=px(x,y),q=px(Math.min(W-1,x+dx),Math.min(H-1,y+dz));const d=Math.hypot(a[0]-q[0],a[1]-q[1],a[2]-q[2]);sum+=d;max=Math.max(max,d);n++;}return{worldUnits:world,meanRgbDistance:sum/n,maxRgbDistance:max}});
const mips=[];let data=b,w=W,h=H,level=0;while(w>=32&&h>=32){let s=0,s2=0,n=0;for(let i=0;i<data.length;i+=4){const lum=.2126*data[i]+.7152*data[i+1]+.0722*data[i+2];s+=lum;s2+=lum*lum;n++;}const mean=s/n;mips.push({level,width:w,height:h,luminanceMean:mean,luminanceStd:Math.sqrt(s2/n-mean*mean)});const nw=Math.floor(w/2),nh=Math.floor(h/2),next=new Uint8Array(nw*nh*4);for(let y=0;y<nh;y++)for(let x=0;x<nw;x++)for(let k=0;k<4;k++){let q=0;for(let yy=0;yy<2;yy++)for(let xx=0;xx<2;xx++)q+=data[((y*2+yy)*w+(x*2+xx))*4+k];next[(y*nw+x)*4+k]=Math.round(q/4);}data=next;w=nw;h=nh;level++;}
console.log(JSON.stringify({receiptType:'H_EARTH_PHASE2_BAKED_MATERIAL_FIELD_MEASUREMENT_v1',sha256:sha,channels:{r:ch[0],g:ch[1],b:ch[2],a:ch[3]},witnesses,spatialRgbVariance:scales,mips},null,2));
