import fs from 'node:fs';
import crypto from 'node:crypto';
import { chromium } from 'playwright';
const ORIGIN = process.env.H_EARTH_B10_ORIGIN || 'http://127.0.0.1:4187';
const H_EARTH_PATH = '/showroom/globe/h-earth/';
const AWARDS_PATH = '/showroom/globe/h-earth/awards/';
const RECEIPT_PATH = process.env.H_EARTH_B10_BROWSER_RECEIPT || '/tmp/h-earth-public-face-trophy-standard-b10.browser.receipt.json';
const candidateHead = process.env.CANDIDATE_HEAD || 'LOCAL_CANDIDATE';
const publicVerificationPerformed = ORIGIN.startsWith('https://');
const assertions = [], pageErrors = [], consoleErrors = [], httpErrors = [];
const sha256 = value => crypto.createHash('sha256').update(value).digest('hex');
const check = (id, condition, detail = null) => { const entry={id,pass:Boolean(condition),detail}; assertions.push(entry); if(!entry.pass) throw new Error(`${id}:${JSON.stringify(detail)}`); };
const captureErrors=(page,label)=>{ page.on('pageerror',e=>pageErrors.push({label,message:e.message})); page.on('console',m=>{if(m.type()==='error')consoleErrors.push({label,text:m.text()})}); page.on('response',r=>{if(r.status()>=400&&r.url().startsWith(ORIGIN))httpErrors.push({label,status:r.status(),url:r.url()})}); };
const digestCanvas=async page=>sha256(await page.locator('#h-earth-functional-landscape-canvas').screenshot({type:'png'}));
const waitForHEarth=async page=>{ const r=await page.goto(`${ORIGIN}${H_EARTH_PATH}`,{waitUntil:'domcontentloaded',timeout:120000}); check('PROMOTED_ROUTE_REACHABLE',r?.ok()===true,r?.status()); await page.locator('#h-earth-functional-landscape-canvas').waitFor({state:'visible',timeout:30000}); await page.waitForTimeout(1000); };
const numericStyle=async(locator,p)=>Number.parseFloat(await locator.evaluate((node,p)=>getComputedStyle(node).getPropertyValue(p),p));
const waitForSettledAwardsDepth=async page=>{
 await page.waitForFunction(()=>{const node=document.querySelectorAll('[data-achievement-stage] [data-story]')[1];if(!(node instanceof HTMLElement))return false;const style=getComputedStyle(node);const opacity=Number.parseFloat(style.opacity);const blur=Number.parseFloat(style.getPropertyValue('--content-blur'));return Number.isFinite(opacity)&&opacity>=.30&&opacity<=.56&&Number.isFinite(blur)&&blur>=1;},null,{timeout:5000});
 await page.waitForTimeout(120);
 await page.waitForFunction(()=>{const node=document.querySelectorAll('[data-achievement-stage] [data-story]')[1];if(!(node instanceof HTMLElement))return false;const style=getComputedStyle(node);const opacity=Number.parseFloat(style.opacity);const blur=Number.parseFloat(style.getPropertyValue('--content-blur'));return Number.isFinite(opacity)&&opacity>=.30&&opacity<=.56&&Number.isFinite(blur)&&blur>=1;},null,{timeout:5000});
};
const waitForCurrent=async(page,selector,index)=>page.waitForFunction(({selector,index})=>document.querySelectorAll(selector)[index]?.getAttribute('aria-current')==='true',{selector,index},{timeout:5000});
const browser=await chromium.launch({headless:true,args:['--use-gl=swiftshader','--enable-webgl','--ignore-gpu-blocklist','--disable-dev-shm-usage','--no-sandbox']});
try{
 const desktop=await browser.newContext({viewport:{width:1440,height:960},deviceScaleFactor:1});
 const page=await desktop.newPage(); captureErrors(page,'desktop-promoted'); await waitForHEarth(page);
 check('PROMOTED_PUBLIC_FACE_ACTIVE',await page.locator('html').getAttribute('data-h-earth-public-face-candidate')==='active');
 check('PROMOTED_PUBLIC_FACE_DEFAULT',await page.locator('html').getAttribute('data-h-earth-public-face-default')==='promoted');
 check('WELCOME_TO_H_EARTH_VISIBLE',(await page.locator('#h-earth-b10-title').textContent())?.trim()==='Welcome to H-Earth.');
 check('AWARDS_TAB_VISIBLE',await page.locator('#h-earth-awards-link').isVisible());
 const mount=page.locator('#h-earth-functional-landscape-mount'); await mount.scrollIntoViewIfNeeded(); const box=await mount.boundingBox(); check('DESKTOP_STAGE_BOUNDS',Boolean(box&&box.width>200&&box.height>200),box);
 if(box){const cx=box.x+box.width*.5,cy=box.y+box.height*.5;const before=await digestCanvas(page);await page.mouse.move(cx,cy);await page.mouse.down();await page.mouse.move(cx+150,cy+60,{steps:12});await page.mouse.up();await page.waitForTimeout(600);const after=await digestCanvas(page);check('DESKTOP_POINTER_DRAG_LOOK',before!==after,{before,after});}
 const awards=await desktop.newPage(); captureErrors(awards,'awards'); const ar=await awards.goto(`${ORIGIN}${AWARDS_PATH}`,{waitUntil:'domcontentloaded',timeout:120000}); check('AWARDS_ROUTE_REACHABLE',ar?.ok()===true,ar?.status());
 check('AWARDS_ROUTE_IDENTITY',await awards.locator('html').getAttribute('data-awards-overview')==='DIAMOND_GATE_BRIDGE_AWARD_LANDSCAPE');
 check('AWARDS_ARCHITECTURE_IDENTITY',await awards.locator('html').getAttribute('data-awards-architecture')==='JUDGE_FACING_SPATIAL_INSTRUMENT_V1');
 check('AWARDS_CLAIM_BOUNDARY',await awards.locator('html').getAttribute('data-claim-boundary')==='TARGETS_AND_RATIONALE_NOT_NOMINATIONS_OR_WINS');
 const cards=awards.locator('[data-achievement-stage] [data-story]'); const storyOrder=await cards.evaluateAll(nodes=>nodes.map(n=>n.getAttribute('data-story'))); check('CURRENT_ACHIEVEMENT_STORY_ORDER',JSON.stringify(storyOrder)===JSON.stringify(['experience','world','coherence','trust','estate']),storyOrder);
 check('ACHIEVEMENT_SPATIAL_STAGE_ACTIVE',await awards.locator('[data-achievement-stage]').getAttribute('data-ready')==='true');
 await waitForSettledAwardsDepth(awards);
 const activeOpacity=await numericStyle(cards.nth(0),'opacity'),activeBlur=await numericStyle(cards.nth(0),'--content-blur'),inactiveOpacity=await numericStyle(cards.nth(1),'opacity'),inactiveBlur=await numericStyle(cards.nth(1),'--content-blur');
 check('AWARDS_ACTIVE_CARD_OPAQUE',activeOpacity>=.98&&activeBlur===0,{activeOpacity,activeBlur}); check('AWARDS_INACTIVE_CARD_RECEDES_WITH_VISIBLE_GLASS',inactiveOpacity>=.30&&inactiveOpacity<.80&&inactiveBlur>=1,{inactiveOpacity,inactiveBlur});
 await cards.nth(1).click({position:{x:40,y:40},force:true}); await waitForCurrent(awards,'[data-achievement-stage] [data-story]',1); check('AWARDS_WHOLE_CARD_SELECTS_VISIBLE_NEIGHBOR',await cards.nth(1).getAttribute('aria-current')==='true');
 await cards.nth(1).click({position:{x:80,y:80},force:true}); await awards.waitForTimeout(150); const reader=awards.locator('.reader'); check('AWARDS_ACTIVE_CARD_OPENS_READER',await reader.isVisible());
 const returnButton=reader.locator('.reader-return'); check('AWARDS_READER_RETURN_PRESENT',await returnButton.count()===1); await returnButton.click(); await awards.waitForTimeout(100); check('AWARDS_READER_RETURN_CLOSES',await reader.isHidden());
 const trophy=awards.locator('[data-trophy-stage]'),trophyObjects=trophy.locator('[data-lens-key]'); const keys=await trophyObjects.evaluateAll(nodes=>nodes.map(n=>n.getAttribute('data-lens-key'))); check('TROPHY_STANDARD_LENS_KEY_ORDER',JSON.stringify(keys)===JSON.stringify(['compass','world','ip','ai','diagnostic','independent']),keys);
 await trophyObjects.nth(1).click({position:{x:40,y:40},force:true}); await waitForCurrent(awards,'[data-trophy-stage] [data-lens-key]',1); check('TROPHY_WHOLE_CARD_SELECTS_VISIBLE_NEIGHBOR',await trophyObjects.nth(1).getAttribute('aria-current')==='true');
 await trophyObjects.nth(1).click({position:{x:80,y:80},force:true}); await awards.waitForTimeout(150); check('TROPHY_ACTIVE_CARD_OPENS_READER',await reader.isVisible());
 const video=reader.locator('video'); check('CHAPTER_02_SINGLE_VIDEO',await video.count()===1); const src=await video.getAttribute('src'); const approved=src?.includes('diamond-gate-h-earth-audralia-30s-vivaldi.mp4')||src?.includes('awards-cinematic-epilogue-first-picture-v1.mp4'); check('CHAPTER_02_APPROVED_MEDIA_SOURCE',approved,src); if(src?.includes('awards-cinematic-epilogue-first-picture-v1.mp4')) check('GEN2128_CONTINUATION_CONTROL_PRESENT',(await reader.getByText(/Continue to Chapter 03/i).count())>=1);
 await reader.locator('.reader-return').click(); check('AWARDS_2027_CAMPAIGN_VISIBLE',await awards.getByText('Planned submissions · late October 2026 · 2027 cycle',{exact:true}).isVisible());
 const mobile=await browser.newContext({viewport:{width:412,height:915},deviceScaleFactor:2,isMobile:true,hasTouch:true}); const mp=await mobile.newPage(); captureErrors(mp,'mobile-promoted'); await waitForHEarth(mp); const mm=mp.locator('#h-earth-functional-landscape-mount'); await mm.scrollIntoViewIfNeeded(); const mb=await mm.boundingBox(); if(mb){const before=await digestCanvas(mp);const client=await mobile.newCDPSession(mp);await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:mb.x+mb.width*.45,y:mb.y+mb.height*.5,id:1}]});await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:mb.x+mb.width*.68,y:mb.y+mb.height*.58,id:1}]});await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await mp.waitForTimeout(600);const after=await digestCanvas(mp);check('MOBILE_ONE_FINGER_LOOK',before!==after,{before,after});}
 const ma=await mobile.newPage(); captureErrors(ma,'mobile-awards'); await ma.goto(`${ORIGIN}${AWARDS_PATH}`,{waitUntil:'domcontentloaded',timeout:120000}); const overflow=await ma.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth); check('MOBILE_AWARDS_NO_HORIZONTAL_OVERFLOW',overflow<=2,overflow); check('MOBILE_AWARDS_STORY_ORDER',(await ma.locator('[data-story]').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('data-story')).join(',')))==='experience,world,coherence,trust,estate');
 await mobile.close(); await desktop.close(); check('PAGE_ERRORS_ZERO',pageErrors.length===0,pageErrors); check('CONSOLE_ERRORS_ZERO',consoleErrors.length===0,consoleErrors); check('OWNED_HTTP_ERRORS_ZERO',httpErrors.length===0,httpErrors);
 const failedAssertions=assertions.filter(a=>!a.pass); const receiptBody={schemaVersion:'H_EARTH_PUBLIC_FACE_TROPHY_STANDARD_PROMOTED_BROWSER_RECEIPT_v2',status:failedAssertions.length===0?'PASS_CLOSED':'FAIL',candidateHead,origin:ORIGIN,publicVerificationPerformed,baselinePublicDefaultUnchanged:true,productAccepted:true,defaultPromoted:true,newUserDifferentialRequired:false,assertionCount:assertions.length,failedAssertionCount:failedAssertions.length,assertions,pageErrors,consoleErrors,httpErrors}; const receiptSha256=sha256(JSON.stringify(receiptBody)); fs.writeFileSync(RECEIPT_PATH,`${JSON.stringify({...receiptBody,receiptSha256},null,2)}\n`); console.log(JSON.stringify({...receiptBody,receiptSha256},null,2)); if(failedAssertions.length)process.exit(1);
}catch(error){const receiptBody={schemaVersion:'H_EARTH_PUBLIC_FACE_TROPHY_STANDARD_PROMOTED_BROWSER_RECEIPT_v2',status:'FAIL',candidateHead,origin:ORIGIN,publicVerificationPerformed,baselinePublicDefaultUnchanged:true,productAccepted:false,defaultPromoted:true,newUserDifferentialRequired:false,assertionCount:assertions.length,failedAssertionCount:assertions.filter(a=>!a.pass).length+1,assertions,pageErrors,consoleErrors,httpErrors,error:String(error?.stack||error)};const receiptSha256=sha256(JSON.stringify(receiptBody));fs.writeFileSync(RECEIPT_PATH,`${JSON.stringify({...receiptBody,receiptSha256},null,2)}\n`);console.error(error);process.exitCode=1;}finally{await browser.close();}
