#!/usr/bin/env node
import fs from"node:fs";import path from"node:path";import crypto from"node:crypto";import{pathToFileURL}from"node:url";
const A=process.argv.slice(2),v=(k,d=null)=>{const i=A.indexOf(k);return i>=0&&A[i+1]?A[i+1]:d},OUT=v("--output"),LOCAL=A.includes("--local-preflight"),R=process.cwd(),bad=[],checks=[];
const add=(n,p,d="")=>{checks.push({name:n,pass:p,detail:d});if(!p)bad.push(d?`${n}:${d}`:n)},txt=r=>fs.readFileSync(path.join(R,r),"utf8"),js=r=>JSON.parse(txt(r)),sha=r=>crypto.createHash("sha256").update(fs.readFileSync(path.join(R,r))).digest("hex"),s=x=>typeof x==="string"&&x.trim();
let C,S,M,X,FV,FI,MAN;
try{C=js("validation/claims/validation-classes.v1.json");S=js("validation/standards/standards-registry.v1.json");M=js("validation/master-validation-register.v1.json");js("validation/schemas/asset-validation-record.schema.v1.json");X=["lrpv1","imi","general-software"].map(n=>js(`validation/crosswalks/${n}.v1.json`));FV=js("validation/harness/fixtures/valid-record.v1.json");FI=js("validation/harness/fixtures/invalid-overclaim.v1.json");MAN=js("validation/manifest.v1.json");add("LOAD",true)}catch(e){add("LOAD",false,e.message)}
const K=new Set(C?.validationClasses?.map(x=>x.id)||[]),ST=new Set(C?.statuses||[]),ES=new Set(C?.evidenceSourceClasses||[]),SI=new Set(S?.standards?.map(x=>x.standardId)||[]),AI=new Set(M?.assets?.map(x=>x.assetId)||[]);
const EK=["IDENTITY_BOUND","IMPLEMENTATION_VERIFIED","SPECIFICATION_CONFORMANT","EXTERNALLY_BENCHMARKED","INDEPENDENTLY_REPRODUCED","SECURITY_REVIEWED","EMPIRICALLY_VALIDATED","CERTIFIED_OR_ACCREDITED"];
add("REGISTRIES",C?.schema==="ESTATE_VALIDATION_CLASS_REGISTRY_v1"&&S?.schema==="ESTATE_VALIDATION_STANDARDS_REGISTRY_v1"&&M?.schema==="ESTATE_MASTER_VALIDATION_REGISTER_v1");
add("CLASS_SET",K.size===EK.length&&EK.every(x=>K.has(x)));add("NO_GENERIC_VALIDATED",!ST.has("VALIDATED"));add("UNIQUE_IDS",SI.size===(S?.standards?.length||-1)&&AI.size===(M?.assets?.length||-1));
function audit(r,full=true){const q=[];for(const k of["assetId","assetName","assetClass","identity","claims","validation","limitations","evidenceRefs"])if(!(k in(r||{})))q.push(`MISSING:${k}`);if(!s(r?.assetId)||!s(r?.assetName)||!s(r?.assetClass))q.push("EMPTY_ID");if(!r?.identity||typeof r.identity!=="object"||Array.isArray(r.identity))q.push("BAD_IDENTITY");if(!Array.isArray(r?.claims)||!r.claims.length)q.push("NO_CLAIMS");if(!Array.isArray(r?.limitations)||!r.limitations.length)q.push("NO_LIMITS");const entries=Object.entries(r?.validation||{});if(full&&(entries.length!==K.size||[...K].some(k=>!(k in(r?.validation||{})))))q.push("INCOMPLETE_CLASS_SET");for(const[c,z]of entries){if(!K.has(c))q.push(`UNKNOWN_CLASS:${c}`);if(!ST.has(z?.status))q.push(`UNKNOWN_STATUS:${z?.status}`);const refs=z?.evidenceRefs||[],src=z?.evidenceSourceClasses||[];if(z?.status==="ESTABLISHED"&&!refs.length)q.push(`NO_EVIDENCE:${c}`);for(const e of src)if(!ES.has(e))q.push(`UNKNOWN_SOURCE:${e}`);if(c==="INDEPENDENTLY_REPRODUCED"&&z?.status==="ESTABLISHED"&&!src.some(e=>["EXTERNAL_INDEPENDENT_IMPLEMENTATION","EXTERNAL_INDEPENDENT_REVIEW"].includes(e)))q.push("FALSE_INDEPENDENCE");if(c==="SECURITY_REVIEWED"&&z?.status==="ESTABLISHED"&&!src.includes("EXTERNAL_INDEPENDENT_REVIEW"))q.push("FALSE_SECURITY_REVIEW");if(c==="CERTIFIED_OR_ACCREDITED"&&z?.status==="ESTABLISHED"&&!src.includes("ACCREDITED_BODY"))q.push("FALSE_CERTIFICATION")}return[...new Set(q)].sort()}
for(const r of M?.assets||[]){const q=audit(r);add(`ASSET:${r.assetId}`,!q.length,q.join(","))}const qv=audit(FV,false),qi=audit(FI,false);add("VALID_FIXTURE",!qv.length,qv.join(","));add("NEGATIVE_OVERCLAIM_REJECTED",qi.includes("FALSE_CERTIFICATION"),qi.join(","));
for(const x of X){add(`CROSSWALK:${x?.crosswalkId}`,x?.schema==="ESTATE_VALIDATION_CROSSWALK_v1");if(x?.assetId!=="MULTI_ASSET_SOFTWARE_REFERENCE")add(`CROSSWALK_ASSET:${x?.crosswalkId}`,AI.has(x?.assetId),x?.assetId);for(const m of x?.mappings||[])add(`STANDARD:${m.standardId}`,SI.has(m.standardId),m.standardId)}
add("STANDARD_TEXT_BOUNDARY",S?.registryBoundary==="STANDARD_IDENTIFIERS_AND_PUBLIC_SCOPE_DESCRIPTIONS_ONLY_NO_PROPRIETARY_STANDARD_TEXT_REPRODUCED");add("ANTI_OVERCLAIM",M?.globalBoundaries?.includes("NO_EXTERNAL_STANDARD_REFERENCE_MAY_BE_RELABELED_AS_CERTIFICATION")&&M?.globalBoundaries?.includes("NO_SOFTWARE_CONFORMANCE_RESULT_MAY_BE_RELABELED_AS_SCIENTIFIC_VALIDITY"));
const mf=MAN?.files||[],mp=new Set;add("MANIFEST",MAN?.schema==="ESTATE_VALIDATION_MANIFEST_v1"&&MAN?.fileCount===mf.length);for(const f of mf){if(!s(f?.path)||!/^[0-9a-f]{64}$/.test(f?.sha256||"")){add(`FILE:${f?.path||"?"}`,false,"MALFORMED");continue}if(mp.has(f.path)){add(`FILE:${f.path}`,false,"DUPLICATE");continue}mp.add(f.path);const p=path.join(R,f.path);if(!fs.existsSync(p)){add(`FILE:${f.path}`,false,"MISSING");continue}const x=sha(f.path);add(`FILE:${f.path}`,x===f.sha256,x===f.sha256?"":`EXPECTED_${f.sha256}_ACTUAL_${x}`)}
const req=["validation/README.md","validation/master-validation-register.v1.json","validation/standards/standards-registry.v1.json","validation/claims/validation-classes.v1.json","validation/schemas/asset-validation-record.schema.v1.json","validation/crosswalks/lrpv1.v1.json","validation/crosswalks/imi.v1.json","validation/crosswalks/general-software.v1.json","validation/harness/verify-estate-validation.v1.mjs","validation/harness/fixtures/valid-record.v1.json","validation/harness/fixtures/invalid-overclaim.v1.json","validation/reproduction/README.md","validation/threat-model/README.md"];add("MANIFEST_SET",req.length===mp.size&&req.every(x=>mp.has(x))&&!mp.has("validation/manifest.v1.json"));
let subjects=true;const sub=(n,p,d="")=>{add(`SUBJECT:${n}`,p,d);if(!p)subjects=false};
if(!LOCAL){try{const p=js("research/route-operator-platform-v1/IMI_PACKAGE_POINTER.json");sub("IMI_SHA",p?.zip_sha256==="0be0608fa9aab10d75eeba796530421e96efc7829364172e52f7925ca74d9c87",p?.zip_sha256||"MISSING")}catch(e){sub("IMI_SHA",false,e.message)}try{const r=txt("infrastructure/lineage-receipt-protocol-v1/README.md");sub("LRPV1",r.includes("LINEAGE_RECEIPT_PROTOCOL_v1")&&r.includes("content-addressed execution lineage"))}catch(e){sub("LRPV1",false,e.message)}try{const r=txt("research/route-operator-platform-v1/README.md");sub("ROUTE_OPERATOR",r.includes("PRE_EMPIRICAL_RESEARCH_PLATFORM_v1")&&r.includes("READ_ONLY_SHADOW_RESEARCH"))}catch(e){sub("ROUTE_OPERATOR",false,e.message)}try{const P=new Set((js(".github/ai-router/router.v1.json")?.projects||[]).map(x=>x.projectId));for(const p of["H_EARTH","LAWS","LINEAGE_RECEIPT_PROTOCOL","ESTATE_VALIDATION"])sub(`ROUTER_${p}`,P.has(p))}catch(e){sub("ROUTER",false,e.message)}}
const HEAD=process.env.EXPECTED_HEAD||process.env.ESTATE_VALIDATION_EXPECTED_HEAD||(LOCAL?"LOCAL_PREFLIGHT_NO_HEAD_CLAIM":"UNRESOLVED");if(!LOCAL)add("EXACT_HEAD",/^[0-9a-f]{40}$/.test(HEAD),HEAD);const msh=fs.existsSync(path.join(R,"validation/manifest.v1.json"))?sha("validation/manifest.v1.json"):null,rsh=fs.existsSync(path.join(R,"validation/master-validation-register.v1.json"))?sha("validation/master-validation-register.v1.json"):null;
let lr=null,lv=null;if(!LOCAL&&!bad.length)try{const mod=await import(pathToFileURL(path.join(R,"infrastructure/lineage-receipt-protocol-v1/javascript/lineage_receipt_protocol_v1.mjs")).href),payload={validation_protocol:"ESTATE_VALIDATION_v1",candidate_head:HEAD,manifest_sha256:msh,master_register_sha256:rsh,asset_count:M.assets.length,standard_count:S.standards.length,validation_class_count:C.validationClasses.length,crosswalk_count:X.length,invalid_overclaim_rejected:true,subject_identity_checks_passed:subjects};lr=await mod.createReceipt(payload);lv=await mod.verifyReceipt(lr);add("LRPV1_BINDING",lv?.state==="VALID",lv?.state||"NO_STATE")}catch(e){add("LRPV1_BINDING",false,e.message)}
const result=bad.length?"FAIL":"PASS",receipt={schema:"ESTATE_VALIDATION_VERIFICATION_RECEIPT_v1",result,validationVersion:"1.0.0",candidateHead:HEAD,localPreflight:LOCAL,checkedFileCount:mf.length,assetRecordCount:M?.assets?.length||0,standardCount:S?.standards?.length||0,validationClassCount:C?.validationClasses?.length||0,crosswalkCount:X.length,manifestSha256:msh,masterRegisterSha256:rsh,checks,reasons:[...new Set(bad)].sort(),lrpReceipt:lr,lrpVerification:lv,externalThirdPartyValidationClaimed:false,certificationOrAccreditationClaimed:false},out=JSON.stringify(receipt,null,2)+"\n";if(OUT){fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,out)}else process.stdout.write(out);process.exit(result==="PASS"?0:1);
