import assert from 'node:assert/strict';import http from 'node:http';import fs from 'node:fs';import path from 'node:path';let puppeteer;try{puppeteer=(await import('puppeteer-core')).default}catch{throw Error('PUPPETEER_CORE_REQUIRED')}
const root=process.cwd(),mime={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.json':'application/json','.css':'text/css'};const server=http.createServer((req,res)=>{let p=new URL(req.url,'http://x').pathname;if(p==='/build/'||p==='/build')p='/build/index.html';const f=path.join(root,p);if(!f.startsWith(root)||!fs.existsSync(f)){res.writeHead(404);return res.end('404')}res.setHeader('content-type',mime[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f))});await new Promise(r=>server.listen(18114,'127.0.0.1',r));const chrome=process.env.CHROME_PATH||process.env.PUPPETEER_EXECUTABLE_PATH;assert.ok(chrome);const browser=await puppeteer.launch({executablePath:chrome,headless:true,args:['--no-sandbox']});
const page=await browser.newPage();await page.setViewport({width:768,height:1024});await page.goto('http://127.0.0.1:18114/build/',{waitUntil:'networkidle0'});await page.evaluate(()=>document.querySelector('[data-open-build-companion],a[href="/build/intake/"]').click());
const body=()=>page.$eval('#build-companion',e=>e.innerText);const input=()=>page.$('#build-companion input');async function set(v){const x=await input();await x.click({clickCount:3});await x.type(v)}async function cont(){await page.evaluate(()=>[...document.querySelectorAll('#build-companion button')].find(b=>b.textContent.trim()==='Continue').click())}async function click(t){await page.waitForFunction(x=>[...document.querySelectorAll('#build-companion button')].some(b=>b.textContent.trim()===x),{},t);await page.evaluate(x=>[...document.querySelectorAll('#build-companion button')].find(b=>b.textContent.trim()===x).click(),t)}
assert.match(await body(),/Diamond Gate Build companion/);assert.match(await body(),/Who am I speaking with\?/);
await set('A');await cont();assert.match(await body(),/at least two characters/);await set('Alex');await cont();assert.match(await body(),/best email/);
await set('x@x');await cont();assert.match(await body(),/email looks incomplete/);await set('alex@example.com');await cont();assert.match(await body(),/10-digit phone/);
await set('5551234');await cont();assert.match(await body(),/full 10-digit/);await set('8175551234');await cont();assert.match(await body(),/What kind of business or project is this website for\?/);
await click('Community / nonprofit / cause');assert.match(await body(),/What brings your organization together\?/);await click('A volunteer group or cause');assert.match(await body(),/Beyond the starting essentials/);
const stored=await page.evaluate(()=>sessionStorage.getItem('dgb-build-companion-v4'));assert.ok(stored&&stored.includes('alex@example.com')&&stored.includes('(817) 555-1234'));
await page.reload({waitUntil:'networkidle0'});await page.evaluate(()=>document.querySelector('[data-open-build-companion],a[href="/build/intake/"]').click());const resumed=await body();assert.ok(!resumed.endsWith('Who am I speaking with?'));assert.ok(!resumed.includes('In a sentence, what is the organization'));
await browser.close();server.close();console.log('BUILD_COMPANION_V4_CONTACT_CONVERSATION_PASS');