import assert from 'node:assert/strict';import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';
let puppeteer;try{puppeteer=(await import('puppeteer-core')).default}catch{throw Error('PUPPETEER_CORE_REQUIRED')}
const root=process.cwd(),mime={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.json':'application/json','.css':'text/css'};
const server=http.createServer((req,res)=>{let p=new URL(req.url,'http://x').pathname;if(p==='/build/'||p==='/build')p='/build/index.html';const f=path.join(root,p);if(!f.startsWith(root)||!fs.existsSync(f)){res.writeHead(404);return res.end('404')}res.setHeader('content-type',mime[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f))});await new Promise(r=>server.listen(18113,'127.0.0.1',r));
const chrome=process.env.CHROME_PATH||process.env.PUPPETEER_EXECUTABLE_PATH;assert.ok(chrome,'CHROME_PATH required');const browser=await puppeteer.launch({executablePath:chrome,headless:true,args:['--no-sandbox']});
const journeys=[
['restaurant',['Restaurant, food service or hospitality','Restaurant or cafe','Receive catering inquiries','Use these choices','Delivery','Use these choices','I decide based on the event'],['Which guest business are we describing?','Beyond the starting essentials, what should this website help people do?','Which catering services do you actually offer?','How should the website describe your delivery coverage?','What should event hosts include in a catering inquiry?']],
['professional',['Professional practice','Consulting or advisory work','Request an initial consultation','Use these choices','My team reviews requests'],['What kind of practice is this for?','Beyond the starting essentials, what should this website help people do?','How should appointment requests work?','What should the appointment request include?']],
['commerce',['Online store / product business','Sell physical products','Use these choices','Shipping','Use these choices','After my team reviews the inquiry'],['Beyond the starting essentials, what should this website help people do?','How will customers receive physical products?','Where should payment happen?']],
['application',['Browser tool / online service','Calculate a price or estimate','Use these choices','An indicative estimate only','A spreadsheet or written rules I have'],['Beyond the starting essentials, what should this website help people do?','What does the calculator return?','Where do the rules or calculations come from?']],
['spatial',['Interactive tour / explorable environment','Explore an imagined world','Use these choices','Explore a limited environment','Use these choices','Drawings or a written concept'],['Beyond the starting essentials, what should this website help people do?','What should visitors do in the first version of the world?','What visual material do you already have?']]];
async function clickText(page,text){await page.waitForFunction(t=>[...document.querySelectorAll('#build-companion button')].some(b=>b.textContent.trim()===t),{},text);await page.evaluate(t=>[...document.querySelectorAll('#build-companion button')].find(b=>b.textContent.trim()===t).click(),text)}
for(const [name,clicks,prompts] of journeys){const page=await browser.newPage();await page.setViewport({width:768,height:1024});await page.goto('http://127.0.0.1:18113/build/',{waitUntil:'networkidle0'});await page.evaluate(()=>document.querySelector('[data-open-build-companion],a[href="/build/intake/"]').click());for(let i=0;i<clicks.length;i++){await clickText(page,clicks[i]);await new Promise(r=>setTimeout(r,20));}const body=await page.$eval('#build-companion',e=>e.innerText);for(const p of prompts)assert.ok(body.includes(p),name+' missing '+p);for(const bad of ['In a sentence, what is the organization','Who does this website need to serve first?','What should the website accomplish for them and for you?'])assert.ok(!body.includes(bad),name+' generic-v2 prompt '+bad);await page.close();}
await browser.close();server.close();console.log('BUILD_MATRIX_V3_BROWSER_JOURNEYS_PASS');