import assert from 'node:assert/strict';import http from 'node:http';import fs from 'node:fs';import path from 'node:path';let puppeteer;try{puppeteer=(await import('puppeteer-core')).default}catch{throw Error('PUPPETEER_CORE_REQUIRED')}
const root=process.cwd(),mime={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.json':'application/json','.css':'text/css'};const server=http.createServer((req,res)=>{let p=new URL(req.url,'http://x').pathname;if(p==='/build/'||p==='/build')p='/build/index.html';const f=path.join(root,p);if(!f.startsWith(root)||!fs.existsSync(f)){res.writeHead(404);return res.end('404')}res.setHeader('content-type',mime[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f))});await new Promise(r=>server.listen(18115,'127.0.0.1',r));const chrome=process.env.CHROME_PATH||process.env.PUPPETEER_EXECUTABLE_PATH;assert.ok(chrome);const browser=await puppeteer.launch({executablePath:chrome,headless:true,args:['--no-sandbox']});
const journeys=[
['restaurant',['Restaurant, food service or hospitality','Restaurant or cafe','Receive catering inquiries','Use these choices','Pickup','Use these choices','Guest count','Use these choices','Start a new website']],
['professional',['Professional practice','Consulting or advisory work','Request an initial consultation','Use these choices','My team reviews requests','Service or appointment type','Use these choices','Start a new website']],
['community',['Community / nonprofit / cause','A volunteer group or cause','Recruit volunteers','Use these choices','Send an interest form for review','Roles they are interested in','Use these choices','Start a new website']],
['commerce',['Online store / product business','Sell physical products','Use these choices','Shipping','Use these choices','Start a new website']],
['application',['Browser tool / online service','Calculate a price or estimate','Use these choices','An indicative estimate only','Start a new website']],
['spatial',['Interactive tour / explorable environment','Explore an imagined world','Use these choices','Explore a limited environment','Use these choices','Start a new website']],
['help',['Help me identify the right starting point','I provide a service to customers','Work at their home or business','Receive quote requests','Use these choices','Service needed','Use these choices','Start a new website']]];
async function click(page,t){await page.waitForFunction(x=>[...document.querySelectorAll('#build-companion button')].some(b=>b.textContent.trim()===x),{},t);await page.evaluate(x=>[...document.querySelectorAll('#build-companion button')].find(b=>b.textContent.trim()===x).click(),t)}
async function contact(page){for(const v of ['Alex','alex@example.com','8175551234']){await page.waitForSelector('#build-companion input');await page.$eval('#build-companion input',e=>e.value='');await page.type('#build-companion input',v);await click(page,'Continue')}}
for(const [name,steps] of journeys){const page=await browser.newPage();await page.setViewport({width:768,height:1024});await page.goto('http://127.0.0.1:18115/build/',{waitUntil:'networkidle0'});await page.evaluate(()=>sessionStorage.clear());await page.reload({waitUntil:'networkidle0'});await page.evaluate(()=>document.querySelector('[data-open-build-companion],a[href="/build/intake/"]').click());await contact(page);for(const x of steps)await click(page,x);const body=await page.$eval('#build-companion',e=>e.innerText);assert.match(body,/I have enough to give Sean a useful picture of the project now/);assert.match(body,/Review what we have/);assert.match(body,/Keep shaping the project/);assert.ok(!body.includes('Who does this website need to serve first?'));assert.ok(!body.includes('What should the website accomplish for them and for you?'));const state=JSON.parse(await page.evaluate(()=>sessionStorage.getItem('dgb-build-companion-v4')));assert.equal(state.sufficiencyOffered,true,name);assert.equal(state.deepMode,false,name);await page.close();}
await browser.close();server.close();console.log('BUILD_COMPANION_V4_SEVEN_SUFFICIENCY_JOURNEYS_PASS');