#!/usr/bin/env node
import fs from 'node:fs';
import {execFileSync} from 'node:child_process';
const BASE=process.env.COMPASS_AWARD_BASE_SHA||'cdb162d14d09ee12f09cdac5cad348c705faafbf';
const OUT=process.env.COMPASS_AWARD_STATIC_OUTPUT||'/tmp/compass-award-presentation-static-receipt.json';
const allowed=new Set(['index.html','assets/compass/compass.css','assets/compass/compass.identity-3d.js','assets/compass/compass.statement-carousel.js','assets/compass/compass.statement-carousel.css','assets/compass/compass.capability-carousel.js','assets/compass/compass.capability-carousel.css','assets/compass/compass.crystals.js','assets/compass/compass.laws-spacecraft.js','assets/compass/compass.cosmos.js','.github/ai-router/projects/compass/verify-award-presentation-successor.v1.mjs','.github/workflows/compass-display-continuity-validation.yml']);
const read=p=>fs.readFileSync(p,'utf8');
const head=execFileSync('git',['rev-parse','HEAD^{commit}'],{encoding:'utf8'}).trim();
const changed=execFileSync('git',['diff','--name-only',`${BASE}...HEAD`],{encoding:'utf8'}).trim().split(/\r?\n/).filter(Boolean);
const statement=read('assets/compass/compass.statement-carousel.js');
const identity=read('assets/compass/compass.identity-3d.js');
const capability=read('assets/compass/compass.capability-carousel.js');
const lawsSpacecraft=read('assets/compass/compass.laws-spacecraft.js');
const index=read('index.html');
const checks=[];const check=(id,pass,evidence='')=>checks.push({id,pass:Boolean(pass),evidence});
check('EXACT_SCOPE',changed.every(p=>allowed.has(p)),changed);
check('IDENTITY_3D_WORDMARK_PRESERVED',identity.includes("GLOBAL='DGB_COMPASS_IDENTITY_3D_GEN1536'")&&identity.includes('DIAMOND GATE BRIDGE')&&identity.includes('THE COMPASS')&&identity.includes("wordmarkGeometry='css-preserve-3d-extrusion-v2'"),'3D wordmark identity remains');
check('COHERISCOPE_PRESERVED',identity.includes('function brandCoheriscope')&&identity.includes("h.textContent='Coheriscope'")&&identity.includes("coheriscopeIdentity='working-product-name'"),'Coheriscope identity remains');
check('REDUNDANT_IDENTITY_SPACECRAFT_RUNTIME_REMOVED',!identity.includes('createCraftCanvas')&&!identity.includes('mountLawsCraft')&&!identity.includes('getContext(\'webgl\'')&&!identity.includes("import('/laws/index.spacecraft.geometry.js")&&identity.includes("spacecraftMounted:false"),'identity owner no longer creates or renders spacecraft');
check('ONE_SPACECRAFT_PRESENTATION_AUTHORITY',statement.includes("spacecraftSurface:'LAWS_SPACECRAFT_ONLY'")&&lawsSpacecraft.includes('DIRECT_LAWS_PRESENTATION_OWNER')&&lawsSpacecraft.includes('DGB_COMPASS_DISABLE_LOCAL_SPACECRAFT=true'),'Laws adapter is sole adopted spacecraft owner');
check('PURPOSE_FIRST_READ',statement.includes('compass-purpose-first-read')&&statement.includes('Useful ideas become easier to navigate')&&statement.includes('Explore the fuller context'),'concise first read plus preserved context');
check('NARRATIVE_SEQUENCE',statement.includes("root.dataset.awardNarrative='identity-experience-purpose-system-readiness-evidence'")&&statement.includes('instrument.after(purpose)')&&statement.includes('purpose.after(capabilities)')&&statement.includes('capabilities.after(readiness)'),'identity → experience → purpose → system → readiness → evidence');
check('TRL_TRA_SHARED_STAGE',statement.includes("readiness.dataset.readinessStage='trl-tra'")&&statement.includes('data-readiness-mode-button="trl"')&&statement.includes('data-readiness-mode-button="tra"')&&statement.includes('Executed Capability')&&statement.includes('Authority Isolation')&&statement.includes('Fail-Closed Evidence')&&index.includes('Software TRL 7'),'same three-card stage alternates TRL/TRA');
check('TRL_TRA_BOUNDARY_LANGUAGE',statement.includes('not a second maturity score')&&statement.includes('does not raise Software TRL 7')&&statement.includes('not external certification or endorsement'),'TRA remains assessment not maturity level');
check('EVIDENCE_EXIT',statement.includes("evidence.href='/evidence/'")&&statement.includes('Open the Evidence Registry'),'direct evidence exit');
check('V_DEPTH_GEOMETRY',capability.includes('perspective:1400px')&&capability.includes('rear-next')&&capability.includes('rear-prev')&&capability.includes('translate3d'),'V-depth carousel preserved');
check('DIMENSIONAL_FLOOR',capability.includes('compass-brain-portal')&&capability.includes('compass-award-trophy')&&capability.includes('compass-house-field'),'brain/trophy/House retained');
check('REDUCED_MOTION_CONTRACT',capability.includes('@media(prefers-reduced-motion:reduce)')&&statement.includes('@media(prefers-reduced-motion:reduce)'),'reduced-motion support retained');
check('KEYBOARD_SEMANTIC_ORDER',capability.includes("e.key==='ArrowRight'||e.key==='ArrowLeft'")&&statement.includes("event.key==='ArrowRight'||event.key==='ArrowLeft'")&&statement.includes("e.key!=='ArrowLeft'&&e.key!=='ArrowRight'"),'keyboard controls retained');
check('CLAIM_BOUNDARY',index.includes('TRL 8 is not claimed')&&index.includes('not a claim of universal product, scientific validation, external certification, or NASA endorsement')&&statement.includes('does not raise Software TRL 7'),'TRL boundary preserved');
check('GEN1538_ROOM_SELECTED_CONTINUITY_BINDING',fs.existsSync('.github/ai-router/projects/compass/verify-display-continuity.v1.mjs'),'Gen1538 verifier remains present');
const failures=checks.filter(x=>!x.pass);
const receipt={schema:'COMPASS_AWARD_PRESENTATION_STATIC_RECEIPT_v1',operationId:'COMPASS_AWARD_PRESENTATION_SUCCESSOR_20260818_v4',lockGeneration:1551,governingHead:'cdb162d14d09ee12f09cdac5cad348c705faafbf',candidateHead:head,baseHead:BASE,changedPaths:changed,result:failures.length?'FAIL_CLOSED':'PASS_CLOSED',checks,failures:failures.map(x=>x.id)};
fs.writeFileSync(OUT,JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt,null,2));if(failures.length)process.exit(1);
