import fs from 'node:fs';
import crypto from 'node:crypto';
import path from 'node:path';
const root=process.cwd(),assessmentPath=path.join(root,'assets/credibility/software-trl7-assessment.v1.json'),readinessPath=path.join(root,'evidence/readiness/index.html'),presentationPath=path.join(root,'assets/credibility/trl7-presentation.v1.js'),claimsPath=path.join(root,'assets/credibility/claims.v1.json');
const failures=[],passes=[],check=(ok,id,msg)=>(ok?passes:failures).push({id,msg});
for(const p of [assessmentPath,readinessPath,presentationPath,claimsPath])check(fs.existsSync(p),'FILE_EXISTS',path.relative(root,p)); if(failures.length)finish();
const raw=fs.readFileSync(assessmentPath,'utf8');let doc;try{doc=JSON.parse(raw);passes.push({id:'JSON_PARSE',msg:'Assessment JSON parses'});}catch(e){failures.push({id:'JSON_PARSE',msg:e.message});finish();}
check(doc.schema==='DIAMOND_GATE_SOFTWARE_TRL7_SELF_ASSESSMENT_v1','SCHEMA_ID','Schema identity frozen');
check(doc.status==='PUBLIC_INSPECTABLE_MECHANICALLY_VALIDATED_AND_SEMANTICALLY_BOUND_SELF_ASSESSMENT','STATUS','Semantic binding status exact');
check(doc.assessmentResult==='SELF_ASSESSED_TRL_7_PASS','RESULT','Result explicitly self-assessed');check(doc.assessedTechnology==='Diamond Gate governed software-construction platform','BOUNDARY_NAME','Technology exact');check(doc.framework?.level===7,'FRAMEWORK_LEVEL','TRL 7 exact');
check(/^https:\/\/nodis3\.gsfc\.nasa\.gov\//.test(doc.framework?.primarySource||''),'PRIMARY_SOURCE','NASA NODIS');check(/^https:\/\/swehb\.nasa\.gov\//.test(doc.framework?.softwareGuidance||''),'SOFTWARE_GUIDANCE','NASA SWEHB');
for(const x of ['authority and intake control','exact-state bounded execution','governed software construction','continuity and recovery','qualification and regression behavior','integration with the actual repository and automation environment'])check(doc.boundary?.included?.includes(x),'BOUNDARY_INCLUDE',x);for(const x of ['enterprise-scale traffic or market adoption','NASA certification, evaluation, affiliation or endorsement','TRL 8 or TRL 9 readiness'])check(doc.boundary?.excluded?.includes(x),'BOUNDARY_EXCLUDE',x);
const expected=new Set(['key-functionality','operational-integration','defect-maturity','documented-test-performance']),seen=new Set(),evidenceIds=new Set();check(doc.criteria?.length===4,'CRITERIA_COUNT','Exactly four criteria');
for(const c of doc.criteria||[]){check(expected.has(c.id),'CRITERION_ID',c.id);check(!seen.has(c.id),'CRITERION_UNIQUE',c.id);seen.add(c.id);check(['PASS','PASS_BOUNDED'].includes(c.disposition),'DISPOSITION',`${c.id}: ${c.disposition}`);check((c.reason||'').length>=80,'RATIONALE',c.id);
 const contract=c.semanticContract;check(contract&&Array.isArray(contract.requiredCapabilities)&&contract.requiredCapabilities.length>0,'SEMANTIC_CAPABILITIES',c.id);check(contract&&Array.isArray(contract.requiredEvidenceClasses)&&contract.requiredEvidenceClasses.length>0,'SEMANTIC_CLASSES',c.id);check((contract?.bindingRule||'').length>=80,'SEMANTIC_RULE',c.id);
 const ev=c.publicEvidence||[];check(ev.length>=2,'EVIDENCE_COUNT',c.id);const caps=new Set(),classes=new Set();for(const e of ev){check(typeof e.id==='string'&&e.id.length>4,'EVIDENCE_ID',`${c.id}:${e.id}`);check(!evidenceIds.has(`${c.id}:${e.id}`),'EVIDENCE_ID_UNIQUE',`${c.id}:${e.id}`);evidenceIds.add(`${c.id}:${e.id}`);check(['implementation','executable-test','execution-record','operational-environment','history','boundary-record'].includes(e.class),'EVIDENCE_CLASS',`${c.id}:${e.class}`);check(typeof e.capability==='string'&&e.capability.length>3,'EVIDENCE_CAPABILITY',`${c.id}:${e.capability}`);caps.add(e.capability);classes.add(e.class);check(typeof e.url==='string'&&(/^https:\/\//.test(e.url)||e.url.startsWith('/')),'EVIDENCE_URL',`${c.id}:${e.url}`);if(e.url?.startsWith('/assets/'))check(fs.existsSync(path.join(root,e.url.slice(1))),'LOCAL_EVIDENCE_EXISTS',e.url);if(['implementation','executable-test'].includes(e.class))check(/github\.com\/smansfield635-create\/smansfield635-create\.github\.io\/blob\/[0-9a-f]{40}\//.test(e.url),'PINNED_CODE_EVIDENCE',e.url);if(e.class==='execution-record')check(/github\.com\/smansfield635-create\/smansfield635-create\.github\.io\/commit\/[0-9a-f]{40}$/.test(e.url),'PINNED_EXECUTION_RECORD',e.url);}
 for(const cap of contract?.requiredCapabilities||[])check(caps.has(cap),'CAPABILITY_COVERAGE',`${c.id}:${cap}`);for(const cls of contract?.requiredEvidenceClasses||[])check(classes.has(cls),'CLASS_COVERAGE',`${c.id}:${cls}`);
 if(c.id==='documented-test-performance'){check(classes.has('execution-record'),'TEST_REQUIRES_EXECUTION','documented-test-performance has execution record');check(classes.has('executable-test'),'TEST_REQUIRES_EXECUTABLE','documented-test-performance has executable test');}
 if(c.id==='defect-maturity'){check(c.disposition==='PASS_BOUNDED','DEFECT_BOUNDING','defect maturity remains bounded');check(/not interpreted as defect-free/i.test(c.reason),'NO_ZERO_DEFECT_CLAIM','no defect-free claim');}}
check([...expected].every(x=>seen.has(x)),'CRITERIA_COMPLETE','All criteria present');check(doc.semanticValidation?.status==='MANDATORY_FAIL_CLOSED_EVIDENCE_BINDING','SEMANTIC_STATUS','Semantic validation fail-closed');check((doc.semanticValidation?.scope||'').includes('does not claim machine understanding'),'SEMANTIC_LIMIT','Machine-understanding limit explicit');
check(doc.mechanicalValidation?.status==='MANDATORY_FAIL_CLOSED','MECHANICAL_STATUS','Mechanical validation fail-closed');const q=doc.closure?.qualification||'';check(q.includes('self-assessment'),'SELF_ASSESSMENT_BOUNDARY','Self-assessment explicit');check(q.includes('not a NASA certification'),'NASA_NONENDORSEMENT','No NASA certification');check((doc.closure?.nextThreshold||'').includes('TRL 8'),'TRL8_CEILING','TRL 8 unclaimed');
for(const [name,text] of [['readiness page',fs.readFileSync(readinessPath,'utf8')],['shared presentation',fs.readFileSync(presentationPath,'utf8')]]){check(text.includes('Self-assessed')||text.includes('self-assess'),'PRESENTATION_SELF_ASSESSED',name);check(text.includes('not a NASA certification')||text.includes('Not NASA certified'),'PRESENTATION_BOUNDARY',name);check(!/NASA[- ](?:approved|certified|endorsed) Diamond Gate/i.test(text),'NO_FALSE_NASA_AUTHORITY',name);}
const receipt={schema:'DIAMOND_GATE_SOFTWARE_TRL7_MECHANICAL_VALIDATION_RECEIPT_v2',assessmentSha256:crypto.createHash('sha256').update(raw).digest('hex'),validationMode:'STRUCTURAL_PLUS_SEMANTIC_EVIDENCE_BINDING',checksPassed:passes.length,checksFailed:failures.length,result:failures.length?'FAIL':'PASS'};fs.writeFileSync('trl7-mechanical-validation-receipt.json',JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt,null,2));finish();
function finish(){if(failures.length){console.error('\nTRL 7 validation failures:');for(const x of failures)console.error(`- ${x.id}: ${x.msg}`);process.exit(1);}console.log(`TRL 7 structural + semantic evidence-binding validation PASS (${passes.length} checks).`);}
