#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { evaluatePlatformControlPlane, REQUEST_SCHEMA } from './platform-control-plane-gate.v1.mjs';
import { REQUEST_SCHEMA as AUTH_SCHEMA } from './identity/authorization-gate.v1.mjs';
import { REQUEST_SCHEMA as FED_SCHEMA } from './federation/federation-gate.v1.mjs';
import { REQUEST_SCHEMA as OBS_SCHEMA, EVENT_SCHEMA } from './observability/control-plane-state-projector.v1.mjs';
import { REQUEST_SCHEMA as ENF_SCHEMA } from './enforcement/enforcement-shadow-gate.v1.mjs';
const ADMISSION_BASE='01da797ff4d46f0b1514dc06a5179818b14b3dfa';
const ALLOWED=[
'.github/ai-router/platform-control-plane/identity/principal-registry.v1.json','.github/ai-router/platform-control-plane/identity/role-policy.v1.json','.github/ai-router/platform-control-plane/identity/authorization-gate.v1.mjs','.github/ai-router/platform-control-plane/identity/authorization-self-test.v1.mjs',
'.github/ai-router/platform-control-plane/federation/repository-registry.v1.json','.github/ai-router/platform-control-plane/federation/federation-protocol.v1.json','.github/ai-router/platform-control-plane/federation/federation-gate.v1.mjs','.github/ai-router/platform-control-plane/federation/federation-self-test.v1.mjs',
'.github/ai-router/platform-control-plane/observability/observability-protocol.v1.json','.github/ai-router/platform-control-plane/observability/control-plane-state-projector.v1.mjs','.github/ai-router/platform-control-plane/observability/observability-self-test.v1.mjs',
'.github/ai-router/platform-control-plane/enforcement/enforcement-policy.v1.json','.github/ai-router/platform-control-plane/enforcement/enforcement-shadow-gate.v1.mjs','.github/ai-router/platform-control-plane/enforcement/enforcement-self-test.v1.mjs',
'.github/ai-router/platform-control-plane/platform-control-plane-protocol.v1.json','.github/ai-router/platform-control-plane/platform-control-plane-gate.v1.mjs','.github/ai-router/platform-control-plane/platform-control-plane-self-test.v1.mjs','.github/workflows/platform-control-plane-strike-v1.yml'];
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v;
function cli(argv){const o={};for(let i=0;i<argv.length;i+=2){if(!argv[i]?.startsWith('--')||argv[i+1]===undefined)throw Error('CLI_ARGUMENT_INVALID');o[argv[i].slice(2)]=argv[i+1];}return o;}
function git(root,args){return execFileSync('git',args,{cwd:root,encoding:'utf8'}).trim();}
function assertExactHead(actual,expected){if(actual!==expected)throw Error('EXACT_CANDIDATE_HEAD_MISMATCH');}
function readJson(root,rel){return JSON.parse(fs.readFileSync(path.join(root,rel),'utf8'));}
function component(root,rel,tmp,name){const out=path.join(tmp,`${name}.json`);execFileSync(process.execPath,[rel,'--output',out],{cwd:root,encoding:'utf8'});return JSON.parse(fs.readFileSync(out,'utf8'));}
function config(root){return{principalRegistry:readJson(root,'.github/ai-router/platform-control-plane/identity/principal-registry.v1.json'),rolePolicy:readJson(root,'.github/ai-router/platform-control-plane/identity/role-policy.v1.json'),repositoryRegistry:readJson(root,'.github/ai-router/platform-control-plane/federation/repository-registry.v1.json'),enforcementPolicy:readJson(root,'.github/ai-router/platform-control-plane/enforcement/enforcement-policy.v1.json')};}
function request(head){return{schema:REQUEST_SCHEMA,authorization:{schema:AUTH_SCHEMA,principalId:'execution:l2-platform-strike-fresh-verifier',identityEvidence:{executionHolder:'L2_CONTROL_PLANE_PLATFORM_STRIKE_FRESH_VERIFIER',repository:'smansfield635-create/smansfield635-create.github.io'},tenantId:'IMI_CONTROL_PLANE_PLATFORM',projectId:'IMI_CONTROL_PLANE_PLATFORM',action:'L2_COMPONENT_VERIFY',resource:'control-plane://l2/strike',subjectHead:head,currentMainHead:head,assertedRoles:['L2_STRIKE_FRESH_VERIFIER']},federation:{schema:FED_SCHEMA,operation:'VERIFY_RECEIPT',sourceRepository:{repositoryId:'repo:website-main',numericId:1142978610,fullName:'smansfield635-create/smansfield635-create.github.io'},targetRepository:{repositoryId:'repo:geodiametrics',numericId:1142904555,fullName:'smansfield635-create/geodiametrics'},sourceHead:head,evidence:{algorithm:'sha256',digest:'c'.repeat(64)},authorityTransferRequested:false,externalWriteRequested:false},observability:{schema:OBS_SCHEMA,events:[{schema:EVENT_SCHEMA,eventId:'integrated-1',operationId:'L2_CONTROL_PLANE_PLATFORM_DEFICIT_STRIKE_v1',sequence:1,lane:'L2_CONTROL_PLANE',status:'CONSTRUCTING',subjectHead:head,evidenceDigest:'d'.repeat(64)}]},enforcement:{schema:ENF_SCHEMA,repository:'smansfield635-create/smansfield635-create.github.io',branch:'main',proposedAction:'EVALUATE_ONLY',observedPerimeter:{branchProtected:false,pullRequestRequired:false,directPushAllowed:true,requiredChecks:[]},exactHeadEvidenceValid:true,explicitMergeAuthority:false,bypassRequested:false,liveActivationRequested:false}};}
const a=cli(process.argv.slice(2)),root=path.resolve(a.root??'.'),expected=a['expected-head'];if(!expected||!a.output)throw Error('CLI_REQUIRED_ARGUMENT_MISSING');
const actual=git(root,['rev-parse','HEAD']);assertExactHead(actual,expected);assert.throws(()=>assertExactHead(actual,'0'.repeat(40)),/EXACT_CANDIDATE_HEAD_MISMATCH/);
const diff=git(root,['diff','--name-only',`${ADMISSION_BASE}..${actual}`]).split('\n').filter(Boolean).sort();assert.deepEqual(diff,[...ALLOWED].sort(),'ADMITTED_18_PATH_SCOPE_MISMATCH');for(const rel of ALLOWED)assert.ok(fs.existsSync(path.join(root,rel)),`MISSING_ALLOWED_PATH:${rel}`);
const fingerprint=crypto.createHash('sha256');for(const rel of [...ALLOWED].sort()){fingerprint.update(rel);fingerprint.update('\0');fingerprint.update(fs.readFileSync(path.join(root,rel)));fingerprint.update('\0');}const packageFingerprint=fingerprint.digest('hex');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'l2-platform-strike-'));const components={identity:component(root,'.github/ai-router/platform-control-plane/identity/authorization-self-test.v1.mjs',tmp,'identity'),federation:component(root,'.github/ai-router/platform-control-plane/federation/federation-self-test.v1.mjs',tmp,'federation'),observability:component(root,'.github/ai-router/platform-control-plane/observability/observability-self-test.v1.mjs',tmp,'observability'),enforcement:component(root,'.github/ai-router/platform-control-plane/enforcement/enforcement-self-test.v1.mjs',tmp,'enforcement')};for(const [name,r] of Object.entries(components))assert.equal(r.result,'PASS_CLOSED',`${name}_SELF_TEST_FAILED`);
const cfg=config(root),base=request(actual),cases=[];function run(name,input,expectedResult,expectedFailed=null){const r=evaluatePlatformControlPlane(input,cfg);assert.equal(r.result,expectedResult,`${name}:result`);if(expectedFailed)assert.equal(r.failedComponent,expectedFailed,`${name}:component`);assert.equal(r.authorityCreated,false);assert.equal(r.mergeMayProceed,false);assert.equal(r.liveEnforcementMayProceed,false);cases.push({name,result:r.result,failedComponent:r.failedComponent??null,enforcementReadiness:r.enforcementReadiness??null,contradictionCount:r.observability?.contradictionCount??null});return r;}
const positive=run('valid integrated evaluation preserves perimeter gap',base,'PASS_CLOSED');assert.equal(positive.enforcement.result,'SHADOW_DENY');assert.equal(positive.enforcementReadiness,'GAP_DETECTED_NOT_ACTIVATED');
const roleInjected=structuredClone(base);roleInjected.authorization.assertedRoles.push('L2_PLATFORM_ORIGINATOR');run('role injection stopped',roleInjected,'STOP_CLOSED','AUTHORIZATION');
const fedMismatch=structuredClone(base);fedMismatch.federation.targetRepository.numericId=1;run('federation identity mismatch stopped',fedMismatch,'STOP_CLOSED','FEDERATION');
const obsInvalid=structuredClone(base);obsInvalid.observability.events[0].evidenceDigest='bad';run('invalid observability evidence stopped',obsInvalid,'STOP_CLOSED','OBSERVABILITY');
const liveActivation=structuredClone(base);liveActivation.enforcement.liveActivationRequested=true;run('live enforcement activation stopped',liveActivation,'STOP_CLOSED','ENFORCEMENT_SHADOW');
const contradiction=structuredClone(base);contradiction.observability.events.push({...contradiction.observability.events[0],eventId:'integrated-2',status:'STOP',evidenceDigest:'e'.repeat(64)});const cr=run('contradiction preserved without false resolution',contradiction,'PASS_CLOSED');assert.equal(cr.observability.contradictionCount,1);assert.equal(cr.contradictionsPresent,true);
assert.equal(git(root,['diff','--name-only']),'','SELF_TEST_MUTATED_TRACKED_REPOSITORY');
const final=stable({schema:'L2_CONTROL_PLANE_PLATFORM_STRIKE_RECEIPT_v1',result:'PASS_CLOSED',terminalDisposition:'PASS_CLOSED',admissionLockGeneration:854,admissionBaseHead:ADMISSION_BASE,exactCandidateHead:actual,allowedPathCount:ALLOWED.length,allowedPaths:[...ALLOWED].sort(),packageFingerprintDomain:{domainId:'L2_CONTROL_PLANE_PLATFORM_DEFICIT_STRIKE_PACKAGE_FINGERPRINT_v1',algorithm:'sha256'},packageFingerprintSha256:packageFingerprint,componentSelfTests:Object.fromEntries(Object.entries(components).map(([k,v])=>[k,v.result])),integratedAdversarialCases:cases,enforcementShadowFinding:positive.enforcement.result,enforcementActivationPerformed:false,repositorySettingsMutated:false,externalRepositoryWritesPerformed:false,hEarthMutationPerformed:false,lawsMutationPerformed:false,mergePerformed:false,authorityCreated:false,evidenceMayPropagate:true,authorityMayPropagate:false,terminationReceipt:{schema:'L2_STRIKE_TERMINATION_RECEIPT_v1',result:'PASS_CLOSED',constructionComplete:true,constructionStoppedBeforeMerge:true,constructionStoppedBeforeLiveEnforcementActivation:true,separateSynchronizationRequired:true}});fs.mkdirSync(path.dirname(path.resolve(a.output)),{recursive:true});fs.writeFileSync(path.resolve(a.output),JSON.stringify(final,null,2)+'\n');process.stdout.write(JSON.stringify({result:final.result,exactCandidateHead:actual,allowedPathCount:ALLOWED.length,packageFingerprintSha256:packageFingerprint})+'\n');
