import{H_EARTH_MAP_WIDE_ENVIRONMENT_REDEVELOPMENT_TERRAIN_EVALUATION as TERRAIN}from'../../../../h-earth-3d/terrain/h-earth.terrain-estate-construction-v1.candidate.js';
const F=v=>Object.freeze(v),OP='H_EARTH_AUDRALIA_OPEN_WORLD_SPATIAL_MIGRATION_v1',COH='H_EARTH_V2_COASTAL_INTEGRATION_AND_POSITIONAL_IDENTITY_CLOSURE',SURFACE='H_EARTH_GRATITUDE_CANONICAL_SURFACE_FIELD_v1',COAST='H_EARTH_OW01_CANONICAL_COAST_BOUNDARY_v1';
export const OW01_CANONICAL_GEOGRAPHIC_ANCHOR_MANIFEST=F({schema:'H_EARTH_OW01_CANONICAL_GEOGRAPHIC_ANCHOR_MANIFEST_v1',parentOperation:COH,governingAcceptedBaseline:'6836288462bbbc7ab7c03d5f12fafaab119f9e36',reviewedReliefReference:'97003e9de386a8962fb46d0b370005b900a167d6',protectedWorkingReference:'bc8974e0ff28da4457559567d8059e14156ca5f0',mirageSolvedReference:'1cbc91a630557c2c89e6d860f68f347a44dd4df3',safeImplementationBase:'30c00000b9b344abce5aad133a3149eabfe00f0b',canonicalCoordinateAuthority:'GRATITUDE_LOCAL_AUTHORING_XZ_MAPPED_TO_AUDRALIA_SPHERE',invariant:'CANONICAL_GEOGRAPHIC_IDENTITY',requiredRepresentations:F(['LOCAL','REGION','CONTINENT','PLANETARY']),roundTripToleranceAuthoringUnits:1e-6,anchors:F([F({id:'PRIMARY_PEAK',x:-79,z:-286,class:'MOUNTAIN_PEAK'}),F({id:'SECONDARY_PEAK',x:-12,z:-282,class:'MOUNTAIN_PEAK'}),F({id:'WATERFALL_CREST',x:-50,z:-278,class:'WATERFALL_CREST'}),F({id:'WATERFALL_BASIN_CENTER',x:-44,z:-211,class:'RESERVOIR_CENTER'}),F({id:'RESERVOIR_EAST_EDGE',x:7.847094968629811,z:-211,class:'RESERVOIR_BOUNDARY'}),F({id:'RESERVOIR_WEST_EDGE',x:-97.2206114596909,z:-211,class:'RESERVOIR_BOUNDARY'}),F({id:'HARBOR_WEST_COAST_BEND',x:-192,z:-56.81629425546011,class:'COASTLINE'}),F({id:'HARBOR_CENTER_COAST_BEND',x:0,z:-43.31331986864843,class:'COASTLINE'}),F({id:'INLAND_BAY_APEX',x:118,z:-89.99197537809627,class:'COASTLINE'}),F({id:'EASTERN_HEADLAND',x:198,z:-40.577666952243305,class:'HEADLAND'}),F({id:'PENINSULA_COAST_REFERENCE',x:256,z:-47.74780290241972,class:'COASTLINE'}),F({id:'ESTATE_REFERENCE_POINT',x:80,z:-172,class:'PROTECTED_ESTATE_REFERENCE'})]),perceptualTrackSet:F(['PRIMARY_PEAK','WATERFALL_BASIN_CENTER','HARBOR_CENTER_COAST_BEND','EASTERN_HEADLAND']),waterfallReservoirRegionProtected:true,acceptedReliefAndDepthProtected:true,beachCorrectionClass:'ZERO_SEPARATE_BEACH_GEOMETRY_TERRAIN_MATERIAL_ONLY'});
export function buildHEarthMapWideEnvironmentPreviewObserverReceipt(renderer){
  const s=renderer.getSnapshot(),c=s.worldContract,g=s.gratitudeStatistics,p=s.planetStatistics,cw=s.coastalWaterStatistics,st=s.stitchStatistics,b=s.beachStatistics,w=s.waterStatistics,e=renderer.getOW01GeographicEvidence(),pos=renderer.evaluateCanonicalGeographicIdentity(OW01_CANONICAL_GEOGRAPHIC_ANCHOR_MANIFEST),corr=renderer.evaluateSurfaceCorrespondence(),cam=renderer.getCameraSafety();
  const boundaryHash=c?.boundaryIdentityHash;
  const checks={
    sourceTerrainEvaluationStillPasses:TERRAIN.eligible===true,
    exactOperation:c?.operationId===OP&&c?.checkpoint==='OW01'&&c?.lockGeneration===473,
    exactCoherenceOperation:c?.coherenceOperation===COH&&e?.coherenceOperation===COH,
    oneGeographicTruthAuthority:c?.geographicTruthAuthorityCount===1&&c?.canonicalSurfaceAuthority===SURFACE&&g?.surfaceAuthority===SURFACE&&e?.surfaceAuthority===SURFACE&&e?.geographicTruthAuthorityCount===1,
    oneCanonicalCoastAuthority:c?.canonicalCoastAuthority===COAST&&e?.coastAuthority===COAST&&corr?.coastAuthority===COAST,
    sharedBoundaryIdentity:typeof boundaryHash==='string'&&boundaryHash===g?.boundaryIdentityHash&&boundaryHash===cw?.boundaryIdentityHash&&boundaryHash===e?.boundaryIdentityHash&&boundaryHash===corr?.boundaryIdentityHash,
    sameGratitudeMeshAtAllScales:renderer.continentMesh===renderer.gratitudeMesh&&g?.singleSurfaceAcrossAllScales===true&&e?.gratitudeUsesSameMeshAtAllViewScales===true&&c?.cameraDistanceCanChangeGeography===false&&g?.cameraDistanceCanChangeGeography===false,
    noGeographicStitchInterpolation:renderer.stitchMesh?.indices?.length===0&&st?.triangleCount===0&&st?.geographicInterpolationConstructed===false&&e?.stitchGeographicInterpolationConstructed===false&&c?.stitchGeographicAuthority===false,
    noIndependentBeachOrWetSandGeometry:renderer.beachMesh?.indices?.length===0&&b?.triangleCount===0&&b?.independentBeachVisualAuthority===false&&b?.separateBeachGeometryConstructed===false&&b?.separateWetSandGeometryConstructed===false&&c?.independentBeachVisualAuthority===false&&c?.separateBeachGeometryConstructed===false&&c?.separateWetSandGeometryConstructed===false&&e?.independentBeachVisualAuthority===false,
    terrainIntegratedSandStillPresent:g?.terrainIntegratedSand===true&&g?.terrainIntegratedSandSampleCount>0&&c?.coastalTerrainMaterialIntegrated===true&&e?.coastalTerrainMaterialIntegrated===true,
    conformingQuadCellCoast:g?.coastlineTopology==='QUAD_CELL_SHARED_EDGE_CONFORMING'&&g?.sharedEdgeRootCount>0&&g?.coastCrossingCellCount>0&&cw?.coastlineTopology==='QUAD_CELL_SHARED_EDGE_CONFORMING'&&cw?.sharedEdgeRootCount===g?.sharedEdgeRootCount,
    curvedCenterlineSandbars:g?.detachedSandbarCount===3&&e?.detachedSandbarCount===3&&e?.rotatedEllipseCallsInCanonicalLandAuthority===0&&e?.sandbarRepresentation==='CURVED_VARIABLE_WIDTH_CENTERLINE',
    coastalWaterConsumesSameBoundary:cw?.canonicalBoundaryConsumer===true&&cw?.waterOwnsGeography===false&&e?.sharedBoundaryBetweenLandAndWater===true,
    coarsePlanetTriangleMaskRemoved:p?.planetaryOceanTriangleCullingForGratitudeMask===false&&p?.gratitudeLandStencilMask===true&&c?.planetaryOceanTriangleCullingForGratitudeMask===false&&c?.planetaryOceanMaskedByCanonicalLandStencil===true&&e?.planetaryOceanTriangleCullingForGratitudeMask===false&&e?.planetaryOceanMaskedByCanonicalLandStencil===true,
    localScaleNotCompressed:g?.localScaleCompressed===false&&g?.localArcScaleOneToOne===true&&g?.localWidthAuthoringUnits===512&&g?.localDepthAuthoringUnits===384,
    protectedHydrology:w?.reservoirProtected===true&&w?.waterfallBasinProtected===true&&e?.waterfallReservoirRegionProtected===true,
    singlePlanetaryOcean:p?.planetaryOceanSingleSurface===true&&c?.planetaryOceanSingleSurface===true,
    canonicalPositionGate:pos?.canonicalPositionalIdentityPassed===true&&pos?.anchorCount===12,
    surfaceCorrespondenceGate:corr?.pass===true&&corr?.maximumAuthorityCount===1&&corr?.scaleDependentGeographicSubstitution===false&&corr?.surfaceAuthority===SURFACE,
    cameraScaleRecognized:cam?.continuousScaleRecognized===true&&cam?.geographySourceInvariantAcrossScale===true&&cam?.canonicalTargetStableUnderPureZoom===true&&cam?.fixedFovAcrossScale===true,
    noLiveMutation:s.liveRuntimeMutated===false&&s.liveCameraMutated===false&&s.liveNavigationMutated===false&&s.liveWaterMutated===false&&cam?.liveMutationAbsent===true,
    unresolvedContinentsRemainAtmospheric:p?.otherContinentsPlacementsCanonical===false&&p?.unresolvedContinentPresentation==='ATMOSPHERIC_HAZE_ONLY'
  };
  const failedChecks=Object.entries(checks).filter(([,v])=>v!==true).map(([k])=>k),mechanicalChecksPassed=failedChecks.length===0;
  return F({schema:'H_EARTH_OW01_COASTLINE_REPLACEMENT_OBSERVER_RECEIPT_v1',operationId:OP,coherenceOperation:COH,result:mechanicalChecksPassed?'PASS_MECHANICAL_USER_DIFFERENTIAL_REQUIRED':'FAIL_MECHANICAL',mechanicalChecksPassed,checks:F(checks),failedChecks:F(failedChecks),canonicalPositionalIdentity:pos,surfaceCorrespondence:corr,surfaceAuthority:SURFACE,coastAuthority:COAST,boundaryIdentityHash:boundaryHash,perceptualPlaceIdentity:'USER_GATE_REQUIRED',coastlineNaturalness:'USER_GATE_REQUIRED',sandbarNaturalness:'USER_GATE_REQUIRED',touchTravel:'USER_GATE_REQUIRED',mergeAuthorized:false,deploymentAuthorized:false,releaseAuthorized:false});
}
export default buildHEarthMapWideEnvironmentPreviewObserverReceipt;
