import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

export const OPERATION_ID = "METHODS_FORMAL_RECORD_TYPE_DEPENDENCY_THREE_ANCHOR_AND_DEVELOPMENTAL_BASELINE_AUDIT_v1";
export const ASSIGNMENT_HEAD = "ce40519190a9048c1e0cef682108c34b0a7f8055";
export const ASSIGNMENT_ID = "8c4d0f0fb1b3068764e476c4";
export const ROLE_ID = "ROLE_6_REQUIREMENTS_AND_CAUSAL_AUTHORITY";
export const ASSIGNMENT_HOLDER = "MIB_ROLE6_FIRST_ASSIGNMENT_HOLDER_20260804_1802_6BB3D2454E65D0254CD93ED7";
export const ACTIVE_LEDGER_HEAD = "c351db89434f9a65a28cbacbd0122c0396b15f12b5e6d529b09dbdfa9bf120a3";
export const PACKET_HEAD = "fa7e74403ff43e017bccef7462f4e001918cf0a3";
export const PACKET_SHA256 = "5c93a8ebe638b9f06a4e14fc42f8ee202c8801e940527aa4fb987006a04e0cdc";
export const REGISTRY_PATH = "control-plane/methods-information-benchmark/role6-audit-bootstrap/audit-output-path-registry.v1.json";

export class AuditError extends Error { constructor(code, detail="") { super(detail?`${code}:${detail}`:code); this.name="AuditError"; this.code=code; this.detail=detail; } }
export function assert(condition, code, detail="") { if(!condition) throw new AuditError(code,detail); }
export function parseArgs(argv) { const out={}; const flags=new Set(["self-test","return-assignment","final"]); for(let i=0;i<argv.length;i++){const token=argv[i]; if(!token.startsWith("--")) throw new AuditError("INPUT_SCHEMA_INVALID",`unexpected_argument:${token}`); const key=token.slice(2); if(flags.has(key)){out[key.replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=true; continue;} const value=argv[i+1]; if(value===undefined||value.startsWith("--")) throw new AuditError("INPUT_SCHEMA_INVALID",`missing_value:${token}`); out[key.replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=value;i++;} return out; }
export function readJson(file){return JSON.parse(fs.readFileSync(file,"utf8"));}
export function writeJson(file,value){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,`${JSON.stringify(value,null,2)}\n`,"utf8");}
function normalize(value){if(Array.isArray(value))return value.map(normalize);if(value&&typeof value==="object")return Object.fromEntries(Object.keys(value).sort().map(k=>[k,normalize(value[k])]));return value;}
export function stableJson(value){return `${JSON.stringify(normalize(value))}\n`;}
export function sha256(value){return crypto.createHash("sha256").update(value).digest("hex");}
export function canonicalPayloadBytes(payload){return `${JSON.stringify(payload,null,2)}\n`;}
export function loadRegistry(repoRoot){const r=readJson(path.join(repoRoot,REGISTRY_PATH));assert(r.schema==="METHODS_ROLE_6_AUDIT_OUTPUT_PATH_REGISTRY_v1","INPUT_SCHEMA_INVALID","registry_schema");assert(r.operationId===OPERATION_ID,"OPERATION_ID_MISMATCH","registry_operation");assert(r.assignmentHead===ASSIGNMENT_HEAD&&r.assignmentId===ASSIGNMENT_ID,"ASSIGNMENT_IDENTITY_MISMATCH","registry_assignment");assert(r.substantiveOutputs.length===27&&r.returnArtifacts.length===2,"OUTPUT_COUNT_MISMATCH","registry_counts");assert(r.packageInputPaths.length===28&&r.commandEmittedPaths.length===1,"OUTPUT_COUNT_MISMATCH","registry_phases");return r;}
export function isPlainObject(v){return Boolean(v)&&typeof v==="object"&&!Array.isArray(v);}
export function packageEntries(pkg){return [...pkg.substantiveOutputs,pkg.returnPacket];}
export function validatePackage(pkg,registry){assert(isPlainObject(pkg),"INPUT_SCHEMA_INVALID","package_not_object");assert(pkg.schema==="METHODS_ROLE_6_AUDIT_PACKAGE_v1","INPUT_SCHEMA_INVALID","package_schema");assert(pkg.operationId===OPERATION_ID,"OPERATION_ID_MISMATCH");assert(pkg.assignmentHead===ASSIGNMENT_HEAD&&pkg.assignmentId===ASSIGNMENT_ID,"ASSIGNMENT_IDENTITY_MISMATCH");assert(pkg.packetHead===PACKET_HEAD&&pkg.packetCanonicalSha256===PACKET_SHA256,"ASSIGNMENT_IDENTITY_MISMATCH","packet_identity");assert(pkg.executionHolder===ASSIGNMENT_HOLDER,"ASSIGNMENT_IDENTITY_MISMATCH","execution_holder");assert(Array.isArray(pkg.substantiveOutputs)&&pkg.substantiveOutputs.length===27,"OUTPUT_COUNT_MISMATCH","substantive");assert(isPlainObject(pkg.returnPacket),"INPUT_SCHEMA_INVALID","return_packet");const actual=packageEntries(pkg);const expected=[...registry.substantiveOutputs,registry.returnArtifacts[0]];const ids=new Set(),paths=new Set();actual.forEach((entry,index)=>{assert(isPlainObject(entry),"INPUT_SCHEMA_INVALID",`entry_${index}`);assert(entry.id===expected[index].id&&entry.path===expected[index].path,"OUTPUT_ID_OR_PATH_MISMATCH",`entry_${index}`);assert(!ids.has(entry.id)&&!paths.has(entry.path),"DUPLICATE_OUTPUT_ID_OR_PATH",`entry_${index}`);ids.add(entry.id);paths.add(entry.path);assert(isPlainObject(entry.payload),"PAYLOAD_NOT_OBJECT",entry.id);assert(!entry.path.startsWith("/")&&!entry.path.includes(".."),"UNAUTHORIZED_PATH",entry.path);});assert(actual.every((e,i)=>e.path===registry.packageInputPaths[i]),"OUTPUT_ID_OR_PATH_MISMATCH","package_path_order");validateReturnPacketPayload(pkg.returnPacket.payload,pkg);return true;}
export function outputManifestSha256(pkg){return sha256(stableJson(pkg.substantiveOutputs.map(({id,path,payload})=>({id,path,payload}))));}
export function validateReturnPacketPayload(p,pkg){assert(isPlainObject(p),"PAYLOAD_NOT_OBJECT","return_packet");assert(p.schema==="METHODS_INFORMATION_BENCHMARK_ROLE_OPERATION_RETURN_v1","INPUT_SCHEMA_INVALID","return_schema");assert(p.assignmentId===ASSIGNMENT_ID&&p.roleId===ROLE_ID&&p.operationId===OPERATION_ID&&p.holderExecutionId===ASSIGNMENT_HOLDER,"ASSIGNMENT_IDENTITY_MISMATCH","return_binding");assert(["PASS_RETURN","HELD_RETURN","FAIL_RETURN"].includes(p.disposition),"INPUT_SCHEMA_INVALID","return_disposition");assert(/^[0-9a-f]{64}$/.test(p.outputManifestSha256||""),"INPUT_SCHEMA_INVALID","output_manifest_sha256");assert(p.outputManifestSha256===outputManifestSha256(pkg),"FINGERPRINT_MISMATCH","output_manifest");assert(p.fixtureOnly===false,"INPUT_SCHEMA_INVALID","fixture_only");}
export function packageFingerprint(pkg,registry){return sha256(stableJson({operationId:pkg.operationId,assignmentHead:pkg.assignmentHead,assignmentId:pkg.assignmentId,packetHead:pkg.packetHead,packetCanonicalSha256:pkg.packetCanonicalSha256,executionHolder:pkg.executionHolder,substantiveOutputIdPathPayloadMap:pkg.substantiveOutputs,returnPacketIdPathPayload:pkg.returnPacket,authorizedChangedPaths:registry.authorizedChangedPaths}));}
export function computeLedgerHead(ledger){return sha256(JSON.stringify(normalize({schema:ledger.schema,genesisCandidateHead:ledger.genesisCandidateHead,bootstrapFingerprint:ledger.bootstrapFingerprint,revision:ledger.revision,assignments:ledger.assignments})));}
export function validateActiveLedger(ledger){assert(ledger.schema==="METHODS_INFORMATION_BENCHMARK_FIRST_ASSIGNMENT_LEDGER_v1","RETURN_OR_TERMINATION_FAILURE","ledger_schema");assert(computeLedgerHead(ledger)===ledger.ledgerHead,"RETURN_OR_TERMINATION_FAILURE","ledger_head");assert(ledger.ledgerHead===ACTIVE_LEDGER_HEAD&&ledger.revision===1,"RETURN_OR_TERMINATION_FAILURE","active_ledger_identity");assert(Array.isArray(ledger.assignments)&&ledger.assignments.length===1,"RETURN_OR_TERMINATION_FAILURE","assignment_cardinality");const a=ledger.assignments[0];assert(a.assignmentId===ASSIGNMENT_ID&&a.roleId===ROLE_ID&&a.operationId===OPERATION_ID&&a.holderExecutionId===ASSIGNMENT_HOLDER&&a.status==="ACTIVE","RETURN_OR_TERMINATION_FAILURE","active_assignment");return a;}
export function safeTarget(root,relativePath){const rr=path.resolve(root),t=path.resolve(rr,relativePath);assert(t===rr||t.startsWith(`${rr}${path.sep}`),"UNAUTHORIZED_PATH",relativePath);return t;}
export function listFilesRecursive(root){if(!fs.existsSync(root))return[];const out=[];const visit=d=>{for(const n of fs.readdirSync(d).sort()){const f=path.join(d,n),s=fs.statSync(f);if(s.isDirectory())visit(f);else out.push(path.relative(root,f).split(path.sep).join("/"));}};visit(root);return out;}
