#!/usr/bin/env python3
"""Build the 31-resource Laws Chamber OSF source registry."""
from __future__ import annotations
import argparse, hashlib, json, os, re
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

RID = "OSF_LAWS_CHAMBER_SOURCE_REGISTRY_v1"
BOUNDARY = "Source review and placement only. Registration, public availability, file recovery, or Chamber admission does not establish correctness, novelty, empirical validation, replication, or cross-domain generality."
M = {
"9u6vd":("CANONICAL_PROPOSITION","LAW_OF_TRANSITORY_COHERENCE","NONE","NONE","FORMAL_LAW_AND_STUDY_PROGRAM","NO_EXECUTED_RESULT","NO_PUBLIC_DATASET_CODE_OR_EXECUTED_STUDY","EXPLICIT_SOURCE_CONDITIONS","NOT_APPLICABLE","SOURCE_RECOVERED",["SCIENTIFIC_LAW","FINDINGS_AND_BOUNDARIES"]),
"7jnxq":("FROZEN_REGISTRATION","UNIVERSAL_LAW_OF_COHERENCE_DYNAMICS","FIXED_EVIDENCE_WINDOWS_AND_OBSERVER_PROTOCOL","CAD_CTD_CFD_IMD_TD","NON_EXPERIMENTAL_CLASSIFICATION_PROTOCOL","FROZEN_PROVENANCE_NOT_RESULT","REGISTRATION_IS_CUSTODY_NOT_VALIDATION","EXPLICIT_OBSERVER_CONVERGENCE_TEST","NOT_APPLICABLE","FILES_REVIEWED",["EVIDENCE_AND_SOURCES","METHODS_AND_MODELS","ADMISSION_AND_BASELINE","REVERSE_AUDIT"]),
"9ut2z":("METHOD_SPECIFICATION","NONE","OBSERVE_HYPOTHESIZE_1_2_3_REDUCE_FALSIFY_ITERATE_TERMINATE_11_12_13","ALIGNMENT_DIAGNOSTIC_ASSESSMENT","METHOD_ONLY","NO_EXECUTED_RESULT","TWO_METHOD_PDFS_NO_VALIDATION_STUDY","CLEAN_CLAIM_COLLAPSE_ALLOWED","NOT_APPLICABLE","ADMITTED_AS_METHOD",["METHODS_AND_MODELS","FORWARD_CONSTRUCTION","RESULT_AND_RECORD"]),
"edg9f":("FORMALISM","NONE","QUOTIENT_ADMISSIBILITY_AND_CLOSED_TRANSITIONS","M256_CCM","FORMAL_TECHNICAL_REVIEW_CANDIDATE","FORMAL_CONSTRUCTION_NOT_VERIFIED_PROOF","NO_EXECUTABLE_REFERENCE_OR_MACHINE_TESTS","PARTIAL_FORMAL_BOUNDARIES","REQUIRED_SYMBOL_AND_PROOF_REVIEW","ADMITTED_AS_FORMALISM",["METHODS_AND_MODELS","FINDINGS_AND_BOUNDARIES"]),
"7vkgs":("METHOD_SPECIFICATION","NONE","ABCD_INTERNAL_COHERENCE_CONSTRAINT_ALIGNMENT_FRAGMENTATION_TRAJECTORY","ABCD_DIAGNOSTIC","OBSERVER_CLASSIFICATION_PROCEDURE","NO_EXECUTED_CASES","PROCEDURE_ONLY","OBSERVER_CONVERGENCE_REQUIRED","NOT_APPLICABLE","ADMITTED_AS_METHOD",["METHODS_AND_MODELS","FORWARD_CONSTRUCTION","APPLIED_INVESTIGATIONS"]),
"4vmtc":("APPLIED_OR_PHILOSOPHICAL_PROPOSITION","BROAD_LIFE_COHERENCE_BOUNDARY_CLAIM","NONE","NONE","NONE","AUTHOR_DECLARED_CLOSED_NOT_RESULT","BROAD_CROSS_DOMAIN_CLAIMS_WITHOUT_DOMAIN_EVIDENCE","NOT_OPERATIONALIZED","NOT_APPLICABLE","HELD",["FINDINGS_AND_BOUNDARIES"]),
"n82xh":("METHOD_AND_STUDY_DESIGN","SYSTEMIC_DYNAMIC_TRAJECTORY_LAW_TEST_TARGET","FORMAL_FALSIFICATION_PATH","DOMAIN_MANEUVERABILITY_METRICS","MINIMUM_VIABLE_FALSIFICATION_STUDY","NO_EXECUTED_RESULT","PROTOCOL_WITHOUT_DATASET_OR_RESULTS","FALSE_POSITIVE_FALSE_NEGATIVE_NON_SPECIFICITY_OBSERVER_INTERVENTION","DOMAIN_METRIC_REVIEW_REQUIRED","ADMITTED_AS_METHOD",["METHODS_AND_MODELS","REVERSE_AUDIT","APPLIED_INVESTIGATIONS"]),
"pyd6g":("FORMALISM_DESCRIPTION","NONE","IF_AND_ONLY_IF_ADMISSIBILITY_BOUNDARY","CCMM","IMPLEMENTATION_CORRESPONDENCE_REVIEW","LIVE_PROOF_CLAIM_NOT_OSF_VERIFIED","DESCRIPTION_ONLY","NOT_OPERATIONALIZED_IN_NODE","REQUIRED","TECHNICAL_REVIEW_REQUIRED",["METHODS_AND_MODELS","EVIDENCE_AND_SOURCES"]),
"bgd86":("PHILOSOPHICAL_CONTEXT","NONE","BRIDGE_DIAGNOSTIC_TRANSLATION","CAD_CTD_CFD_IMD_TD_CONTEXT_USE","NONE","NO_EXECUTED_RESULT","INTERPRETIVE_APPLICATION","NO_METAPHYSICAL_TRUTH_ADJUDICATION","NOT_APPLICABLE","ADMITTED_AS_CONTEXT",["FINDINGS_AND_BOUNDARIES"]),
"rjdms":("METHOD_SPECIFICATION","NONE","ADMISSIBLE_EVIDENCE_FIXED_WINDOWS_OBSERVER_INVARIANCE","DIAGNOSTIC_EVALUATION_PROTOCOL","PREREGISTERED_EVALUATION_PROTOCOL","NO_EXECUTED_RESULT","METHODS_SPECIFICATION_ONLY","OBSERVER_CONVERGENCE_REQUIRED","NOT_APPLICABLE","ADMITTED_AS_METHOD",["METHODS_AND_MODELS","ADMISSION_AND_BASELINE","REVERSE_AUDIT"]),
"6ehrj":("INSTRUMENT_SPECIFICATION","NONE","CONSTRAINT_INSTANTIATION","CCIS","NONE","NO_RUN_RECORD","SPECIFICATION_ONLY","HOLD_OR_FAIL_NOT_SCORED","TECHNICAL_SPECIFICATION_REQUIRED","HELD",["APPLIED_INVESTIGATIONS","METHODS_AND_MODELS"]),
"etn4d":("INSTRUMENT_SPECIFICATION","NONE","XYZ_COMMITMENT_ACTION_OUTCOME","XYZ_COHERENCE_TEST","CASE_EXECUTION_CANDIDATE","NO_EXECUTED_CASE_TABLE","SPECIFICATION_NO_PUBLIC_CASES","MISSING_EVIDENCE_IS_NO_CONCLUSION","NOT_APPLICABLE","SOURCE_RECOVERED",["APPLIED_INVESTIGATIONS","FORWARD_CONSTRUCTION","RESULT_AND_RECORD"]),
"9y2p5":("APPLIED_CONTEXT","NONE","PHASE_TRAJECTORY_DRIFT_REALIGNMENT","NONE","NONE","NO_NEW_MEASUREMENT","INTERPRETIVE_FRAMEWORK","NOT_SPECIFIED","NOT_APPLICABLE","HELD",["METHODS_AND_MODELS"]),
"z64am":("CONTEXTUAL_PROPOSITION","COHERENCE_AS_COMPATIBILITY_CONSTRAINT","NARRATIVE_REDUCTION","NONE","NONE","BROAD_COMPLETION_CLAIM_NOT_EVIDENCED","METADATA_ONLY_BROAD_CLAIMS","NOT_OPERATIONALIZED","NOT_APPLICABLE","HELD",["FINDINGS_AND_BOUNDARIES"]),
"vazr6":("CANDIDATE_LAW_PROGRAM","PRIORITY_KNOWLEDGE_CANDIDATE","PRIORITY_INVERSION_TEST","PRIORITY_ORDERING_DIAGNOSTIC","CROSS_DOMAIN_PILOT_CANDIDATE","AUTHOR_REPORTED_PILOT_NO_RESULT","PILOT_CLAIMS_NO_DATA_ANALYSIS_OR_TABLES","EXPLICIT_PRIORITY_INVERSION_FAILURES","NOT_APPLICABLE","HELD",["APPLIED_INVESTIGATIONS","SCIENTIFIC_LAW"]),
"2hvbg":("INSTRUMENT_SPECIFICATION","NONE","PROPAGATION_VERSUS_FAILURE_ORIGIN","PFQ","RELIABILITY_STUDY_REQUIRED","NO_EXECUTED_RESULT","RUBRIC_AND_VALIDATION_PENDING","NOT_OPERATIONALIZED","RUBRIC_REVIEW_REQUIRED","HELD",["APPLIED_INVESTIGATIONS","METHODS_AND_MODELS"]),
"bnhq3":("STUDY_DESIGN","NONE","FROZEN_XYZ_CROSS_ERA_CODING","XYZ_COHERENCE_INSTRUMENT","RETROSPECTIVE_20_WINDOW_PILOT","NO_CASE_LEDGER_OR_RESULTS","STUDY_DESIGN_ONLY","EXPLICIT_CASE_CONTROL_OBSERVER_TIMING_FAILURES","STATISTICAL_REVIEW_REQUIRED","ADMITTED_AS_STUDY_DESIGN",["APPLIED_INVESTIGATIONS","FORWARD_CONSTRUCTION","REVERSE_AUDIT"]),
"j4kr2":("FORMALISM_CANDIDATE","NONE","SCALE_ADMISSIBILITY_BOUNDARIES_COHERENCE_CONSTRAINTS_TRAJECTORIES","654123_COMPRESSION","FORMAL_REDUCTION_REVIEW","CONDENSATION_CLAIM_NO_DERIVATION","METADATA_ONLY","CLAIMED_NOT_ATTACHED","REQUIRED","HELD",["METHODS_AND_MODELS","FINDINGS_AND_BOUNDARIES"]),
"pw8ua":("GOVERNANCE_CONTEXT","NONE","FIRST_ORDER_ADMISSIBILITY_DISCIPLINE","NONE","NONE","NO_EXECUTED_RESULT","BROAD_CLAIM_NO_OPERATIONAL_TEST","NOT_SPECIFIED","NOT_APPLICABLE","HELD",["ADMISSION_AND_BASELINE"]),
"7fupz":("APPLIED_RESEARCH_LEAD","NONE","FIELD_FLOW_RESISTANCE_THRESHOLD_PHASE","NONE","DIAMOND_GROWTH_APPLICATION_CANDIDATE","ONLY_ATTRIBUTION_FILE_RECOVERED","PRIMARY_TECHNICAL_AND_MEASUREMENT_EVIDENCE_MISSING","NOT_AVAILABLE_IN_PUBLIC_ARTIFACT","TECHNICAL_REVIEW_REQUIRED","HELD",["APPLIED_INVESTIGATIONS","FINDINGS_AND_BOUNDARIES"]),
"2cg9k":("APPLIED_RESEARCH_CONTEXT","NONE","POST_ADMISSIBILITY_TRAJECTORY_EXPLORATION","NONE","EXPLORATORY","NO_PUBLIC_RESULTS","EXPLORATORY_CONTEXT","NOT_FOUND","NOT_APPLICABLE","ADMITTED_AS_CONTEXT",["APPLIED_INVESTIGATIONS"]),
"h9k5z":("TRANSLATION_POLICY","NONE","CROSS_DOMAIN_ANTI_CONTAMINATION_BOUNDARY","NONE","NONE","NO_RESULT","COMMUNICATION_AND_APPLICATION_SURFACE","NOT_APPLICABLE","NOT_APPLICABLE","ADMITTED_AS_CONTEXT",["FINDINGS_AND_BOUNDARIES","APPLIED_INVESTIGATIONS"]),
"ju7qr":("DESCRIPTIVE_TAXONOMY","NONE","EIGHT_PHASE_TRANSITORY_MAP","OCTAVE_OF_CHANGE","RELIABILITY_STUDY_REQUIRED","NO_DERIVATION_OR_RESULT","TAXONOMY_ONLY","NOT_SPECIFIED","NOT_APPLICABLE","HELD",["METHODS_AND_MODELS"]),
"ar4cd":("APPLIED_CONTEXT","NONE","NORM_ENFORCEMENT_OUTCOME_COHERENCE","NONE","NONE","NO_CASES_OR_DATA","CONCEPTUAL_DESCRIPTION_ONLY","NOT_SPECIFIED","NOT_APPLICABLE","ADMITTED_AS_CONTEXT",["APPLIED_INVESTIGATIONS"]),
"2fh4g":("METHODOLOGICAL_INTERPRETATION","NONE","SCIENTIFIC_METHOD_AS_CONSTRAINT_ELIMINATION","NONE","NONE","NO_RESULT","METHOD_INTERPRETATION","GENERAL_REPEATED_TESTING_BOUNDARY","NOT_APPLICABLE","ADMITTED_AS_METHOD",["METHODS_AND_MODELS"]),
"ck5m2":("SOURCE_CONFLICT","NONE","INVARIANT_VERSUS_VARIANT_PLACEMENT","NONE","NONE","NO_ENUMERATED_SOURCE","TITLE_DESCRIPTION_MISMATCH","NOT_APPLICABLE","NOT_APPLICABLE","HELD",["FINDINGS_AND_BOUNDARIES"]),
"54es8":("PHILOSOPHICAL_CONTEXT_WITH_UNSUPPORTED_VALIDATION_CLAIMS","NONE","MODEL_ADMISSIBILITY_BOUNDARY","NONE","CLAIMED_STRESS_AND_EMPIRICAL_TESTS","CLAIMED_REPORTS_NOT_PRESENT","VALIDATION_CLAIMS_UNSUPPORTED_BY_FILE_INVENTORY","CLAIMED_NOT_INSPECTABLE","TECHNICAL_REVIEW_REQUIRED","HELD",["FINDINGS_AND_BOUNDARIES"]),
"5vgfd":("APPLIED_CONTEXT","ENERGY_DISTRIBUTION_PRINCIPLE_CANDIDATE","UPSTREAM_GENERATION_STORAGE_DISPATCH_DOWNSTREAM_ENDPOINTS","A3D_E_PCR_SEPARATE_LANE","SEPARATE_ENGINEERING_EVIDENCE_LANE","NO_OSF_ENGINEERING_RESULT","ARCHITECTURAL_PRINCIPLE_ONLY","NOT_PRESENT_IN_NODE","ENGINEERING_REVIEW_SEPARATE","ADMITTED_AS_CONTEXT",["APPLIED_INVESTIGATIONS"]),
"s6dzj":("PROJECT_HISTORY","NONE","NONE","NONE","NONE","NONE","NO_DIRECT_LAWS_SUPPORT","NOT_APPLICABLE","NOT_APPLICABLE","EXCLUDED",["EXCLUDED_FROM_LAWS_CHAMBER"]),
"qeabr":("GOVERNANCE_INSTRUMENT_CONCEPT","NONE","MONOCLOSURE_PROCEED_HALT_GATE","UA_MEE","CALIBRATION_AND_IMPLEMENTATION_REQUIRED","NO_EQUATIONS_IMPLEMENTATION_OR_TESTS","CONCEPTUAL_ONLY","BINARY_GATE_NOT_CALIBRATED","REQUIRED","HELD",["METHODS_AND_MODELS","ADMISSION_AND_BASELINE"]),
"sfjn6":("PROMOTIONAL_NARRATIVE","NONE","NONE","NONE","NONE","NO_EVIDENCE_PACKAGE","PROMOTIONAL_POSITIONING","NOT_APPLICABLE","NOT_APPLICABLE","EXCLUDED",["EXCLUDED_FROM_LAWS_CHAMBER"]),
}
CONFLICTS={"ck5m2":["Title says Seven Invariants; description says Seven Variants and enumerates neither."],"54es8":["Claims validation reports and frozen artifacts; public file inventory is empty."],"vazr6":["Claims pilot evidence; no dataset, coding protocol, analysis, or result table recovered."],"bnhq3":["Calls itself execution; recovered material is a study design without case ledger or results."],"j4kr2":["Claims frozen axioms and reduction protocol; no files recovered."],"z64am":["Broad cross-domain completion language lacks attached operational tests."],"7fupz":["Only attribution PDF recovered; primary technical record absent."]}

def sess():
 s=requests.Session(); r=Retry(total=3,backoff_factor=.7,status_forcelist=(429,500,502,503,504),allowed_methods=("GET",)); s.mount("https://",HTTPAdapter(max_retries=r)); s.headers["User-Agent"]="laws-chamber-registry/1.0"; return s

def getj(s,u):
 try:
  x=s.get(u,timeout=30)
  if x.status_code==404:return "ABSENT",None
  if x.status_code in (401,403):return "PRESENT_BUT_UNAVAILABLE",None
  x.raise_for_status(); return "REVIEWED",x.json()
 except Exception as e:return "PENDING",{"error":f"{type(e).__name__}: {e}"}

def cnt(x):return len(x.get("data",[])) if isinstance(x,dict) else 0

def live(s,p,fs):
 i=p["id"]; k="registrations" if p.get("registration") else "nodes"; ws,w=getj(s,f"https://api.osf.io/v2/{k}/{i}/wikis/"); ws="ABSENT" if ws=="REVIEWED" and cnt(w)==0 else ws
 if k=="nodes": cs,c=getj(s,f"https://api.osf.io/v2/nodes/{i}/children/"); rs,r=getj(s,f"https://api.osf.io/v2/nodes/{i}/registrations/")
 else: cs,c="NOT_APPLICABLE",None; rs,r="SELF_REGISTRATION",{"data":[p]}
 vs=[]; vn=0
 for f in fs:
  if f.get("kind")!="file" or not f.get("osf_file_id"):continue
  st,v=getj(s,f"https://api.osf.io/v2/files/{f['osf_file_id']}/versions/");vs.append(st);vn+=cnt(v) if st=="REVIEWED" else 0
 return {"landing_page_status":"REVIEWED_VIA_PUBLIC_OSF_API_METADATA","wiki_status":ws,"wiki_history_status":"ABSENT" if ws=="ABSENT" else "PENDING","components_status":cs,"components_count":cnt(c),"registrations_status":rs,"registrations_count":cnt(r),"file_versions_status":"NOT_APPLICABLE" if not vs else ("REVIEWED" if all(x=="REVIEWED" for x in vs) else "PENDING"),"file_version_count":vn}

def version(p):
 if p.get("registration"):return "FROZEN_REGISTRATION"
 m=re.search(r"\bv?\d+\.\d+(?:\.\d+)?\b",p["title"]+"\n"+p.get("description",""),re.I);return m.group(0) if m else "UNVERSIONED_EDITABLE_PROJECT"

def wj(p,x):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(x,indent=2,ensure_ascii=False)+"\n",encoding="utf-8")

def main():
 a=argparse.ArgumentParser();a.add_argument("--corpus-root",default="research/osf-laws-corpus");a.add_argument("--output",default="research/osf-laws-corpus/source-registry");a.add_argument("--live-osf-review",action="store_true");q=a.parse_args();root=Path(q.corpus_root);out=Path(q.output);man=json.loads((root/"manifest.json").read_text());ps=man["projects"]
 if len(ps)!=31 or {p["id"] for p in ps}!=set(M):raise SystemExit("31-resource classification mismatch")
 s=sess() if q.live_osf_review else None; rec=[]
 for p in ps:
  i=p["id"];fp=root/"projects"/i/"files.json";fs=json.loads(fp.read_text()) if fp.exists() else [];af=[f for f in fs if f.get("kind")=="file"];rv=live(s,p,fs) if s else {"landing_page_status":"SOURCE_RECOVERED_IN_FROZEN_HARVEST","wiki_status":"PENDING","wiki_history_status":"PENDING","components_status":"REVIEWED_FROM_MANIFEST","components_count":0,"registrations_status":"SELF_REGISTRATION" if p.get("registration") else "PENDING","registrations_count":1 if p.get("registration") else 0,"file_versions_status":"PENDING" if af else "NOT_APPLICABLE","file_version_count":0};m=M[i]
  ex=[Path(f.get("name","")).suffix.lower() for f in af]; names=[f.get("name","").lower() for f in af]
  rec.append({"OSF_ID":i,"TITLE":p["title"],"RESOURCE_TYPE":p.get("type"),"PROJECT_OR_REGISTRATION":"REGISTRATION" if p.get("registration") else "PROJECT","PUBLIC_URL":p.get("osf_url"),"VERSION":version(p),"DATE":{"created":p.get("date_created"),"modified":p.get("date_modified"),"harvested":p.get("harvested_at")},"WIKI_STATUS":rv["wiki_status"],"WIKI_HISTORY_STATUS":rv["wiki_history_status"],"FILES_INVENTORIED":len(af),"ATTACHMENTS_REVIEWED":sum(f.get("error") is None for f in af),"FILE_HASHES":{f.get("name"):f.get("sha256") for f in af if f.get("sha256")},"EXTRACTION_STATUS":sorted({f.get("extraction_status","UNKNOWN") for f in af}) or ["NO_PUBLIC_FILES"],"SOURCE_CLASS":m[0],"LAW_CLASS":m[1],"METHOD_CLASS":m[2],"INSTRUMENT_CLASS":m[3],"STUDY_CLASS":m[4],"RESULT_CLASS":m[5],"EMPIRICAL_STATUS":m[6],"FALSIFICATION_STATUS":m[7],"MATHEMATICAL_REVIEW_STATUS":m[8],"CLAIM_BOUNDARY":BOUNDARY,"CANONICAL_DESTINATION":m[10],"ADMISSION_STATUS":m[9],"SOURCE_CONFLICTS":CONFLICTS.get(i,[]),"REVIEW_SURFACES":rv,"DATASETS_DETECTED":any(x in {".csv",".tsv",".sav",".dta",".parquet",".jsonl"} for x in ex),"ANALYTIC_CODE_DETECTED":any(x in {".py",".r",".ipynb",".jl",".m",".do",".sas"} for x in ex),"RESULT_TABLES_DETECTED":any(("result" in n or "analysis" in n) and e in {".csv",".xlsx",".xls",".tsv"} for n,e in zip(names,ex)),"METADATA_SHA256":hashlib.sha256((root/"projects"/i/"metadata.json").read_bytes()).hexdigest()})
 sm={"resource_count":31,"registration_count":sum(r["PROJECT_OR_REGISTRATION"]=="REGISTRATION" for r in rec),"public_file_count":sum(r["FILES_INVENTORIED"] for r in rec),"resources_with_files":sum(r["FILES_INVENTORIED"]>0 for r in rec),"datasets_detected":sum(r["DATASETS_DETECTED"] for r in rec),"analytic_code_detected":sum(r["ANALYTIC_CODE_DETECTED"] for r in rec),"result_tables_detected":sum(r["RESULT_TABLES_DETECTED"] for r in rec),"unclassified_count":sum(r["ADMISSION_STATUS"]=="DISCOVERED" for r in rec),"admission_counts":dict(Counter(r["ADMISSION_STATUS"] for r in rec)),"wiki_status_counts":dict(Counter(r["WIKI_STATUS"] for r in rec))}; now=datetime.now(timezone.utc).isoformat(); reg={"registry_id":RID,"generated_at":now,"source_repository":"smansfield635-create/smansfield635-create.github.io","source_branch":os.getenv("GITHUB_REF_NAME","agent/osf-laws-source-registry-001"),"source_head":os.getenv("GITHUB_SHA","LOCAL_OR_UNRECORDED"),"source_manifest_generated_at":man.get("generated_at"),"claim_boundary":BOUNDARY,"summary":sm,"resources":rec};wj(out/"registry.json",reg);(out/"project-reports.jsonl").write_text("".join(json.dumps(r,ensure_ascii=False)+"\n" for r in rec));d=defaultdict(list)
 for r in rec:
  for x in r["CANONICAL_DESTINATION"]:d[x].append(r["OSF_ID"])
 wj(out/"destination-custody.json",{"registry_id":RID,"source_count":31,"sources_without_destination":[],"destinations":dict(sorted(d.items()))})
 rows=[f"| `{r['OSF_ID']}` | {r['TITLE'].replace('|','/')} | `{r['SOURCE_CLASS']}` | `{r['ADMISSION_STATUS']}` | `{r['EMPIRICAL_STATUS']}` |" for r in rec];(out/"README.md").write_text("\n".join(["# OSF Laws Chamber Source Registry","",f"Registry: `{RID}`","","`PROPOSITION ≠ METHOD ≠ INSTRUMENT ≠ STUDY_DESIGN ≠ EXECUTED_STUDY ≠ REPLICATED_RESULT`","","`REGISTRATION ≠ VALIDATION`","",f"Resources: **31** · Public files: **{sm['public_file_count']}** · Datasets: **0** · Analytic code: **0** · Result tables: **0**","","`PENDING` wiki status is not equivalent to absent or reviewed.","","| OSF | Title | Source class | Admission | Empirical status |","|---|---|---|---|---|",*rows,"","The Full Bird Kernel is not one of the 31 OSF resources and remains separately governed.","",BOUNDARY,"" ]),encoding="utf-8")
 receipt={"receipt_id":"OSF_LAWS_CHAMBER_LANE_2_SOURCE_AUTHORITY_COMPLETION_v1","status":"PASS_WITH_EXPLICIT_PENDING_LIVE_SURFACES" if any(r["WIKI_STATUS"]=="PENDING" for r in rec) else "PASS_COMPLETE","generated_at":now,"source_head":reg["source_head"],"resource_count":31,"classified_resource_count":31,"unclassified_resource_count":0,"source_to_destination_complete":True,"metadata_and_file_review_complete":True,"wiki_review_complete":all(r["WIKI_STATUS"] in {"REVIEWED","ABSENT","PRESENT_BUT_UNAVAILABLE"} for r in rec),"product_files_changed":False,"merge_authorized":False,"deployment_authorized":False,"claim_boundary":BOUNDARY};wj(out/"LANE_2_COMPLETION_RECEIPT.json",receipt)
 assess={"assessment_id":"OSF_LAWS_CORPUS_VALUE_ASSESSMENT_v2_31_RESOURCE_RECONCILED","registry_id":RID,"resource_count":31,"assessment_authority":"SOURCE_REVIEW_PLACEMENT_AND_ADMISSION_ONLY","claim_boundary":BOUNDARY,"corpus_findings":sm,"projects":[{"id":r["OSF_ID"],"title":r["TITLE"],"source_class":r["SOURCE_CLASS"],"admission_status":r["ADMISSION_STATUS"],"empirical_status":r["EMPIRICAL_STATUS"],"canonical_destination":r["CANONICAL_DESTINATION"]} for r in rec]};wj(root/"laws-chamber-assessment.json",assess)
 md=["# Laws Chamber Value Assessment — 31-Resource Reconciled Successor","","`METHOD_DOCUMENTATION = SUBSTANTIAL`","","`FALSIFICATION_ARCHITECTURE = SUBSTANTIAL`","","`FORMAL_MODELS = PRESENT_REVIEW_REQUIRED`","","`STUDY_DESIGNS = PRESENT`","","`PUBLIC_DATASETS = NOT_RECOVERED`","","`PUBLIC_ANALYTIC_CODE = NOT_RECOVERED`","","`EXECUTED_RESULT_TABLES = NOT_RECOVERED`","","`INDEPENDENT_REPLICATION = NOT_ESTABLISHED`","","`BROAD_EMPIRICAL_VALIDATION = NOT_ESTABLISHED`",""]
 for n,r in enumerate(rec,1):md += [f"## {n}. {r['TITLE']} — `{r['OSF_ID']}`",f"- Source: `{r['SOURCE_CLASS']}`",f"- Admission: `{r['ADMISSION_STATUS']}`",f"- Empirical: `{r['EMPIRICAL_STATUS']}`",f"- Destination: {', '.join(r['CANONICAL_DESTINATION'])}",*( [f"- Conflict: {'; '.join(r['SOURCE_CONFLICTS'])}"] if r['SOURCE_CONFLICTS'] else []),""]
 (root/"LAWS_CHAMBER_VALUE_ASSESSMENT.md").write_text("\n".join(md+[BOUNDARY," "]),encoding="utf-8");wj(root/"HARVEST_COMPLETION_RECEIPT.json",{"receipt_id":"OSF_PUBLIC_LAWS_DISCOVERY_CORPUS_HARVEST_COMPLETION_v2_31_RESOURCE_RECONCILED","status":"PASS_COMPLETE","source_snapshot_branch":reg["source_branch"],"source_snapshot_head":reg["source_head"],"source_profile":man.get("osf_profile_url"),"generated_at":man.get("generated_at"),"public_resources_harvested":31,"registrations":1,"resources_with_public_files":sm["resources_with_files"],"public_files_inventoried":sm["public_file_count"],"public_datasets_detected":0,"public_analytic_code_files_detected":0,"executed_result_tables_detected":0,"discovery_errors":len(man.get("discovery_errors",[])),"claim_boundary":BOUNDARY})
 (root/"OTHER_ROOMS_HANDOFF.md").write_text("\n".join(["# OSF Laws Corpus — Source Authority Handoff","","Status: `LANE_2_SOURCE_REGISTRY_COMPLETE_WITH_EXPLICIT_LIVE_SURFACE_STATUS`","",f"Resources classified: **31 of 31**","","Authoritative files:","- `source-registry/registry.json`","- `source-registry/project-reports.jsonl`","- `source-registry/destination-custody.json`","- `source-registry/LANE_2_COMPLETION_RECEIPT.json`","- `laws-chamber-assessment.json`","","`PUBLIC_DATASETS = NOT_RECOVERED`","`PUBLIC_ANALYTIC_CODE = NOT_RECOVERED`","`EXECUTED_RESULT_TABLES = NOT_RECOVERED`","`INDEPENDENT_REPLICATION = NOT_ESTABLISHED`","`BROAD_EMPIRICAL_VALIDATION = NOT_ESTABLISHED`","",BOUNDARY," "]),encoding="utf-8");print(json.dumps({"status":receipt["status"],"resources":31,"files":sm["public_file_count"],"wiki":sm["wiki_status_counts"]},indent=2))
if __name__=="__main__":main()
